### ISSUE TITLE
[Bug]: Computed value of Table's column should also gets updated when column name gets updated in Table Widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3816a1189c1744beb933650680590481-00001.gif)](https://www.loom.com/share/3816a1189c1744beb933650680590481)

### Steps To Reproduce

1. Add a Table widget
2. Update the column name from property pane
3. Click on gear icon and observe that computed value of the column remains same as previous name of the column instead of new updated name

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Hey @chandannkumar we can't do that by default because the computed value refers to the key in the data that you want to reference while column name can be much more user friendly, plus it can also happen that one column is a mix of two fields from the data. 

We can't automatically change this. Please add more queries if any, but this is not an issue.

![Screenshot 2022-01-13 at 6 01 26 PM](https://user-images.githubusercontent.com/19730984/149330945-cc93970b-3be1-44b9-9048-8ec647eeb96c.png)
