### ISSUE TITLE
[Bug] Mustache templating is not supported in curl commands (old title: Curl import should accept single quotes around the url)

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1032]
## Steps
1. import the following curl 
curl --location --request GET '{{host}}/scrap/api?slugifiedName=Freshdesk&ownerName=volodimir.kudriachenko'
2. The import fails to add the {{host}}

**Comment by pc9795** [comment]
It happens because of an exception here due to `{{host}}`: https://github.com/appsmithorg/appsmith/blob/9ac935c4242ac582a18c77bef20eda60514a5145/app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterService.java#L385

Because of which no URL is set in the data-source configuration: https://github.com/appsmithorg/appsmith/blob/9ac935c4242ac582a18c77bef20eda60514a5145/app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterService.java#L400

Because of which the name of data-source is not able to set: https://github.com/appsmithorg/appsmith/blob/9ac935c4242ac582a18c77bef20eda60514a5145/app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterService.java#L73

Because of which we get a bad request here: https://github.com/appsmithorg/appsmith/blob/9ac935c4242ac582a18c77bef20eda60514a5145/app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java#L173

**Comment by pc9795** [comment]
I don't think this is a bug.

**Comment by mohanarpit** [comment]
@pc9795 Thanks a lot for triaging the issue. This is indeed not a bug. Marking it as such.
