### ISSUE TITLE
[Bug]: Renaming of an application/page/organization changes sequence.

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#10346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Renaming of an application/page/organization changes sequence. (Refer video)
https://loom.com/share/79cc9d4c38eb4e4fad158947a597cd41

### Steps To Reproduce

1. Go to release
2. Create new organization; ideally the organization will be named Untitled application 1 
3. Create one more organization; it'll be automatically renamed Untitled application 2.
4. Now rename Untitled application 2 to Untitled application 50 > Create one more new organization and observe the name.

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Looks like there's a common code doing this, the problem i see with this issue is if we fix it there's a chance of it breaking. 

If you have an app, with pages  - 1,2,3 and you change 3 to 4. Next time you click new page, 4 cannot be used anymore because it's already exists. Since page, app and org names are unique, i don't think this solution will work @shwetha-ramesh. Any other suggestions on how to fix this?

**Comment by trishaanand** [comment]
Not a regression since this has always been the behaviour. Removing the Regressed tag.
