### ISSUE TITLE
[Bug]: Failed to build on windows

### ISSUE THREAD

**Issue by rizkyramadhan** [appsmithorg/appsmith#10366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appsmith is throwing error in postgressPlugin when building it in windows.

### Steps To Reproduce

When I follow https://github.com/appsmithorg/appsmith/blob/release/contributions/ServerSetup.md

After running `mvn clean compile` the guide tells me to run `./build.sh`, but since I'm in windows, i just read it and run the command line by line. 

When running this `mvn clean package`

It throws this
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 30.926 s <<< FAILURE! - in com.external.plugins.PostgresPluginTest
[ERROR] com.external.plugins.PostgresPluginTest  Time elapsed: 30.926 s  <<< ERROR!
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
```

Attached is surefire-report generated by maven
[surefire-reports.zip](https://github.com/appsmithorg/appsmith/files/7859935/surefire-reports.zip)

### Environment

Deploy Preview

### Version

Self-Hosted

**Comment by mohanarpit** [comment]
Please ensure that Docker is running on your system. This is because the JUnit tests leverage TestContainers for real world testing. This requires Docker to be running on your system when you compile or run the tests. 

Alternatively, you can skip running the tests on your local machine via the command: `./build.sh -DskipTests`

**Comment by rizkyramadhan** [comment]
Ah thanks, skipTest flag is what I need.
