### ISSUE TITLE
[Bug] When an API is copied multiple time the suffix "Copy" as many time it is copied

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1038]
## Steps
1. Create an API
2. Copy the API
3. Copy the API again
4. The name of the new apis is APICopyCopy instead of API Copy(1)

**Comment by Sufiyan1997** [comment]
@prapullac I would like to work on this. Can you assign it to me?

**Comment by mohanarpit** [comment]
@Sufiyan1997 Go for it! 🎉

**Comment by karmanya007** [comment]
Is this bug actively been worked on?

**Comment by Sufiyan1997** [comment]
Yes, I'm working on it

**Comment by Sufiyan1997** [comment]
Just clarification on expected behavior here. 
What should be the name of first copy? Should it be `API Copy` or `API (1)`?
Basically should it go API -> API(1) -> API(2) ? Or API -> API Copy -> API Copy(1) -> API Copy(2) ?

Also there is a function here:[https://github.com/appsmithorg/appsmith/blob/release/app/client/src/utils/AppsmithUtils.tsx#L68](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/utils/AppsmithUtils.tsx#L68) that does API -> API1 -> API2. Should I modify it add the parenthesis?

**Comment by trishaanand** [comment]
@prapullac : If an API is copied, it outputs API Copy. If you copy API again, it outputs API Copy1. On another iteration its output is APICopy2.
If you copy the `API Copy`, then the expected API name should be `API Copy Copy`.
How would we distinguish between copying the original API multiple times, vs copying the copy iteratively?

**Comment by trishaanand** [comment]
@Sufiyan1997 : Could you hold the implementation for some time? Would love to first get on the same page about the expected behaviour. I am speaking to our test engineer, @prapullac, to resolve the expectation as soon as possible.

In the mean time, if you would like, you can check out a few other first time issues to contribute to. Cheers!

**Comment by trishaanand** [comment]
@Sufiyan1997 : I had a conversation with @prapullac and have decided that the current behaviour is acceptable and is the expected behaviour for now. We wouldn't be fixing this.

I hope you are able to pick up other good first issues for Hacktoberfest!

Cheers and good luck!
