### ISSUE TITLE
[Feature]-[560]:Limit GSheets datasource access for invited users

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#10434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This is a user-reported issue. Suppose I have a GSheets datasource in my org, and I invite a user to my org, that user can now access all my drive's GSheets.

Steps to reproduce:
1. set up two appsmith accounts, for users "a" and "b": a@appsmith.com and b@appsmith.com
2. with account "a": 
3. go to google drive and create some google sheets: Spreadsheet1, Spreadsheet2, and Spreadsheet3
4. create an app on appsmith 
5. create a new GSheets data source, and select Spreadsheet1 as the Spreadsheet url
6.  invite user "b" to your org as an admin or developer
7. with account "b":
8. create an app on appsmith
9. use the wizard "generate from a data table"
10. select datasource as GSheets
11. in the dropdown "select spreadsheet from GSheets", notice that user "b" now has access to all of "a"'s spreadsheets Spreadsheet1, Spreadsheet2, Spreadsheet3

This is a problem. The solution is not clear yet - will discuss with the team and update this issue accordingly.

There are two options:
1. first, user "a" does not know that when they invite a user to their org, they are also ceding access to their drive's GSheets to all invited users. One option could be to inform the user of this fact. However, in a typical google drive account, I have many sheets in many folders, and if I know of this "limitation", I would be discouraged from using Appsmith altogether - this is not a viable option
2. compartmentalize access to google sheets, so that only the user account that was used to create a particular authorization retains authorization to the GSheets datasource, even after inviting other users to the org.

### Why should this be worked on?

The access to all my drive's sheets is being given to the invited user, and this fact is not apparent to me. I might have some sensitive content that I did not intend to share with the invited user.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_574r0)

**Comment by areyabhishek** [comment]
Got one more request on Intercom for improving Google sheets/drive integration

![Uploading Screenshot_20220122-112129.jpg…]()

**Comment by rohan-arthur** [comment]
related:  #3313

**Comment by nidhi-nair** [comment]
For us to be able to let authentication be stored at a per user level we need to be doing the following things:
1. Store datasource credentials at a per user per datasource level
2. Expose a widget that has a CTA to perform authentication
3. To be able to address the concern from the screenshot, we also need to be able to set the scope of authentication as a configuration. For example, in this users' case they could specify each file that the authentication should have access to.
4. We would still need to grant some form of access on the editor mode of queries to be able to gather information and test data out. This could possibly stay the same as it is today. But these creds should never be used in view mode.

For now, the open items to think about are whether the widget based design would provide good UX, and what sort of properties we'd need to have on the widget. Since datasources do not have a published and unpublished mode, auth info per user can be shared across edit and view mode. 

@areyabhishek @Nikhil-Nandagopal  could you please help with the UX questions?

**Comment by rohan-arthur** [comment]
@nidhi-nair mentioning this here so that it doesn't get lost. There's also the unpleasant "duct-tape" option to consider, in case this becomes critical - to use google's drive permissions API to patch things up for the timebeing.

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair why do we need a widget to do this? Whenever a query is run on this data source, can we simply throw a 401 that says it's unauthenticated and that prompts the user to authorize the application? I think the editor mode and view mode should both work exactly the same in this manner.

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal how would we trigger authentication in view mode? Do you mean to say we intercept action execution results and insert an authentication flow at that point? 

I think it's cleaner to use a widget because it allows us to customize scopes on the basis of what the user wants it to be, and allows them to insert the authentication flow at the appropriate point in their application.

**Comment by nidhi-nair** [comment]
From a discussion with Nikhil:
We could think about solving this by exposing a a function the end user (say `authorize("Datasource1")`). The user could then program their API call to be authorized when they receive a 401 from their server. 

Alternatively, we could expose the status of the datasource authentication to let the user control the call using that flag. We could also think about abstracting this layer into the function itself so that authorize only happens if it hasn't already. 

This change will need us creating said function in our IDE, and make it call the API server in the same way as the datasource authorize button does.

Tagging @ayushpahwa for an analysis on feasibility and effort.

**Comment by rohan-arthur** [comment]
gsheets usage in 6 months: 1400
assume [20%](https://mixpanel.com/project/2032485/view/178891/app/insights#report/15422135/installation-goal/~(columnWidths~(bar~())~description~'~displayOptions~(chartType~'pie~plotStyle~'standard~analysis~'linear~value~'absolute)~sorting~(bar~(sortBy~'column~colSortAttrs~(~(sortBy~'value~sortOrder~'desc)~(sortBy~'value~sortOrder~'desc)))~line~(sortBy~'value~sortOrder~'desc~valueField~'averageValue~colSortAttrs~(~(sortBy~'value~sortOrder~'desc~valueField~'averageValue)))~table~(sortBy~'column~colSortAttrs~(~(sortBy~'label~sortOrder~'asc)~(sortBy~'label~sortOrder~'asc)))~insights-metric~(sortBy~'value~sortOrder~'desc~valueField~'totalValue~colSortAttrs~(~))~pie~(sortBy~'value~sortOrder~'desc~valueField~'totalValue~colSortAttrs~(~(sortBy~'value~sortOrder~'desc~valueField~'totalValue))))~timeComparison~null~querySamplingEnabled~false~dashboard~(id~1369067~title~'New*20Developers*20Pod~creator_name~'Nikhil*20Nandagopal~can_update_basic~true~can_share~true~allow_staff_override~false~is_superadmin~false)~title~'Installation*20Goal~sections~(show~(~(dataset~'!mixpanel~value~(name~'Installation*20Setup*20Complete~resourceType~'events)~resourceType~'events~profileType~null~search~'~dataGroupId~null~filter~(~(dataset~'!mixpanel~value~'email~resourceType~'events~profileType~null~search~'~dataGroupId~null~filterType~'string~defaultType~'string~filterOperator~'does*20not*20contain~filterValue~'appsmith.com~propertyObjectKey~null~determiner~'all))~math~'unique~perUserAggregation~null~property~null~filterDeterminer~'all))~group~(~(dataset~'!mixpanel~value~'goal~resourceType~'events~profileType~null~search~'~dataGroupId~null~propertyType~'string~typeCast~null~unit~null))~time~(~(dateRangeType~'in*20the*20last~unit~'month~window~(unit~'month~value~3))))~legend~(individualSelectedSegments~(selected~(~(key~'just*20exploring)~(key~'personal*20project)~(key~'work*20project)~(key~'other)~(key~'undefined))))~originDashboard~(id~1369067~title~'New*2520Developers*2520Pod))) need this feature: 280

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 280 |
| Effort (months)  | 1 |

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/msg_1eflxv0s) wants to give Appsmith access only to a specific Google Sheet instead of ALL my files in Google Drive.

**Comment by rohan-arthur** [comment]
will be fixed with #20191
