### ISSUE TITLE
[Bug]: Trimming column headers google sheets

### ISSUE THREAD

**Issue by vasani-arpit** [appsmithorg/appsmith#10444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was trying with Google sheets but this might be common issue for all 

https://user-images.githubusercontent.com/6497827/149771311-968f22c1-794b-4b3f-92a8-2d5443c2b442.mp4

So, There is a space in header so the actual data is 

```json
[
  {
    "Name ": "Arpit",    <---- space in key
    "Mobile": "9033000000",
    "Address": "Naranpura",
    "rowIndex": "0"
  }
]
```

but evaluated value doesn't show that. Which misleads user. (I got confused, Spent huge amount of time figuring this out)

If you copy the value using copy button then it copies correct data in clipboard. 

_I understand this is a small thing but some times these things easily go unnoticed which can make your head scratching_

### Steps To Reproduce

1. Connect google sheet
2. Intentionally put space at start or end of heading 
3. load that sheet in appsmith 
4. try to use the data with column name which has space in it

### Environment

Production

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment]
It looks like that only the keys are affected (trim spaces, from both ends), values retain the extra spaces.

![image](https://user-images.githubusercontent.com/1573771/149879454-288b052d-a650-43b3-b4bf-86df52b6f0d9.png)

Notice that "SpaceAtEnd     " heading (on the left) is reported as "SpaceAtEnd" in the API Response(on the right); but the value retains the space.

**Comment by IAmAnubhavSaini** [comment]
The solution is to add `white-space: pre-wrap` to the offending elements. These elements however live in react-json-view. 


Solution:
![image](https://user-images.githubusercontent.com/1573771/149891012-1e5a4a9f-59df-45d2-8d90-d7371ecbfc17.png)

Or just add it to higher up component that appsmith controls (it might break other views, but this does preserve white-spaces):
![image](https://user-images.githubusercontent.com/1573771/149891647-492c5e43-ee09-451e-b9c9-76398911fd0b.png)


In app/client/src/pages/Editor/QueryEditor/JSONViewer.tsx

```
const Record = styled(Card)`
  margin: 5px;
  border-radius: 0;
  span.string-value {
    overflow-wrap: anywhere;
  };
  white-space: pre-wrap;
`;
```

My guess is where ever we show the user data, we can pre-wrap the whitespaces.

**Comment by vasani-arpit** [comment]
Nice catch !! @IAmAnubhavSaini

**Comment by IAmAnubhavSaini** [comment]
Table also has this issue. Check below: same data, no spaces.

![Screenshot-2022 01 18-14 56 05](https://user-images.githubusercontent.com/1573771/149910743-af81a330-cece-4003-bc8c-13873b621fa3.png)

There are two issues with table:

1. the column headers are already modified to use `_` instead of ` ` (space).
2. the data still has white-space, but cannot be rendered as such.

The solution of adding `white-space: pre-wrap;` to an element up in the hierarchy might work with Record but not in Table.

When I tried to add pre-wrap to any parent of data-cell, it didn't work. 

Check role="cell" child-div (works) vs role="rowgroup" (didn't work).

![Screenshot-2022 01 18-15 00 03](https://user-images.githubusercontent.com/1573771/149911853-1caffc13-ac01-4d1d-8d97-94012effdf8a.png)

**Comment by nidhi-nair** [comment]
This is no longer an issue with Table widget v2. It is also not a query response issue, but only causes a confusion in the evaluated value window, switched labels accordingly.
