### ISSUE TITLE
[Epic]: Widget Reskinning project

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10483]
Objective
1. First widget drag drop, should be amazing. When a user drops a widget they should feel amazed and it should be consistent with the theme they have defined.
2. Users should be able to style the widgets to give it their own look. This will flow into the variant design.

Outcome
1. Better looking widgets - Changed visuals for each widget
2. Ability to expose any style control quickly
3. New style properties for each widgets

https://www.notion.so/appsmith/Reskinning-widgets-80a31c4019ec41d7936621c39865ee14

All inconsistencies document
https://www.notion.so/appsmith/Widget-reskinning-inconsistencies-a7716e441e8646dcb74d30e63ebd23e9

**Comment by dilippitchika** [comment]
Items discussed today
1. Platform items vs app widgets - Tabs vs Nav for pages and Toolbar actions vs button
2. Items we are trying to achieve in the project - https://www.notion.so/appsmith/Reskinning-widgets-80a31c4019ec41d7936621c39865ee14
3. Widget design system by @jsartisan and how it can help us. Awesome work.

Action items
1. Estimate product backlog - @jsartisan @keyurparalkar 
2. Resolve items in Needs PRD with the design team - @dilippitchika 
3. Catchups for this project - Re-use the meetings for theming
4. @dilippitchika to catchup with @vivekverma2312 and team to give an initial overview of the project.
5. All design doubts to be raised in figma

CC - @somangshu

**Comment by dilippitchika** [comment]
Discussed with @vinay-appsmith and here are the next steps for us

Pending items
1. The remaining widgets to be audited are table and text widgets for widget reskinning.
2. We need a design POC to drive the project forward.

Action items
1. Vinay to check if we can get someone from the Rival team to close table and text widgets for reskinning.
2. Vinay to internally work on handing this to one of our 3 designers for becoming the POC and driving the reskinning project forward.

We will get an update on this tomorrow on item 1 and need some time to get to item 2.

CC @somangshu

**Comment by dilippitchika** [comment]
JOB STORIES

When i start creating a new app in appsmith, I want all widgets to feel visually consistent by default so that I can focus on building my apps rather than styling them to begin with.

**Push forces**

1. The UI looks weird when I try to add some widgets and align them. This weirdness looks due to the probably the following reasons
    1. Missing polish on each widget
    2. States are inconsistent across widgets
2. This UI looks inconsistent and I also don’t have the styling options available to fix this myself. This is frustrating for me.
3. The finished product doesn’t look as good as the design I had in my mind.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika some more detailed job stories are needed here
- When building a form, I want the inputs, date pickers, selects, switches & buttons to all look consistent and have great defaults so that my form looks good
- When building a table with filters, I want the date pickers and selects to match the style of the table whether they are inside a container or not, so that I don't have to spend much time styling them
- When building a dashboard with stats, I want the charts, stat boxes and filters to all have consistent styles so that my dashboard can look great
- When building a drill-down view, I want my table and corresponding form / drill down to match so that I don't have to spend too much time styling it
- When building an editable view inside a modal, I want the form to look great inside the modal with as little input from me as possible so that I don't need to spend time styling it
- When creating a destructive query, I want the confirmation option in the query to match my apps style so that I don't need to build my own confirmation modal

**Comment by dilippitchika** [comment]
**Had a dev kickoff yesterday, notes from the call**
- All inconsistencies are documented here - https://www.notion.so/appsmith/Widget-reskinning-inconsistencies-a7716e441e8646dcb74d30e63ebd23e9
- Pawan to discuss checkbox reskinning today and help with estimates
- Keyur to discuss chart today and help finalise inconsistencies and estimates
- Dilip to ask in group if we can move to 4px as default border radius than 6px
- Dilip to document the release strategy and Pawan/Keyur/Vivek to review it and share it with @somangshu 
- Estimate the work on widgets discussed and plan for week 1 of the work.

**Comment by dilippitchika** [comment]
@somangshu @jsartisan @keyurparalkar @vivekverma2312 please review the release strategy here - https://www.notion.so/appsmith/Release-strategy-3809d98748f94c16bdf31647c8c44131

**Comment by dilippitchika** [comment]
@vivekverma2312 while testing we should these stories to test things out, it will give us an overview of the inconsistencies across widgets

https://github.com/appsmithorg/appsmith/issues/10483#issuecomment-1156057501
