### ISSUE TITLE
[Bug]: Organisation Invite Email Uses Current Session Base Address, and not Custom Domain

### ISSUE THREAD

**Issue by lukearran** [appsmithorg/appsmith#10598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Expected**: When I send an invite to an organisation, I expect the button to be linked to the custom domain I have set (e.g https://appsmith.domain.com/user/signup?email=john@address.com).
**Actual**: When I send an invite to an organisation, the button link's base address is incorrectly set to the address which I sent the email from (e.g https://0.0.0.0/user/signup?email=john@address.com).

### Steps To Reproduce

1. Set a custom domain e.g appsmith.domain.com
2. Access Appsmith via it's IP address e.g https://0.0.0.0/
3. Click on the "Share" button next to an organisation
4. Send an invite to a user
5. The button's link in the email is set incorrectly to https:/0.0.0.0/user/signup?email=john@address.com and not to the custom domain set in the environment configuration.

(**Context**: The client has an custom domain set which is valid only from within their internal network. However, we access Appsmith during development via their public IP address. So we're unable to send invites to users, without being on-site).

### Environment

Release

### Version

Self-Hosted

**Comment by Nikhil-Nandagopal** [comment]
@lukearran we're a little confused by why you're accessing the appsmith instance via the IP and not using a VPN? The public IP seems to defeat the purpose of the VPN

**Comment by lukearran** [comment]
> @lukearran we're a little confused by why you're accessing the appsmith instance via the IP and not using a VPN? The public IP seems to defeat the purpose of the VPN

Yes @Nikhil-Nandagopal, in every other case we would use a VPN. However, in this particular case, the client is unable to provide us with VPN access due to policy.

**Comment by sharat87** [comment]
Hey @lukearran, I understand the problem, but if this is changed, someone inviting another person who only has access via the public IP won't be able to use the link in the email, because it contains the internal domain.

The reason the email uses the domain that was accessed was based on practicality, over configuration. Consider your own case. For whatever policy reasons, you are not using the configured custom domain, you are instead using a public IP. Then it's a fair assumptions that _everyone_ would be accessing the Appsmith instance in the same fashion, no? A similar frustration could be faced in the other way around as well. Like, "why is Appsmith using the custom domain in the email, instead of just using the host I'm accessing it with?".

I'm going to go ahead and close this. Please consider using the same domain to access your Appsmith instance. Also, if you are using an IP address, I suspect you are not using SSL to access the instance. Normally that's probably okay, but considering this Appsmith instance was put behind a VPN, I'd recommend against accessing it without VPN and without SSL as well.
