### ISSUE TITLE
[Bug]: Dropping currency widget on to list widget causes app to crash

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#10683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Drag and drop a currency widget onto a list widget and observe the app crash and be unable to load the app if the widget is on the home page

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/347446a1abd147f9bb14f9459ecf62bb-00001.gif)](https://www.loom.com/share/347446a1abd147f9bb14f9459ecf62bb)

### Environment

Production

### Version

Cloud

**Comment by somangshu** [comment]
@sbalaji1192 could you take a look at this?

**Comment by sbalaji1192** [comment]
RCA of the original issue: The currency widget and Phone input widget updates meta property(countryCode) when it gets mounted. List widgets changes its children's id to `list-widget-child-id-${itemIndex}-${widgetName}`. when updating the meta property we're sending this id instead of the original Id and this id is supposed to be only used by the list widget, hence platform is not recognizing this and we end up with an invalid canvas widget state as a result, App crashes. The above solution to restrict widgets with meta property from being dropped inside the list widget should solve this issue.

**Comment by sbalaji1192** [comment]
fixed as part of https://github.com/appsmithorg/appsmith/pull/10928

**Comment by dilippitchika** [comment]
@sbalaji1192 reopening this issue, but with a lower priority. We can still drop blacklisted widgets by dragging them into the canvas first and then dropping them into the list

**Comment by sbalaji1192** [comment]
@dilippitchika  I did discuss this with @riodeuno . There is an open story to address this issue - https://github.com/appsmithorg/appsmith/issues/10659 . Lets close this and track this over there

**Comment by dilippitchika** [comment]
Got it, could you please add a note/update the issue #10659, it's not very understandable for non-developers

**Comment by riodeuno** [comment]
@dilippitchika I have updated the task details in #10659 However, it is still quite technical in the description.
