### ISSUE TITLE
[Bug]: The update query fails in Crud pages

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#10748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The update query Fails in Crud pages 
![image](https://user-images.githubusercontent.com/45958978/151769399-77863fc9-9a4f-4072-a571-660a4d70fe6e.png)

### Steps To Reproduce

1. generate a crud page
2. Now Try to update the data form update form
3. try to update data from input widget
4. For few the input widget the extra spaces is created when user types the data in input widget
5. Now click on update 
6. The update query failes

### Environment

Release

### Version

Cloud

**Comment by sumitsum** [comment]
The error that we are seeing here is expected behavior. The `gender` field is mapped against a `Postgres` db column whose data type is `bpchar(120)` - internal name for `character(n)` type - it is a fixed length field which does padding with space to always store a `n` length string. Hence, any attempt to store a char seq of length greater than the designated length will cause an error. Quoting from the documentation: 
```
An attempt to store a longer string into a column of these types will result in an error, unless the excess characters are all spaces, in which case the string will be truncated to the maximum length. (This somewhat bizarre exception is required by the SQL standard.) If the string to be stored is shorter than the declared length, values of type character will be space-padded; values of type character varying will simply store the shorter string.
```
Ref: 
https://www.postgresql.org/docs/current/datatype-character.html
https://www.postgresql.org/message-id/6312.979871228@sss.pgh.pa.us
