### ISSUE TITLE
[Bug]: Unable to download file from Image widget when file uploaded from local device

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#10753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The image uploaded via local device is not getting downloaded but redirecting the link to new tab and nothing happens there

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/d0dc87174f814407ba36a1a39c1e30fb-00001.gif)](https://www.loom.com/share/d0dc87174f814407ba36a1a39c1e30fb)

### Steps To Reproduce

1. Add Image widget to canvas
2. Add File picker widget to canvas and bind it with image widget {{FilePicker1.files[0].data}}
3. Upload any files from your device using File Picker widget
4. Enable download option from property pane of Image Widget
5. Try to download the image you have uploaded

### Environment

Release

### Version

Cloud

**Comment by wmdev0808** [comment]
@somangshu , @Tooluloope 
This issue is production specific issue, in particular, CSP(Content Security Policy) relevant one.
Our current CSP setting doesn't allow data url, so it is blocked and lead to the above issue.
That's why, this issue should be handled by server-side

**Comment by Tooluloope** [comment]
@somangshu who should we alert on this,
And should I close this issue?

**Comment by somangshu** [comment]
@sharat87 can you check this out please

**Comment by sharat87** [comment]
This is because our CSP  doesn't allow connecting to image URLs, `data:` or otherwise. But this is _release_ environment only, not production.

I can add this to the CSP to allow this, but I'm wondering why this was implemented in such a way. If the download button was a `download` link, something like this:

```html
<a href="data:base64ImageURI" download>
```

Then it would work without the need for whitelisting more things in the CSP right? I think it won't even open a new tab, it'll just download, much cleaner even. No Javascript needed even. Any reason we aren't doing that instead?

**Comment by sharat87** [comment]
Example of what I'm detailing in my previous comment:

![Screenshot 2022-02-17 at 18 26 47](https://user-images.githubusercontent.com/120119/154486444-5974ab84-cc9a-4676-b3f9-31f925acf620.png)

**Comment by techbhavin** [comment]
@sharat87  Here we were facing a CROS issue with 3rd party URL which has Disable CROS. so users can’t download images. 

related issue [5764](https://github.com/appsmithorg/appsmith/issues/5764) 

cc: @somangshu  @wmdev0808

**Comment by sharat87** [comment]
@techbhavin Same problem. We are trying to load the image like an XHR, CORS will be denied, that's the default behavior. Since we actually don't do anything with the loaded data, a download link works best in my opinion. It'll work even if the image is an external URL, is a `data:` URL, is an Appsmith image URL, it'll work irrespective of CORS. Can we move to use that for the download link here?

**Comment by techbhavin** [comment]
agree with @sharat87,  we can continue with your suggestion 

 @wmdev0808  can you plz continue with @sharat87 suggestion

**Comment by somangshu** [comment]
@techbhavin I suggest you take this up since you have worked on it before, I dont understand why this is in review right now, Moving it back to product backlog and assigning you

**Comment by somangshu** [comment]
@techbhavin please confirm with @wmdev0808 if there is a PR that exists already
