### ISSUE TITLE
[Bug]: Race condition in updating meta property of widgets during first evaluation

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#10818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Currency Input gets mounted, it formats the text and stores it in meta property. This value gets overwritten by the evaluations when it updates the meta property of the widget with defaultText during first evaluations. As a result currency input value and `CurrencyInput.text` are differing. Refer loom
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/12a2ac078d9a458c9dbe7636f86f0349-00001.gif)](https://www.loom.com/share/12a2ac078d9a458c9dbe7636f86f0349)

### Steps To Reproduce

1. Add a currency widget
2. Set default value as 10000
3. Refresh the entire application. Currency input has 10,000 (formatted) as value but `CurrencyInput1.text` has 10000 (unformatted).

### Environment

Production

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
This issue occurs because as per new changes, defaultValue on eval updates meta value inside data tree and meta reducer.

1. Eval cycle -   text = {{defaultText}} = 10000 
2. In PhoneInputWidget's `ComponentDidMount` we have  `updateWidgetMetaProperty` changing text in metaReducer to `10,000`

In the next eval, cycle it was noticed that the metaReducer value was updated to `10000` which is an old meta value.

This indicated after eval we received an old meta values instead of new, This needs to be debugged further.
