### ISSUE TITLE
[Bug]-[120000]:Status details section in the API Response view needs Adjustment

### ISSUE THREAD

**Issue by danieldare** [appsmithorg/appsmith#10959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The API Response view needs to show the success status scenario in its entirety

https://user-images.githubusercontent.com/25982036/152947924-5e6adc8f-a0fe-4dd0-a10c-b589108ffb81.mov

### Steps To Reproduce

1.  Create a GET Request
2. Check the status code.
3. Observe that the success status is not shown in full.

### Environment

Release

### Version

Cloud

**Comment by parth-appsmith** [comment]
Concatenation of status to only show the error codes was a solution to a previous bug [#6862](https://github.com/appsmithorg/appsmith/issues/6862).

> message overflows in the API pane when the error message is too long.

The idea was to only show error messages because error codes are universal and the code conveys the type of error that has occurred. I understand that we have some appsmith specific error code, we should try sticking with universal error codes as they are easily recognized by users and they dont need to learn new ones which are just specific to appsmith context.
As far as this design is concerned the hovering on three dots was supposed to show a tooltip and not the whole error message in the pane itself. 

![image.png](https://images.zenhubusercontent.com/616e6ca5bc03b81db0d9e2a0/8e175ac4-fc34-4a3a-bf7e-b2aa0f8cbbee)

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | <<number>> |
