### ISSUE TITLE
[Enhancement]: Map widget reskinning

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#10980]
https://www.notion.so/appsmith/Map-b799350c9cf44bf7bcd39efdc76385ef

**Comment by dhruvikn** [comment]
The only change needed here was to theme the Google Map Search and Zoom Controls. However, for these small changes, we'll need to create [custom controls](https://developers.google.com/maps/documentation/javascript/examples/control-custom) to change the styles, and check their compatibility with react-google-maps. Moreover, since theming Google Maps is not in our designs, I'm closing the issue. 

PS - Maps component states in our Design -

<img width="705" alt="image" src="https://user-images.githubusercontent.com/22471214/190396028-0d80f4f5-3668-4781-8685-5693c7c8e2ac.png">
