### ISSUE TITLE
[Bug]: Make JS Object page consistent with Query and Api pages.

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#11008]
Description

- The name/ title component of the JSObject is different from that of Apis and Queries.

<img width="247" alt="Screenshot 2022-02-08 at 11 26 12 PM" src="https://user-images.githubusercontent.com/458946/153047263-d5a7f787-ebd3-4126-862c-d4bbc8da0e48.png">

<img width="272" alt="Screenshot 2022-02-08 at 11 26 06 PM" src="https://user-images.githubusercontent.com/458946/153047268-41a9d83d-891c-4582-865b-34bf103131bd.png">

- The JS Object UI doesn't seem the same as our queries. It is moving positions like in the video below

https://user-images.githubusercontent.com/46670083/166943948-d324f444-eebb-49e2-b9b2-2121727df4f9.mov

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

See Description

### Steps To Reproduce

1. Create a JSObject. See the UI. 
2. Create an API. See the UI.
3. Create a Query. See the UI

### Environment

Production

### Version

Cloud

**Comment by adarshlilha** [comment]
hey @mohanarpit can I take this up? thanks

**Comment by devnamrits** [comment]
Hi @mohanarpit, have made some changes.
<img width="291" alt="Screenshot 2022-03-09 at 9 25 59 AM" src="https://user-images.githubusercontent.com/54183698/157369901-95a6f7d4-be73-43ee-8227-786f9324b454.png">
Will this work fine??
Also, I've gone through the code as well.

The change at two places is due to the existence of two different components of almost the same type. They are as follows:

https://github.com/appsmithorg/appsmith/blob/cd3c8c0c9658e1d1d80b7bfb0a695f4699943166/app/client/src/components/editorComponents/EditableText.tsx#L168

and 

https://github.com/appsmithorg/appsmith/blob/cd3c8c0c9658e1d1d80b7bfb0a695f4699943166/app/client/src/components/ads/EditableText.tsx#L86

I think changes are configured differently in the JSObject one, which is the recent one. I guess, it is configured in a way to display ads as well.

Can you please tell me how to proceed further??

**Comment by amandaqiu1** [comment]
Hi @mohanarpit, may I work on this issue? Thanks.
