### ISSUE TITLE
[Bug]: Text should be visible always if only 1 long text option is selected in Multi-select widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the options in the dropdown have long text name then Multi select and Multi Tree select widget displays **+1more** instead of text name

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/43824fa013c74d0da9f847309993deb3-00001.gif)](https://www.loom.com/share/43824fa013c74d0da9f847309993deb3)

Enhancement: If we have long text name in dropdown list, truncate the text if only 1 option has been selected

### Steps To Reproduce

1. Add Multi-select or Multi-tree select widget on the canvas
2. Add long text option in the dropdown list
3. Observe that truncated text name is not displayed instead of **+1more**

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
Hey @chandannkumar the reason we don't truncate text is because we will have to truncate again when another item is added. 

More the items, more the truncation which won't be useful for anyone. To navigate around this, we simplified by adding +1 +2 etc. 

I don't see a strong reason to change this to truncation.

**Comment by chandannkumar** [comment]
Thanks @dilippitchika  for sharing this information. I agree to keep this as it is now.
