### ISSUE TITLE
[Bug]: Widgets inside a container widget must not alter in size when resizing the container

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Widgets grouped inside a container must not auto-resize when container size is changed.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f310ab59058e4bf89855239779259b8d-00001.gif)](https://www.loom.com/share/f310ab59058e4bf89855239779259b8d)
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/47d394034a5c4d9e94cd2e1270fd48f4-00001.gif)](https://www.loom.com/share/47d394034a5c4d9e94cd2e1270fd48f4)

An additional feature that could be added to enhance user experience would be to provide an auto-pad option when widgets are placed within a container.

### Steps To Reproduce

1. Group haphazardly placed widgets or place widgets inside a container widget
2. Attempt to create a boundary for the widgets and observe that child widgets vary in size as container widget is changed

### Environment

Production

### Version

Cloud

**Comment by Tooluloope** [comment]
@dilippitchika What would be the desired behaviour?

**Comment by dilippitchika** [comment]
I am not sure why this was done in the first place, i still struggle with this. 

@somangshu @momcilo-appsmith @Nikhil-Nandagopal container resize after adding something changes the width of children. 
This then prompts the dev to resize everything inside again. Can you give us insights as to why we built it this way?

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika @ramsaptami this is the expected behavior and not a bug. Would like to understand why you're struggling with this? We can discuss an enhancement to improve this experience

We do this for a few reasons today
- Fluid width and responsiveness. As screen sizes change, the widgets need to scale to accommodate them
- When moving a widget into a container, if it doesn't resize, it cannot fit into the container
- When designing UI inside a container, I generally ensure that the relative positions & sizes of the elements look good and later tend to tweak the position and size of the container because the size you allocate for the container keeps changing as you add new widgets and get new data. If I had to realign and resize every widget every time I tweaked the size of the container, that would be incredibly harrowing. So please consider the app builders' flow while thinking through this as a problem and solution.

**Comment by dilippitchika** [comment]
For me, i believe we can have a different experience while building a container vs responsiveness in the view mode. While building things for theming and other apps which largely relied on making sure the containers and the components inside it are properly sized, when I change the container width slightly other elements also change their positions which then frustrates me. 

If i was able to lock elements in a container while resize or make sure the elements occupy more width than basic by default would help me not to resize everytime.

I understand that no-one may have complained about it, but we can look at evidence in smartlook on how people have had to re-arrange stuff in a container. Even a simple discord/intercom survey would fetch us responses to this.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika Agreed let's look at smartlook for videos regarding how people are building UI. I don't think a survey is good here because it's very hard to communicate or be self-aware of this interaction when you're building.

Could you also share a picture of a container that when resized frustrates you?

**Comment by Nikhil-Nandagopal** [comment]
Here is my UI. Whenever I add a column or remove/resize a column in the table, I need to resize the detail view and if I had to redo this for every widget inside the details view, that would be crazy. Similarly whenever I need to change the size of the modal or give the chart more room because of a new data point, if I had to re-adjust the table, it would be very painful
<img width="1272" alt="Screenshot 2022-02-26 at 2 26 10 PM" src="https://user-images.githubusercontent.com/3897254/155837044-1315419f-fc99-4aac-9c8e-b4b8f4555569.png">
<img width="1101" alt="Screenshot 2022-02-26 at 2 25 52 PM" src="https://user-images.githubusercontent.com/3897254/155837039-da768ff6-8053-4f3d-92a7-9869dc8050db.png">
<img width="1675" alt="Screenshot 2022-02-26 at 2 25 38 PM" src="https://user-images.githubusercontent.com/3897254/155837027-576b77f0-8fd5-4a01-8de4-63eab25c9d79.png">

**Comment by ramsaptami** [comment]
The root cause of the problem for me when dropping widgets into a container box is that my expectation is: I can resize the container to align widgets inside aesthetically without altering child widget size. Since we don't have grids where widgets snap into place, the experience of resizing the container box is painful (seen in the video attached to the issue). I'll need to plan where child widgets need to be exactly and then drop them in.

Another case is when the container already has widgets placed inside, and then while trying to place more widgets by expanding the container causes all child widgets to resize. This essentially adds another step where I have to reduce the size of child widgets and then place new widgets. This happens more when the container is being horizontally expanded.

Arranging widgets inside the container is a lot easier when widgets are grouped post placing them in the positions but the problem repeats when trying to add more widgets inside the container.

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami thank you for that detailed explanation!

**Comment by momcilo-appsmith** [comment]
@Nikhil-Nandagopal @dilippitchika @ramsaptami 
I think we have 2 problems here and I agree with both of them. These two problems are unrelated to the responsiveness for the appviewer.
1. Sometimes you want everything to resize (@Nikhil-Nandagopal's example) because you need widgets inside the container to fill the width of the container.
2. Sometimes you don't want everything to resize (@ramsaptami's example) because all you want to do is to resize the container, and widgets inside of it do not look good if they are smaller or bigger, so you have to resize them again.

I don't think solving for any of the two only is the right way since the other problem will still exist.

**Comment by momcilo-appsmith** [comment]
The solution that I have at the moment is to ask the developer what does he want to do (a standard way is locking a widget).

**Comment by Tooluloope** [comment]
Probably a Property on the Container to lock the widgets in Place would help solve both Scenarios.

**Comment by Nikhil-Nandagopal** [comment]
I think we should start by solving some of the base problems first. 
- The real pain is that it's so slow to resize stuff and that amplifies this problem because fixing the alignment & positioning is a huge pain.
- We cannot group resize items so if the size breaks, we need to manually update every item's size, which is painful.
- Solve for some obvious cases like when moving from outside a container to inside, maintain the size by resizing to the nearest grid of the original size

I think if we do these 3, then we'll know whether this is really still a big pain and can start thinking of whether it should be locking or not resizing in any case or having a way to resizing the container without the children etc.

**Comment by momcilo-appsmith** [comment]
@Nikhil-Nandagopal What do you mean by resizing to the nearest grid of the original size?

**Comment by Nikhil-Nandagopal** [comment]
@momcilo-appsmith it means it should retain it's size

**Comment by Nikhil-Nandagopal** [comment]
Not relevant anymore with Anvil and was expected behavior

**Comment by computrav** [comment]
I'm a bit confused why this was closed, or why it's not relevant anymore. I am doing layout on a new app in which I have text widgets inside a container. I want them to be a fixed size. I totally understand the use case for fluidity -- yet I find it hard to believe that the use case of "keep my 10 text boxes the width I set them" is not valid. 

Simple example: i create an empty container and make it about 50% of the screen width. I drop a handful of wigets inside, and resize them to my liking. I then end up with "excess" width in my container, so I go to reduce the size -- and it makes all of my widgets narrower. Then I have to manually increase the size. Another example -- which is even more frutsrating -- I want to "insert' a new widget in between existing ones. First, I need to make room, so i have to make the container wider -- and doing that stretches out the width of the existing widgets (annoying part one). Then I move things over and put in a new widget. Now I want to get them the size I want, so I adjust... but then have extra container width, so I reesize it -- then the widgets all change again. it's a vicious loop and incredibly laborious to get just right.

To me, it's not about "locking" elements in a container, it's simply about providing an option whether or not to resize elements when the container size changes. 

Is this possible as of now?
