### ISSUE TITLE
[Bug]: some .jpg images don't load in the Image Widget

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#11206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to display a .jpg image in the image widget when being loaded from a URL, it doesn't display the output, and continues to display the default image. Some examples are:

http://eimages.valtim.com/acme-images/product/m/h/mh01-gray_main.jpg
https://www.simplyrecipes.com/thmb/nAuodqCn_xVyOfRCuqIwQ-j1izo=/2000x1333/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__simply_recipes__uploads__2007__05__mango-chutney-horiz-a-2000-2b99607680ef4c0fb0dcd470d158982d.jpg

### Steps To Reproduce

1. Add an image widget to the application
2. Enter any of the above URLs

The image doesn't load when it should

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@somangshu @sbalaji1192 can we look into this?

**Comment by sbalaji1192** [comment]
The first URL has problem with the same-origin policy, it's not loading on the [js fiddle](https://jsfiddle.net/91d7wogj/) as well.
The second URL is not getting displayed because we're not properly escaping the special character in the URL in widget.

Currently, we show the default image when the given URL is not getting loaded. I think we should show the error instead of showing the default image as a fallback when something is wrong with the URL.
