### ISSUE TITLE
[Bug]: Comment box on Git commit overlaps with other UI elements when box is expanded

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Comment box on Git commit tab overlaps as seen in the video when the box is expanded.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/9111b07bedcf4aa69ea39799144799aa-00001.gif)](https://www.loom.com/share/9111b07bedcf4aa69ea39799144799aa)

### Steps To Reproduce

1. Try to enlargen the comment box on Git pop-up and observe the elements overlap

### Environment

Release

### Version

Cloud

**Comment by IAmAnubhavSaini** [comment]
I cannot reproduce it on linux on firefox and chrome.

It can be because of spell-check, or grammarly extension. But those things didn't affect the view on linux, in both the browsers. 

Linux, chrome:
![Screenshot-2022 02 18-13 06 47](https://user-images.githubusercontent.com/1573771/154638975-f7dc2dfb-3d72-482d-820d-35d68361f589.png)

Linux, firefox:
![Screenshot-2022 02 18-13 07 11](https://user-images.githubusercontent.com/1573771/154639009-a20b1a33-c9cc-4898-8f20-bfb0b124311d.png)


This needs more investigation.

**Comment by IAmAnubhavSaini** [comment]
Reproducible on Mac.

Mac, chrome:

https://user-images.githubusercontent.com/1573771/155090011-aef34c2c-042e-4720-88f2-2b277b6cdde1.mov

Mac, firefox:

https://user-images.githubusercontent.com/1573771/155091047-3b0cf8e7-ac27-45cb-87e2-0d009dafc586.mov

**Comment by ramsaptami** [comment]
Looks like Windows and Mac systems have this issue
