### ISSUE TITLE
[Bug]: Syntax error is displayed when table column name starts with numeric value

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a table column name has a restricted keyword, debugger shows syntax error during computation

![image](https://user-images.githubusercontent.com/79509062/154490613-977b69c0-8444-46c9-9824-3a8184caa6fe.png)

![image](https://user-images.githubusercontent.com/79509062/154489619-f08d2dc4-ad00-4420-9f8f-ee58654e1a67.png)

### Steps To Reproduce

1. Use a google sheet datasource with reserved keywords present on the column names and observe the syntax error on debugger as seen in the screenshot above

### Environment

Release

### Version

Cloud

**Comment by nidhi-nair** [comment]
Seems to be an issue with how the table widget handles column names in computed value. The dot notation breaks for columns that start with a numeric literal (like `123_col`). The computed value would have to user square bracket notation instead (like `{{ currentRow["123_col"]`).

**Comment by dilippitchika** [comment]
@sbalaji1192 can you link this to table v2 issue that you solved for the same? I believe this is being solved there with the apporach we are taking.

**Comment by shadabbuchh** [comment]
This issue is resolved. Tested the same in DP and now the user does not get any syntax error if the Column name(s) start with a numeric value.

![Screenshot 2022-05-24 at 12.34.37 PM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/9bcc5b53-c39d-454b-b483-390b3c791500)

![Screenshot 2022-05-24 at 12.34.51 PM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/ebfd7cd8-3f0e-4f72-af91-dfd4053ae3fb)

Moving it to `Done`.
