### ISSUE TITLE
[Feature]: Allow users to export, clone & fork application at branch level 

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#11270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For the git connected application we should allow the users to export a specific branch changes.

### Why should this be worked on?

- Fall back mechanism incase the app is messed up due to bad commits and migrations

**Comment by abhvsn** [comment]
We already have APIs for these functionalities, client-side execution is pending. Reassigning to relevant folks to take this further as community member on discord requested for this feature.

**Comment by hiteshjoshi** [comment]
Closing this for now. We will come back at this later.

**Comment by ame-appsmith** [comment]
[Another BE user](https://internal.appsmith.com/app/oracle/ticket-details-662d74ffc3e4d34941e56ede?zid=cnv_1e8nupl8) requested this feature.

**Comment by sondermanish** [comment]
We can export our git connected application on branch level, we need to follow the steps shared in this video in order to export on a branch level.
https://www.loom.com/share/e5a573dd939642259cc29904adfd10b4
Steps:

- Open the git connected application
- Checkout to the desired branch
- Click on the Top Center app and workspace name options, 
- Click on export application
- Save the JSON
