### ISSUE TITLE
[Bug]: filter un-necessary global autocomplete items

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#11310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

e.g. latLong, dropdownOption, chartData etc...

<img width="314" alt="image" src="https://user-images.githubusercontent.com/66776129/154941316-54163b09-63fa-4791-a055-8bec12179701.png">

### Steps To Reproduce

1. Open a JS binding {{}}
2. type `latLong`, `chartData` etc...
3. These are not entities that should be listed as suggestions.

They are internal types used within widgets. And should be filtered.

### Environment

Production

### Version

Cloud

**Comment by spark-c** [comment]
Hey, I'm working on Chart docs -- is `chartData` going to be removed from autocomplete suggestions?

If so, I won't bother documenting the property. Otherwise, I was probably going to open a ticket asking for a cleaner workaround for using it, as currently you have to use something like
```javascript
{{ Chart1.chartData[Object.keys(Chart1.chartData)[0]].data }}
```
in order to actually access the series data 😂

**Comment by eco-monk** [comment]
@spark-c, this bug only focuses on the global entries. (e.g. `chartData`)
Not the chartData inside a chart object. (e.g. `Chart1.chartData`)

---

Please feel free to join our discord server, we have a dedicated channel for support queries.

**Comment by spark-c** [comment]
*AH*, thank you! I didn't notice that detail :)
