### ISSUE TITLE
[Task]: Design improvements in API Editor 

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#11374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Headers Tab
- Show a list of standard headers which can be added to the query
- Add a way to enable/disable a header in the query

### Method Dropdown
- Add typeahead or enable search in the method dropdown

**Comment by parth-appsmith** [comment]
@rashmi-rai right now when we run an api in appsmith, the standard headers are not necessary to written to execute the query in the first place. From what I understand the headers that are expected to be inputted are the API specific header information that needs to be sent in and not standard headers like "content-type, connection & etc".

The postman interaction that you showed makes it easier to select standard headers and enable / disable them, but for appsmith there doesn't seem to be a need to do it. As far as API specific header information, is there a way for us to map out all the possible headers for all api's so that user can select from the list?

**Comment by parth-appsmith** [comment]
#11235

**Comment by nidhi-nair** [comment]
Closing this issue since we have the feature request to track the design task
