### ISSUE TITLE
[Feature]: JSfunction to select table row (&fill Table.selectedRow.{})

### ISSUE THREAD

**Issue by unknown1337** [appsmithorg/appsmith#11509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Goal: navigate to a CRUD page with a selected item (by default) 

### Why should this be worked on?

Example use case: a page that lists todo's also lists the owner (IDx) of the todo (IDy). In case of clicking on the 'edit owner' button we want to redirect the user to the crudUser page with the table row corresponding to user with IDx selected. This allows him to directly change that user.

### Quick and dirty workaround 
1. add a 'defaultFilter' param to the navigateTo request
2. in the target page set the defaultSearchFilter to appsmith.URL.queryParams.defaultFilter

Drawbacks of this workaround:
A). undesired from user experience POV as the user might not be aware that a filter is applied when he wants to show different users/ table rows as well
B). the table search in general (without changing query), for a text field. Theses are non-unique. This for this function to work properly the text field/ query shall be adopted every time such that the primary key can also be search and ensure only one unique results

**Comment by Nikhil-Nandagopal** [comment]
@unknown1337 setting the selected row won't help here because if the data set is server-side paginated, you won't be able to set the selected row since the row may not be present in the first load. The best way to achieve this is:
pass the id of the user you want to select in the appsmith store using storeValue and in the query check if the id has been set and query rows that are -5 and + 5 ids from the id that is set. Then onPageChange, you can clear the ID that is set. If you want the id to even be selected, you can find the index of the id in the table and set it in the default selected row property. Do let me know if this doesn't solve the problem for you.
