### ISSUE TITLE
Remove the "label" text inside label within select family widgets

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

By default when you drag an input, you don't see a label but you see a label for select widgets (select, multi-select, tree-select and multi-tree-select). Please remove the text "label" for consistency until we launch #7064 

### Why should this be worked on?

Top labels are not discoverable in other widgets and this top label also occupies a lot of space in the page. Users remove this and add text widgets as labels.

**Comment by Tooluloope** [comment]
@dilippitchika 
The label helps for dragging.
The Dragging issue we have with multi-select and tree-select is reduced because users have an alternative way to drag using the label part.
If we remove that without fixing the drag issue, it might be difficult for them to drag.

So this would be picked up once that is resolved
