### ISSUE TITLE
[Bug]: Refresh toast message appears whenever a new app is created 

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#11681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time a new app is created, "Hey! There is a new version of Appsmith available. Please consider refreshing your window. REFRESH" messages appears on Release

https://loom.com/share/3461e3499de4433ca40af5eb8d5c75dd

![image](https://user-images.githubusercontent.com/92293815/157018586-6fa99688-fcca-4e70-acbf-58e789497800.png)

### Steps To Reproduce

1. Go to release
2. Create new applications and observe

### Environment

Release

### Version

Cloud

**Comment by somangshu** [comment]
@shwetha-ramesh please understand the right owner, that speeds up the communication.

Also please do not add the POD tags, these things are automated, Add only the feature labels and the pod will be assigned automatically.

**Comment by IAmAnubhavSaini** [comment]
Change added: https://github.com/appsmithorg/appsmith/commit/09eff2347918871c94f5270a14e9bd1c40066315#diff-9eeb6a1a11eacf5e6fabe4f173de9e59f8272a911812f32b6df0c89742c96eed
File: https://github.com/appsmithorg/appsmith/blob/release/app%2Fclient%2Fsrc%2Fsagas%2FWebsocketSagas%2FhandleAppLevelSocketEvents.tsx

**Comment by IAmAnubhavSaini** [comment]
LHS=either of following
```
appVersion: {
      id: process.env.REACT_APP_VERSION_ID || "",
      releaseDate: process.env.REACT_APP_VERSION_RELEASE_DATE || "",
    },
```

from app/client/src/ce/configs/index.ts

OR `window.APPSMITH_FEATURE_CONFIGS.appVersion`

RHS=
```
function* readFromAppSocket(socket: any) {
  const channel = yield call(listenToSocket, socket);
  while (true) {
    const action = yield take(channel);
    switch (action.type) {
      case WEBSOCKET_EVENTS.DISCONNECTED:
        yield put(setIsAppLevelWebsocketConnected(false));
        break;
      case WEBSOCKET_EVENTS.CONNECTED:
        yield put(setIsAppLevelWebsocketConnected(true));
        break;
      default: {
        yield call(handleAppLevelSocketEvents, action);
      }
    }
  }
}
```

where `action: {event: { type: APP_LEVEL_SOCKET_EVENTS.RELEASE_VERSION_NOTIFICATION, payload: [MUST_BE_RELEASE_ID] }}`

The LHS and RHS are not equal, i.e. `process.env.REACT_APP_VERSION_ID || window.APPSMITH_FEATURE_CONFIGS.appVersion != event.payload[0]`.

This is happening only on https://release.app.appsmith.com and not on release branch locally. This makes me believe that there is something wrong with environment (may be the release info is not correct) or socket is not passing the correct value.

Cannot reproduce locally, without changes on release branch.

**Comment by IAmAnubhavSaini** [comment]
Last changes rts files were made by me here: https://github.com/appsmithorg/appsmith/commit/989086337a2f77191d925624d6bd55fa36294402

I guess if we revert this commit, release might stop having issue.

**Comment by IAmAnubhavSaini** [comment]
@hiteshjoshi I have no idea who to contact for fixing build version.

**Comment by sharat87** [comment]
I'm looking into this. The RTS is reporting the version correctly, but client apparently doesn't have the version at all. I'm investigating why.

![Screenshot 2022-03-09 at 09 58 07](https://user-images.githubusercontent.com/120119/157372815-42f9d24f-0983-4f6a-b033-7ae20d49eeec.png)

**Comment by sharat87** [comment]
Okay, so looks like there's two places in the client that can hold this information. One in `index.html`, and another in `index.ts`. The one in `index.html` turns out empty, as in the screenshot in my previous comment. But the one in `index.ts` ends up in the main chunk file, and it does hold the correct version information, as can be seen below:

![Screenshot 2022-03-09 at 10 15 09](https://user-images.githubusercontent.com/120119/157374502-8afcfcd4-c859-405e-b273-b47e702853b9.png)

I think, in the implementation of which value we should consider, we are preferring the empty value here? I'm not very sure. Can we fix it to pick the non-empty value if one of them are non-empty and the other is empty?

If not, we can even remove this entry in the `index.html` file. This value will _always_ be coming from `index.ts`, never from `index.html`, since this is a build-time environment variable, and not a runtime one.

**Comment by sharat87** [comment]
Okay, on a second look, appears I missed one of the comments above. I'm now looking into why RTS is reporting 15 in the version number, instead of 14. 😞 

![Screenshot 2022-03-09 at 10 29 02](https://user-images.githubusercontent.com/120119/157375948-8aeec246-2568-4cea-868d-3cb3d28d378a.png)

![Screenshot 2022-03-09 at 10 29 18](https://user-images.githubusercontent.com/120119/157375986-c3967e31-e0f3-4452-807f-68c6d5d495ca.png)

**Comment by sharat87** [comment]
Cool. This should now be fixed. It's not a single thing going wrong that caused this, it's a few things that were harmless until today. The stars just aligned again. 🤦

Can we verify that it is indeed fixed please?

**Comment by IAmAnubhavSaini** [comment]
Fixed. RTS is sending `v1.6.14-SNAPSHOT`. Thanks @sharat87 

![Screenshot 2022-03-09 at 12 02 41 PM](https://user-images.githubusercontent.com/1573771/157385646-fc0ddc2f-0ca5-4cdc-b0af-a2029b6c93bc.png)
