### ISSUE TITLE
[Bug]: mySQL store boolean inputs false and true as 0 and 1 when table column type is varchar 

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

mySQL insert or update query saves boolean values false and true as 0 and 1 even when column type is varchar

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/97ff9a03db8c4eafba3bd1c1d54a9c28-00001.gif)](https://www.loom.com/share/97ff9a03db8c4eafba3bd1c1d54a9c28)

### Steps To Reproduce

1. Create a CRUD using mySQL table that has a varchar column
2. During update and insert use false and true to update the value and observe that DB stores it as 1/0 instead

### Environment

Production

### Version

Cloud

**Comment by somnathdasadhikari** [comment]
@ramsaptami the issue is not clear. First of all MongoDB automatically identify the data type when we create collection and insert documents in it, thus we don't create any table with data type in MongoDB. Secondly video available in the Current Behavior section is all about MySQL. Can you please clarify?

**Comment by somnathdasadhikari** [comment]
@ramsaptami @sumitsum By default MySQL does not contain built-in Boolean or Bool data type. MySQL TINYINT datatype instead, and converts every Boolean input (true/false) into 0 or 1 which are integer value. Example given below :

![image](https://user-images.githubusercontent.com/17508328/174530545-c591eb51-e34c-49e4-b9aa-43aad734ba9b.png)


If any column is VARCHAR or TEXT type and We want to store Boolean data in it then MySQL should store those values as String of 0 or 1. Example given below :

![image](https://user-images.githubusercontent.com/17508328/174530794-e0f1feac-dda8-4d7d-9e3b-277554970e49.png)


If We have to store true or false into VARCHAR We have to provide input as string ('true' or 'false').  Can we consider this as an issue?

**Comment by sumitsum** [comment]
This issue is occurring because when using prepared statement with mustache binding, the data type of `true` is getting evaluated as boolean and MySQL plugin has handled the boolean type that way: 
```
else if (DataType.BOOLEAN.equals(valueType)) {
                connectionStatement.bind((index - 1), Boolean.parseBoolean(value) == TRUE ? 1 : 0);
            } 
```
Ideally this issue should be resolved within the framework decided by the datatype project cc: @nidhi-nair @rohan-arthur @ajinkyakulkarni . Hence, un-assigning Somnath.

**Comment by subrata71** [comment]
This is not an issue. This is the behavior of `MySQL`. There is no `boolean` data type in `MySQL`. `MySQL` interprets `true` as `1` and `false` as `0`.  Even if you create a table with one column having a boolean data type `MySQL` won't restrict you to do so. It will allow you to create the table and you will notice that the type of your requested `boolean` column is of type `TINYINT`.


<img width="644" alt="Screenshot 2022-10-14 at 9 43 21 PM" src="https://user-images.githubusercontent.com/3524599/195887312-e820e91c-3259-45c6-932a-70331a1f5c1d.png">


cc: @sribalajig @riteshkew

**Comment by sumitsum** [comment]
@subrata71 IMO, the issue here is that the user is trying to store string `true` or `false` but it is getting stored as 0 or 1 (even if `true` / `false` is wrapped within quotes ?) - can you please investigate from this PoV ?

**Comment by subrata71** [comment]
Thanks, Sumit. If I understand the requirement correctly then I would say that it's already resolved.

`{{true}} vs {{"true"}}`
The former is treated as a boolean and the latter is treated as a string now. This is already in release and waiting to be shipped into production through the next release.

@sumitsum

**Comment by sumitsum** [comment]
@subrata71 apologies, the video use case looks slightly different - can you please check if this works or if we can make it work - the user has `{{my_binding}}` where the binding itself receives the value as a string `true` . The intent of the user is to save the string `true` as a string since the column type is varchar.

**Comment by subrata71** [comment]
@sumitsum This should work as you said. 
If the value of `my_binding` is evaluated to string "true" then "true" will be stored in that column.

**Comment by sumitsum** [comment]
@ramsaptami can you please verify if this has been fixed in release ?

**Comment by ramsaptami** [comment]
Still getting saved as 0/1 when the value is false/true @sumitsum

**Comment by sumitsum** [comment]
@ramsaptami asking just for confirmation - were you able to verify the use case exactly as shown in the description video ?

**Comment by ramsaptami** [comment]
Yep, created a CRUD of the same table and inserted true/false values expecting them to save as true/false - which it did thankfully! :) 

@subrata71 @sumitsum 
![image](https://user-images.githubusercontent.com/79509062/196407350-c61279eb-cb0f-497e-9b15-dbf420b7c090.png)
