### ISSUE TITLE
[Bug]-[36.235]:Button labels don't show up on hover when labels are truncated

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#11732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When text in button is longer, we truncate the text but upon hovering on the button we can't see the full text.

### Steps To Reproduce

1. Add a new button widget.
2. Change the label text to see truncation in the button 
3. Observe that on hover button label doesn't show up in the view mode

### Version

Production/Cloud

**Comment by somangshu** [comment]
I dont think we should pick this up, This conflicts with the tooltip prop of button widget, What is the gain in doing this @dilippitchika, do we know people who have paced this problem in the past a lot.

**Comment by somangshu** [comment]
This should be closed if not relevant.

**Comment by dilippitchika** [comment]
I didn't know this has any impact on tooltip, the problem is I can't see dynamic button labels today if they are long. 

This is against our standard truncation behaviour, where we show the detail on hover. Clearly an inconsistency, nothing more. Can be parked outside of the epic for now.

**Comment by dilippitchika** [comment]
Needs validation before we solve it

**Comment by makulais** [comment]
A better solution would be to simply allow a wrap of the button text! In designing apps for mobile devices, the height of the button is often increased rather than the width to provide larger selection areas and you end up with square buttons. But without the ability to wrap button text, the viewer is unable to discern information as easily. And hovering over a mobile app? How do you implement that? Not going to happen. Appsmith needs to provide the ability to wrap text on buttons, and to allow the developer the ability to create those enforced break points with standard UI techniques, e.g. Ctrl-Enter where line breaks appear.

![image](https://user-images.githubusercontent.com/34661597/193275904-2066b037-c580-4d12-a046-9e657d6f3f71.png)

**Comment by jsartisan** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 57.976 |
| Effort (months)  |1 |
