### ISSUE TITLE
[Feature]-[116]:Map Widget - Add MapTypeControl (Satellite/Roadmap)

### ISSUE THREAD

**Issue by dwapps** [appsmithorg/appsmith#11815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add an option to enable/disable MapTypeControl (For switching between roadmap and satellite.)
[https://developers.google.com/maps/documentation/javascript/controls](https://developers.google.com/maps/documentation/javascript/controls)

<img width="439" alt="MapTypeControl" src="https://user-images.githubusercontent.com/59294996/158014259-840f57ab-b821-4604-8c17-4925e5d340c2.png">

### Why should this be worked on?

Some projects require a satellite map instead of a roadmap. 
Currently there’s no way to switch between map types.

**Comment by momcilo-appsmith** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 58 |
| Effort (months)  | 0.25 |

**Comment by raapeland** [comment]
Dear Appsmith R&D,

Any news/plans on this feature request?

My use-case is a backoffice app used to pinpoint the exact location of deployed IoT-devices (fuel tank level measurement).
It would be very helpful for our service personnel to switch to satellite view in order to pinpoint the exact location, for instance "on the south west corner of the gas station". Pure map/road view isn't that detailed always.

Regards,
Rein A.

**Comment by somangshu** [comment]
@raapeland @tf-sodicastech this is not in our backlog yet, Ill try and take up this discussion internally, cant promise a date right now thought. 

If you are willing to contribute (sounds like a small fix) for this feature, Please raise a PR on our repo and let me know here. Ill be more than happy to take it forward.

**Comment by janbre** [comment]
@somangshu I submitted a PR that fixes this
