### ISSUE TITLE
[Bug]-[1400]:Additional rows gets added into the header section on new created REST API

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#11832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user navigates to the Header section on the API it is observed that the additional two rows are automatically added into the section 

### Steps To Reproduce

1) Create an API 
2) Ensure the Header section has two rows
3) Click on the Back option
4) Now navigate to Entity explorer an open the API that was created
and observe

Observation 
It is observed that the rows have been added (From 2 rows to 4 rows have been displayed to the user)

Video Link 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/6ebf2db7bde14c93938905c4d852d964-00001.gif)](https://www.loom.com/share/6ebf2db7bde14c93938905c4d852d964)

### Version

Cloud Release v1.6.14

**Comment by rohan-arthur** [comment]
reach 3500

**Comment by ajinkyakulkarni** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 700 |
| Effort (months)  | 0.25 |

**Comment by AmanAgarwal041** [comment]
We are passing `actionConfigurationHeaders` values to `KeyValueFieldArray` component to render the header values on the ui. If the array value passed to `KeyValueFieldArray` is of length 0, then it. maintains at least length 2. So when the ApiForm is rendered the component gets rendered multiple times with values 0 and then actual headers array, hence it appends two extra array values which results in the above mentioned issue. 
Due to the above description, it seems to be a performance issue.
