### ISSUE TITLE
[Bug]: [execute action] : Send a sentry error when action execute response returns with a non 200 status from the server

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#11841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Also include the git version in the metadata

### Steps To Reproduce

N/A

### Version

All instances

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand can we please not fire this event? We decided that sentry would be only for crash and severe error monitoring so unless the backend is crashing due to a nullpointer, we shouldn't fire this because it distracts us.
Is there any reason you wanted this? What we badly need on sentry is tying the users to the userID
