### ISSUE TITLE
[Bug]: Text overlap from actual widget size when Label name is long text in Select family widgets

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#11844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

![Uploading image.png…]()
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7476a5f7784c4b409f26afda6d913156-00001.gif)](https://www.loom.com/share/7476a5f7784c4b409f26afda6d913156)

### Steps To Reproduce

1. Add any select widget to canvas
2. Add label name as long text
3. Observe the size of the widget and see the long text. It is overlapping the canvas too

### Version

Cloud - Release

**Comment by dilippitchika** [comment]
Being fixed in #7064

**Comment by wmdev0808** [comment]
@somangshu,
 I think the issue has already been fixed by the PR at https://app.zenhub.com/workspace/o/appsmithorg/appsmith/issues/10600.
Could you please check that PR if it is actually fixing the issue?
After that, if this issue is not covered by that PR, please be more specific with the requirements about this PR

**Comment by Tooluloope** [comment]
fixed in #10600
