### ISSUE TITLE
[Bug]: Console logs an uncaught promise when home page is loaded

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#11895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Browser console shows an uncaught promises error logged after loading the home page.

![image](https://user-images.githubusercontent.com/79509062/158565809-54731589-b2c5-4bbc-acf0-4a209b44aefd.png)

### Steps To Reproduce

1. Login and open the browser console when home page has loaded. Observe the error seen about displayed

### Version

Cloud

**Comment by ohansFavour** [comment]
This error is caused by a chrome extension. Observe that this is not seen on incognito tabs nor in other browsers. This is particular to a chrome extension (not sure which one it is).

Checkout [this comment ](https://stackoverflow.com/questions/71517919/typeerror-cannot-read-properties-of-null-dont-catch-data-react#comment126404623_71517919)

**Comment by ramsaptami** [comment]
The error stopped occurring now even though nothing changes extension-wise on my end ... But will keep an eye out for this
