### ISSUE TITLE
[Bug]-[24000]:JSObejct/Query/API shows as "not defined"

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#11943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After reloading an application, the connected data source shows as "not defined" in the code editor.
<img width="960" alt="Screenshot 2022-03-17 at 6 17 25 PM" src="https://user-images.githubusercontent.com/10436935/158811893-57d55e9f-4e85-4a9b-8690-fdf2d3337b48.png">

### Steps To Reproduce

1. Create a new JSObject or Query or API
2. Bind the created object to a button or any widget
3. Turn on the JS editable option if you bound the query to the widget using action selector UI
4. Refresh the page and check the same code where you bound the query and widget to see the error

### Public Sample App

https://app.appsmith.com/applications/6233205d0c166d1757961b3f/pages/6233205d0c166d1757961b42

### Version

Cloud v1.6.16 (released on 17th March 2022)

**Comment by eco-monk** [comment]
Also to be checked by deleting and creating actions/JSobjects. Which are used in the binding.

**Comment by rohan-arthur** [comment]
incidence of `'x' is not defined`, 6m: 
- total 76,000
- unique 1258

On an average, a user sees this error 22 times in a day. Let's generously say that 75% of those times is for genuine error cases. That means I still wrongly see this error 7 times a day.

There are two ways that this problem affects users:
1. when I first see this error, I get confused/panicked/misled that I have either
    a. misspelled the name of an entity
    b. horror of horrors, I have deleted an entity inadvertently 
    c. etc
2. when I see this error several times, I know that this is again a case of appsmith acting sketchy. Over time:
    a. I learn to not trust lint errors anymore
    b. I figure out my own system to debug issues because lint is hinky

with all these in mind, although the impact is "medium", this problem is far-reaching. And over time, that reach can cause the actual impact to increase, but that actions is always working below the quantifiable surface. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 12000 |
| Effort (months)  | <<number>> |

**Comment by Nikhil-Nandagopal** [comment]
This is a serious problem. When can we prioritize it? Users feel like their code is wrong

**Comment by rohan-arthur** [comment]
everything that is reference in the OnClick trigger path suffers from this issue. Example, JS Object, Query
