### ISSUE TITLE
[Bug]: Using code with lint errors inside JS object makes all functions un-runnable on response tab

### ISSUE THREAD

**Issue by eco-monk** [appsmithorg/appsmith#12012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using `eval` in any of the JsObject function. The whole list of functions become un-runnable. 
Even though, they work fine when called elsewhere in application. (e.g. on button click)

### Steps To Reproduce

1. Create a JsObject with the code below
```
export default {
	myVar1: [],
	myFun1: () => { return "abc" },
	myFun2: (index) => {
		return eval("1 + 1")
	}
}

```
2. Notice you're not able to run, any functions from the response tab 
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/66776129/159232656-63ab8347-0784-4cbb-af96-5c66d2356775.png">

3. But they'll work fine if used in widgets.

### Public Sample App

[App export for reference](https://drive.google.com/file/d/1QZXmEI4ReCz_RjwCr4lbkH-Aql_vvHU_/view?usp=sharing)

### Version

Cloud - 1.6.16

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk should we support this or just blacklist eval?

**Comment by eco-monk** [comment]
This bug might be hinting at something else that needs to be fixed.
It seems we are considering all lint errors as JS errors and are blocking the users from running any function in the response tab.
They could be considered warnings instead?

Another case raised by a discord user.
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/66776129/159698520-f4bc1436-36e7-402b-843f-67e8de1d0044.png">

**Comment by eco-monk** [comment]
@Nikhil-Nandagopal, as of now I have only seen one user using eval.
The use-case was:
- A widget name is stored as a string
- And they were using eval to access that widget

 Something like `eval(appsmith.store.widgetName).text`
 where the store maybe updated based on a certain condition/action.
 widgetNames could be - Input1, Input2, Input3 etc...
 
 They could use a switch case to do this instead, but using eval reduced the number of lines they'd write (although prone to more errors in the long run, I suppose)

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk is it a warning or a genuine syntax issue? If it's a warning that's a big problem we need to fix. If it's a syntax error then isn't it expected?
Understood the use case, it's not something we thought about supporting before. Feels like a hack we should avoid and probably expose some safe method to do this

**Comment by zzgvh** [comment]
I reported both of these issues. The JSEditor is now good enough for me to actually dare use it, but it's still prone to slowness so I very seldom edit directly in Appsmith. Rather, I grab all of the code of one JSObject and copy/paste it into an external editor to write code and then copy/paste back the full document into the JSEditor. The external editor automatically formats the code using [prettier](https://prettier.io/). The ternary expression problem stems from how prettier formats long lines, so it's definitely not an error, but a warning generated when Appsmith processes the code guess. When you put the same code in a widget the "?" gets a red squiggly and when you hover over it it's a warning about "misleading line breaks".

As for the eval() I know it's kinda cheeky to use, but when there are four similar widgets, and I need a way to programmatically decide from which I should read a value, doing eval(\`WidgetName${somevar}\`).text beats a five line switch() harangue quite handily :wink:. I have since found that in many cases I can use Form.data[\`WidgetName${somevar}\`] instead to get at a widget in a form. So the ternary issue is actually more annoying.

**Comment by eco-monk** [comment]
@Nikhil-Nandagopal, this should be considered warning because this is not a JS breaking error.
The function will execute fine if used on click / elsewhere.

The problem here is JS object considering this a parse error, which should be looked into.

**Comment by eco-monk** [comment]
Created a different item to address eval blacklisting.
So here, we can focus on address just the linting errors, which are blocking the response tab.

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk then the issue is that we should not block the JSEditor for warnings and we should solve this because there could be other warnings that could cause this as well right?

**Comment by eco-monk** [comment]
@Nikhil-Nandagopal exactly.
We need to see which lint errors are actually syntax errors. And block the response tab only in those cases.

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/12012?planning-poker) with ZenHub @ohansFavour

**Comment by rohan-arthur** [comment]
another test case: 
![Screenshot 2022-05-09 at 14 56 58 (1)](https://user-images.githubusercontent.com/94514895/167430456-781ba9d5-a2dc-4574-a4d1-0f421bbae6f8.png)
