### ISSUE TITLE
[Bug]: k8s setup can't enter admin settings

### ISSUE THREAD

**Issue by Dieken** [appsmithorg/appsmith#12046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I followed https://github.com/appsmithorg/appsmith/tree/release/deploy/k8s to install appsmith on k8s, my k8s cluster can't connect to Internet, it can only accept connections from Internet.

After I explicitly set `APPSMITH_CLOUD_SERVICES_BASE_URL: http://localhost:1234 ` in https://github.com/appsmithorg/appsmith/blob/release/deploy/k8s/scripts/appsmith-configmap.yaml.sh,  I can login successfully and AppSmith almost works,  but the "Admin Settings" page just hangs forever,  the log of appsmith-server shows it's trying to connect to http://localhost:1234.

How can I disable the behaviour that AppSmith tries to connect https://cs.appsmith.com?

### Steps To Reproduce

Described above, it's a fresh install.

### Version

Self Hosed - v1.6.16

**Comment by Nikhil-Nandagopal** [comment]
@Dieken thank you for reporting this!

@sharat87 @sub1983 can we have a look?

**Comment by Dieken** [comment]
The connection error is annoying but it's probably not the cause.   I find another error in the log:

```
 - Unable to read env file /appsmith-stacks/configuration/docker.env
java.nio.file.NoSuchFileException: /appsmith-stacks/configuration/docker.env
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
        at java.base/java.nio.file.Files.readAllBytes(Unknown Source)
        at java.base/java.nio.file.Files.readString(Unknown Source)
        at java.base/java.nio.file.Files.readString(Unknown Source)
        at com.appsmith.server.solutions.ce.EnvManagerCEImpl.lambda$getAll$5(EnvManagerCEImpl.java:278)
```

**Comment by Dieken** [comment]
After manually touch a file at `/appsmith-stacks/configuration/docker.env`,  the admin settings page normally show with default configuration. So in k8s deployment  the admin settings is actually useless because all settings are in environment variables.

**Comment by sharat87** [comment]
Hey @Dieken, Appsmith today needs to access cs.appsmith.com to function correctly. There's a few features in the product that will either not work at all, or fail in subtle ways when it's not able to connect to cs.appsmith.com. Would it be possible to whitelist just this domain so that your Appsmith instance can indeed talk to cs.appsmith.com?

Reg. missing `docker.env` file, that file should've been generated on first startup of the container. If that didn't happen, it's very likely a bug. Can you share how you deployed the Appsmith container on your cluster? Like, what commands did you use and what env variables were set at first launch etc.?

Admin Settings should actually work _reasonably_ fine for on Kubernetes, but if there's environment variables coming in from something like a `ConfigMap`, then those take precedence over what's configured in Admin Settings. In that sense, yes it's not as useful as it is in a `docker-compose` setup. We are currently already exploring options to solve this particular problem.

**Comment by Dieken** [comment]
I use the k8s deployment way, not the helm way because the former looks simpler.

https://github.com/appsmithorg/appsmith/tree/release/deploy/k8s

the `appsimth-server` container used in the yaml above doesn’t generate `docker.env`.

About the network whitelist, I’m afraid that’s impossible, we have very strict network policy in financial industry.  Is it possible to gracefully downgrade when can’t connect to cs.appsmith.com?  The most serve issue is it blocks home page loading because the connection just hangs for a long time due to firewall policy, it can be bypassed by set cloud services base url to http://localhost:1234.

**Comment by Nikhil-Nandagopal** [comment]
@Dieken we don't support air gapping in our community edition. We have plans to support this in our commercial edition that you can talk to us about
https://calendly.com/d/yvb3-dyks/talk-to-appsmith-team?month=2021-11

**Comment by mingfang** [comment]
what is the resolution to this?
I'm running in Kubernetes and I'm unable to open the `admin settings`.

**Comment by mingfang** [comment]
I create this hack around for the problem.
https://github.com/mingfang/terraform-k8s-modules/blob/master/modules/appsmith/server/main.tf#L19
