### ISSUE TITLE
[Bug]: The resource not found error is displayed when a new app is created

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The resource not found error is displayed when a new app is created
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/159406640-79661324-022c-4c74-a9e2-327d156ec191.png">

### Steps To Reproduce

1. Add a new org rename it and add a new app
2. Now delete the app 
3. Delete the org 
4. Now again add the new org 
5. Rename it 
6. CLick on new to create a new app
7. The resource not found toast is displayed

### Version

release

**Comment by AnaghHegde** [comment]
@RakshaKShetty Is this still valid ?

**Comment by RakshaKShetty** [comment]
Yes  @AnaghHegde i am still facing this issue

**Comment by micarner** [comment]
I can take a look at this one if that's ok. 

Couple things here:

I'm able to recreate the issue by:

1. Creating a new workspace
2. Immediately renaming it
3. Immediately creating a new app

Looking at the console output, there are several API calls that are getting 404 responses. The specific one that is triggering the "No resource found" toast is this one:

https://dev.appsmith.com/api/v1/workspaces/645926e6b34d0118faef79e9/members

Response:
`{"responseMeta":{"status":404,"success":false,"error":{"code":"AE-APP-4027","title":"INTERNAL_ERROR","message":"Unable to find workspace 645926e6b34d0118faef79e9","errorType":"No resource found"}},"errorDisplay":"AE-APP-4027: Unable to find workspace 645926e6b34d0118faef79e9"}`

I tracked it down on the server side and that API call is returning an AppsmithException here:

**Comment by micarner** [comment]
Can I take a look at this one? Should have an update here in a bit.

Seeing some funny things, looks like it's being triggered by an API call that is executed every time I try to edit an app, however it only propogates through as an error when following these steps:

1. Creating a new workspace
2. Immediately renaming it
3. Immediately creating a new app

**Comment by AnaghHegde** [comment]
@micarner Sure, i am assigning this to you

**Comment by micarner** [comment]
So this seems to be triggered by the following API call, which is returning a 404:
https://dev.appsmith.com/api/v1/workspaces/645ab04e263a3b4a440e944c/members

Taking a closer look at XHR, the initial request that fails is actually using the ID of the previously deleted workspace:

1. Delete previous workspace A
2. Create new workspace B
3. Rename workspace
4. Create new app
5. XHR call to `/api/v1/workspaces/<id for A>/members` - returns 404
6. XHR call to `/api/v1/workspaces/<id for B/members` - returns 200

I'll play around with it further, but I think that quickly following steps 1-4 are preventing some sort of housecleaning functions from fully completing, which is why that first XHR call uses the old id instead of the new one. Perhaps when it fails it triggers a follow up function that corrects the local state before redoing the API call.

**Comment by micarner** [comment]
The culprit is this useEffect firing before the recently deleted workspaceId is replaced with the current workspaceId in the AppState. I'm still trying to figure out the exact sequence of events and what can be done about it

app/client/src/pages/Editor/EditorHeader.tsx
```javascript
//Fetch all users for the application to show the share button tooltip
  useEffect(() => {
    if (workspaceId) {
      dispatch(fetchUsersForWorkspace(workspaceId));
    }
  }, [workspaceId]);
```

**Comment by micarner** [comment]
So the workspaceId appears to be coming from:

State > ui > workspaces > currentWorkspace

Ideally, we would want this null/undefined so that the useEffect would properly skip the first time. We could do this two ways:

1. Ensure that the DELETE_WORKSPACE_SUCCESS redux action clears out that value
2. Hardcode a function to clear this out on the homepage

As for 1, DELETE_WORKSPACE_SUCCESS removes it from list of workspaces, however that doesn't affect `currentWorkspace`. Even if we changed this, we'd still still be waiting for the async action to finish which would potentially give us the same problem.

The better option seems to be #2. `currentWorkspace` stays populated on the Applications page even though it isn't used until viewing something workspace specific. If we can clear this value out here, it shouldn't trigger that useEffect while also being properly populated by downstream effects as the Editor page continues to load.

**Comment by micarner** [comment]
@AnaghHegde 
I have created a PR that fixes this issue: https://github.com/appsmithorg/appsmith-docs/issues/1227
