### ISSUE TITLE
[Bug]: SSL error when connecting to MySQL from TED image

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#12063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Docker commands for ted:

```sh
docker run --name appsmithted -d -p 2222:22 -p 5001:5001 -p 3306:3306 -p 28017:27017 -p 5432:5432 -p 25:25 -v `pwd`/git-server/keys:/git-server/keys -v `pwd`/git-server/repos:/git-server/repo --pull always appsmith/test-event-driver
```

Here's the repository link : https://github.com/appsmithorg/TestEventDriver

**Comment by sharat87** [comment]
The issue here is that connecting to MySQL from the TED image doesn't work, and throws an SSL error _sporadically_. Disabling SSL also doesn't help.

Currently on-hold since MySQL doesn't seem to be coming up in the latest TED image which @Parthvi12 is looking into. Once that is running, I'll investigate the original issue again.
