### ISSUE TITLE
[Feature] New Screen advising mobile users switch to a desktop for Appsmith

### ISSUE THREAD

**Issue by aakashDesign** [appsmithorg/appsmith#1228]
## Summary

Appsmith experience isn't ideal on mobile devices. After a mobile signup, we should communicate that appsmith isn't yet supported for mobiles.

## Screen Design

<img width="300" alt="Screenshot 2020-10-15 at 6 05 12 PM" src="https://user-images.githubusercontent.com/65771350/96123964-fb016c80-0f10-11eb-96fa-cc7cdf7707b1.png">

**Comment by K-Kumar-01** [comment]
I had some questions regarding the issue.
We only have to display a new screen basically a new UX when the signup is complete for the above purpose

**Comment by Nikhil-Nandagopal** [comment]
@K-Kumar-01 that is correct and this screen has to be displayed only if the app is loaded on a mobile device

**Comment by K-Kumar-01** [comment]
So can i take up this issue. I will try to work on it.

**Comment by Nikhil-Nandagopal** [comment]
@K-Kumar-01 go for it! I'm assigning this to you

**Comment by K-Kumar-01** [comment]
@Nikhil-Nandagopal Do i have to design it as shown in the image or can i create any ux of my choice as long as it seems good.

**Comment by Nikhil-Nandagopal** [comment]
The picture in the description is the ui we would like to use.

**Comment by aakashDesign** [comment]
@K-Kumar-01 Here is the design file, use it for specs
https://www.figma.com/file/rk9VnIDGKTMKSVEVOVKcIx/Mobile-users-caution-state?node-id=0%3A1

**Comment by K-Kumar-01** [comment]
@Nikhil-Nandagopal. Can we show the screen on signup page load. I mean when the user is trying to sign up we can show him the screen therehand only.

**Comment by Nikhil-Nandagopal** [comment]
@K-Kumar-01 we'd like to do this post signup so that we can notify them when we have a mobile-ready version of the app!

**Comment by K-Kumar-01** [comment]
@Nikhil-Nandagopal  @aakashDesign 
This is the design implemented by me in the [sandbox] (https://codesandbox.io/s/awesome-glitter-k0sd8?file=/src/styles.css:0-962)

Also i had a doubt.
When the user will sign up he will land on applications page so we will show the page there i guess in useEffect hook.
This is the way i am thinking of implementation.

1. Check if user is on mobile in useEffect
2. If true check if the router contains signup as history
3. If true show the screen else render the applications screen.

Please tell me if can i implement in this way.

1. 

>

**Comment by satbir121** [comment]
@K-Kumar-01 We do not want to bind this UI to `/applications` route because if a user is given a link for an application, they get redirected to an application. Also, tomorrow we may want to change the default route from `/applications` to something else. Ideally, this should be done on `SignIn/SignUp Success`.

**Comment by satbir121** [comment]
@K-Kumar-01 We can try this: Redirect all routes except `login` and `signup` to `/mobile` when . Now, when you click on `Continue with Desktop version`, you override and enable                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           the routes.
Let's say a user has a application link and the user is not logged in. With the logic given above, it will redirect to `/mobile` page rather than `/login`. So, you have to make sure that redirection to `/mobile` only happens when the user logged in.

Enabling/disabling routes is similar to how some pages are only viewable by logged in user.

**Comment by K-Kumar-01** [comment]
@satbir121  
I think the width one would be a bit buggy as i may open window say in 568 px in my pc by resizing the window. I was able to find the following function:
```
 function detectMob() {
    const toMatch = [
        /Android/i,
        /webOS/i,
        /iPhone/i,
        /iPad/i,
        /iPod/i,
        /BlackBerry/i,
        /Windows Phone/i
    ];

    return toMatch.some((toMatchItem) => {
        return navigator.userAgent.match(toMatchItem);
    });
}
```
As of the redirection part i will try to implement them.
Just a thing i wanted to know. 
Is it possible if someone can tell me how authentication is done here(i mean using jwts and reading them or any other way).
Thanks for the help and clarification.

**Comment by satbir121** [comment]
Check `LandingScreen.tsx`

**Comment by satbir121** [comment]
@K-Kumar-01 Please check `LandingScreen.tsx`

**Comment by K-Kumar-01** [comment]
@satbir121 
I checked the landing page and its using email to check the authentication.
Now as of redirecting to the `/mobile` i am not able to figure out how to do the particular thing. 

What i am thinking:
1. Make the component for mobile screen advise
2. in its useeffect check if the screen is mobile or not.
3. if yes show the html and onlick continue to desktop hide the html else leave it.
4. Use the component in the top level.

**Comment by ofpiyush** [comment]
We'll need one for unsupported desktop browser versions as well

**Comment by Nikhil-Nandagopal** [comment]
Closing since we're now introducing a way for users to build apps for mobile and tablet resolutions
