### ISSUE TITLE
[Bug]: Canvas jitters on page refresh on an application where widgets don't occupy the entire width of the canvas

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Canvas jitters when widgets of differing widths are present and the page is refreshed. Seems to happen more strangely on apps where the widget width is not the entire length of the canvas

### Steps To Reproduce

1. Create a new application
2. Drop any widget and refresh the page. Observe the canvas jitter
3. Drop another widget of a different size and refresh the page. Observe the canvas jitter again
4. Drop more widgets or differing widths and refresh the page. Observe the canvas jitters even more with increasing widths of widgets

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/581c1322417049bebc6a813449c7d2d9-00001.gif)](https://www.loom.com/share/581c1322417049bebc6a813449c7d2d9)

### Version

Cloud

**Comment by jsartisan** [comment]
I am helping @yaldram on this. Will need to get back to him on this by tomorrow

cc: @rohitagarwal88

**Comment by rohitagarwal88** [comment]
@jsartisan / @yaldram : Any update on this?

**Comment by jsartisan** [comment]
@rohitagarwal88 Picking this up now.

**Comment by riodeuno** [comment]
@rahulramesha This seems to be caused by the `UPDATE_CANVAS_LAYOUT` redux update. I could see 5 consecutive updates. Could you help triage this?

<img width="280" alt="Screenshot 2022-05-24 at 12 09 11 PM" src="https://user-images.githubusercontent.com/103687/169965070-24eab79f-2c6e-40f6-b536-359ea480f81c.png">
<img width="265" alt="Screenshot 2022-05-24 at 12 09 07 PM" src="https://user-images.githubusercontent.com/103687/169965079-508b90fe-c66c-4a34-b336-f0bab7c57e0b.png">
<img width="253" alt="Screenshot 2022-05-24 at 12 09 02 PM" src="https://user-images.githubusercontent.com/103687/169965082-d41495c1-15c1-4522-89f8-c30277f2dc7d.png">
<img width="336" alt="Screenshot 2022-05-24 at 12 08 57 PM" src="https://user-images.githubusercontent.com/103687/169965083-d5c545ff-6c38-429c-ae3c-c97acf65a4b0.png">
<img width="293" alt="Screenshot 2022-05-24 at 12 08 54 PM" src="https://user-images.githubusercontent.com/103687/169965091-9a493a23-cc7a-4e44-97de-ac3d2eb7328b.png">

**Comment by rahulramesha** [comment]
@riodeuno @rohitagarwal88, looks like @jsartisan has already raised a PR fixing this and it looks to work really well, without any jitters. https://github.com/appsmithorg/appsmith/pull/13917

**Comment by btsgh** [comment]
Tested and found to be fixed.
