### ISSUE TITLE
[Bug]: Delay in capturing input value

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#12318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Input value is not sent properly to an action.
e.g. if we type "abc" only "a" was getting sent to the function.

User is using `appsmith.store` to store the value and display it somewhere. Problem seems to be from debounce we have and we can not remove the debounce.

Slack thread: https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1648215497106399

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/e84cc1b54c6646bda47572ff61cdce30-00001.gif)](https://www.loom.com/share/e84cc1b54c6646bda47572ff61cdce30)

### Steps To Reproduce

**Setup**
- Create a moderately complex app, you can clone our Aforce app.
- Add an input field, button, and a text widget
- On button click save the input value to appsmith store
- Show the stored stored value in the text widget

**Action**
- Type into the input, and click the submit button very fast.
- Try this multiple times.

**Observation**
- You will see that in some cases text widget is not updating correctly. It doesn't have the complete typed text

Note: Though the recording is on editor, it happens in view mode as well.

### Public Sample App

https://dev.appsmith.com/applications/624151206c86dd5be6fdd5a9/pages/624151216c86dd5be6fdd5c4

### Version

cloud & self hosted

**Comment by ame-appsmith** [comment]
This issue is also similar: https://community.appsmith.com/t/input-box-didn-t-change-value/756/3

**Comment by Rishabh-Rathod** [comment]
### Workaround to temporarily solve the issue.

This workaround will add a delay between submit button click and the actual storing of the input value to make sure the latest changes are picked.

1. Create a JSObject with the code mentioned below. 
```
export default {
	// This will add a delay in storing the input value to store, hence making sure correct value is stored every time.
	init: () => storeValue('tryCount',0),
	storeInput: async () => {
		return this.init().then(()=> {
				setInterval(this.callback,100,'storeInterval');
				return Promise.resolve("Done");
          })
	},
	callback: () => {
		const tryCount = appsmith.store.tryCount; 
                 return storeValue('tryCount',tryCount + 1).then(() => {
			const count = appsmith.store.tryCount;
			if(count === 2){
				storeValue('storeVariable',Input1.text); // widget name
				console.log('STORE',Input1.text); // widget name
				clearInterval('storeInterval');
				this.init(); // reset
			}
    })
	},
}
```
2. Change the widget name from `Input1.text` to your Input Widget name and also `storeVariable` name to your own choice name for the store variable.
3. Use the storeInput using `{{JSObjectName.storeInput()}}` on Submit button onClick.
NOTE:- JSObjectName needs to be replaced with your JSobject's name.

**Comment by rohan-arthur** [comment]
applied priority "Medium" based on [this](https://www.notion.so/appsmith/Applying-RICE-for-prioritisation-08c2a3cf3e2a4bd291e68a0236664ad2).

**Comment by rohan-arthur** [comment]
active app viewers (reported data): 1500

**Comment by Rishabh-Rathod** [comment]
> Looks like a similar issue here - https://discord.com/channels/725602949748752515/760761686549463060/958678136030121994

> This issue is also similar: https://community.appsmith.com/t/input-box-didn-t-change-value/756/3

Both of the mentioned issues were not related to this issue and are separately opened https://github.com/appsmithorg/appsmith/issues/12520 here

**Comment by Rishabh-Rathod** [comment]
For analyzing this issue, we needed a complex application where it was reproducible. 
Thanks to our user @SidHiremath for helping us out with that.

<hr/>

## RCA 


### Problem:

When the user typed for example `"ABCDEF"` in an Input widget and quickly submitted an action using a Button click.
It was noticed that for most of the cases only truncated values like "ABC" was passed on to the action.
Also, when adding a binding to the text widget to check evaluated values. It was noticed that when the user was clicking the button. Evaluated values were "ABC" but it was expected to be "ABCDEF".

### Cause:

To give a rough idea about internal data flow, below are steps with time when user typed and clicked in button. 
> ( this is just for demonstration and the actual value might not be following same time delay )  

1. State when the user typed ABC (time - 0 ms )

| Widget  |  MetaHOC  | denounced function  <br/> (200 ms delay)  |  metaReducer  |  unEvalTree <br/> ( 370 ms) |  DataTree   <br/> (eval 170ms) |
|---|---|---|---|---|---|
|  `"ABC"`  |  `"ABC"`   |  `"ABC"`      |  `"AB"`  |   `"A"`  | `""`  |

2. State when the user typed ABCDEF (time - 200 ms )

| Widget |  MetaHOC  | denounced function  <br/> (200 ms delay)  |  metaReducer  |  unEvalTree  <br/> ( 370 ms) | DataTree   <br/> (eval 170ms)   |
|---|---|---|---|---|---|
|  `"ABCDEF"`  |  `"ABCDEF"`   |  `"ABCDEF"`      |  `"ABC"`  |   `"AB"`  | `""`  |

3. State when user clicks on button (time - 600 ms )

| Widget  |  MetaHOC  | denounced function <br/> (200 ms delay)  |  metaReducer  |  unEvalTree <br/>( 370 ms) | DataTree   <br/> (eval 170ms)  |
|---|---|---|---|---|---|
|  `"ABCDEF"`  |  `"ABCDEF"`   |  `"ABCDEF"`      |  `"ABCD"`  |   `"ABC"`  | `"AB"`  |

When the evaluation of action (Button click) happens in the worker, we will receive the value which was present in unEvalTree i.e., `"ABC"` in this case.

The main cause of the incorrect value passed in action is debounced function inside metaHOC which waits for 200 ms to update the widget state to `metaReducer` and the delay caused by [DataTreeFactory.create ](https://github.com/appsmithorg/appsmith/issues/12966 )

- Q: Why don't we see this issue in the smaller applications?
Ans: This does happen in smaller applications but it is hard to reproduce as `DataTreeFactory.create` doesn’t add much delay for smaller applications.
> DEMO in smaller application

https://user-images.githubusercontent.com/23132741/163672768-e8152d3e-fa3b-4f01-b3e5-1adddd9f82ff.mov

### Solution [DRAFT] 

#### To solve the debounce function problem

We pass all the metaState from metaHOC to the worker and then run actions evaluation according to dependency updating all the widgets meta values in the data tree before running the action.

- Detail steps
Instead of storing metaState in metaHOC, we will need to store it in external storage ( neither react state nor redux state ) 
- i. This external storage will have getter and setter APIs exposed and consumed by metaHOC. ( Initially )
- ii. metaHOC will register `setState` & the `redux dispatch` action to it (callback function) and then update meta values using setter. POC - https://stackblitz.com/edit/react-ts-zamtjn?file=index.tsx
- iii. External storage will force re-render metaHOC by updating its state value which is maintained just for re-rendering metaHOC and after debouncing dispatch redux action.
- iv. When we trigger an action we read the complete external storage state and pass it to the worker.

2.

**Comment by SatishGandham** [comment]
@Rishabh-Rathod , UnEvalTree takes the value in metaReducers. The values in your table should be AB,ABC,ABCD and the same values will be present in data datatree.

here is whats happen

1. User starts typing,
2. Types  AB
3. Pauses for 200ms
4. AB is updated in the meta properties
5. This has to go for evaluations, UNEVAL tree is computed and goes to worker. [main thread is free at this moment]
6. user types CD. In the two  200ms it waits, user click the submit button. It's action is executed with the old data.

You can verify this by increasing the debounce time in updateMetaProperty


Won't it be a simple solve if we debounce getUnevaluatedDataTree instead of debouncing the meta updates? Is it even posisble?

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod, UnEvalTree takes the value in meta reducers. The values in your table should be AB,ABC,ABCD and the same values will be present in the data tree.

@SatishGandham 
Yes, true. I was trying to represent not after evaluation but the current state at that time. As that seems confusing, I have updated it to what you mentioned. Now data tree values are what they would be after evaluation.

**Comment by Rishabh-Rathod** [comment]
> Won't it be a simple solution. if we debounce getUnevaluatedDataTree instead of debouncing the meta updates? Is it even possible?

@SatishGandham Yes, it seems to me this is possible by just removing evaluation to run on `SET_META_PROP`, and instead, we could create a new redux action which we will run in debounced fashion so that evaluation still run with the same delay as before but just metaReducer stays updated now. 

Also, I would like to move the metaHOC state to metaReducer directly. This will also resolve https://github.com/appsmithorg/appsmith/issues/12365 and the complexity of updating stale metaHOC state when we change metaReducer values via data tree changes.
cc: @hetunandu

**Comment by SatishGandham** [comment]
@Rishabh-Rathod , You want to remove redundant data from this step here?
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/MetaHOC.tsx#L126

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod, do you want to remove redundant data from this step here? https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/MetaHOC.tsx#L126

Yes, the metaHOC state becomes stale when we reset a widget or if the default value needs to override the meta value.
As it lies inside a react component, it is difficult to listen to those redux actions and update this stale state.
We have patch fixed those cases earlier by https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/MetaHOC.tsx#L96 & 
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/MetaHOC.tsx#L77 but this logic doesn’t work for all cases and is not an ideal way to approach this. 

If we remove this state, `metaReducer` becomes the single source of truth of all meta values and can be easily updated by listening to any redux action.

- we will only subscribe widgets meta state from metaReducer for each widget. 
- metaHOC stores initialState of the widget and when it doesn't receive value from metaReducer like in the case of reset widget. It will provide the initial state. ( if reset action does that part too then metaHOC will only run denounced EVAL_META_CHANGES to run evaluation as is. )

**Comment by Rishabh-Rathod** [comment]
## Solution Summary

We are going ahead with removing the metaHOC state and making metaReducer always in sync with the latest meta values. 

This resolves https://github.com/appsmithorg/appsmith/issues/12365 core issue of stale metaHOC state.

### How do we trigger evaluations, if not when we setMetaProp in metaReducer?
Instead of triggering evaluation on `SET_META_PROP`, now we will create a new action let's name it `EVAL_META_CHANGES` for now. This will be triggered inside metaHOC in debouched fashion we were updating the metaReducer earlier. 
Resulting in the same behavior in evaluations as before.

#### Other points to note
- We only subscribe widgets meta state from metaReducer for each widget.
- MetaHOC stores initialState of the widget and when it doesn't receive value from metaReducer like in the case of reset widget. It will provide the initial state. ( if reset action does that part too then metaHOC will only run denounced EVAL_META_CHANGES to run evaluation as is. )

**Comment by Rishabh-Rathod** [comment]
<img width="761" alt="Screenshot 2022-04-24 at 1 45 58 AM" src="https://user-images.githubusercontent.com/23132741/164944746-eb4e5422-b8e8-4b65-973b-2ff7cc4a9356.png">

Even after the above-mentioned changes truncated values seem to be still present.

<img width="524" alt="Screenshot 2022-04-25 at 11 47 46 AM" src="https://user-images.githubusercontent.com/23132741/165031199-45eda9fc-116e-4ec4-b84e-c7116440a5c9.png">

The root cause of the truncated issue seems to be related to `inputText` getting the wrong value after evaluation. 

As we have multiple points of failure, the current focus is to fix all of them and test 

- Architectural changes - PR https://github.com/appsmithorg/appsmith/pull/13084 ( ~20 Cypress tests failing  )
- If input widget logic is the cause - POC PR https://github.com/appsmithorg/appsmith/pull/13269
- Small bug in meta values updation logic which could also led to such weird behaviour - PR to fix  https://github.com/appsmithorg/appsmith/pull/13311 ( 2 Cypress tests failing )
