### ISSUE TITLE
[Bug]: New branch creation throws an error when the user switch SSH access from read to write in the git 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#12346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

New branch creation throws an error when the user switch SSH access from read to write in the git 

### Steps To Reproduce

1. Try to connect to a git 
2. Now add an ssh key in the git with a read access 
3. Now come back to the application
4. Try to create a new branch
5. The error will be displayed which is correct
6. Now go back and add an SSH with a write access
7. Now come back to the application and try to create a new branch
8. The error will be displayed but after refreshing the page manually the branch name will be displayed

### Version

release

**Comment by vuiets** [comment]
@RakshaKShetty after step 6, does it work if you hit _Sync branches_ on the branch modal and then try to create a new barnch?

**Comment by AnaghHegde** [comment]
@RakshaKShetty I tired the above steps.  As @vuiets mentioned if refresh the page or click on sync the list shows branch f1. 
The reason for the error is the fact that we push the branch to remote after creating and because of read only access this fails. I am not sure what should we do in such scenario, because if the user try to click on sync branch workflow the stale branch will be deleted.
