### ISSUE TITLE
[Feature]-[445]:Menu Button widget - dynamic `Menu items`

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I'd like to have an option to add the menu options dynamically, using JS.

### Why should this be worked on?

![Screenshot 2022-03-30 at 12 15 38 PM](https://user-images.githubusercontent.com/13262095/160768884-5b28e93e-f5b9-46ac-8834-605f45acfc1b.png)

#### Use case -
I am trying to create an action column to set the status of the current row. I had to manually add all the items and the `onClick` of each one and it is really time-consuming. It would've helped if I could use my JS snippet to generate these.

**Comment by vmatt** [comment]
+1, would be greate to have it. 

I tried to somewhat reverse-engineer the js objects behind the curtains. I first only tried to update a single MenuButton widget. I printed all the records in the MenuButton1 object, and tried to find and update all related records in it. However for some unknown reason, the changes are not updated on the UI. 

Let emphasise, that is still for a MenuButton widget, not a MenuButton widget integrated in a Table, which actually has a completely different structure. 

```
updateMenuButton1: async () => {
  MenuButton1.menuItems["menuItem2"] = {
        "label": "Mö",
        "id": "menuItem2",
        "widgetId": "",
        "isVisible": true,
        "isDisabled": false,
        "index": 1
      };
  MenuButton1bindingPaths["menuItems.menuItem2.isVisible"]  = 'TEMPLATE';
  MenuButton1bindingPaths["menuItems.menuItem2.isDisabled"]  = 'TEMPLATE';
  MenuButton1bindingPaths["menuItems.menuItem2.label"]  = 'TEMPLATE';
  MenuButton1reactivePaths["menuItems.menuItem2.label"]  = 'TEMPLATE';
  MenuButton1reactivePaths["menuItems.menuItem2.label"]  = 'TEMPLATE';
  MenuButton1reactivePaths["menuItems.menuItem2.label"]  = 'TEMPLATE';
  MenuButton1reactivePaths["menuItems.menuItem2.onClick"]  = true;
  MenuButton1validationPaths["menuItems.menuItem2.isVisible"]  = { "type": "BOOLEAN"};
  MenuButton1validationPaths["menuItems.menuItem2.isDisabled"]  = { "type": "BOOLEAN"};
  MenuButton1validationPaths["menuItems.menuItem2.label"]  = { "type": "TEXT"}; 
}
```

**Comment by dilippitchika** [comment]
Job stories - 
1. When working with dynamic data like tables or lists, I want the menu options to be dynamic so that I can only show specific actions.
2. When adding dynamic menu options, I don't want to transform query data so that I don't have to learn something new.

This looks achievable actually, within the menu button we can add a parent field for dynamic. When dynamic is selected, similar to List we allow user to enter the source data which can be linked to any query like the list widget. 

The field config will show a generic menu button where the user can add the text for label by referencing currentItem.

To allow onClick to be dynamic we need to expose a selectedButton property which will have all the details like List.selectedItem. Will work with design on a POC.

CC @Nikhil-Nandagopal

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 445 |
| Effort (months)  | 0.5 |

**Comment by ragnorok** [comment]
This would be great as this could be used for headers on pages with menu buttons to control what the logged in user has access to instead of manually updating each page I could use this to get the information from the database and populate through JS function.  At least until you have multi page widgets working.

**Comment by dilippitchika** [comment]
Adding PRD here - 

Job stories -

1. When working with dynamic data like tables or lists, I want the menu options to be dynamic so that I can only show specific actions.
2. When adding dynamic menu options, I don't want to transform query data so that I don't have to learn something new.

Acceptance criteria
1. People should be able to select menu button type as static or dynamic
2. When static is select the menu button behaves exactly as it does today.
3. When dynamic is selected they should bind a source data of arrays (Tolu to check if only string arrays will work or only arrays with objects)
4. The menu buttons in dynamic has all properties same as static menu button
5.  Binding in the dynamic menu button can be done by referencing currentItem
6. There is a max no. of dynamic menu buttons that can be added (Andrew to update us on the limit)
7. Standard flow like labels and onClicks work dynamically as expected.

Scope of widgets
1. Menu button
2. Table column > Menu button
3. Button group > Menu button

Action items before picking - 
1. @andrewdietekoki @Tooluloope @vivekverma2312  please read the above items
2. @andrewdietekoki please add the link to figma below
3. @andrewdietekoki @Tooluloope please discuss point 6 in acceptance criteria and update in the thread
4. @andrewdietekoki make sure you discuss with @vasanth-appsmith on the updated property pane in the widgets and propose newer versions of property pane.

**Comment by andrewdietekoki** [comment]
Figma Design: https://www.figma.com/file/Dwng9laAPen5uNYArmMt9z/Menu-Button-Widget---Add-Dynamic-Menu-Items?node-id=222%3A2798

**Comment by andrewdietekoki** [comment]
For the limit of Max No. of Dynamic Menu Button items, it can be quite tricky. But I would suggest a maximum of 10 items.
Though we could give a number based on usage by users.

**Comment by vmatt** [comment]
Hey Team,
is there an ETA when this function will get implemented?

**Comment by dilippitchika** [comment]
Hey @vmatt we are planning to pick this up soon in the next few weeks. We will keep you posted

**Comment by dilippitchika** [comment]
@dhruvikn can you create a new issue for doing the same change in button group?

**Comment by dhruvikn** [comment]
Two more issues for adding dynamic menu items inside the table widget (#17955) and in the button group widget have been created (#17956).
