### ISSUE TITLE
[Bug]: `resetWidget` fails to reset the current page number of the Table Widget

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#12365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

A user wants to reset the `pageNo` of the table. This should be possible with the `resetWidget` function.

#### Use Case -
The user has external filters that operate on the table. Every time they change the filter, the pageNo should start from 1. But it stays to what it was before changing the filter (even after using resetWidget). 

### Steps To Reproduce

1. Create a table & add pagination
2. Go to next page (2)
3. Try to reset it on the external button click.
4. You'll see `pageNo` does not get reset back to 1

### Version

Cloud

**Comment by dilippitchika** [comment]
@sbalaji1192 can you investigate this once?

**Comment by sbalaji1192** [comment]
@Rishabh-Rathod This issue is related to https://github.com/appsmithorg/appsmith/issues/9603. 
`widget.meta` contains `selectedRowIndices` even after resetWidget is called on the Table, hence the fix you provided is not working in this case. Could we connect on this and debug?

CC @dilippitchika

**Comment by sbalaji1192** [comment]
Next action:
@Rishabh-Rathod will be working on refactoring metaHOC to fix this issue and similar issues with the reset widget functionality.

**Comment by aswathkk** [comment]
Noticed that `resetWidget` also doesn't reset the `Table.selectedRow`.
@dilippitchika Is it a part of this problem or is it intentional?

**Comment by Constantine9527** [comment]
This problem is repeated in v1.7.9。Here is my code:
`
	list: () => {
		console.log('---------------pageNo---------------',Table1.pageNo)
		resetWidget('Table1', true)		
		console.log('---------------pageNo---------------',Table1.pageNo)
		templateItemsCount.run();
		queryTemplateItemsListByPage.run(function(res){
			return res.data
		}, function(e) {
			showAlert('error', 'error')
		})
	}
`
effect:
![image](https://user-images.githubusercontent.com/20188341/184281216-1993e242-2c8e-485d-833c-5b07b483f182.png)

**Comment by Constantine9527** [comment]
This problem reappears in version v1.7.9 , Then I tried in the Appsmith Cloud and found that the same problem existed。
Here is the public sample app: https://app.appsmith.com/app/testtablepage/page1-62f5e62174d6e95d0a54a3e5

Steps To Reproduce
1. Create a table & add pagination
2. Go to next page (6)
3. Enter "Erin" in Name field, and  click the Submit button.
4. You'll see there is no data in table, but Erin Newman should be show, I found it because the Table Widget's  pageNo does not get reset back to 1.

https://user-images.githubusercontent.com/20188341/184306892-2c2a973f-8f53-4b5c-857b-7629c7837605.mov

Uploading demo2.mov…


My Submit js function:
![image](https://user-images.githubusercontent.com/20188341/184307167-2b5fb32e-3bdc-4e64-a7cc-5b9eba2598f9.png)


My Query sql:
![image](https://user-images.githubusercontent.com/20188341/184307215-ade2dfe4-281c-4430-aa2d-f52e40171e7c.png)

@sbalaji1192

**Comment by sbalaji1192** [comment]
@Constantine9527 Could you give me edit access to the applications `balaji@appsmith.com` ?

**Comment by Constantine9527** [comment]
> @Constantine9527 Could you give me edit access to the applications `balaji@appsmith.com` ?

I have invited you.

**Comment by sbalaji1192** [comment]
@Constantine9527 `resetWidget` is an asynchronous action. so you need to await before calling the `Query.run()` in your js function. I have added await before the resetWidget call and search is working fine now.
CC @Rishabh-Rathod

**Comment by Constantine9527** [comment]
> @Constantine9527 `resetWidget` is an asynchronous action. so you need to await before calling the `Query.run()` in your js function. I have added await before the resetWidget call and search is working fine now. CC @Rishabh-Rathod

Thanks very much.
