### ISSUE TITLE
[Bug]: CVE-2022-22965 Spring Vulnerability Spring4Shell

### ISSUE THREAD

**Issue by clouddistortion** [appsmithorg/appsmith#12514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi unfortunately Appsmith is vulnerable to the Spring4Shell vulnerability. My security scan shows that you are using spring-core 5.3.15 and that the CVE is resolved in version 5.3.18 (Spring Boot 2.6.6) @see: https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement

Please consider updating!

### Steps To Reproduce

See Spring dependency

### Version

1.6.15

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit @sharat87 could you have a look?

**Comment by mohanarpit** [comment]
Thanks for opening an issue and pointing this out. We are in the process of upgrading our spring-boot dependency to address this CVE. 

In the meantime, I'd like to mention that even though this vulnerability shows up in automated security scans, Appsmith is **not** vulnerable to this CVE. This is because the vulnerability requires the application to be run as a WAR via Tomcat. Appsmith is bundled has a JAR file and run on the command line via Netty. Hence, there is no known exploit yet. 

Having said that, in the interest of caution, we are still looking at to upgrade this dependency on priority.
