### ISSUE TITLE
[Bug]-[400]:Select widget's default selectedOptionLabel shows data from the value field and not the label field

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#12554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i drop a select widget and bind a text widget to use selectedOptionLabel, the value shown in text widget is the value and not the label of the item selected by default. 

However, this is fixed when I select any other value by interacting with the widget.

Also happening in the multi-select widget

### Steps To Reproduce

1. Add a new select widget
2. Bind the selectedOptionLabel to a text widget
3. See that it shows the incorrect data

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8950222cc6ee4824acad50fe41d96f6b-00001.gif)](https://www.loom.com/share/8950222cc6ee4824acad50fe41d96f6b)

### Version

Production

**Comment by dilippitchika** [comment]
Reach: 103
Impact: Low

**Comment by prsidhu** [comment]
@dilippitchika This happens when the provided defaultValue is a simple string ("GREEN") instead of an object ({ "label": "Green", "value": "GREEN" })

**Comment by dilippitchika** [comment]
@prsidhu understood, I did not try with the object notation. We are still fixing this right?

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 100 |
| Effort (months)  | 0.25 |

**Comment by wmdev0808** [comment]
@somangshu 
I am increasing the original estimate to 3 because of the following increased complexity:
- selectedOptionLabel/selectedOptionLables, even selectedOptionValues does not work with the select widgets(Select/MultiSelect, TreeSelect/MultiTreeSelect)
- We need to re-calculate the selected labels when the widgets are mounted, defaultOptionValue and even options changes for single source of truth.
- The implementation is even more complicated when it comes to MultiTreeSelectWidget because:
  .  It also needs to be selected in nested way, leading to a recursive calculation of sub-trees
- With all the widgets, Cypress test cases are required to cover all the possible cases in cases of mounting, updating defaultValues and even updating options

**Comment by somangshu** [comment]
@prsidhu @Tooluloope can you kindly review this approach?

**Comment by wmdev0808** [comment]
@somangshu ,
I am increasing the estimate by 1 because of the following reason:
- After receiving @Tooluloope 's feedback on the PR,  
  . Server side filtering needs to be considered for SelectWidget and MultiSelectWidgetV2, resulting in changing the core logic
  . Add additonal Cypress/unit tests

FYI, please refer to the [comment](https://github.com/appsmithorg/appsmith/pull/13079#pullrequestreview-946838604)

**Comment by Tooluloope** [comment]
fixed in #13079
