### ISSUE TITLE
[Bug]: layoutOnLoadActions don't register query/js settings and hence on page actions don't get executed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#12643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

No page load actions either from queries or objects are registered on the `layoutOnLoadActions` 

Sample app with various scenarios to test - https://release.app.appsmith.com/nested-calls/js-js-624dd82bbf89be21c7d4690f/edit

### Steps To Reproduce

1. Mark any API or JS object to run on page load and refresh the page
2. Observe no confirmation box or console logs take place

### Public Sample App

https://release.app.appsmith.com/nested-calls/js-js-624dd82bbf89be21c7d4690f/edit

### Version

Cloud

**Comment by ramsaptami** [comment]
Removing this as a release blocker since we're adding a `Beta` tag

**Comment by sumitsum** [comment]
Unable to reproduce it on my local setup with the latest code. I have also tried importing the same application that is failing on release to my local instance, but the imported application works as expected. I have also asked Saptami to help reproduce it, but we haven't been able to so far. We should monitor this issue for a while and close it if the issue seems un-reproducible.

**Comment by ramsaptami** [comment]
Closing this regressed issue since it seems to have been rectified by some fix.
