### ISSUE TITLE
Perf: Open property pane post dragging or resizing of a widget.

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#12747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

When a widget's property pane is not open and the user starts to drag that particular widget then, the propertyPane of that particular widget opens up at the moment of starting to drag or resize. This blocks the main UI thread and gives the perception of a lag at the start of drag or resize.
This can be solved by making sure the property pane renders or re-renders at the end of drag or resize.

**Comment by somangshu** [comment]
The Root Cause can be divided into two causes,
- The redux States  `isDragging` or `isResizing` is being subscribed in too many components, So we are rendering all the canvases on the canvas and re-render all the `positionedContainer` and `DraggableComponent` of each and every widget on the canvas.
- The Second Reason, is that when we start dragging or resizing a widget, we select the widget, that causes the propertyPane to show up, and This rendering takes a lot of time.
This could be solved by opening the propertyPane at the end of the drag or resize.

[Ref](https://www.notion.so/appsmith/Performance-Findings-ccb489d6101e4ca7ad25ac2e0917b348#c9160aa659664ed88af03922a9f0fa83) by @rahulramesha
