### ISSUE TITLE
[Bug]-[748]:Table widget - Cell background for Step column is applied incorrectly

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#12823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When cell background colour is applied to the Step column, the cell background colour is applied for the entire column as well as the other cells which do not contain data.
It should only be applied to the cells of the Step column, which has data (the first three cells of the step column)

-- UPDATE 10 May 22 @dilippitchika 
- Cell background will be applied to the full column/columns, not just the rows which have data. This is to prevent inconsistency in the UI.

### Steps To Reproduce

1. Drag and drop a table widget onto the canvas.
2. In the Property Pane, go to the Step column settings
3. Choose a Cell Background colour as say orange or yellow
The cell background colour is applied for the entire Step column as well as the other cells which do not contain data. 
It should only be applied to the cells of the Step column, which has data (the first three cells of the step column), as per behaviour of other columns
<img width="1054" alt="Tablewidget_Step_Cellbackground" src="https://user-images.githubusercontent.com/101863839/162881253-8fa4a123-5673-44b4-88da-6c716905435b.png">

### Version

Release

**Comment by Nikhil-Nandagopal** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 374 |
| Effort (months)  | 0.25 |

**Comment by dilippitchika** [comment]
https://github.com/appsmithorg/appsmith/pull/13257#issuecomment-1120945177

@techbhavin @Tooluloope based on the comment in the PR, the issue is updated to the following. A cell background color either at a row or at a column level will always be applied to all the data even if it's empty. This is to maintain consistency. 

@btsgh please review this once as this is different from your expectation. You can find our discussion in the PR mentioned above.

**Comment by btsgh** [comment]
@dilippitchika - took a look at the PR discussion... sounds good (Late response as was on leave last week)
