### ISSUE TITLE
[Bug]: [UI] Padding around Canvas 

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#13111]
### SubTasks

- [ ] Padding around Canvas is asymmetric
- [ ] Padding is probably not required in fluid layout.

**Comment by hiteshjoshi** [comment]
@roopKrrish9696 This needs design.

**Comment by hiteshjoshi** [comment]
@vinay-appsmith do you know who should pick this up?

**Comment by RoopKrrish9696** [comment]
Hey @hiteshjoshi I think we will pick this up alongside with colour swap for the canvas task. cc @vinay-appsmith @kocharrahul7 @aakashDesign @aa

**Comment by Nikhil-Nandagopal** [comment]
@RoopKrrish9696 @vinay-appsmith are we doing a color change to the canvas? Can you share the updated color? We can't update this for existing apps because it will hurt the design of existing apps. What will be the style of apps expected?

**Comment by RoopKrrish9696** [comment]
@Nikhil-Nandagopal To make apps look good we are changing the default canvas color to white and the gutter space to grey ish. Since theming is live, users can still choose their background color. Also there are issues with current theming when the canvas is complete white ( canvas borders are missing ), in this ticket we can handle this as well. From my understanding, this would be better handled by UI builders pod since we need to check for all widgets and how they look if the canvas background color is white. ( afaik , form and container should be looked at ). cc @vinay-appsmith @aakashDesign @kocharrahul7

**Comment by Nikhil-Nandagopal** [comment]
@RoopKrrish9696 @vinay-appsmith pure white might look weird right? Most internal tools ensure there is a contrast between the background and the containers
https://coderthemes.com/hyper/creative/crm-dashboard.html
https://themes.getbootstrap.com/preview/?theme_id=19799
https://themes.getbootstrap.com/preview/?theme_id=6063

This feels like a step back in the direction of making the apps look good by default

**Comment by RoopKrrish9696** [comment]
+1 , yes @Nikhil-Nandagopal this is just a proposed color by abhishek, but imo this is not a small problem, so there should be some exploration to be done around this and as you said, we should relook at the direction.

**Comment by vinay-appsmith** [comment]
Not going to talk about the solution here, but the aspect we need to solve for is that the widgets placed on the canvas have to be sufficiently demarcated from the canvas, irrespective of the background color being used. And the canvas needs to be demarcated from the rest of the UI.

We could achieve this demarcation through a combination of color, shadow, outline etc.

@Nikhil-Nandagopal While we agree that the padding needs to go, we haven't solved for this yet. I think white is a color that a team member proposed. We need to invest a little and iron out the scenarios that this change would affect. @RoopKrrish9696

**Comment by Team-wb** [comment]
To give the developer more control, it would be good to offer padding, as well as width and height, directly as properties. And while we're at it, also provide custom CSS classes at the widget and the ability to create custom CSS classes in the page, as well as define global CSS classes for the application. (Yes, that's a lot, but would be great ;-) )

**Comment by Nikhil-Nandagopal** [comment]
@Team-wb would love to hear about why you think CSS control is essential. Typically we've seen that since Appsmith is used for internal tooling, the number of controls being limited is convenient so long as it ensures consistency and good default. Would love to understand your use case better for #3095
