### ISSUE TITLE
[Bug]: Default Value is not working for Input type fields & date picker when used inside Array/Object type of JSON form

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#13128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2431c4700ed446c7bbd7029aca7a5d6e-00001.gif)](https://www.loom.com/share/2431c4700ed446c7bbd7029aca7a5d6e)

### Steps To Reproduce

1. Add Json form onto canvas
2. Add new field type as Array. Now add Input type field such as Phone Input, Number Input, Multi line Input, Text Input etc.
3. Add any default value in the input types fields and observe that the value are not displayed as Default value

### Version

Cloud/Production

**Comment by dilippitchika** [comment]
@chandannkumar this is not a bug, here's the reason why
There are 2 defaults for an array
1. At the array level - you have a default value which will be an array of something. When you add a new array custom field you see [{"first_field":""}], this is the default array.
2. At the field level - as you showed when you edit this at field level, you see data not changing because we are using the array level default here. You can see the default value you configured at field level when you click add new.
