### ISSUE TITLE
[Bug]: Property Pane - JS Enabled property value is visible only when clicked on the code editor.

### ISSUE THREAD

**Issue by ashit-rath** [appsmithorg/appsmith#13227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a property pane when a section is collapsed by default and a property under that section has the JS mode enabled, the value only shows up when the JS enabled input is clicked.

Note: This only happens if the Section is collapsed by default but not on the opened one as shown in the loom video.

### Steps To Reproduce

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/f202f73819b749699962c416e95212a9-00001.gif)](https://www.loom.com/share/f202f73819b749699962c416e95212a9)

### Version

Cloud

**Comment by btsgh** [comment]
Testing on Release- Only in JSON form widget, Form Styles, Submit Button Styles and Reset Button Styles are collapsed by default. In all other widgets, all the sections are expanded by default. 
1. The scenario described in the loom video for all the JS options, expanding the sections, on enabling JS, going out of the widget property, coming back to widget property and expanding the sections, all the JS property values are retained except the following -

- Border Color in font styles, which is empty as nothing is set for Border color.
- Border width in font styles has no JS option. (Even in Form it is the same)
- In Submit Button Styles and Reset Button Styles, Icon and Icon alignment is not set, hence on JS enable field is empty (will discuss with dev and see if this also can default to none as current behaviour in Box Shadow field for JS enable).
- Placement shows empty on JS enable for the first time (Discussed with @ashit-rath  and raising a separate bug for that)
Verified and this issue is found to be fixed.
