### ISSUE TITLE
[Bug]: Multiple Cyclic Dependency Errors

### ISSUE THREAD

**Issue by awanishraj** [appsmithorg/appsmith#13228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Lately many of our dashboards have started throwing cyclic dependency errors. Looking at the logs, it looks like one of the objects in the dependency map incorrectly adds a reference to itself.

In the below case, UngroupClient.config.formData has an entry for itself. This is causing the entire application to error out and reset.

<img width="382" alt="Screenshot 2022-04-22 at 7 21 16 PM" src="https://user-images.githubusercontent.com/6928709/164728736-a33464ff-9c73-4615-a8eb-dbddd28befc1.png">

Have noticed this in at least 4 different queries, all were MongoDB queries.

While the issue is looked into, is there a way to remove the reference manually for my application?

### Steps To Reproduce

Occurs only for MongoDB queries written a few months back.

### Version

Self Hosted - 1.6.20

**Comment by rohan-arthur** [comment]
Hi @awanishraj thanks for reporting this, we will surely look into it. So you see these errors, and then are you able to proceed with using the app? Or is the app broken?

**Comment by rashmi-rai** [comment]
Right now we don’t know at what point this issue is getting created. We are working to find out the exact cause.
Most likely this issue exist with FIND command. Meanwhile here is a workaround suggested by @Rishabh-Rathod 
1. Open the Mongo query. Change your command to something else, let us say `Update Documents`. Let it get saved successfully.
<img width="296" alt="Screenshot 2022-04-27 at 6 51 18 PM" src="https://user-images.githubusercontent.com/89374972/165527541-2a3147dc-c0f6-48cb-a33b-11a07b5d6568.png">

2. Change the command back to your original command.

**Comment by Rishabh-Rathod** [comment]
@awanishraj Could you please try the above workaround and if the issue persists please let us know. We will need to connect for a debugging session.
