### ISSUE TITLE
[Bug] In SAML auth the data is not retained when user switch between the tabs 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the data is not retained when the user switches between the tabs

### Steps To Reproduce

1. Go to the admin setting page
2. Navigate to the authentication tab
3. Enable the SAML auth method
4.Add a details in the Metadata url and now navigate to XML tab and come back
5. The data will not be retained 

### Version

local

**Comment by ankitakinger** [comment]
This is intentional as users should be allowed to use only one of the 3 methods to configure SAML. Initially, we thought of adding a note on the SAML page to let users know about changing tabs won't retain the values. Later we came to the conclusion to not add anything as it would be obvious either one of the methods has to be used. Closing the issue.
