### ISSUE TITLE
[Bug]-[1500]:Switch Datasources menu in QueryEditor

### ISSUE THREAD

**Issue by rashmi-rai** [appsmithorg/appsmith#13326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we open datasources menu in query editor the datasources which are not compatible shows up.

### Steps To Reproduce

- Create datasource airtable datasource
- Create postgres datasource
- To create query on postgres datasource open query editor
- In the switch datasource dropdown you will also see airtable datasource.
<img width="988" alt="Screenshot 2022-04-26 at 6 38 47 PM" src="https://user-images.githubusercontent.com/89374972/165307049-48d682ad-2206-4be8-8a0a-f8c1f7741a03.png">

### Version

Cloud

**Comment by rohan-arthur** [comment]
event `SWITCH_DATASOURCE`, 
unique: 150
total: 509

This is a ux issue, and the numbers above do not correctly correspond to the number of people who have experienced this.
SWITCH_DATASOURCE is only called when I:
1. expand the dropdown, and
2. select one of the datasource options

We don't know how many times users have simply expanded the dropdown, but haven't selected any option. While this may well be a small number, it is not to be sneezed at, because the values in the dropdown are misleading, and the user might have decided not to make a selection because:
1. they got confused, or
2. if they are exploring appsmith, then they don't know what this dropdown does, and it failed to inspire them to take action

So, I would apply 50% more to the reach above simply to represent the number of users who probably encountered the dropdown.

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 750 |
| Effort (months)  | <<number>> |

**Comment by rohan-arthur** [comment]
decision: this dropdown should show only datasources of the matching plugin of the current query

**Comment by prapullac** [comment]
https://github.com/appsmithorg/TestSmith/issues/1936
Please find the test cases for the same 
Moving it to In progress for adding Cypress tests
