### ISSUE TITLE
[Bug]: Icon is missing in columntype iconButton in tablewidget for exting user

### ISSUE THREAD

**Issue by techbhavin** [appsmithorg/appsmith#13325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

An icon is missing in the column type icon button in the table widget for existing users who have not set the icon name

### Steps To Reproduce

It’s happen on existing user application

### Version

release

**Comment by sbalaji1192** [comment]
https://github.com/appsmithorg/appsmith/issues/9135

**Comment by shadabbuchh** [comment]
This issue is fixed. Tested the following:

1. Adding a column and then changing the `Column Type` to `Icon Button`: The "Add Icon" button gets displayed by default - _Pass_
2. Adding a column and then changing the `Column Type` to `Menu Button`: By default no icon is added to the column - _Pass_
3. In a `Menu Button` column after adding any icon (other than the "add icon"), when the user changes the type of the column to `Icon Button` the "Add Icon" gets displayed by default - _Pass_
4. If a user selects any icon (other than the "add icon") in a `Menu Button` column and then changes the `Column Type` to `Icon Button` and then again changes it back to `Menu Button`, the previously selected icon is retained and the "add icon" is not displayed for the `Menu Button` column - _Pass_

Moving this bug to `Done`.
