### ISSUE TITLE
[Feature] Ability to restrict signups

### ISSUE THREAD

**Issue by seehafer** [appsmithorg/appsmith#1342]
## Summary

The ability to either remove the ability to arbitrarily signup, or restrict it to some whitelist.

## Motivation

For on-premise deployment, if one can guess the relevant URL, then one can create an account for the application. This is sub-optimal and requires the administrator to be manually checking the mongo db for errant accounts.

**Comment by Nikhil-Nandagopal** [comment]
@seehafer thank you for the feature request! We'll prioritise this and update you soon.

**Comment by Nikhil-Nandagopal** [comment]
@seehafer After talking this out, we felt that this doesn't pose a security risk because even rogue users who sign up won't have access to your apps or orgs unless they are explicitly invited by an administrator. So at most they might run an app on your instance and consume a few resources in the short term. An additional layer of security can also be to host it behind a VPN to avoid this entirely. 
As such we're deferring this feature request for a little later down the road. Please feel free to reach out if you feel differently about this.

**Comment by mohanarpit** [comment]
This is partially fixed by #2512 . 

Ideally, the env variables `APPSMITH_OAUTH2_ALLOWED_DOMAINS` should also work for Github OAuth2 and Form signups. Can we make that change as well to close this issue in it's entirety?

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit since we don't verify email addresses we should still not allow domains for form sign up. Those can be invite only. Let's simply disable form login signup only

**Comment by Nikhil-Nandagopal** [comment]
@seehafer this feature is now live so I'm closing this issue
