### ISSUE TITLE
[Bug]: Scrollbar is shown in git sync modal

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#13508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We should not show the scroll at the bottom as it is not part of the designs.

 
<img width="576" alt="image (3)" src="https://user-images.githubusercontent.com/12005551/166408230-02a8016e-6663-4e26-96f0-83f705415e2f.png">

### Steps To Reproduce

Open the git sync modal and then generate the ssh key.
Notice the scroll at the bottom

### Version

Cloud v1.6.22

**Comment by vuiets** [comment]
@AnaghHegde did you attach the wrong screenshot by mistake here?

**Comment by AnaghHegde** [comment]
Yes my bad. I will update it.

**Comment by IAmAnubhavSaini** [comment]
This bar is now present in every modal. It hints towards a change in common modal that we use.

![Screenshot 2022-05-03 at 11 18 59 AM](https://user-images.githubusercontent.com/1573771/166409612-c8f51557-4099-4cf9-bdc8-d85d03622dc4.png)
![Screenshot 2022-05-03 at 11 19 07 AM](https://user-images.githubusercontent.com/1573771/166409616-e73000e7-337a-498d-9032-236897ab56c1.png)
![Screenshot 2022-05-03 at 11 19 15 AM](https://user-images.githubusercontent.com/1573771/166409619-23fb96c0-6b82-4da5-84d8-2d592d38367c.png)

It is even present in git import modal (which uses git connection modal, but lets see if it is due to underlying component change)
![Screenshot 2022-05-03 at 11 19 30 AM](https://user-images.githubusercontent.com/1573771/166409655-9d117e96-b139-4cab-b7a7-721c1310af36.png)

**Comment by IAmAnubhavSaini** [comment]
This bar was introduced in PR: #12189 

The exact change that causes this bar to appear is https://github.com/appsmithorg/appsmith/pull/12189/files#diff-a9e89817480e902f90382662965dfc200a72566de917626db002de7a7e2920ddR51
