### ISSUE TITLE
[Bug]-[1600]:REST API response with charset=windows-1253 - blank in query pane, garbled in evaluated value

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#13515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Creating this issue on behalf of a user. The user is calling a REST API endpoint on Appsmith and Postman:

1. **On Appsmith**
    a. on clicking the run button, the response status is 200 (sucess), but the response tab is otherwise empty
    b. when the result of the query is bound to a widget, the widget's content and the evaluated value of the result both show garbled characters, like this:
<img width="434" alt="Screenshot 2022-04-29 at 4 08 39 PM" src="https://user-images.githubusercontent.com/94514895/166417024-ea9bd81d-2972-4887-affb-5de91941e6e1.png">

2. **On postman**
    a. the user is able to see a response
    b. the header includes content type as `application/json;charset = windows-1253`
    c. the response also includes both english and greek characters

a snippet from the response:
"objs": [
        {
            "COMPANY": "sensitive(was a number)",
            "COMPANYNAME": "retracted, english characters",
            "BRANCH": "sensitive(was a number)",
            "BRANCHNAME": "Εδρα",
            "MODULE": "0",
            "MODULENAME": "Χρήστης",
            "REFID": "sensitive(was number)",
            "REFIDNAME": "WEB",
            "USERID": "sensitive(was a number)",
            "FINALDATE": "",
            "ROLES": "",
            "XSECURITY": "",
            "EXPTIME": ""
        }
    ],
    "ver": "5.00.521.11454",
    "sn": "sensitive(was a number)",
    "off": false,
    "pin": false,
    "appid": "sensitive(was a number)"

### Steps To Reproduce

NA - we have yet to set up an example service that returns such a response

### Version

self hosted

**Comment by rohan-arthur** [comment]
REST usage, 6m: 4000
apply 10% requirement, 400

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 400 |
| Effort (months)  | <<number>> |

**Comment by Irongade** [comment]
RCA: User is specifying a character set value, which is not being handled/sent back to the client side. The server seems to be sending a default character set value of 'utf-8'.

**Comment by rohan-arthur** [comment]
Also see conversation here: https://theappsmith.slack.com/archives/C0341RERY4R/p1653040742188789?thread_ts=1653040742.188789&cid=C0341RERY4R

**Comment by IraklisBek** [comment]
I am adding here how I managed to get the correct response via NodeJS and axios, in case it can be used for any help

```
            let customers = await axios.request({
                method: 'POST',
                url: url,
                data: { ... },
                responseType: 'arraybuffer',
                reponseEncoding: 'binary'
            });
            const decoder = new TextDecoder('ISO-8859-7');
            let decodedCustomers = decoder.decode(customers.data)
            res.send(JSON.parse(decodedCustomers))
```

**Comment by subrata71** [comment]
@rohan-arthur 
Can you please share the exact API spec which reproduces this issue? I tried to create a mock API as directed by your post but this doesn't seem to show garbled data in the response tab.


Please refer to the following mock API spec and API response tab in Appsmith.

### Mock API Rule
![Mock API Rule.png](https://images.zenhubusercontent.com/6285d4bd3bfe8b03b07c8593/40223081-4484-47a3-a0ea-557807bedb6d)



### Response Tab
![Response Tab.png](https://images.zenhubusercontent.com/6285d4bd3bfe8b03b07c8593/265e2100-f044-41d6-9c7f-7f587fd99eab
)

**Comment by subrata71** [comment]
I have tried to invoke this API (`https://apis-sandbox.fedex.com//ship/v1/shipments`) and found the hint message and response garbled. Please refer to the following screenshot.

![Screenshot 2022-06-03 at 1.39.49 PM.png](https://images.zenhubusercontent.com/6285d4bd3bfe8b03b07c8593/372cd436-b1ca-4779-bc2b-39805824fdd5)

Is it what the issue is concerned about? @rohan-arthur

**Comment by sumitsum** [comment]
@subrata71 yes looks like you have been able to repro the correct problem.

**Comment by rohan-arthur** [comment]
@subrata71 
1. When you run the same thing on postman, do you see a proper response?
2. Is our hypothesis that this garbling of the body due to unsupported charset valid?

**Comment by subrata71** [comment]
@rohan-arthur 

> 1. When you run the same thing on postman, do you see a proper response?

This is the API response on Postman. Please note that that this API (https://apis-sandbox.fedex.com/ship/v1/shipments) has content-type `application/json;charset=UTF-8`

![Screenshot 2022-06-03 at 3.43.58 PM.png](https://images.zenhubusercontent.com/6285d4bd3bfe8b03b07c8593/1bf00307-914b-4795-bd6e-d679b9719210)

> 2. Is our hypothesis that this garbling of the body due to unsupported charset valid?

The mock API that I created has `content-type=application/json;charset=windows-1253` and it doesn't appear to be garbled in Appsmith. Our hypothesis may be or may not be related to the different character set in `content-type `header.  I am trying to figure out the root cause and share it with you soon after finding it.

**Comment by subrata71** [comment]
The issue has two variants
- JSON data is treated as TEXT in the API response
![Mismatch between content-type and datatype.png](https://images.zenhubusercontent.com/6285d4bd3bfe8b03b07c8593/3eb2290b-b1aa-42af-9b17-262a92cbf66c)
- Garbled characters in the API response tab and in the hint message
![Garbled Appsmith response.png](https://images.zenhubusercontent.com/6285d4bd3bfe8b03b07c8593/f5fca22b-10bf-4cf3-bbbe-4d781f3e7531)

cc: @rohan-arthur @sumitsum

**Comment by subrata71** [comment]
# RCA- Garbled Characters in API Response

Read in [Notion](https://www.notion.so/appsmith/RCA-Garbled-Characters-in-API-Response-4f00ddb75cd74fb5b5e8987d552eac81)

[Development Branch](https://github.com/appsmithorg/appsmith/tree/fix/13515-rest-api-garbled-response)


There are **two** variants of this issue.

- **[1] JSON type data treated as TEXT in the API response**
    
    ### **Reason**
    
    A mismatch between content-type and `X-APPSMITH-DATATYPE` API response headers
    
    ### Explanation
    
    I assume that irrespective of the character set defined in the content-type header the `X-APPSMITH-DATATYPE` header must comply with the value of `content-type` header. That means if the content-type header has any of the following values, the `X-APPSMITH-DATATYPE` header must be of JSON type
    
    - application/json
    - application/json;charset=utf-8
    - application/json;charset=windows-1253
    - etc.
    
    Based on the above assumption this wasn’t found when the charset contains any other character set other than the `UTF-8`. As long as the `X-APPSMITH-DATATYPE` header reflects the correct datatype we should not be bothered about what character set is there in the `content-type` header due to the fact that `UTF-8` is the most standard character set.
    
### Demonstration
    
<img width="1000" alt="Mismatch between content-type and datatype" src="https://user-images.githubusercontent.com/3524599/172323535-e009dd1a-b2d9-48ce-96a5-4939952f1e1f.png">

## Proposed Solution
Currently, `content-type` matching for `application/json` type is done by the following code snippet

```
if (MediaType.APPLICATION_JSON.equals(contentType) ||
    MediaType.APPLICATION_JSON_UTF8.equals(contentType)) {
	//Do something awesome
}
```

When the `contentType` variable holds a value like `application/json;charset=windows-1253` then it doesn’t satisfy any of the above clauses. Thus it falls into the default case which is `TEXT`. In order to avoid this scenario, the above code snippet can be rewritten into 
    


```
if (contentType.includes(MediaType.APPLICATION_JSON)) {
	//Do something awesome
}
```

**Reference** 
[MediaType.includes](https://docs.spring.io/spring-framework/docs/3.0.x/javadoc-api/org/springframework/http/MediaType.html#includes(org.springframework.http.MediaType):~:text=if%20not%20present-,includes,if%20this%20media%20type%20includes%20the%20given%20media%20type%3B%20false%20otherwise,-isCompatibleWith)

In my opinion, we shouldn’t do any kind of character set conversion on the server-side rather the actual API response should be passed on.

### Demonstration
    
After implementing this proposed solution the `X-APPSMITH-DATATYPE` header now complies with the value in content-type header.

<img width="1255" alt="Solved-Datatype mistmatch issue" src="https://user-images.githubusercontent.com/3524599/172352542-1b50eead-53ba-4f1f-993f-c6b9909fcc1e.png">

### Test API

[https://chars.free.beeceptor.com/charset-windows1253](https://chars.free.beeceptor.com/charset-windows1253)


- **[2] Garbled characters in the response tab and hint message**
    
If an API has a `Content-Encoding` header then Appsmith doesn’t decode the response before rendering it to the client. As a result, the client sees garbled data.
    
### Demonstration
    
**Garbled Appsmith Response Header**
<img width="974" alt="Garble Appsmith response header" src="https://user-images.githubusercontent.com/3524599/172352829-9c5f8da8-eda6-4d55-a85e-a3b6ac0ac65a.png">

**Garbled Appsmith Response**

<img width="1040" alt="Garbled Appsmith response" src="https://user-images.githubusercontent.com/3524599/172352902-20835634-3cb5-4821-9a78-58f7386d1862.png">

## Proposed Solution

While creating HttpClient we need to pass true to the compress function like below


```
HttpClient httpClient = HttpClient.create(provider)
                    .secure(sslContextSpec -> {
													//Doing science here...
                            });
                        }
                        sslContextSpec.sslContext(sslContextSpec1);
                    })**.compress(true);**

```

If `true` is passed as a parameter to the `compress` function then it checks whether compression is enabled or not by parsing the `Accept-encoding` response header. If it finds that the compression is enabled then it adds this piece of information to the `HttpClient` and returns it otherwise it just returns the current `HttpClient` instance.

### Demonstration

After implementing this solution the garbled character issue has gone away

<img width="1019" alt="Solved-Garbled Appsmith Response" src="https://user-images.githubusercontent.com/3524599/172352990-59e5f0cc-4aa1-46de-89cb-5b6d2871b683.png">

### Test API

[https://apis-sandbox.fedex.com/ship/v1/shipments](https://apis-sandbox.fedex.com/ship/v1/shipments)
