### ISSUE TITLE
[Docs]: Renaming organizations to workspaces in documentation

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#13556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Related to #9537

Renaming Organizations to Workspaces across the product would lead to documentation to be out of date. The documentation, tutorials, etc. would also need to be updated to reflect the convention change.

### Describe the improvement

Renaming Organizations to Workspaces across the product would lead to documentation to be out of date. The documentation, tutorials, etc. would also need to be updated to reflect the convention change.

**Comment by jnikhila** [comment]
@ajinkyakulkarni - Moved it to current sprint pipeline for pirotizing estimation.

**Comment by jnikhila** [comment]
@vihar - For your information for Tutorials.

**Comment by jnikhila** [comment]
@trishaanand - As discussed, the documentation efforts seem to be of 3-4 days. No blockers from the documentation side.

**Comment by jnikhila** [comment]
@vihar and @cokoghenun - Could you please update the ticket with estimates for changes needed to Tutorials and Videos, respectively?

**Comment by cokoghenun** [comment]
Hey @jnikhila I'm not sure it's worth the effort to remake video content based on this change. Because
- We don't have any video specifically focused on organisations
- On the other hand, lots of time would go into rewatching all previous videos to fine instances where the word 'organisation' is said
- For those videos, the entire video would need to be rerecorded and uploaded to YT

So I'm not sure about this 🤷‍♀️

**Comment by jnikhila** [comment]
Hey @cokoghenun - thanks for coming back to me on this. 

As per your comments, the existing videos will not be updated. @trishaanand Please note.

**Comment by vihar** [comment]
Hey @jnikhila, the old tutorials need lots of updates regarding new product features and terminology.

Example: Today, most of the tutorials have the APIs, Datasources, and Widgets directories instead of the new Navigation. Hence, instead of doing this all at a time, we'll plan sprint-wise and re-update them. We'll also make sure to update the Orgnaisatrions to Workspaces simultaneously. 

For now, let's update the two tutorials on the docs: 
- Store Catalog Manager
- Review Catalog Manager

Additionally, we'll be adding this on changelog/release notes to help users know about this change. 

Let me know your thoughts here.

**Comment by jnikhila** [comment]
Moving this back to backlog as it will be picked once the ticket is progressed on by engineering team.
