### ISSUE TITLE
[Bug]: [Deploy preview]The git discard functionality fails

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The discard doesn't happen in the child branch
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/3a2e24cec21b408088ea4a8a416853aa-00001.gif)](https://www.loom.com/share/3a2e24cec21b408088ea4a8a416853aa)

### Steps To Reproduce

1. create a sub-branch from master
2. Add few pages 
3. Add a CRUD page, Pages with JS and API 
4. Now commit and push 
5. now when u try to merge it says there are some uncommitted changes in master 
6. Discard those changes
7. Now come to sub branch
8. Even here there are some uncommitted changes
9. Click on Discard changes
10. The discard is not working

### Version

deploy preview

**Comment by IAmAnubhavSaini** [comment]
It looks like it has something to do with every branch being a separate app and not hard reloading on branch change. This means the state of application on branch change or (less likely) git-status-response after commit-and-branch-change are incorrect. 

Needs more investigation.

**Comment by abhvsn** [comment]
@IAmAnubhavSaini if I'm not mistaken this happens when we have client side migration, is this correct assumption? If this is true we don't have a solution today for this and we are dependent on the user to commit the client changes. Consider a following situation:
1. User connect the app to git and make a commit
2. In next release we do client side migration
3. User will see random uncommitted changes
4. User will do discard and pull
5. As server don't have any idea about client side migration, server will check if any server side migrations required and apply them if necessary
6. Now as the user is in edit mode itself clint code will apply client side migration and again updates the DSL to latest version
7. Status API will show some uncommitted changes again

**Comment by IAmAnubhavSaini** [comment]
@abhvsn yes, client side migration makes more sense. 

There is another bug that @RakshaKShetty will report which is similar. In that we load an app and then client-side-migration runs unbeknownst to user and user always see a pending change on discard.

**Comment by abhvsn** [comment]
Reducing the priority considering we don't have solution as yet considering the platform limitations

**Comment by Nikhil-Nandagopal** [comment]
@IAmAnubhavSaini @abhvsn what is the condition we check to do migrations? I'm assuming it's some sort of version check that if the app version < the migration version then we should migrate. In that case, if the user discards a change, can't we simply commit the latest app version in the repo so that re-pulling the code won't re-trigger a migration?

**Comment by abhvsn** [comment]
@Nikhil-Nandagopal as you said we are tracking the client and server side migrations in separate boolean variables as ownership to run the migration is distributed. Now when we discard the changes if we have server migration we can run the migration in the same call and make new commit which will not show any uncommitted changes on the client side, but the same is not true fro client side migration. Check the point number 5 in the above steps to reproduce the issue

**Comment by RakshaKShetty** [comment]
This commit contains the changes that we see every time after discarding an old, git-connected app.
https://github.com/RakshaKShetty/1234test/commit/4719bd0ee899346bb32f2495d062c62ec79ffd5c

as you can see it contains version change , it happens for migrated application.
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/45958978/169299309-36d8a7dd-6d36-402f-906d-55e05ac122af.png">

**Comment by hiteshjoshi** [comment]
I think auto committing migration changes will solve this? As you won't be able to discard changes. And when we are going to work on auto-commit for migration, does it make sense to pick this up?

**Comment by vuiets** [comment]
@hiteshjoshi bumping this back to `High` because in the scenario that @RakshaKShetty has raised, we can't perform the discard. We are categorising any flow that doesn't break the app but breaks nevertheless as `High` impact for the time being. 

The  [impact](https://www.notion.so/appsmith/Applying-RICE-for-prioritization-08c2a3cf3e2a4bd291e68a0236664ad2#962e0b57432242f1ae9f7773227bb985) section on our document on RICE throws more light on this.
