### ISSUE TITLE
[Feature] In an On-premise Deployment, there should ability to disable signups

### ISSUE THREAD

**Issue by naqushab** [appsmithorg/appsmith#1362]
## Summary

In an on-premise deployment, there should be an option where people can directly go and use the page without having to login at all. 

## Motivation

On an on-premise deployment there would be people on a restricted network and not random people. So the users should be able to use the dashboards and intersect with it without any sign-up. Only admins need to have a sign up page and can restrict if sign-ups are enabled or not.

**Comment by hetunandu** [comment]
Hey @naqushab, this is a nice feature request. Just wanted to confirm a few things. It is possible to have an app have public view access, since this would be inside your network, it will restrict it only to the people who have access to the network. Does this work out for you or do you expect edit access to be public as well?

**Comment by naqushab** [comment]
Hey @hetunandu ,
Thanks for the quick response. Yeah, sorry, I got the point where I could manage access. That should do it.

Also, it would be nice to have slug names for different applications, but regarding this issue, I think it is already there.

I will close the ticket.

**Comment by hetunandu** [comment]
NP @naqushab 😄 That slug name feature is useful as well. Request you to open a new issue around it so we can add it to our roadmap

**Comment by naqushab** [comment]
Sure thing @hetunandu
