### ISSUE TITLE
[Bug]:The discard changes progress bar will be stopped in the middle and the action is not completed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The discard changes progress bar will be stopped in the middle and the action is not completed
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/167068461-0ec0eb61-18af-456d-846c-e9e5ca1eb296.png">

### Steps To Reproduce

1. Connect application to git
2. Create a new Branch from master
3. Add a new page in the branch 
4. now do the discard change the modal will be the 

### Version

Deploy Preview

**Comment by IAmAnubhavSaini** [comment]
It gets stuck because frontend is not handling this error case as of right now.

The response from API is:

```json
{
    "responseMeta": {
        "status": 404,
        "success": false,
        "error": {
            "code": 4027,
            "message": "Unable to find pageId 6274ab5ee257b32033aae1dc",
            "errorType": "INTERNAL_ERROR"
        }
    }
}
```

Even though the page id exists as it is newly created: `app/heisenbergs-discard/page1-6274ab5ee257b32033aae1dc/edit/generate-page?branch=second`, local git repo doesn't have this page yet in the file system, due to it not being committed, and thus backend cannot find it.

@abhvsn is my understanding correct here?

**Comment by abhvsn** [comment]
PR has been raised for this already and @IAmAnubhavSaini you are partially correct here as the page don't have the published version yet this is happening.  
https://github.com/appsmithorg/appsmith/pull/13487 this will fix the above issue
