### ISSUE TITLE
[Bug]: cyclic dependency error is displayed in the view mode

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#13755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Getting cyclic dependency error in one of my app
Facing the issue only in the view mode not in the edit mode
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/167859846-ffc83907-b260-445a-8e76-8fde91f5cefc.png">

facing it in this app->made this app public
https://release.app.appsmith.com/applications/626a7f2e7e182b2589133461/pages/626a7f327e182b258913346e?branch=master

### Steps To Reproduce

1. go to git-template-3-foodtruck app
2. Launch the app 
3. Now go to the dish tab
4. the cyclic dependency error will be displayed

### Version

release

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/13755?planning-poker) with ZenHub @ohansFavour

**Comment by eco-monk** [comment]
Observation 1:

Noticed actions array is missing for Jsobject in view mode
![image](https://user-images.githubusercontent.com/66776129/171413335-e97b88c8-1085-4dd0-ba8d-8d04728a45a1.png)

But present in edit mode
![image](https://user-images.githubusercontent.com/66776129/171413655-9ea883f9-bbb7-4edb-8534-de5e819f768b.png)


---

Observation 2:

When updating local unEvalTree.
We are assigning `.data` to a `String` instance.

When this is being replaced by a different value.
It is not identified as a delete event. (when translating diffs)

Which is why .data doesn't get removed. Hence creating the cyclic dependency.
<img width="701" alt="image" src="https://user-images.githubusercontent.com/66776129/171417513-e288ddc5-db9b-4e7f-813c-80144c1e6260.png">

**Comment by Rishabh-Rathod** [comment]
> Observation 1:
> 
> Noticed actions array is missing for Jsobject in view mode 
> But present in edit mode 

Similar behavior was noticed here https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1654054200770169
Issue - https://github.com/appsmithorg/appsmith/issues/14202
