### ISSUE TITLE
[Bug]: Failure to tag a function `async` after resolving linter errors

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#13826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/168258011-dde834fc-3851-496e-ae86-4af4960c87d5.mov

### Steps To Reproduce

1. Create a simply JS to run a Query1
2. Make sure Query1 does not exists when this JSObj is created
3. Observe the lint error in JSEditor for the missing Query1
4. Now create Query1
5. Come back to JS Editor & observe lint error is gone
6. **Observe: Still this function does not show up in Async Function Settings tab until page is refreshed**
7. **Expected : As lint error disappears & since the function qualifies for async - it should start to show up in Async Function Settings tab without a page refresh**

### Version

Prod/Release v1.6.26

**Comment by bharath31** [comment]
@satbir121 could we perform an RCA on this?

**Comment by satbir121** [comment]
Currently, we are only checking for async when JS object is edited. A simple solution would be to do the async check on addition/rename of an api/query. @ohansFavour It might have performance implications. We need to figure out a solution which does not trigger `async check` on every `api or query` addition/rename.

**Comment by ohansFavour** [comment]
@satbir121 This issue is a result of the team's decision not to make JS functions reactive to entities bound within them. Today, JS functions are only reactive to changes made to their body, and the entire JSObject (See screenshot).

<img width="1273" alt="Screenshot 2022-11-17 at 06 27 58" src="https://user-images.githubusercontent.com/46670083/202364683-083f9511-e498-4840-8d5c-eb38a18772d1.png">

Introducing reactivity of JS functions to other entities bound within them will affect performance, as it will increase the number of cycles in evaluation, and introduce unnecessary evals.
