### ISSUE TITLE
[Bug]: No search results image is misaligned on applications page

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#13949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i search something on applications page and there are no results, the no results image shown is misaligned.
![image](https://user-images.githubusercontent.com/28362912/169229427-1a4d9181-a04f-4613-9785-f714659a0515.png)

### Steps To Reproduce

1. Go to the applications page
2. Search for anything random making sure there are no results.
3. Look at the no results image, it is misaligned.

### Public Sample App

https://app.appsmith.com/applications

### Version

Cloud / Self Hosted

**Comment by RakshaKShetty** [comment]
reopening the issue facing the same issue in release but seems to be fixed in dp 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/45958978/170634869-9f9b71ca-43f1-43bb-8de7-7f313a7f6bf2.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/170634902-cd8a8a62-0990-440c-8c65-4c3b8a9ec5dc.png">

**Comment by ankitakinger** [comment]
This is because `Sync Community Workflow` is in failure state.

**Comment by ankitakinger** [comment]
This has been fixed on release. 
CC: @RakshaKShetty

**Comment by RakshaKShetty** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/170921230-f951b999-3150-4e53-a38d-92b333592709.png">
