### ISSUE TITLE
[Task] Review for lazy loading opportunities

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#13959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Identify the widget components which can help reduce chunk sizes by lazy loading
- Try to isolate imports as much as possible to enable lazy loading
- Update imports for each of the opportunities. 

Note: The PR(s) must contain the before and after screenshots which show the chunk sizes, to confirm that this has helped with the chunk sizes.

**Comment by SatishGandham** [comment]
- Some widget libraries are already lazy loaded.
- We tried optimising the chunks before, since this improvement will be useful only when the user comes to Appsmith for the very first time, we picked other impactful features. We still have more impactful features at this time.
- We should analyse the problem first, estimate the effort and plan how to split it.

We should use a tool like Madge or other bundle analysers to get an idea of the problems at medium priority and take a call on further steps.
