### ISSUE TITLE
[Bug]: Curl Import Not Detecting Right Body Type

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#13978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Whenever a URL is imported via CURL, the right body type is not detected and always defaults to RAW

### Steps To Reproduce

Try importing this multipart form request

```curl
curl --location --request POST 'https://api.stripe.com/v1/transfers' \
--header 'Authorization: Basic c2tfdGVzdF81MUpqSlh0RlRiN09mV3VhUjFTcXJoNFF3cU5haDZHcDBhanRpMGhqZlczWjl4MXg4RzFRYUhxNlRZcXBvd1IwVGczcDFadWViQjAwSHB4VnBiUmg6' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'amount=1' \
--data-urlencode 'currency=usd' \
--data-urlencode 'destination=acct_1L0mdx2Ym60mujGg'
```

### Version

Cloud/v1.6.26-SNAPSHOT

**Comment by AmanAgarwal041** [comment]
Here's the RCA :
File `CurlImporterServiceCEImpl.java` has a function `parse` - line number `310`. This function parses the curl command being imported from the client side, but it does not handles the `formData` in the `actionConfiguration` object which determines the Body Type for the client side editor. 
If we set `apiContentType` key inside `actionConfiguration.formData` object with respect to the `contentType` being calculated, then the issue is resolved.

**Comment by cokoghenun** [comment]
@sondermanish any updates on this? 
I get PTSD every time I realize I'm going to use CURL on Appmsith 😂

**Comment by sondermanish** [comment]
@cokoghenun trying to figure out the issue. Let's cure cURL. #nomorePTSD

**Comment by prapullac** [comment]
@sneha122 : Verified on the DP and looks good to me
