### ISSUE TITLE
POC for using WASM for parsing

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#14138]

**Comment by AmanAgarwal041** [comment]
We worked on doing some research about using WASM for parsing. 
Here are some docs that we created regarding the argument of using WASM for the logic: 
- [Why WASM for AST?](https://www.notion.so/appsmith/Why-WASM-for-AST-e47e81b395ba4764ad923b302f81f8e6)
- [AST with Rust and WASM - Phase 2](https://www.notion.so/appsmith/AST-with-Rust-and-Wasm-2nd-Phase-fe9ff10712e4435eaf0c3cc13d1dabbb)

But we are going ahead with the creating of package with mono repo for now. We came up with this conclusion due to reasons like :
- Time frame to solve the purpose of AST parsing
- Overhead of adding new technology to the project
- Educating other developers about the new technology
- Solving our purpose with the above technology may not have existing solutions for now

Due to above arguments, closing the issue for now.
