### ISSUE TITLE
[Bug]: JS Object broken in working app

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#14146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Github Manager App broke due to a parse error in the Query

### Steps To Reproduce

1. Open the [github manager app](https://app.appsmith.com/applications/60d72903ee9aa1792c5bf168/pages/614d9b9e18a27e5288afa99d/edit?branch=master)
2. Try to update a label name
3. It fails to update with no message
4. Go to the JS Object. The update label function is not runnable due to a parse error
5. There are no errors in the logs

### Public Sample App

https://app.appsmith.com/applications/60d72903ee9aa1792c5bf168/pages/614d9b9e18a27e5288afa99d/edit?branch=master

### Version

Cloud

**Comment by eco-monk** [comment]
My bad, The API has been fixed.
But we're still unable to run this function from the JsObject.

Console error:
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/66776129/172556463-1227dd29-8f37-480b-a43b-da6757396e71.png">

---

https://www.loom.com/share/fef916e0410e492fa4c7b29e1a7d1b54

**Comment by Irongade** [comment]
@eco-monk Seems this is a separate issue, can we close this issue and open a new one, and also assign it to an appropriate person from the FE coders Pod.

**Comment by eco-monk** [comment]
This is still a big part of the same issue. `JS Object broken in working app`

Noticed the problem started with the API. (which is fixed now)
Seems like fixing that wasn't enough.

---

Thanks to @ramsaptami for pointing this out.

**Comment by Nikhil-Nandagopal** [comment]
This seems to be working now so closing this

**Comment by ramsaptami** [comment]
As Anand mentioned, API call is working fine now. But running `updateLabel` function from the editor itself returns an error seen only on the `Response` tab of the debugger, but no errors are present in the `Errors` tab. This issue is being tracked in #14503. 

@ohansFavour please refer to this **app+function** as well when solving this issue since we'll need to verify fix here as well

![image](https://user-images.githubusercontent.com/79509062/173999214-c7faf4f0-8530-4a43-aae9-1554b9aac77f.png)

QA will be verified once both issues on this app have been resolved.

**Comment by ohansFavour** [comment]
@ramsaptami I have identified three different issues from RCA. I have described them [here](https://github.com/appsmithorg/appsmith/issues/14503#issuecomment-1157062955). All of these will be handled [here](https://github.com/appsmithorg/appsmith/pull/14555).
