### ISSUE TITLE
[Epic]: Property Pane reorganisation

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#14192]
### Objective

https://www.notion.so/appsmith/Property-Pane-tabs-rules-properties-etc-b60821925884420f85f198e648f91b38

### Success Metrics

| Metric         |
| -------------- |
| Customer satisfaction score increases  |
| Decrease churn rate down to 30%        |

### Prioritised User Stories

| User Story    |
| ------------- |
|  |
|  |

### Developer Handoff Document in Figma

https://www.figma.com/file/hlOcM5LasxcRqEwHPXe5lm/UI-%7C-Content-Property-Pane

### RACI matrix
| | |
| ------------- | ------------- |
| Responsible  |     @aswathkk           |
| Accountable  |      @aswathkk          |
| Consulted      | @dilippitchika @riodeuno  |
| Informed       |   @rohitagarwal88             |

**Comment by dilippitchika** [comment]
## **Problem Statement**

Today our property pane is heavily disorganised across the widgets. This leads to the following pain points from our users

**When I try to configure a widget, I want to easily find the property i have to configure so that I can focus on building my app faster**

- When I try to configure a property in larger widgets like table JSON form etc. this issue is prominent
- When I have a few properties to configure together to achieve a functionality, I want them to be close to each other so that I can configure them faster

**First time users** 

- When I am configuring a widget for the first time, I want to immediately see it in action so that I see value in appsmith platform

## Solution

High level changes being suggested

1. Re-arrange properties in each widget as per the order of importance and configuration by users
2. Group properties which are usually configured together to ensure the dev is able to fully configure a flow within a widget from one place
3. Split the tabs in Content/Properties and Styles
4. De link the Label configuration for a property to be easily managed by our internal team
5. Add a search bar to allow users to search for properties

**Broad** **Scope of project**

1. Re-arrange the properties in all the widgets as per the design mentioned in Figma
2. Support a search bar to allow users to search for properties

**Next steps**

1. Plan the scope better
    1. Go through each of the top widgets - Table, Button, Input and JSON form and understand all the changes for those
    2. Start formulating smaller PRDs for each of these widgets
    3. Repeat the process with other widgets
2. Discuss with @Aswath K  on how we can improve the maintenance and scalability of the property pane

**Comment by aswathkk** [comment]
Regarding the release process, we will make changes under a feature flag and ship the changes to release after review and QA.
Before working on individual widgets, we need to make some platform changes to support Content/style tabs and the feature flag.

#### Next Steps

1. Create a PR with the platform level changes (feature flag, content/style tabs) and get it merged
2. Create a POC by changing a simple widget ( May be button widget )
    This will help us in estimating the time/efforts required for other widgets
3. Go through each widget and create PRSs and do an estimation on each of them.

cc: @rohitagarwal88

**Comment by aswathkk** [comment]
### Catchup - 22nd June

@NandanAnantharamu will work on the Cypress failures once we merge the changes to release

### Action items

- [ ] @aswathkk will include JSONForm in the current POC
- [ ] @aswathkk will include search feature also to the POC

**Comment by aswathkk** [comment]
### Catchup - 7th Sep

Pending items:
1. Code cleanup, documentation updates and update widget scaffolding script
2. Search functionality improvements
3. Collapse all sections except first one by default
4. Apply new visual changes according to Figma design
    1. Make a list of visual changes
5. Update Tooltip for all the widgets
