### ISSUE TITLE
[Bug] Improve Query / API Timeout error

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1422]
## Description

When a query / API times out, the message is to check your internet connection

### Steps to reproduce the behaviour:
1. create a query
2. set the timeout to 10 ms
3. execute the query
4. See the error

The error should say "`QueryName` took longer than 10ms to execute"

**Comment by rohitgeddam** [comment]
i would like to work on this

**Comment by Nikhil-Nandagopal** [comment]
@rohitgeddam go for it!

**Comment by trishaanand** [comment]
@rohitgeddam : You can experiment with the following :
In file `NewActionServiceImpl`, function `executeAction`, we use the following :
`.timeout(Duration.ofMillis(timeoutDuration))`
Instead of the above, we should add our own fallback like below :
`.timeout(Duration.ofMillis(timeoutDuration), Mono.error(new AppsmithException(AppsmithError.PLUGIN_EXECUTION_TIMEOUT)))`

Please edit the PLUGIN_EXECUTION_TIMEOUT error to include the name of the query and pass the name as a parameter in the above Mono.error call.

In `GlobalExceptionHandler`, PLUGIN_EXECUTION_TIMEOUT is being handled separately. 

I am hoping this change would solve this issue.

Let me know if you hit any roadblocks or have any other doubts I can help with.

Good luck!

**Comment by mohanarpit** [comment]
@rohitgeddam Since you haven't raised a PR in 6 days, I'm unassigning this issue. I'm sure you're busy elsewhere. Please do come back to this project whenever you have time again.

**Comment by nidhi-nair** [comment]
@trishaanand I see that the `executionMono` is mapping another type of Exception into an `AppsmithPluginException`. Since the timeout throws its own error, can we simply map that into an exception as well? This would be in place of using a fallback.

**Comment by trishaanand** [comment]
@nidhi-nair : That sounds fair. Let's throw an AppsmithPluginException in this case as well.
