### ISSUE TITLE
[Enhancement]-[84]:Currency widget should allow `,` to be used as decimal seperator

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#14261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Some locale (ex: de-de germany) use `,` as decimal and `.` as thousand separators. so we need to allow commas to be entered on the currency widget.

### Steps To Reproduce

1. Try to enter `,` in the currency input
2. observe that you're not allowed to.

### Version

cloud

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 21 |
| Effort (months)  | 0.5 |

**Comment by jmortigosa** [comment]
Not only the currency widget also the input wigdet with type number. Please consider prioritizing this bug.

**Comment by jmortigosa** [comment]
+1

**Comment by ashit-rath** [comment]
Another user on discord is facing similar issue
Locale - `pt-PT`
Thousand separator -  ` ` (space)
Decimal separator -  `,` (comma)
https://discord.com/channels/725602949748752515/989129968141336606

**Comment by liebig** [comment]
This problem is certainly more than an enhancement but a bug. In all browsers that use the comma to separate decimals (e.g. Germany) neither the input nor the currency object works with decimal places! Because a dot is interpreted by my browser as a separator from the thousands place, not as a decimal place.
![image](https://user-images.githubusercontent.com/3033740/177975814-11c6c103-f6c0-43ba-8673-c011e5eae4c9.png)

**Comment by sbalaji1192** [comment]
@liebig We have triaged this. The currency widget will accept the decimal character based on the locale. Will pick this up during the first part of the following week.

**Comment by dilippitchika** [comment]
@techbhavin assigning this to you, please pick this up as part of this sprint.

**Comment by dilippitchika** [comment]
@techbhavin can you please discuss with @sbalaji1192 on how you plan to fix this?

**Comment by dilippitchika** [comment]
@somangshu @sbalaji1192  fyi, this didn't work out as expected. We were trying to use the browser locale to manage this, but turns out some browsers don't support this well enough. 

I will work on a new prd for this which is much more comprehensive and easy for devs to implement

**Comment by dilippitchika** [comment]
Discussed the default value problem with @keyurparalkar and @sbalaji1192 -

The default value will only support `.` as the decimal separator for now. 

@keyurparalkar instead of using helper text, just show an error message if the user enters , or any other value as decimal separator saying that "Invalid number, please use `.`/point as the decimal separator for default values."

cc @chandannkumar

**Comment by MrWombastic** [comment]
Hi, just to be sure that you focus on the other problem too, so not only the default value problem but the fact that in every country where the , is the decimal seperator the field does not accept decimal places at all. , in a currency field cannot be entered in languge de-DE and . is interpreted as a thousand delimiter.

**Comment by dilippitchika** [comment]
Hello @MrWombastic yes, we already fixed it in the PR linked. Based on the locale we will accept either , or . 

We are working on an expansion to also fix this in the default value field
