### ISSUE TITLE
[Bug]-[Infinity]:Google OAuth redirect URI no port

### ISSUE THREAD

**Issue by disl-pdavid** [appsmithorg/appsmith#14290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I run an instance via docker on port 8080.
I've set the Google OAuth redirect and javascript URI's to include this (example.com:8080 and example.com:8080/login/oauth2/code/google).

I've added the client and secret to the docker.env file.

The Google auth option shows up on login page, but following it kicks a 400 error from Google `Error 400: redirect_uri_mismatch`.

Google says that `redirect_uri` _doesn't_ include the port 8080...

### Steps To Reproduce

1. Host docker app on port other than 80.
2. Setup Google OAuth.
3. Attempt to login via Google.

### Version

Self-hosted 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5w970)

**Comment by vuiets** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 806 |
| Effort (months)  | ? |

@hiteshjoshi could we get someone to help with the effort estimate for this?

Reach for this is people using Google OAuth to login in the last 3 months on self-hosted instances: 806

**Comment by patdavid** [comment]
Was there any movement on this by chance?  I'm on 1.7.14 and still seeing the issue.

**Comment by SvV-CWinJS** [comment]
I too am having this issue (running on another port, port 30000) and would appreciate seeing updates on this issue.
I'm running v1.8.8.

**Comment by disl-pdavid** [comment]
Dropping back in - this is still apparently an issue on `1.9.19`. :(
(Hopefully it's not just me.  Well, hopefully it *is* just me and I just need to rtfm somewhere :) ).

**Comment by ame-appsmith** [comment]
[Another user](https://app.frontapp.com/open/cnv_152q7nyk?key=zflzWyftMfXEXlSC_8zNpjlQgILLOvE6) reported this issue.

**Comment by karlfrankeser** [comment]
We're running on Appsmith Business v1.9.39 and have the same issue, it seems that the port is not being populated in the redirect_uri parameter correctly although it is correctly shown in the not editable fields used to copy from when setting up the client credentials.

**Comment by sharat87** [comment]
I think this is a side-effect of Docker's port forwarding working on Layer-4, instead of Layer-7. So when incoming requests are forwarded to Appsmith in the container, Appsmith doesn't see that the original request was on a different port. Docker cannot pass it on, because it's not aware of HTTP (Layer-7), and is only working at the TCP (Layer-4) level.

To solve this, we'll need to take the `Origin` header's value and use that to create the `redirect_uri`. This header will be sent by the browser and will include both the protocol and the port, in addition to the host. This will need changes in the backend's OAuth2 implementation.

**Comment by trishaanand** [comment]
This issue has been fixed.
