### ISSUE TITLE
[Enhancement]: Show asterisked password after datasources are saved

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1429]
## Description

The backend does not return any password after saving the data source for security reasons. This can sometimes be confusing for a user and it would help if we could display some asterisked password so that users don't feel like they need to re-enter the password.

**Comment by Nikhil-Nandagopal** [comment]
@prapullac this is intentional due to security reasons

**Comment by prapullac** [comment]
@nikhil : Can we add asterisk into the field  instead of leaving the field empty this is because leaving it empty would lead user to confusion of password not being added

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal I had asked Prapulla to report this issue because it's still a UX problem. Instead of returning the actual password, we can return a flag that says there is a password entered earlier. The UI can then just display a few asterisks to indicate this to the user. 

This originated from a user problem where they forgot if they had saved the password earlier or not.

**Comment by ajinkyakulkarni** [comment]
Related to https://app.zenhub.com/workspaces/appsmith-actions-pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/3233
