### ISSUE TITLE
Merge system logs and user generated console logs to the Logs tab

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith#14432]

**Comment by rohan-arthur** [comment]
notion doc: https://www.notion.so/appsmith/Console-log-ac7c5c69a5c94670a691706a3a9061bd 

Associated job stories:

- [x ] 1. When I run a query / function, I want to immediately see the response so that I can understand the data being returned and validate that it is correct. (Top user story) - _this is already supported in the Response tab_
- [ x] 2. When I run a query / function and run into an error, I want to be able to see all associated error messages of this entity so that I can be sure I can fix my configuration mistake. (2nd most important user story because user ran into an error) - _this is already supported in the Errors tab_
- [ ] 3. When I run a query / function successfully but it gave me an unexpected output, I want to be able to see the logs of every execution step so that I can identify the logical error in my query / function. (Tertiary user story because it's successful but logically incorrect) - _this is what we need to implement_
- [ ] 3.a. When I write JS in appsmith , I want to be able to print console messages , so I can debug the application in edit mode.
- [ ] 3.b. When use console statements , I want to see the output easily & intuitively , so I can debug the application in edit mode 
- [ ] 3.b.i. When I execute some js code in appsmith , I should see the system logs, user-created logs, and any result of return stateme ts all in one place , so I can debug the application in edit mode.
- [ ] 3.b.ii. When open the debugger window, I want to be able to find and distinguish between system, user logs and output of function executions (response of JS object) , so I can debug the application in edit mode.
- [ ] 3.c. When I execute code with multiple console statements multiple times, I want to be able to distinguish between my different runs , so I can compare the difference of outputs.

**Comment by nidhi-nair** [comment]
Closing since feature branch has been merged into release.
