### ISSUE TITLE
[BUG] Updation of inverseDependencyMap is incorrect when widget dynamically updates binding

### ISSUE THREAD

**Issue by Rishabh-Rathod** [appsmithorg/appsmith#14436]
Table widget V2 evaluation issue 

#### Observation
When a theme value (ex, color) is changed , the value is not getting reflected on the newly added column unless the page is refreshed. I dug a little bit and found out that the data tree difference is not getting calculated properly in this case. Could someone help me debug the issue?

#### Steps to reproduce 

https://user-images.githubusercontent.com/23132741/175926899-ae2cd92e-9643-48e3-a3ea-607f4faf1655.mov

`updateDepedencyMap` -> `DataTreeDiff.NEW` case -> didn't updated inverse dependencyMap as `!isDynamicLeaf` = `false`.

**Comment by sbalaji1192** [comment]
Issue not related to the Table widget.
InverseDependencyMap in DatatreeEvaluator is not getting updated when a widget updates its property with dynamic values in an update hook during updateDataTree flow. Temporarily patched this issue from Table v2 side by setting a non-dynamic value property along with other dynamic properties, which makes the evaluations to recompute the InverseDependencyMap. However this needs to be fixed in DatatreeEvaluator.

**Comment by bharath31** [comment]
@satbir121 could you triage this issue?

**Comment by satbir121** [comment]
There was a workaround implemented for this issue. It doesn't exist anymore.
