### ISSUE TITLE
[Docs]: Set up SPF record for SMTP plugin

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#14537]
<p>A user would be helped by adding documentation for configuring SFP for SMTP/emails to prevent emails being flagged as spam.<br /><br />> I've added the whitelisted server addresses in my domain record however emails keep being flagged as spam.<br /><br />Discord thread can be found [here](https://discord.com/channels/725602949748752515/760761686549463060/986066909642510376)</p>

**Update 19 Aug 2022** - Based on the discussion - we need to update the doc to add a callout and add a link to the[ AWS SES](https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication-spf.html) link which users can follow to resolve the issue.

**Comment by tzahari** [comment]
In my opinion this is is the responsibility of the used email system. 
Because Appsmith is not relaying themself but is using an smtp relay server. 
Therefore this has nothing to do wich is specific to Appsmith rather than a correct configuration of the mail system. 

Example: For AWS SES is everything documented to setup SPF and so on... https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication-spf.html

**Comment by spark-c** [comment]
assigned @sum35h (sorry for the accidental tag Sumit!)

**Comment by Nikhil-Nandagopal** [comment]
@tzahari that's a good point. @spark-c @sum35h I think this should not come under our purview right?

**Comment by jnikhila** [comment]
@sum35h - I think we can add a disclaimer in our docs and link to the AWS SES page so that it's easy for users to find their way quickly. CC: @Nikhil-Nandagopal - Your thoughts??

**Comment by Nikhil-Nandagopal** [comment]
@jnikhila yeah just a callout that this may happen and that they should look to AWS to resolve it

**Comment by jnikhila** [comment]
[Published](https://docs.appsmith.com/getting-started/setup/instance-configuration/email/amazon-ses).
