### ISSUE TITLE
[Bug]: Running an API query returns a missing organization ID error for an unsaved datasource (existing apps)

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Running an API query using a URL as is (i.e, without saving it as a datasource) returns an error for missing organization ID. This is observed on already existing queries, not newly created ones.

### Steps To Reproduce

1. Use an API URL to run a query without saving it as a datasource and observe the error as seen in the screenshot
2. Or go to the app at [this](https://release.app.appsmith.com/app/scratch-pad/iframe-629d9ca4b1677a11502ab3e2/edit/api/629da545b1677a11502ab586) location. Run the query and observe the error displayed on the debugger.

![image](https://user-images.githubusercontent.com/79509062/174004877-fae66e84-884b-4bb9-8486-a424adfd281a.png)
![image](https://user-images.githubusercontent.com/79509062/174004927-9a8d5220-2949-4cc6-b57f-3bd35518d23b.png)

### Public Sample App

https://release.app.appsmith.com/app/scratch-pad/iframe-629d9ca4b1677a11502ab3e2/edit/api/629da545b1677a11502ab586

### Version

Cloud

**Comment by ramsaptami** [comment]
@sidhantgoel Copying the query returns an error seen in the screenshot

![image](https://user-images.githubusercontent.com/79509062/174033239-b7ef1f64-458b-4f36-974a-9035a1f5c400.png)

**Comment by emilvidmark** [comment]
When will this be released? we are in quite a hurry right now for this to be solved

**Comment by cobrimusic** [comment]
This issue has been deployed?

**Comment by emilvidmark** [comment]
Even though I'm updating with the newest release as mentioned here: https://docs.appsmith.com/setup/docker
it doesn't seem to solve the issue?

**Comment by emilvidmark** [comment]
Thanks @ramsaptami

**Comment by rubabuddin** [comment]
Thanks team - can we have instructions on how to rollback versions manually in situations like this?

**Comment by hawisizu** [comment]
hello there! Sorry to be pushy, but do you have an ETA about the release of the correction? thanks a lot!

**Comment by ramsaptami** [comment]
This seems to happen on existing API queries that were not saved as a datasource, so editing the URL on your query or re-creating the query with all the same details should help clear this error. Could you'll try one of these workarounds while we work on getting the fix out please? 
Also, to add, in case you'll choose to recreate a query with the same name, it shouldn't create an issue since backward compatibility will pick up bindings automatically.

**Comment by rubabuddin** [comment]
Recreating the query did not work. Also that would be an extremely time consuming process for # of queries per app.

Do we have an ETA on the resolution?

**Comment by jingrenlim** [comment]
Recreating does work. You have to create like its brand new. You cannot copy. But that would be extremely time consuming to do for the many API endpoints in each page.

Do we have an ETA on the resolution?

**Comment by mohanarpit** [comment]
**Update:** Apologies for this bug. We appreciate your patience as we fix the problem. We will also post a more detailed RCA shortly. 

As we speak, we are in the process of releasing a new version v1.7.4. This should be available for all self-hosted instances within 2 hours. This is because our CI takes time to run all tests & build the Docker images for various platforms (x86 and ARM).

**Comment by HantaoCai** [comment]
Please let me know when the repair is complete

**Comment by mohanarpit** [comment]
**Update:** The fix for this issue has been released in [v1.7.4](https://github.com/appsmithorg/appsmith/releases/tag/v1.7.4). If your instance has been set to auto-update, you should simply refresh your browser page and everything should ideally start working. If you don't have auto-update setup, I'd highly recommend that you update to v1.7.4 manually by following the instructions [here](https://docs.appsmith.com/setup/docker#updating-appsmith-without-docker-compose). 

If you still see an issue, please edit the API endpoint with a minor change & then revert it back. For eg, remove the last character of the URL and add it again. This will trigger an update for the API which will restore it back to a good state. 

Once again, I apologize for the bad release & appreciate your patience as we triaged and fixed the problem.
