### ISSUE TITLE
[Bug]-[400000]:In signposting, clicking a page tab doesn’t take the user to the page but shows the next step in the checklist

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#14628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the signposting checklist, checklist, clicking a page tab doesn’t take the user to the page but shows the next step in the checklist

https://user-images.githubusercontent.com/20532920/174258216-c39e1632-9701-4dec-a59f-d25ce6fe4e0e.mov

### Steps To Reproduce

Create a new account
select I want to build something myself
Follow a few steps of signposting, and create a new page
try clicking to a new page
It will show a full page prompt for the next page of signposting rather than navigating to the said page

### Version

1.7.1 Cloud

**Comment by Nikhil-Nandagopal** [comment]
60% of users go through sign posting
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 20000 |
| Effort (months)  | 0.1 |

**Comment by Richarex** [comment]
This is fixed verified it on release branch

**Comment by Parthvi12** [comment]
https://user-images.githubusercontent.com/80334441/176891447-0235c311-25e7-4573-b4f4-d76525b49581.mov

@akash-codemonk  On adding new page It shows a full page prompt for the next page of signposting, although on navigating to another page and coming back , it goes away.

**Comment by akash-codemonk** [comment]
I think it makes sense to show the page as the user is in signposting. Also the user can click on the cta `Add a widget` to see the canvas. The task page is shown when there are no widgets on the canvas so it isn't really hiding any widget.  @kocharrahul7

**Comment by Parthvi12** [comment]
@kocharrahul7 @akash-codemonk Yeah, I think we should continue to show the task page when there is no widget/query and hide it in preview and comment mode.

**Comment by akash-codemonk** [comment]
https://appsmith-agvtov3eb-get-appsmith.vercel.app/
signups don't seem to work on deploy previews so added a video

We also hide the task page and show the canvas when we open the widget tab or when the user clicks on one of the ctas on the task page. The task page is hidden when the widget tab is clicked on to allow drag and drop behaviour as you cannot drag a widget on to the task page. Also once we hide the task page we don't show it back again, but the task list page is still accessible from the top left. Also the above points mentioned are existing behaviour to clarify that these seem to be intentional. 

https://user-images.githubusercontent.com/67054171/177292574-fae4f397-be12-4dfb-9bd6-6dbd56538331.mov

**Comment by hiteshjoshi** [comment]
@Parthvi12 can you verify this? If all good, lets close this one.
