### ISSUE TITLE
[Bug]: Max Zoom Level is not allowing to disable JS toggle until we remove the data from the field.

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#14647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Max Zoom Level in image widget is not allowing to disable JS toggle until we remove the data from the field.

![image (4)](https://user-images.githubusercontent.com/10436935/174292301-4b1c36e8-4995-455e-bdca-3daaa70104ca.png)

### Steps To Reproduce

Add image widget. Toggle JS for zoom level property

### Version

Cloud

**Comment by btsgh** [comment]
Tested the image widget for the JS toggle on Max Zoom level. Now with the values present in the dropdown are entered on JS Toggle, the JS button is still enabled. Only when we enter a number which is not there in the dropdown, then the JS button is disabled, and until we clear the data or enter a value that is part of the dropdown, it remains disabled.
@aswathkk  - is this the right expected behavior?

**Comment by aswathkk** [comment]
@btsgh Yes. This is the expected behaviour.

**Comment by btsgh** [comment]
Thanks! Marking as Verified this issue as it has been resolved.
