### ISSUE TITLE
[Bug]-[6000]:For Api which returns string datatype as response, the table in response tab doesn't show any data.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#14666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/174493807-fdb1cd20-26eb-41b9-8d52-d13cad1569a9.mov

### Steps To Reproduce

1. Create a new API
2. Enter URL = https://raw.githubusercontent.com/dmfilipenko/timezones.json/master/timezones.json
3. Hit run

### Version

v1.7.4

**Comment by Parthvi12** [comment]
@ChandanBalajiBP If response can't be shown in table, can we remove that option. Something like this:

**Comment by ChandanBalajiBP** [comment]
@Parthvi12 understood the required output. Thank you!!

**Comment by sneha122** [comment]
For the API mentioned in the ticket, response returned is of type string, because of which it is not being parsed and shown in the table format.

In order to fix this issue, we can:
- Parse the response string at client side using `JSON.parse` and then display it in table, For this to work, the response string has be a json string.
- We can remove the table tab altogether if API response is not an array.

**Comment by rohan-arthur** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4822 |
| Effort (months)  | <<number>> |

**Comment by rohan-arthur** [comment]
@sneha122 I agree with @btsgh's comment, in such cases, we should simply not show the `Table` format. 
- we should not be doing magic with the response from the service
- assumption is that the user should still be able to format the response on their own for any further processing

**Comment by sneha122** [comment]
Got it, so it makes sense to remove the table tab if the response is not in the format which table expects, right? @rohan-arthur
