### ISSUE TITLE
[Bug]: Lot of deviation in time taken to setup autocomplete

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith#14749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`startAutoComplete`  took 3600ms in one profile and 2400ms in other profile. That is 50% deviation, while the rest of the code has around 2.5% deviation.

It would help with performance monitoring and performance in general if this deviation can be reduced.
Profiles can be found in the slack thread.

https://theappsmith.slack.com/archives/C024GUDM0LT/p1655467501490139

### Steps To Reproduce

Check the profiles on slack thread attached.

### Version

Both / Latest

**Comment by Rishabh-Rathod** [comment]
Application link :- https://release.app.appsmith.com/applications/62f4fa6eac988524cd26df4b/pages/62f4fa6eac988524cd26df4d/edit

Steps to test :-
1. Open the application ( stress select widget )
2. In dev mode, i added performance.now() before and after the `startAutoComplete` and logged the difference in console
3. Click on select widget
4. Check logs

Results
| Test serial no | metrics |
|---|---|
| 1 | ![SCR-20220811-pv1](https://user-images.githubusercontent.com/23132741/184141109-d882b844-ac1d-45a2-9c7f-048b7f6cb604.png) |
| 2 |  ![SCR-20220811-pvi](https://user-images.githubusercontent.com/23132741/184141124-61bc4455-5acf-4ff6-b814-8790e1bcd51e.png) |
| 3 | ![SCR-20220811-pwr](https://user-images.githubusercontent.com/23132741/184141130-e4dc8202-9cb5-4872-bead-dfd188ca3cdf.png) |
| 4 | ![SCR-20220811-py5](https://user-images.githubusercontent.com/23132741/184141135-536b4cab-7ddd-4d6e-9449-f38cd57afafa.png) |

Numbers seemed to be very close and in expected range.
cc: @SatishGandham can you please check and comment if something was missed or needs to be looked again.

**Comment by SatishGandham** [comment]
@Rishabh-Rathod , It was random and I have seen it 3-4 times in the automated performance testing.
If you are not able to reproduce it, please go through the code once and see if anything stands out.

40ms is a long time to setup autocomplete, any way to minimize this?

**Comment by Rishabh-Rathod** [comment]
> If you are not able to reproduce it, please go through the code once and see if anything stands out.

@SatishGandham just confirming, you meant the perf test code here, correct? 


> 40ms is a long time to setup autocomplete, any way to minimize this?

I will check what could be possibly improved here.

**Comment by SatishGandham** [comment]
> @SatishGandham just confirming, you meant the perf test code here, correct?
@Rishabh-Rathod, No. Autocomplete code.

**Comment by Rishabh-Rathod** [comment]
> 40ms is a long time to set up autocomplete, any way to minimize this?

`startAutoComplete` calls `TernServer.updateDef` which is an expensive call ( even for small def it takes ~40ms and it does deviate ) and as it is a method from the tern library we don’t have control over its logic directly and hence, it limits us to make performance improvement to it.

In [this PR](https://github.com/appsmithorg/appsmith/pull/16263), we are moving customDataDef's update on editor focus instead of `startAutoComplete` with a check to only updateDef when there is a new customDataTree and the editor is onFocus, this way we reduce the number of `TernServer.updateDef` calls and hence performance should be less impacted. 

After these changes, `startAutoComplete` would take around ~0.1 ms as the expensive `TernServer.updateDef` call is moved on focus. 

cc: @SatishGandham
