### ISSUE TITLE
[Task]: Add new toggle for APPSMITH_MAIL_SMTP_AUTH to show/hide SMTP Username & password fields

### ISSUE THREAD

**Issue by ankitakinger** [appsmithorg/appsmith#14798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We are currently turning the function of the GUI toggle item "TLS Protected Connection" to the APPSMITH_MAIL_SMTP_TLS_ENABLED setting.

However, there is a second toggle value APPSMITH_MAIL_SMTP_AUTH in the config, this one has no GUI element (yet).

In the file 'app/client/src/pages/Settings/config/email.ts' for the elements "SMTP Username" and "SMTP Password" via isVisible the visibility is bound to the setting APPSMITH_MAIL_SMTP_TLS_ENABLED - but this is wrong. The visibility must be bound to the setting APPSMITH_MAIL_SMTP_AUTH. Or not?

URL: [localhost/settings/email](localhost/settings/email)

### Version

Self-hosted - latest

**Comment by PerioBalance** [comment]
Færge

**Comment by sharat87** [comment]
The `APPSMITH_MAIL_SMTP_AUTH` is automatically inferred based on whether credentials are provided or not. See:

https://github.com/appsmithorg/appsmith/blob/dbbae79aec1933d7c4d21e59f8b5a872c9b694c5/app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java#L135-L140

Setting this to true when there's no credentials doesn't make sense, and similarly, setting this to false when there's credentials provided, is usually a mistake. We've seen users who were very confused why auth wasn't working, despite giving the credentials. The problem was they often forgot to set this to `true` as well.

**Comment by ankitakinger** [comment]
@sharat87 That makes sense. Closing this issue.
