### ISSUE TITLE
[Task]: PoC on sending binding parameters in a JSON like structure with content-type text/plain

### ISSUE THREAD

**Issue by ChandanBalajiBP** [appsmithorg/appsmith#14792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Client side implementation to send JSON in payload which includes evaluated value of a particular Moustache binding and the data type as well.
2. Verify if all the data in server arrives at once
3. PoC on reactor stream API to clear concepts on this and on the point # 2

Read relevant discussion on [Notion](https://www.notion.so/appsmith/MOM-23rdJune-b849bf73b747469798ac348b2ffc8876)

**Comment by ChandanBalajiBP** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BE-Coders-Pod-6167d73fab4b07001219a3d0/issues/appsmithorg/appsmith/14792?planning-poker) with ZenHub @subrata71

**Comment by subrata71** [comment]
We might need to drop this PoC before it starts. Here's the [comment](https://www.notion.so/MOM-23rdJune-b849bf73b747469798ac348b2ffc8876?d=e3cc8a4849e4451594a1799a1a7480fc#d80ea908242949f58023b233c6d5981d) from Nidhi which indicates that we may need to backtrack at the middle of this PoC due to some issues in JSON. 

Reference (Whole Disucssion)
https://www.notion.so/appsmith/MOM-23rdJune-b849bf73b747469798ac348b2ffc8876

**Comment by subrata71** [comment]
Shared my opinion on this [Notion doc](https://www.notion.so/appsmith/Action-Execution-Request-Payload-e98e58d7e45b4980b5c9c44f8875cfc7)

**Comment by subrata71** [comment]
Currently, we have identified three approaches. Each approach has its own pros and cons. We are trying to convey our understanding through the following Miro board.

https://miro.com/app/board/uXjVOlF6jIQ=/

**Comment by subrata71** [comment]
We have decided not to adopt this approach. The server has to go through the following data conversion when binding parameters are received from the client-side.

- The server receives the binding parameter value along with its data type in a JSON-like structure as byte array e.g. `{"NUMBER": 3233}, {"STRING": "Hello World!"}, {"file": <binary representation of file data being encoded in Base64>}`
- Next the server converts the byte array to `JsonNode` by `objectMapper.readTree(byteArray)`
- After converting into a JsonNode the evaluated value of the binding parameter is extracted from the respective `JsonNode` by `JsonNode.asText()`
- `JsonNode.asText()` returns the string value of the binding parameter and it gets set into the respective parameter variable in the server-side

The above approach didn't work in the case of file data due to the fact `JsonNode.asText()` function returns an empty string when the content is large. A relevant [StackOverflow post](https://stackoverflow.com/questions/48655074/what-is-the-difference-between-astext-and-tostring-in-jsonnode) is shared for reference.

We also had a discussion on this in our first [weekly sync meeting](https://www.notion.so/appsmith/Weekly-Sync-01-a7460c3e0dbe4394a25f5dbcf9abe3ad) of Datatype Handling V1.

Considering the above facts we are closing this issue.

cc: @nidhi-nair @ChandanBalajiBP @sumitsum
