### ISSUE TITLE
[Bug]: Table column's cell background color sets 2 different color in same column when selecting theme color over other colors

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#14943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Table column's cell background shows different color in same column when we select any color from the popup and then select theme color.

Also, it is observed that, **Theme color** is only applicable to the rows where data is present and not to the entire column visible

https://www.loom.com/share/d5417dc138cf42beb0293f519ff989b8

### Steps To Reproduce

1. Drag & Drop Table widget
2. Select any column from property pane
3. Add any color into 'Cell Background' field
4. Now select theme color from the popup
5. Observe that there is 2 different colors can be seen in same column

### Version

Cloud/ Production

**Comment by dilippitchika** [comment]
@shadabbuchh can you check if this is happening in table v2?

**Comment by shadabbuchh** [comment]
> @shadabbuchh can you check if this is happening in table v2?

@dilippitchika the exact same thing does not happen in the Table v2 DP but I observed something similar:
https://www.loom.com/share/e2c7ae5dfd9f416395c6cd4940e46595
If you change the `Cell Background` for the first column, the change occurs for rest of the columns as well where no data is populated.

**Comment by dilippitchika** [comment]
Ok this is a bug we fixed already in v1, @sbalaji1192 can you check this issue - https://github.com/appsmithorg/appsmith/issues/12823 and make the changes in table v2 as well to follow the same.

@shadabbuchh can you please track this in the doc. 

Regarding the issue chandan raised, @sbalaji1192 can you link this issue to table v2 PR so that this automatically closes once table v2 is in prod

**Comment by dilippitchika** [comment]
Fixed in reskinning
