### ISSUE TITLE
[Bug]-[10888]:The Gsheet name is not being displayed to user in the Regular field

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#14977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the user opens an old app with Query it is observed that the Spreedsheet Name is not displayed to user in Regular field format however the it is present in JS format as URL and Query RUN as expected 

### Steps To Reproduce

1) Open an older app 
2) navigate to API 
3) Scroll to  Spreadsheet field name 
and observe that the Sheet name is not populated 
4)Click on JS format 
and observe the URL is present 
5) Click on RUN 
and observe it is working as expected

### Public Sample App

release

### Version

cloud

**Comment by btsgh** [comment]
@nidhi-nair  - Also observed - when we create a Query and choose Fetch Many - here in the screenshot, it shows 19 records, but in my google sheets online I have 21 files.
<img width="872" alt="Screenshot 2022-07-05 at 10 14 41 AM" src="https://user-images.githubusercontent.com/101863839/177251345-90f00eee-740f-44f8-a9ff-b5b26e2c2254.png">

**Comment by rohan-arthur** [comment]
a. 6m gsheet users: 2734
b. 3m gsheet users: 1373
(a-b): 1361

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1361 |
| Effort (months)  | <<number>> |

**Comment by sneha122** [comment]
The issue occurs because `trigger API` which fetches spreadsheet data fails with `500 Authentication failed error`. On further investigation it seems that, refreshToken was not present in database for this particular datasource, re authentication of data source helps but we checked how many such datasources without refreshToken exist in db, so there are total 2080 google sheets datasources on release environment, out of which 1039 were not authenticated and 10 datasources were authenticated but for which refreshToken does not exist. For these 10 datasources we would face the same issue on opening gsheet query, unless user re-authenticates datasource. Reach of this issue to about 1%.

**Note: All the data was obtained from release DB.**

**Comment by rohan-arthur** [comment]
closing this because this looks very much like an edge case, and we haven't heard complaints from users.
