### ISSUE TITLE
[Bug]-[600]:Autocomplete does not update datatype when variable values are changed

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#14989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When variable datatypes are changed from their default values, then autocomplete does not update the data type.

### Steps To Reproduce

1. Add variables of different data types to a JS object and try to access them via widget binding
2. Change variable datatypes by manipulating values - observe that datatypes of variables are not updated as and when datatypes are changed

https://www.loom.com/share/00bf972c69644a0e86740612aa6604fb

### Version

Cloud

**Comment by bharath31** [comment]
Assuming 20% of JSEditor users face this issue 

```jsx
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 600 |
| Effort (months)  | <<number>> |
```

**Comment by Rishabh-Rathod** [comment]
The root cause here is how we evaluate JSObject's variables currently. We only update the value of the variable once the user refreshes the page. 

- Try changing a variable and consuming it in a separate function, you could notice that on the change of variable also the value is not reflected until we refresh the page. 

If we aim to fix the above issue, we would need to also agree on changing the JSObject variable behavior to reflect changes in change. ( _It is possible to do that without enabling reactive variables_ )

The estimation for changing the JSObject behavior would be 4 SP (1 SP = 1 day )

cc: @bharath31 @satbir121

**Comment by bharath31** [comment]
@Rishabh-Rathod thanks for sharing an RCA!
