### ISSUE TITLE
[Epic]: Table widget v2 stability

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#15072]
Epic to track and fix the v1 table issues in v2.

**Comment by zzgvh** [comment]
Maybe I'm posting in the wrong issue, since it's not a "stability" issue per se, and if so I'm sorry. But there is a bug in both v1 and v2 that I'd like to see fixed: 

When the default selected row is set, the table page shown should be the one of the selected row and not the first page. As it is, default selected row is kinda useless as there's no way the user will know that the row is selected unless it's among the first few items.

**Comment by dilippitchika** [comment]
@zzgvh can you help me understand the following
1. Is all your data on the client side? Like you are not using server side pagination?
2. If it's client side data, are you simply suggesting we change the page till we land on the default selected row?

**Comment by zzgvh** [comment]
Hello @dilippitchika! Thanks for taking the time. I guess I'm somewhat of an outlier. I have been using Google spreadsheets as my "database" :stuck_out_tongue:. I did this because it makes changing both data structure and data itself trivial which is very nice when you're developing and trying lots of things out. Sure it has a lot of down sides too, but it has been good when everything is in flux. It also allows my users to easily "get at" the raw data which has proven very useful. So server side pagination isn't available (AFAIK).

My main use case where I need the page of a table to be set is as follows:

* I have a "switchboard" view which serves as the starting point of tasks that the user completes. See image below.
* first, the user selects a row in the top, "master", table 
* this in turn populates a second table, the "tasks", in the same view 
* the user now initiates an action by pressing a button in the "tasks" table
* the user is navigated to another view where the task is completed
* at the end of the task, the user is navigated back to the switchboard

![appsmith_main_view](https://user-images.githubusercontent.com/142613/182545318-52eac635-a0d9-44d2-afc4-30ff918b0332.jpg)

When the user selects a row from the "master", I store the rowIndex in the Appsmith store and the default selected row of the "master" is set to the stored row. This is because most of the time several actions from the "tasks" table are completed one after the other with the selected row of the "master" remaining the same.

And this is where the UX will break if the default selected row in "master" is not on page 1, as the table now shows page 1. The user probably won't notice this, instead, to user it seems like the selected row in "master" has disappeared! 

So it all boils down to the inability to restore the "full state of a page" after leaving and then coming back to it.

Since I'm using google sheets as database my ignorance about server side pagination is more or less complete, hence the following questions. Would the use case described above be solved by using it? Could I store the Table.pageNo and use it when the user returns to the page? Will the table show the correct page in this case? I'm asking because I am considering migrating my backend to Postgres. This is a major undertaking so it'd be good to know of all the upsides!

As always, keep up the good work! What you're doing is amazing, but it could be even more so! :wink:

**Comment by dilippitchika** [comment]
Hey thanks for the info, i believe if you are going to postgres then simply solving the problem on client side will not solve it well enough. 

My current idea is we add a new default page along with default selected row which can contain the details of the page we can go to, however there maybe a few concerns here. I have created a new issue to track this - https://github.com/appsmithorg/appsmith/issues/15672
