### ISSUE TITLE
[Task] Make the Primary CTA on the app contextual

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1508]
## Description

Developers should see Edit as the only CTA on hovering an app card on the applications page.
The launch CTA should move to the context menu of the application card

App Viewers should see Launch as the only CTA in the app card and not see it in the context menu

**Comment by mohanarpit** [comment]
I'm sorry but I don't agree with this implementation. When I have multiple apps (some with edit access & some with view access), I have to change my behaviour for viewing them. This is very disconcerting to me as a user. I wouldn't find the "Launch" button in a consistent place. 

Please re-consider this implementation.

**Comment by Nikhil-Nandagopal** [comment]
@aakashDesign ☝️

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal why is this change necessary? What is the goal here? I don't agree with the implementation suggested because of inconsistency.

**Comment by areyabhishek** [comment]
Aakash and I discussed a consistent solution to this. I understand that the reason to hide the view button is so that new users click on 'Edit' instead of 'View'.
1. Don't show the view button to users if they haven't hit deploy even once in their application(i.e. differentiate between the view mode auto-generated for an app vs. view mode explicitly created by the user)

Minor addition for making the cards look cleaner for view mode folks:
2. Remove the view CTA for users with view permission and turn the entire card clickable(this was part of the old designs, but not implemented)
