### ISSUE TITLE
[Bug]: Table v1 is coming in suggestions on query page

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#15180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="1782" alt="Screenshot 2022-07-13 at 5 26 31 PM" src="https://user-images.githubusercontent.com/83569920/178728755-d8bae9a1-38a9-4c55-b4a7-8728edefd612.png">

### Steps To Reproduce

1. Go to ant query page
2. Run the query and get a response
3. Click on table option from suggestions
4. Observe that Table v1 is dropped on canvas

### Version

Cloud

**Comment by yaldram** [comment]
I did triage this issue here are my findings - 
- Under `ActionRightPane/index.tsx` if we `console.log suggestedWidgets` we get the following 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/13429535/178979024-7f2d600d-4c4d-4736-bffe-f9e1cfd78e81.png">

- In our table widget v2 we have widgetType as TABLE_WIDGET_V2, therefore we are still see table v1 when we click on the table from the suggested widgets tray.

- The `suggestedWidgets` property comes from the backend, whenever we run a `query` or `api` we POST on this url - `Request URL: https://dev.appsmith.com/api/v1/actions/execute`
<img width="486" alt="image" src="https://user-images.githubusercontent.com/13429535/178979659-8f527f54-129e-491d-834b-47123c3d0e05.png">

**Comment by sbalaji1192** [comment]
closing this in favour of #15256
