### ISSUE TITLE
[Bug] Watermark showing up in charts

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1520]
## Description

FusionCharts trial watermark is showing up inside Appsmith

<img width="269" alt="Screen Shot 2020-11-03 at 11 13 16 AM" src="https://user-images.githubusercontent.com/30255708/97953164-ae99a600-1dc5-11eb-90b3-b7eb822c6304.png">

**Comment by mohanarpit** [comment]
Have talked to FusionCharts and gotten a license key from them. Please DM me for this key. This will remove the watermark only on Appsmith Cloud. The self-hosted instances will still have this watermark visible to them.

In order to solve this, please refer to https://www.fusioncharts.com/dev/upgrading/license-activation for steps on license activation for FusionCharts. This should be a build-time variable that is injected when we execute `yarn build`. Please check the implementation of `APPSMITH_SEGMENT_CE_KEY` as a template for how to do this.

**Comment by areyabhishek** [comment]
This is a poor move by them. 👎  They had said we can use Fusioncharts for our open source project. We should move away from them soon.

**Comment by jsartisan** [comment]
@mohanarpit Hey are you sure we can pass this license key in the environment variable? The docs link shared above is not working.

I read this article ( https://www.fusioncharts.com/dev/upgrading/upgrading-from-evaluation-versions ) and It says we will need to download the fusion charts files after purchase.

**Comment by prapullac** [comment]
The watermark is still visible to user. Please refer the the screenshot for the same 
![Screenshot 2020-12-02 at 7 52 51 PM](https://user-images.githubusercontent.com/71753653/100885215-6a8ae580-34d8-11eb-8228-c963c20ec64c.png)

**Comment by prapullac** [comment]
Closing the issue as it is resolved

**Comment by areyabhishek** [comment]
@prapullac @jsartisan @mohanarpit We can use FC in self-hosted versions, so could we please add the license key for those versions? We've already got the confirmation, no need to ask or check.

This is the link to FC docs: https://www.fusioncharts.com/dev/upgrading/license-activation

**Comment by Nikhil-Nandagopal** [comment]
This seems to be working on selfhostes as well now

**Comment by kylewill** [comment]
seeing this as well on self host randomly: 
![image](https://github.com/appsmithorg/appsmith/assets/3108182/368cd95f-26fa-47fa-8d73-3bcadceccf7d)

**Comment by Nikhil-Nandagopal** [comment]
@kylewill we've begun deprecating fusion charts and so you will see this till you update to the latest version where we now have e-charts that does not require a watermark

**Comment by kylewill** [comment]
Ah ok. Is there an upgrade path? I’m woefully out of date :/ guess it’s time
