### ISSUE TITLE
[Bug]: Dynamic height issues observed in Phone widget on DP

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#15388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- [ ] Scenario 1:
1. Drag and drop a Phone Input widget
2. Change height from Fixed to Auto height
3. Observe the Phone number Input area's height of the white space is reduced as below
![image](https://user-images.githubusercontent.com/104895602/180418732-4855dcb2-9df7-46e2-9323-2717e0978efa.png)

- [ ] Scenario 2:
1. Drag and drop a Phone Input widget
2. Enter more than four words in the Label text of the widget
3. Change the Position of the Label from Left to Top
4. Change the Height from Fixed to Auto height
5. Again change the Auto height to Fixed
6. Change the position again from Top to Left
7. Observe the widget is larger in size 
![image](https://user-images.githubusercontent.com/104895602/180426670-537ef163-a026-4647-a33b-bf64325d10ef.png)

**Comment by ankurrsinghal** [comment]
@riodeuno 
For the Scenario 1,
We added a css property in the BaseInputComponent to set `height: auto` when DH is enabled, it's happening because of that. I don't know what changed in the components but it's not serving its purpose. We can remove that.

For Scenario 2,
This is now an anti DH problem, since the height is already increased, changing the label position after setting the `DH` to fixed will not bring any change.

**Comment by ankurrsinghal** [comment]
@Sripriya93 Please find the fix for this issue here #16268

**Comment by btsgh** [comment]
With regards Scenario2 - I would still expect the behavior to be as explained in the bug steps. Is there anyway this can be achieved? @ankurrsinghal @riodeuno 
Scenario1 is solved.

**Comment by ankurrsinghal** [comment]
Yes I agree, that it should revert back, but since the Auto Height is disabled there is no way to change the height on the Fixed mode, may be we can change the height one last time before disabling it, @riodeuno .

**Comment by btsgh** [comment]
Raised a separate issue for Scenario2. Scenario1 is solved.
