### ISSUE TITLE
[Bug]: Generate form button is disabled when JS property is enabled for Auto Generate Form in JSON Form widget

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#15412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we enable JS property for Auto Generate form on JSON Form widget, the Generate form button is seems disabled and cannot be clicked. 
Suppose Auto generate form is set to false under js property, then the Generate form button must be enabled to generate form manually.

https://www.loom.com/share/62c80dabce634934a8cefa4850993085

### Steps To Reproduce

1. Drag & Drop JSON Form onto canvas
2. Disable Auto Generate Form from property pane
3. Now Enable JS property for Auto Generate Form
4. Observe that Auto Generate form is set to false
5. Observe that Generate Button is also disabled

### Version

Cloud/Production

**Comment by dilippitchika** [comment]
@chandannkumar the reason the button will always be disabled is because the JS can change dynamically in the view mode. Since the end user doesn't have access to generate button and only a developer, we didn't enable the button to work with JS.

When using JS for auto-generate evaluates to off, then we freeze the schema to prevent further changes in the schema when data changes. That is the purpose it serves.
