### ISSUE TITLE
[Bug] Appsmith version doesn't show up

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1544]
## Description

On Appsmith cloud, the Appsmith version number and last updated timestamp doesn't show up. Instead there's an empty space at the bottom of the card. Two solutions:
1. Update it to show the version number
2. Or remove the extra space at the bottom of the card so that it doesn't look empty
<img width="267" alt="Screen Shot 2020-11-03 at 11 54 01 PM" src="https://user-images.githubusercontent.com/30255708/98025667-040a9d00-1e30-11eb-8275-d00871f36066.png">

**Comment by hetunandu** [comment]
This needs getting the `REACT_APP_VERSION_ID` & `REACT_APP_VERSION_RELEASE_DATE` env variables set. Good candidates for build time variables right @mohanarpit

**Comment by sharat87** [comment]
@hetunandu The UI of the help box gets quirky when version information is set. Can you take a look or shall I open a new issue for this?

<img width="305" alt="Screenshot 2020-12-11 at 17 07 58" src="https://user-images.githubusercontent.com/120119/101899204-6e52f200-3bd3-11eb-8cfb-68761f2e9f55.png">

Also, if I set the version ID and no version date set, then the Release Date shows "Invalid Date" instead of just not showing up at all.

**Comment by mohanarpit** [comment]
@sharat87 Is there a reason to preface the version with the string "Appsmith"? Can we remove that string? Maybe the text will fit better then?

**Comment by sharat87** [comment]
That string is from the UI, not the environment variables. That is, for the second screenshot, this is the environment variables I set:

```sh
REACT_APP_VERSION_ID=1.2.22 \
REACT_APP_VERSION_RELEASE_DATE=2020-12-10 \
```

**Comment by sharat87** [comment]
Closing as done.
