### ISSUE TITLE
[Feature] Exposing unsafe session token via bindings

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#1547]
## Summary

Appsmith already provides authentication and access control out of the box for the platform, it would be great to extend this to an API backend so that authentication for internal tools no longer need to be built.

## Motivation

This feature makes the process of building an internal tool faster and more secure. Users no longer have to worry about building their own authentication and access control and can directly leverage appsmith.

## Additional Context

The change prosed is as follows
* Expose email, roles, and accessToken as fields in the editor and allow users to send these to their backends
* Expose a backend API /verify which accepts an accessToken and verifies whether the user is authenticated
* Enable restricting APIs based on certain roles

**Comment by Nikhil-Nandagopal** [comment]
@srijanshetty This is the write-up of what we discussed yesterday. Let me know if it looks good.

**Comment by srijanshetty** [comment]
@Nikhil-Nandagopal this looks good. Having this would make applications on appsmith secure by default. :lock:

**Comment by srijanshetty** [comment]
@Nikhil-Nandagopal and @mohanarpit bumping this issues for visibility. Would be nice to know if this is still in design phase and whether I could help somehow :smile:

**Comment by Nikhil-Nandagopal** [comment]
@srijanshetty we came to a conclusion on how to move forward on this today. We'll expose the accessToken as a param in the appsmith.user object and to verify the accessToken, you can hit our already present /me API

curl --location --request GET 'https://api.appsmith.com/api/v1/users/me' \
--header 'Cookie: SESSION={{appsmith.user.accessToken}}' \
--header 'Content-Type: application/json'

This API will return the user object which you can use to verify on your end.

**Comment by srijanshetty** [comment]
This sounds perfect @Nikhil-Nandagopal and @mohanarpit. Will integrate this within a week :smile:

**Comment by hetunandu** [comment]
Implementation details:

- We get the authenticated user information from [this api call](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/userSagas.tsx#L84) you can parse the `document.cookie` at this level to extract the session token set by the server
- We can then set this token with the `unsafe__session_token` key in [this request payload](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/userSagas.tsx#L103) being sent to our redux state along with other user details. This will automatically add this inside the `appsmith.user` object
- If we want to remove this result from the autocomplete hints, we will have to manipulate [this function](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts#L35)

**Comment by mohanarpit** [comment]
On further discussion and evaluation of the pros & cons of this implementation, we've decided to change the implementation for this feature. I was the one who suggested the implementation and on further education, I've changed my opinion. 

The biggest problems with the suggested implementation are: 
1. Exposing `SESSION_ID` in the browser is a security risk. Refer [SO question](https://security.stackexchange.com/questions/150716/does-exposing-a-session-id-create-security-risks).
2. Since we operate on HTTPS, the JS in the browser cannot read the cookie. This makes the entire implementation moot. 

New implementation: 
1. We will add a setting (toggle component) in the API pane which the user has to switch on incase they want the session ID to be sent along with their API invocations being made through Appsmith. 
2. The Appsmith server will honour this setting and stamp all such API calls with the header `X-APPSMITH-SESSION-ID` to the API calls. This header will contain the session Id of the logged in user initiating the API call. 
3. The user can then read this custom header and make a call to `/api/v1/users/me` with the `Cookie` header to verify if the user was really logged in. Curl sample code below:

```
curl --location --request GET 'https://api.appsmith.com/api/v1/users/me'
--header 'Cookie: SESSION={{appsmith.user.accessToken}}'
--header 'Content-Type: application/json'
```
