### ISSUE TITLE
[Bug]: Dynamic height issues observed in Rating widget on DP

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

1. Drag and drop a rating widget and set Height to auto height. Now set Max Rating to 100. Observe that the height increases to hug contents. Now set Max Rating back to 5. The height does not decrease.
<img width="699" alt="Rating_AutoHeight_Rating_Dec" src="https://user-images.githubusercontent.com/101863839/181708329-e7f6f4cf-4ac1-41aa-9210-837154c59e33.png">

**Comment by ankurrsinghal** [comment]
@riodeuno This is happening because, when the rating is between 1 to 5, the expectedHeight in rows is 3 but the logic in the shouldUpdateDynamicHeight is such that it will only compute if its greater than the minDynamicHeightInRows which is set to be 4. Therefore it is not computing it.
<img width="719" alt="Screenshot 2022-08-16 at 7 50 29 PM" src="https://user-images.githubusercontent.com/17961105/184903349-10a279ea-bc86-4d1e-a4c4-8072d2e3deb9.png">

**Comment by ankurrsinghal** [comment]
@btsgh  Please find the fix for this issue, here, #16268

**Comment by Sripriya93** [comment]
Working fine.

![image](https://user-images.githubusercontent.com/104895602/186602624-47582e57-8c70-4c8b-92ce-da20fb600da3.png)

![image](https://user-images.githubusercontent.com/104895602/186602581-401f35fd-53db-4a5e-afb4-9fb6935454b6.png)
