### ISSUE TITLE
[Bug]: Checkbox Group/Switch Group - On selection change> Navigate to page issues on checking/switching

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#15590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I set a onSelectionChange to Navigate to a page, and I check or uncheck a checkbox from the checkbox group, though it navigates to the required page, the box does not get checked or unchecked. 
Note: Navigate to URL works correctly. 

Same behavior is observed even on Switch Group widget

### Steps To Reproduce

Drag and drop a Checkbox Group widget
Set the onSelectionChange to Navigate to a page. 
Uncheck one of the boxes.
User is taken to the Page that he set
However, when we see the checkbox group, we see that the box is not unchecked.
Note: Navigate to URL works correctly. 

Same behavior is observed even on Switch Group widget

### Version

Release

**Comment by dilippitchika** [comment]
@btsgh this is not a bug for the following reason - 

Once you change the page and come back the all the input widgets reset to the default state. 

If you observe the same in input widget ontextchange, you will notice that the value goes back to default value once you come back to the page. All our page context is lost when we leave the page. 

We don't maintain it because we see it as a fresh page now (standard web apps behavior). The way to get this to work is to open the new page in a new tab.
