### ISSUE TITLE
[Feature]: Option to parse CSV Data as per RFC 4180

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith#15747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I am able to upload my CSV file via File picker as a text, and then use javascript snippet to parse the same to return an array of objects which i can feed it to my table widget.

This works fine for a simple CSV file. But if any of the data values in the CSV contains newline characters or commas, then the snippet being used returns incorrect data.

### Why should this be worked on?

When creating a CSV file, need to follow certain standards as per RFC 4180.
Example would be, when using commas or newline characters within the data value, it needs to be enclosed in double quotes or so.

This can get fairly complex to parse via native javascript. Hence we need an alternative, whether it is a library function which we can invoke or a widget's capability to parse the data.

**Comment by dilippitchika** [comment]
Blocks users from visualising their csv data directly in appsmith tables or other places

**Comment by dilippitchika** [comment]
## PRD

### Job story
When my users are working with csv data in filepicker, I want the filepicker to convert csv data to appsmith format so that they can use it in widgets.

## What are we optimising for?
We are optimising for giving a better UX to handle csv files in appsmith and make it convenient to reference data.

### Design flow
1. We introduce a new data format called Arrays for csv data. See image below
2. When this is selected AND user uploads a csv file, the filepicker[id].files.data should now have a parsed csv into array of objects
3. When this is selected AND user uploads a non csv file, the filepicker[id].files.data will be an empty array.

### Parse csv data
We need to see if we can use a library like this to parse the csv file - https://www.npmjs.com/package/csv-parser internally to do this.

### Testing
1. We need to take @tomjose92's help because he is a bit more aware of the problems users run into while using csv data. 
2. We need to check if our delimiter is only `,` or if there's something else which we can support as well. If we can support other formats, then we should just add them as well.
3. We need to specifically check in edge cases like data already having a `,` as part of a string and similar scenarios. Maybe we can find these cases if we just look at how the library tests these cases.

**Comment by dilippitchika** [comment]
Link to internal discussion - https://theappsmith.slack.com/archives/CGBD4N6LX/p1661767341914459

**Comment by dilippitchika** [comment]
Had a discussion with Satish and Tolu. Here are the notes
1. We will support showing array data irrespective of file size.
2. In this case we need to inform the dev that the app will be slower. 
    1. We plan to do this using a helper text below the property for data format after the user selects arrays as the data format. https://github.com/appsmithorg/appsmith/issues/16753 -- Tolu will be picking up this issue in the property pane to add the helper text framework which we can use.
    2. This feature will be blocked until the above one is merged. Once the helper text is available and the dev selects the "Arrays (CSV only)" option we show the following helper text. "Larger files will slow down the app. In such cases upload files to a database and query them"

Other changes - 
Enable dynamic typing field - We need to re-order and re-name it
    1. Re-order it to be below the data-format field
    2. Re-name it to be "Infer data-types from CSV"
    3. Tooltip - Controls if the arrays should try to infer the best possible data type based on the values in csv files.

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika why not continue with the blob approach because the main use case is to insert a CSV into a DB. Editing the CSV in a table seems like the minority use case and not very useful. This way be default, the user gets what they want and it remains peformant

**Comment by dilippitchika** [comment]
It will be a very limiting use case if we go this way, are you sure? Like it's quite likely for people to not get the point of doing this parsing. I thought the opposite was a bigger use case where people wanted to process data on appsmith than upload to db.

**Comment by dilippitchika** [comment]
@Tooluloope @Nikhil-Nandagopal went through some user requests and saw that the aforce team built a sample app around this - uploading csv and showing it in a table. We have quite some requests around it, there were also some where they wanted to upload it to a db.

I suggest we currently **don't enable the functionality of displaying data in the frontend for larger files** (keep showing blobs instead) but allow them to upload the array data into dbs and create a new issue for rendering larger csv files on our UI. Let's see how much traction it gets. With this limited data it's hard to predict if it's essential to work on bigger data right now.

**Comment by dilippitchika** [comment]
Additional scope after discussing with ashit and tolu
- We want to inform users that this will only work with csvs in the helper text when non-csv values are selected in the filepicker file types. So we are appending the following text in such cases - "All non csv filetypes will have an empty value."

**Comment by dilippitchika** [comment]
@Tooluloope reviewed the current message, please update to - "Large files used in widgets directly might slow down the app."
