### ISSUE TITLE
[Bug]: Iframe stop working 

### ISSUE THREAD

**Issue by rodrigo-mahamud** [appsmithorg/appsmith#16172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Before the new update, the iframe with the appsmith app that I had inserted in my website worked fine. Now I get the following error in the console:

Refused to frame 'https://app.appsmith.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

I know that there is a solution for this error by modifying the docker settings, but since I am using the cloud service I don't know how to fix it.

### Steps To Reproduce

Go to the app
Click on the share button
Make the app public
Inser the link the src="" of a html file hosted in a diferent domain
Open the HTML

### Version

Cloud

**Comment by sharat87** [comment]
Hey @rodrigo-mahamud, thank you for reaching out. This was an unintended regression from our recent migration and should now be resolved. Please reopen if you are still facing this problem. Thank you. 🙏

**Comment by snadal** [comment]
Hello @sharat87

I'm not sure if should open a new ticket for this. Self-hosted appsmith with autoupdate still is facing this issue. I tried to manually upgrade without luck.

Are you releasing this fix for self-hosted instances soon?

Thanks

**Comment by rodrigo-mahamud** [comment]
@sharat87 For me the issue has successfully been fixed, thanks a lot 😄

**Comment by sharat87** [comment]
@snadal, sorry you are still facing trouble here. The fix is actually a configuration fix, since the problem is specific to Appsmith's cloud offering. If you are facing the same problem on a self-hosted instance, can you try the configuration from https://docs.appsmith.com/getting-started/setup/instance-configuration/frame-ancestors to whitelist the domains that are allowed to embed your apps and try please? If that doesn't work, please feel free to open a new issue for this. Thanks!

**Comment by snadal** [comment]
Thank you @sharat87 ! 

I didn't noticed this improvement was released in 1.17.10.
