### ISSUE TITLE
[Bug] Reorder widgets logically

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#1622]

**Comment by Debsourabh** [comment]
Reorganise the left-side widgets.

**Comment by areyabhishek** [comment]
1. Icons for the widgets

@Nikhil-Nandagopal Should we break different widgets into discrete items like for charts, multi-select, single-select, etc? Should we do it now, or do it later when we redesign the widget pane?

**Comment by Debsourabh** [comment]
I am handing off the review design for the same. In case we are not breaking things we can just alphabetically organize them and move away from grouping them. This screenshot has some minor modifications made but we can ignore them as we will revamp the widgets at a later point in time. 

So this is just organised as A>Z. I highly recommend a Z>A sorting system and the search to be active when they click on add a widget also. This way they can just press on + and type to search something. Today they have to click on + and then click on search and then type. 

![Capture](https://user-images.githubusercontent.com/34486435/102319894-8e066380-3fa1-11eb-83ed-bba8afe15d2c.PNG)

List in Order

Button
Chart
Checkbox
Container
Date Picker
Dropdown
File Picker
Form
Image
Input
Map
Radio
Rich Text
Table
Tabs
Text
Video

**Comment by Debsourabh** [comment]
Another thing to keep in mind for this is how do we break them up. For example, if we are breaking down the dropdown into 2 parts, then should the text be Single Select Dropdown and Multi-Select Dropdown, or should they be Dropdown - Single and Dropdown - Multiple?

This comes us as people usually first decide what they want and then decide property. So If we write Single Select Dropdown then they have to search for "S" and not "D" but if we name them as Dropdown Single then they can search for "D" and find all the dropdown options. 

This could be a deal-breaker if we do not organize this properly. Think about how they would use it once the Omnibar comes into play. Just putting it out here.

**Comment by Nikhil-Nandagopal** [comment]
We can do this as a quick change so we should do breaking up widgets separately because we need to solve 
"how to create widgets with predefined settings"
If we do break widgets up, we need a search first approach to adding widgets because a read first approach makes discovery very hard. Today widget search is very hard to discover and doesn't feel like the main way a user should add widgets so I think it makes sense to do this with omnibar.

If we're ordering it alphabetically here, don't you feel it makes sense to make it a list and give more focus to names/descriptions instead of the images? Otherwise, I'm not sure how usable alphabetical ordering will be. Apart from that this looks good.

I didn't understand the point about the ordering being Z>A, this would be very hard to read because intuitively we know the alphabets A>Z so searching by reading is easier

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal For now we don't want to change the widget pane designs. We'll do the list view, keyboard first way, etc a little bit later.

So for now:
1. Reorder A to Z
2. Keep the search in focus when someone switches to the widget pane so that they can start typing to find the widget they need

**Comment by prapullac** [comment]
Reopening the issue as the expectation is half fulfilled ie : Re-ording of the widget is done , however the focus on the widget search is functional.
