### ISSUE TITLE
[Bug]: Unable to make public app private

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#16382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to make public app private. this issue is specific to this app. 
https://www.loom.com/share/71a0c84e4c384cb187faf3e441d40bcd

### Steps To Reproduce

https://www.loom.com/share/71a0c84e4c384cb187faf3e441d40bcd

### Public Sample App

https://release-ee-https.appsmith.com/applications/62e3a8b3cde9b676bd1283a8/pages/62e3a8b3cde9b676bd1283aa

### Version

self hosted

**Comment by eco-monk** [comment]
Resource not found is thrown due to missing permission group:
![image](https://user-images.githubusercontent.com/66776129/187363511-11a56681-7e05-4c36-9b10-5eca3ceb6373.png)

App id is being sent properly:
![image](https://user-images.githubusercontent.com/66776129/187363934-c0763e5a-f7e1-46db-ad01-1018cf33b224.png)

**Comment by eco-monk** [comment]
Workaround: Duplicating the application solves this.

- Exporting and importing persists the issue though.
- Not reproducible in https://release.app.appsmith.com

**Comment by eco-monk** [comment]
Nor reproducible in prod.
Tested with app export where the issue was originally reported. 
https://drive.google.com/file/d/1wl4-zI1H2__NjMCYuRxtNYBTa5A9Wr22/view?usp=share_link
