### ISSUE TITLE
[Feature]: Better share-able URL's for Apps

### ISSUE THREAD

**Issue by rbcb-bedag** [appsmithorg/appsmith#16429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Following is an example of a link of an shared app:

https://BASE-URL/app/demo/page1-630f4e9208f7de3285b66fa6

It consists of three parts:
https://BASE-URL/app/#WORKSPACE#/#PAGE#-#ID#
![grafik](https://user-images.githubusercontent.com/71006179/187681429-00fe339d-a0f9-457a-a880-60f250b2aa37.png)

The Workspace and Page name are defined via the creator. But the ID is generated and cannot be changed manually.

### Problem:
Because the last part of the link get's generated (ID), we cannot directly make redirects to this URL before the app is not published/deployed (e.g. for ingress rules in kubernetes etc.)

### Suggestion
Make the URL more friendlier for external configurations. Best would be to remove the ID at the end of the url, because with workspace and page name, it's should already be clear, which page is meant to be loaded.
I can think of the ID as utility for loading the specific version of the app. If this is the case, it would also be possible to just add an additional redirect rule to the latest version, e.g.
https://BASE-URL/app/#WORKSPACE#/#PAGE#-latest
=> points to the latest id of this page of this workspace

### Why should this be worked on?

Allow to share app's without id's in the link, so third-party systems and configurations doesn't need to now the specific version (e.g. ingress rules, DNS Entries). If for some reason the id changes in the link, the configuration in the other systems doesn't need to be updated, because they alleady point to the latest version.

**Comment by areyabhishek** [comment]
Thanks for the request. We do need to update the URLs to be friendlier and easier to read. We’ll prioritise this early next year.

**Comment by Nikhil-Nandagopal** [comment]
@rbcb-bedag the ids in the URL are stable and won't change across deployments. We use them as a unique identifier because the URLs will soon be fully customizable. Are you still facing a challenge when the IDs are stable across versions and deployments? Would love to understand your use case a bit better

**Comment by RowanG1Bilue** [comment]
This feature would be great. In our case, deploying the latest version of the app on the main git branch, to a specific url like: http://baseUrl/app/one-specific-app/deployed
would be good, so that our users will always get the latest version from a static url. They only need to arrive at the default page, so pageId is not important.

**Comment by mp-gh** [comment]
I am working on a control panel type app and I need the pages to be bookmark-able by the end users.  It seems that the act of exporting and importing your app, even if you delete the original app and keep the exact same name, causes the "id" to change, and all of your urls are now different.   
Surely there must be some way around this?  What happens when you need to revert a change and go back to an older version, everyone needs to update all their bookmarks?

**Comment by Nikhil-Nandagopal** [comment]
@mp-gh is there any reason you are using export and import instead of the git feature? You can revert commits and make changes to an app on your users system by pulling changes which will not change the URLs. This is the best way to maintain your applications.

**Comment by mp-gh** [comment]
I was under the impression that the git support was experimental for some reason, if it is fully supported now I'll give it a try.

However another other reason I was interested in importing and exporting was being able to manually ( i.e. sed )  change the files to easily clone and switch to a different host for a testing environment.

If you are able to accomplish imports from git without changing all of the urls hopefully there would be an easy way to let people import from files without changing all of the urls.

**Comment by Nikhil-Nandagopal** [comment]
@mp-gh  just checked with the team and this is available via the app settings. You can select import there and it will overwrite the existing app and not change the URL. I'm now closing this issue
