### ISSUE TITLE
[Bug]: Postgresql db column names not taking dynamically when creating crud with wizard

### ISSUE THREAD

**Issue by diazoxide** [appsmithorg/appsmith#16430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I'm trying to create new table (empty) crud pages on my localhost docker instance, column names setting "col1, col2, col3. e.t.c."

But when adding at least one item on table, wizard generating columns well. 

### Steps To Reproduce

1. Go +New
2. Generate from a data table
3. Select data source "Some Postgres DB"
4. Click "Generate page"

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/25997814/187693451-f2d3b643-0864-42e2-b47a-8a7d526d1ac2.png">

### Version

Self Hosted v1.7.14

**Comment by Nikhil-Nandagopal** [comment]
@diazoxide this some times happens when the first query fails the first time. Is it consistently happening for you?

**Comment by diazoxide** [comment]
@Nikhil-Nandagopal yes it's happening consistently. Even I try to reinstall.

**Comment by Nikhil-Nandagopal** [comment]
@diazoxide can you check whether the select query in your app is able to run? It's possible this is a permission issue preventing it from running.

**Comment by diazoxide** [comment]
@Nikhil-Nandagopal all queries working well. So I find case when it's happening, only when table is empty. When I'm adding only one record on table all column names taking well.

**Comment by nzidol** [comment]
Can confirm the behavior using bit.io and Postgres DB driver, empty table results in right number of columns and data types but not their names. Raw response from the query is an empty array "[]". Might be side effect of how a table widget configures columns from query result, note that "Computed Value" of a column on an empty table is also "{{currentRow.col2}}" but updates to actual column name when table is populated. Since it has the right number of columns and data types it looks like the correct names are available...

**Comment by Nikhil-Nandagopal** [comment]
Oh! Yes that makes sense. The JSON form generates it;s field based on the rows in the table so an empty array would have this effect. We'll look at improving this
