### ISSUE TITLE
[Bug]-[400]:Autocomplete suggestions after this keyword is incorrect during certain conditions

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#16450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When using this keyword, we get autocomplete suggestions referencing the same function as seen in the image and video attached

### Why should this be worked on?

![image](https://user-images.githubusercontent.com/79509062/187932997-c08e3222-a765-4ef8-acf1-b2e116873825.png)

**Comment by Rishabh-Rathod** [comment]
@ramsaptami this doesn’t seem to be related to `console.log` for arrow function JSObject `this.` autocompletion is not supported as discussed before.

**Comment by ramsaptami** [comment]
My bad with the example there, posting the correct snippet where the autocomplete suggestion is incorrect
![image](https://user-images.githubusercontent.com/79509062/188131545-48877af8-a8aa-4587-af15-02728600dc0d.png)

**Comment by Rishabh-Rathod** [comment]
> My bad with the example there, posting the correct snippet where the autocomplete suggestion is incorrect ![image]


This seems like an issue to me rather than a feature request.

Can you please add steps to reproduce this issue? @ramsaptami 

When I tried with normal `console.log(this.)` it gave expected result.
<img width="597" alt="Screenshot 2022-09-02 at 5 19 29 PM" src="https://user-images.githubusercontent.com/23132741/188135243-c18f9226-dc47-49ae-bf5c-d44641ea973d.png">

**Comment by ramsaptami** [comment]
@Rishabh-Rathod this comes up on console log implementation DP. Found at [this](https://github.com/appsmithorg/appsmith/pull/16286) PR

**Comment by Rishabh-Rathod** [comment]
> @Rishabh-Rathod this comes up on console log implementation DP. Found at [this](https://github.com/appsmithorg/appsmith/pull/16286) PR

DP link - https://appsmith-git-feat-console-log-get-appsmith.vercel.app/app/rca-app/autocomplete-62d98f7a93f9315d3b622f65/edit/jsObjects/62da3ec57b5f2a1c15da2ad2

I tried to reproduce the same and wasn’t able to. Can you help with the steps to reproduce? @ramsaptami 

Also, I went through the PR and couldn’t find any change which impacts autocomplete behavior so ideally if the issue was noticed it should also be reproducible on release IMO.

<img width="604" alt="Screenshot 2022-09-03 at 12 25 49 AM" src="https://user-images.githubusercontent.com/23132741/188219689-5fb79500-5901-4975-815b-d8cc5ab0584d.png">

**Comment by ramsaptami** [comment]
So I wasn't able to repro this consistently, I'm suspecting it to be a parsing issue and it only appears under certain conditions. In the video attached, this issue is reproducible only towards the end, which was my third try, and after a while, the incorrect suggestion corrected itself on its own but continued to incorrectly suggest the parent function sometimes.

https://www.loom.com/share/48825e4860504cc995dbc28c49887bab

**Comment by Rishabh-Rathod** [comment]
@ramsaptami I tried to reproduce this and was able to do it once. This happens without `console.log` statement too and is not related to the console feature. 

I would suggest updating the issue title accordingly.

**Comment by bharath31** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 200 |
| Effort (months)  | 0.5 |

**Comment by bharath31** [comment]
@arunvjn is this related to #15472?

**Comment by arunvjn** [comment]
Yes. If we are looking to implement multiple exports, `this` value and is autocomplete suggestions might have to be adjusted differently.

**Comment by rohan-arthur** [comment]
tried several times (~15), and could not reproduce this issue.
