### ISSUE TITLE
[Bug]: When height is changed from minimum to a larger size input space is also expanded along with the label space

### ISSUE THREAD

**Issue by Sripriya93** [appsmithorg/appsmith#16494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Drag and drop any of the Input type widgets and change height property to Auto height with limits, Change the Min height to a larger size than the actual height and observe the Input space is also getting expanded, but its different for the select type widgets.

Which one is the right way to get expanded, Input type widgets or the Select type widgets

Currency Input (Input, Phone input) 
Date picker (Multi tree select, Multi select, Select, Tree select)

![image](https://user-images.githubusercontent.com/104895602/188124443-7a8656bb-f228-4bf1-8bb0-25222a581712.png)

**Comment by ankurrsinghal** [comment]
<img width="562" alt="Screenshot 2022-10-26 at 12 40 42 PM" src="https://user-images.githubusercontent.com/17961105/197958549-43c073e2-c639-492e-a5b7-b1dc7b0353bc.png">

Hey @Sripriya93 I was checking this issue, it is the same expected behavior in the release, we shouldn't divert from anything different from the release (the screenshot is what we have in the release). So please close the issue if you agree.

**Comment by Sripriya93** [comment]
Based on the comment above, closing this issue for dynamic height. But as part of release this is still an issue, so if we could push this issue to the concerned person, it could be solved in release. @rohitagarwal88 , could you help here please.
