### ISSUE TITLE
[Bug]: Null inputs somehow become empty strings when they are added in Supabase

### ISSUE THREAD

**Issue by muezz** [appsmithorg/appsmith#16604]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Discord message link : https://discord.com/channels/725602949748752515/1014430738889850930/1016987275273453588

When I make a form and use its input fields to create a row in my Supabase table, the `null` fields somehow become empty strings. It is hard to explain in words so please have a look at the steps to reproduce and the relevant screenshots.

<details><summary>Read this after going through the steps below</summary><p>

All steps show that there is no way to enter a null value to Supabase through Appsmith. Now it is possible that I am doing something wrong. Please let me know if that is the case. It is also possible that the fault is in Supabase but that is unlikely, I think.

</p></details>

### Steps To Reproduce

1. Create a `test` table in your Supabase Table Editor with the given constraints. Keep in mind that `col_1` is **nullable** and its default value is `NULL`. `col_2` is **NOT nullable** and its default value is also `NULL` but this becomes pointless as any row added with a null will not be allowed and there never will be a row with this default value. `col_3` is also **nullable** and the default value is an **Empty String** (one of two default options  in Supabase).
<details><summary>screenshot for 1</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188819698-6047584d-015f-4fa0-8a47-b81dca5a34de.png)

</p></details>

2. Try to insert a new row from within your Supabase table editor without entering any values in any column field. It would give you an error given below which is the correct behavior. 
<details><summary>screenshot for 2</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188823849-7c2af244-a460-48b5-8581-19b306864ec7.png)

</p></details>

3. After the error, enter any value in the highlighted field and leave the rest empty. This should add the following row. Notice that all fields have the values that they should up until now.
<details><summary>screenshot for 3</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188824307-86ce0cca-349d-43f9-b6ca-aba55279db98.png)

</p></details>

4. Now start a new Appsmith app and create the following UI. Leave the default values as empty (**Nothing inside the Default Text param**.
<details><summary>screenshot for 4</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188828423-58987a89-b318-452e-bedc-b7c40f24cc16.png)

</p></details>

5. Link your Supabase with Appsmith and then create the following `INSERT` query.
<details><summary>screenshot for 5</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188825142-c6fa77c2-5f51-4708-8ae2-55bbdc2f0efd.png)

</p></details>

6. Right after making creating this `INSERT` query, run this query while there is no data in the fields. The query goes through successfully and a new row given below is added to the table. Ideally, I should have gotten an error that no null value is allowed in `col_2` as its not nullable. This is the first encounter with the possible problem.
<details><summary>screenshot for 6</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188825562-32486892-f0de-4de9-b7d9-191ad22988a2.png)

</p></details>

7. Now insert `null` into all three fields by inserting `{{null}}` in  their **Default Text**. Now run the query again and it should go successfully again. The inserted row is exactly the same as before. Problem mentioned in the last step is still present.
<details><summary>screenshot for 7</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188826256-4b10fbc4-4439-4038-8f0f-439430da072e.png)

</p></details>

8. Just out of curiosity, lets see what happens if we insert double quotes either inside the field or the Default Text of all fields.
<details><summary>screenshot for 8</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188826745-7987a270-6c84-46ad-92bf-29ade2a73320.png)

</p></details>

9. To be sure how Supabase will read each row in its Database functions, I ran a simple query to select all rows inside the SQL Editor of the Supabase Dashboard. The only value that is truly `null` is in the first row. 
<details><summary>screenshot for 9</summary><p>

![image](https://user-images.githubusercontent.com/100420605/188827250-5bc03bd9-ee7d-4f39-804f-a444d11b152a.png)

</p></details>

### Version

Cloud - v1.7.15

**Comment by Nikhil-Nandagopal** [comment]
@muezz can you try inserting {{"NULL"}}?

**Comment by Nikhil-Nandagopal** [comment]
@muezz this is because you're trying to translate javascript null to postgres NULL which are 2 different types.
You can handle this by adding a check in the query {{ Input1.text || "NULL" }} Hope this works for you!

**Comment by PaulMcF1987** [comment]
@Nikhil-Nandagopal I have asked the same thing in the discord chat and been pointed here...

The issue I see with this is....

Adding `{{ Input1.text || "NULL" }}` might work fine with the initial entry...
However... If the entry is then to be edited, you can either fill the cell with `{{appsmith.URL.queryParams.columnA}}` or the above...

So when editing the entry, it can then lead to blank cells again if using `{{appsmith.URL.queryParams.columnA}}` or double work to repopulate the input if using  `{{ Input1.text || "NULL" }}`

For example... I use appsmith to record jobs that I have done, when the jobs are saved, there is no invoice number attached but because there is no invoice number input field in the `add job` form, the field saves as `NULL`
I then have a query which looks for jobs with a `NULL` value in the invoice field so that I can then create an invoice and add the invoice number...
However, the `Edit Job` form has a space to add the invoice number... If I edit the rest of the job and do not add an invoice number the field changes from `NULL` to a `blank field`

Similarly... If I had an invoice number added and used the default value of `{{ Input1.text || "NULL" }}` I would then need to make sure and remember to re-add the invoice number for every job that needs edited

This creates a lot of additional work that shouldnt be needed if there is a way to treat blank inputs in the query as `NULL`

**Comment by PaulMcF1987** [comment]
Also... I noticed that if a Date/Time input is left blank, that it populates the cell as `NULL` why does the date/time widget do this but the text input widget does not?

**Comment by Nikhil-Nandagopal** [comment]
@PaulMcF1987 I think the default value for date is undefined while it must be "" for text. So potentially passing {{undefined}} may also work
