### ISSUE TITLE
[Feature]: Provide form fields for entering API/Query params on the action selector

### ISSUE THREAD

**Issue by rimildeyjsr** [appsmithorg/appsmith#16899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As of now, Users must enter JSON key-value pairs for passing params to APIs and Queries. A simple form experience would be helpful

### Why should this be worked on?

This will improve the user experience

**Comment by ravikp7** [comment]
Considering the current behavior, when we add a new query, we already have a default commented-out key-value pair for the params object. The behavior looks good to me and I think this issue is no more applicable. @bharath31 Can you please confirm?
![Screenshot 2023-05-29 at 12.09.18 PM.png](https://images.zenhubusercontent.com/634fa41f0ccac9aa40f755c2/d906e1c4-5246-4523-ad7a-251c0e82ef4b)

**Comment by bharath31** [comment]
@ravikp7 we should improve this experience by providing form fields for entering params

**Comment by bharath31** [comment]
25% of all executed queries have parameters. Form fields will add more value.

**Comment by Nikhil-Nandagopal** [comment]
@rishabhrathod01 we should remove the params entirely from the action selector because we do not expect users to pass values as params.
