### ISSUE TITLE
Select widget deselects on clicking again

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#16948]
The select widget works weird on prod as well, selecting the widget and then clicking on it sometimes deselects the widget in previous and this version of react, this is because of the combination of our keyboard navigation on the property pane that we kick off when a widget is selected vs the select widgets own keyboard navigation support. This is a hunch based on how the widget behaves but needs more investigation coz its a third party widget.

_Originally posted by @marks0351 in https://github.com/appsmithorg/appsmith/issues/16257#issuecomment-1236882805_

**Comment by somangshu** [comment]
@Tooluloope can you check what is happening here, I believe this is happening in the edit mode.

@marks0351 can provide more context here

**Comment by marks0351** [comment]
https://www.loom.com/share/d478188c87124f02b769b806c0c546af
@Tooluloope

**Comment by marks0351** [comment]
https://www.loom.com/share/b7938d17a978448685a2c27f6b9cf991

**Comment by aswathkk** [comment]
Here are my observations:
- SelectWidget makes use of Blueprint Select
  - When we open the dropdown, we can scroll the canvas
  - When we open the dropdown, the focus sometimes shifts from input to property pane's first property. This happens due to a change I've done while working on making the property pane keyboard accessible. This is something that is found to be fixed in another PR that I'm working on currently.
- TreeSelect, MultiSelect, MultiSelectTree makes use of rc-select & rc-tree-select components
  - When we open the dropdown, we are unable to scroll the canvas unless we close the dropdown
  - Sometimes, when we open the dropdown the property pane is not getting opened
  
The problem with SelectWidget is something that is related to the property pane.
@Tooluloope have you got some time to investigate on what's happening with TreeSelect, MultiSelect and MultiSelectTree?
I think it's something to do with rc-select

cc: @somangshu @marks0351

**Comment by somangshu** [comment]
> When we open the dropdown, we are unable to scroll the canvas unless we close the dropdown
This seems like an appropriate behaviour according to me, compared to the dropdown scrolling with the page. 

> Sometimes, when we open the dropdown the property pane is not getting opened
We will have to check this internally, Let us know if you have more info on this @aswathkk

**Comment by laveena-en** [comment]
Tested and verified the fix for the entire select widget family on this PR.
