### ISSUE TITLE
[Bug]-[5000]:Clear history on logout

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#16941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Navigation history should be cleared when a user logs out of Appsmith, to prevent leaking of resource IDs and any sensitive information in URL query params.

Slack conversation: <https://theappsmith.slack.com/archives/CPG2ZTXEY/p1663750172617339>.

### Steps To Reproduce

https://user-images.githubusercontent.com/120119/191460664-02cc63a2-3846-42f7-b068-694b494f163a.mov

### Version

Cloud

**Comment by kocharrahul7** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 5000 |
| Effort (months)  | 0.5 |

**Comment by ginilpg** [comment]
@hetunandu The back button issue might be resolved by deleting the navigation history, but the same errors still appear if the URL is accessed from the browser's history. Instead of clearing the navigation history, should we focus on fixing the redirection problem when there is no user authentication?

**Comment by eco-monk** [comment]
Added estimates for cypress.

**Comment by eco-monk** [comment]
Turns out this happens only locally.
Moving to QA, so we can get this verified and closed.
