### ISSUE TITLE
[Bug]: In google sheets ds, xslx extension files are not being fetched from gs data source

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#17108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In google sheets ds, when we create a Query and choose Fetch Many and choose Fetch Spreadsheets - xslx extension files are not seen in the list that is fetched

### Steps To Reproduce

1. Create a Google sheets ds .. save and authorize it. Ensure there is a file of extension xslx in your google sheets database, along with other gsheets files.
2. Now create a new api - choose Fetch Many -> Spreadsheets
3. Note that the file with the xslx extension does not get pulled/listed.

### Version

Production

**Comment by sneha122** [comment]
When fetching the list of spreadsheets from Google Drive API, in the query we specify the mimeType as `application/vnd.google-apps.spreadsheet` which fetches all google sheets but does not list files with xlsx extension. In order to resolve this issue, we found a mimeType which can help us fetch xlsx files as well `'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'`, Now the problem occurs when we try to fetch sheet rows for this xlsx file it throws the error:
```
{
    "code": 5000,
    "message": "This operation is not supported for this document",
    "errorType": "INTERNAL_ERROR"
}
```
Google Sheets API does not support reading/updating files with other mime types. In order to solve this problem, we have a couple of approaches:

- We can show these xlsx files while listing the spreadsheets, but when user wants to fetch the sheet rows data for such files, we can show the error message saying they need to convert these xlsx files to google sheets and then perform these operations.
- We can convert these xlsx files into equivalent google sheets on the server side and use converted google sheets files to read information from xlsx files. But we can use this approach only for reading data from xlsx files and not modifying, because if we insert or update any data, it will be updated in the converted file and not the original xlsx file.
- We can read other type files as a binary and try to interpret them on the API server but it does not seem feasible because of the effort required.

**Comment by Nikhil-Nandagopal** [comment]
This doesn't seem like an expectation for users since the xslx is different from the GSheet File type. If this is a need, lets raise this as a separate feature request but I don't think we've heard this before
