### ISSUE TITLE
[Bug]: Unlink show pagination property to server side pagination property

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#17148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i turn off show pagination today, it also hides server side pagination property. This creates a problem because users are not able to understand how to make the table scroll yet

### Steps To Reproduce

1. Add a table
2. Set show pagination to off
3. Observe it hides server side pagination setting
4. Turn show pagination on
5. Set server side pagination to true
6. Observe that the table scrolls if you have longer data

### Version

Production

**Comment by kamakshibhat-appsmith** [comment]
@aswathkk @dilippitchika  Should we disable the Total Records Count and other on page change properties if Show Pagination is OFF and Server Side Pagination is ON ?
Because if pagination is OFF ,the user has no use of Total Records Count and other Page Change action. 
Does this make sense? Or am i missing some sort of use case here

**Comment by dilippitchika** [comment]
@kamakshibhat-appsmith we will fix this in another epic - https://github.com/appsmithorg/appsmith/issues/13180
