### ISSUE TITLE
[Bug]: Expressions used in a binding on the query editor are not resolved to a value

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#17211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

An extension of #16377 where expressions used within a query editor was being truncated but the issue with resolving a value from the expression still needs a fix

### Steps To Reproduce

1. Follow steps mentioned in issue #16377 

### Version

Cloud

**Comment by ramsaptami** [comment]
Set these functions to run on page load and you can see the queries fail since the fail safe-expressions are not picked up for evaluation

**Comment by Irongade** [comment]
I can't seem to reproduce this bug, can you make a video where this scenario is happening?

**Comment by Irongade** [comment]
![image (1)](https://user-images.githubusercontent.com/37867493/193795251-c8ae669e-3063-4a01-8d21-2a599cd047bb.png)

After triaging this issue with @ramsaptami We came to the conclusion that this isn't a bug, The  evaluation is happening correctly and the API is only failing because the URL is wrong.
