### ISSUE TITLE
[Bug]: In Few workspaces the internal server error is displayed when user tries to leave the workspace

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#17235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the internal server error is displayed when a user tries to leave the workspace this is happening in 2 of my workspaces
1.Regression_sep19
2.share_modalcheck
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/193259832-3feaad75-cd5b-449c-b5c9-6936a66b1b1e.png">

### Steps To Reproduce

1. Login as user eleven@appsmith.com
2. the workspace name is Regression_sep19
3. try to leave the workspace
4. the user is facing the error "internal server error"

### Version

release

**Comment by trishaanand** [comment]
This issue is being seen only on Enterprise Edition. Only the Developers and the App Viewers are currently not able to leave a workspace which has been created over the last two weeks. The out right for such workspaces would be to request an administrator of such workspaces to remove the member from the workspace from `Manage members` page.

**Comment by vuiets** [comment]
@trishaanand doesn't look like this is isoloated to _Business_ edition users, a cloud user has complained about this a few days back in https://github.com/appsmithorg/appsmith/issues/17606. Could we check what's going wrong?
