### ISSUE TITLE
[Feature] Execute functions after a page load action

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#1725]
## Summary
After we set a Api or Query to be on page load, there should be a text binding space to execute any actions after the action is loaded

## Motivation
There can be workflows like Auth that need to store token or navigate according to the response of the call.

<img width="311" alt="Screenshot 2020-11-14 at 12 33 15 PM" src="https://user-images.githubusercontent.com/12022471/99141892-9f441380-2675-11eb-8c16-547f08df474d.png">

**Comment by mohanarpit** [comment]
Instead of adding this as another setting in the API pane, we should enable this feature via JS functions. So in this case, the user would have to write a JS function that invokes the API and then stores the result in the browser's localStorage. The JS function would be executed onPageLoad.

IMHO, the JS function solve will be a more holistic solve rather than adding more settings to the API pane itself.

**Comment by Nikhil-Nandagopal** [comment]
+1 We should enable this via onPageLoad for JS

**Comment by mohanarpit** [comment]
Closing this issue in favour of: #1640
