### ISSUE TITLE
[Feature]: Create a loader/progress indicator widget, which will update as the queries and widgets load in on the background.

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#17267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user wants to implement a global circular progress indicator where the loading widget comes in the foreground while the widgets in the background are slightly faded.

### Why should this be worked on?

This is a way for users and app viewers to see their app load in, while still being informed that the app is taking some time to fetch their data.

**Comment by muezz** [comment]
For my particular use case, I, willingly, disable "Run on Page Load" option for ALL of my database queries as I want to run them in a specific order. I run them individually and in order using a JS async function which is the only thing that is allowed to run on page load. Although this works for me, the queries running, loading and updating values on my dashboard one by one is not visually pleasing and would like the following feature:

- In some option/property of the app, I should be able to provide this feature a single async function where if that async function is running, the app automatically puts the whole app in the background (slightly faded) and an infinitely loading progress indicator until the function is done.
- You can also choose to let the user make it the default behavior where if they choose this option, ANY async function or query call brings up this loading indicator.
- This functionality should also be extended to errors. I do not like when something bad happens and all of a sudden, 20+ text boxes and charts in my dashboard either become empty or say "NaN". It would be better that, just like the indicator, an error message could be made visible in the global foreground.

To be fair, this could be done with an automatic navigation to an error and loading tab/page when my async function's `isLoading` method is true. But this should be built-in as, otherwise, setting this up is too much work for every new app.

**Comment by Nikhil-Nandagopal** [comment]
@muezz could you not achieve this with a circular progress widget and the modal? You can show the modal with the progress widget till the data is loaded and then hide it

**Comment by muezz** [comment]
@Nikhil-Nandagopal I could do it that way and in fact I am implementing it right now. However, I think this could be a good feature if this becomes a built-in property.
