### ISSUE TITLE
[Feature] Google Sheets Plugin

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#1729]
A user should be able to link their Google sheets and use that as a data source.

- [ ] Google sheet custom plugin
- [ ] Custom UI form and editor for Google Sheets in the API pane. Try using the Query Editor component in the API pane first.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit @aakashDesign where are the designs for this?

**Comment by Nikhil-Nandagopal** [comment]
## Product Note
The following actions need to be supported via the google sheet plugin
- List Sheets
  - returns a list of sheet objects
- Delete Sheet
  - Deletes a sheet with a specified sheet id, returns a success/failure 
- Create New Sheet
  - Takes a sheet name and array of Row Objects as an input and creates a sheet. Returns a sheet object
- Fetch Sheet Rows
  - Takes a spreadsheet ID
  - Takes a Sheet Name
  - Takes a Column Header Index: Default 1, This value is used as the keys for the response and is ignored from the list of rows returned
  - Takes a Query Method (Default Query Rows)
    - Query Rows: Returns a list of Row objects
      - Takes an offset
      - Takes a limit
    - Query Range: Returns a list of Row Objects
      - Takes a range A1:B
- Update Row
  - Takes a Sheet Name
  - Takes a Row Object and index as inputs. Returns success/failure
- Delete Row
  - Takes a Sheet Name 
  - Takes a row index as input. Returns success/failure
- Insert Row
  - Takes a Sheet Name
  - Takes a Row Object as input and adds a row after the last filled row with any column filled
- Bulk Update
  - Takes an Array of Row Objects
  - Takes a Primary Column ID which is the name of the column used to find the Row Object to update  

Sheet Object
1. URL
2. ID
3. Name
4. Created Date
5. Updated Date
6. Permissions (optional)

Row Object: { [columnName]: cellValue, index: rowIndex }

**Comment by nidhi-nair** [comment]
Adding questions that might add more visibility into how things work:
1. Do we only support deleting an entire spreadsheet file or deleting a single sheet within a spreadsheet as well? The latter will then need sheet Id
2. While creating a new sheet, since we have no initial data, how do we determine the ordering of columns?
3. Since we allow fetching rows with row and column offsets, how do we determine this offset (if present) when trying to update? I feel like these offsets can be something users should save in their Appsmith store, because we do not retain context between two different actions and two different action executions ourselves.
4. What is the purpose of taking the primary column ID in the bulk update request?
5. We have an unsolved problem with the current implementation which is that we do not retain ordering of columns between the sheet's _array of arrays_ and returned _array of objects_. This breaks the way columns are displayed when the column headers are numerical. Can we start using a columnIndex in the tableWidget to help with this?

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair 
1. We should support deleting a sheet so lets add a sheet name parameter as well
2. Since the sheet is being programmatically created, the order should not matter I think it's best to just use the object key order here
3. Not sure about what you mean here. Can this just be treated as a skip parameter? i.e if the value is 10 start from the 10th row?
4. It is to compare the column value in the row object with the value in the sheet so we're able to update the corresponding rows in the sheet
5. Can you give me an example of this?

**Comment by nidhi-nair** [comment]
For 4, the row objects should be able to do this mapping, similar to the update query right?

For 5, consider the following _array of arrays_:
```
[
  [h1, h2, 3, h4],
  [v1, v2, v3, v4]
]
```
This gets converted into:
```
[{
  "3": "v3",
  "h1": "v1",
  "h2": "v2",
  "h4": "v4"
}]
```

**Comment by nidhi-nair** [comment]
#3589 for other enhancements that are needed in the plugin

**Comment by nidhi-nair** [comment]
@Nikhil-Nandagopal Documenting changes from list above, not including behaviour:

* We will be losing the ability to map responses to tables with row objects

1. List Sheets
  -- If we return just the name and id, this is one API call. If we want to also retrieve metadata, this is n+1 calls , since every file's metadata is retrieved separately
2. Delete spreadsheet
3. Delete sheet
4. Create sheet
  -- Column ordering will need to be looked at for this request
5. Update row
  -- This will need a GET call to understand which columns to update. But which range would we use in this get call? One option is to get the entire sheet, but in the case of get requests with non-default header rows, which row would we use to map the column headers? Should we add the header row option here?
6. Insert row
  -- Same as update
7. Bulk Update
  -- Not clear on what the user experience would be. Seems a little different from the others.

**Comment by Nikhil-Nandagopal** [comment]
These have been resolved

**Comment by nidhi-nair** [comment]
* Delete spreadsheet is done via delete sheets, by using the option "All"
* Insert row will have the same structure as update
* Bulk update will also have a Table header index

**Comment by nidhi-nair** [comment]
@prapullac These changes will be coming into release soon, but could you please help out with testing changes in a separate environment in the meantime? This will help us reduce the load on release.

Test env: https://test.appsmith.com

**Comment by prapullac** [comment]
@nidhi-nair Sure I would test in the above mentioned test environment.
