### ISSUE TITLE
[Bug] development nginx conf does not force redirect to https

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#1732]
## Description

I was setting up local environment, didn't realise I was on http instead of https. everything seemed to work on the surface, only to break down on API calls.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Go to http://dev.appsmith.com
2. Try logging in

### Important Details
 - Version: dev on latest `release`  [799b88b](https://github.com/appsmithorg/appsmith/commit/799b88b6d4b9b400198b6d7f0289fb661f5e73f0)
 - OS:  Ubuntu on WSL2 (Independent of OS)
 - Browser: Chrome (Independent of browser)

I'll submit a PR to force a redirect to https in local nginx.conf template files

**Comment by mohanarpit** [comment]
I don't think we should do this because ideally, we would like all developers to be running the Appsmith system (in it's entirety) on their own local machines. I know that the release endpoint is documented in our contribution guide today, but we should remove that from the contribution doc as well and give people a simple Docker-driven way to setup the Java server as well on their own machines.

I understand that this causes some issues & heartburn during the contributor setup process, but I don't think this is the right solve.

**Comment by ofpiyush** [comment]
I've been seeing this from the lens of improving the existing setup. 

I don't think I understand the average contributor enough yet to make a broader call on "do we want to double down on docker?"

One way to think about it is to have minimal dependencies/steps:

Right now, the setup without docker is still fairly straightforward for someone that wants to work just on the UI. With a little bit of work, we can remove the dependency on nginx as well and simplify dev UX further.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit this seems to have come up quite a few times with frontend folk. If we want good frontend contributions, maybe we should re-think our philosophy on this?

**Comment by ofpiyush** [comment]
closing as the related PR has been merged
