### ISSUE TITLE
[Feature] Create a preview mode for apps

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#1741]
## Summary

Appsmith needs a preview mode so that users can easily see their changes before deploying them to a live URL. This will enable developers to quickly see their updates and understand how their app's current version works.

## Motivation

This should be worked on because it's a way of allowing developers to try the end-user mode without deploying changes.
They can test their app if they have conditional visibility for certain widgets.

**Comment by nidhi-nair** [comment]
@areyabhishek Will the edit mode then disable action events (like onClick of button, or onPageChange of table)? I have always been using just a click on the widget to open the property pane, because that is so much more convenient but I realized that I have actually been triggering the onClick action every time I click a button.

**Comment by areyabhishek** [comment]
I'm not sure about disabling these actions because it's convenient to be able to test while building. It might become annoying to always use the preview mode for testing basic functionality.
We should definitely disable zoom for the map widget because it interferes with drag and drop.
