### ISSUE TITLE
[Bug]: Table shows a scrollbar when trying to fit all items in table window

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#17857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When i try to adjust the height of table to make sure no more rows are present, the table still ends up showing an extra row all the time.

### Steps To Reproduce

https://www.loom.com/share/6141092d38ef4be09ce24ed85fd4d8f6

### Version

Release

**Comment by keyurparalkar** [comment]
@dilippitchika @sbalaji1192 I think rather than solving this issue via JS, we should solve it via another approach. 

I have analysed this issue and found out that this issue happens whenever the table's content exceeds the height of the parent container. 

To solve this we should:
1. When we remove the `ROW_VIRTUAL_OFFSET` from the size parameter of `FixedSizeList`
2. Set the table's header to be 30px 
3. Set the parent container's height with an offset. With this offset in place the height of the parent container remains greater than the table's content thus helping to keep table with no vertical scroll bars when rows are completely fit.

**Comment by dilippitchika** [comment]
Internal comment

Requirement - @dilippitchika to rephrase

Context of table - Table row height is default, short or tall we will stick to this logic
1. 10 rows that perfectly fit without scrollbar and you have only 20% space remaining to show 11th row, then we only show 10 rows
2. 10 rows that perfectly fit without scrollbar and you have only 35% space remaining to show 11th row, then we only show 11 rows. WE WILL CONTINUE TO SEE SCROLLBAR
3. When 30% of space remains - 11th row is shown. WE WILL CONTINUE TO SEE SCROLLBAR. 

This doesn't apply to rows with images and wrapping, we will only follow the page size variable to determine the logic

Suggestions
1. Change this to task or feature
2. Hypothesis - Our current hypothesis is just to fit for scenarios where it's expected to not exceed.
3. New hypothesis - We will show blank space and let the 11th row only come when 100% space is available for 11th row.

NOT DOING
5. New new hypothesis - We have a max row height and min row height and the height of a row is variable. Virtualisation has to be updated

style is default - 40px
min row height - 36px
max row height - 44 px

10 rows fit and 11th row fits 50% - 20px
20px/10 = 2px per row - each row will have 42px now

Impact - Event - table resize exceed -> if there's a scrollbar on table and page size
Laveena is using this feature
1. 11 rows coming but space is only there for 10 - scrollbar true, pagesize 10
2. 10 rows come - scrollbar false, pagesize 10
3. Create a new event - launch that, then we will launch our fix and we see if there's a dip


1. Gitstart updates the widget_resize_end event to contain the details of table's scrollbar and pagesize. -- Create a new issue @keyurparalkar 
2. We assign the issue to gitstart

**Comment by sbalaji1192** [comment]
@somangshu @dilippitchika I propose a small change in the suggested change, We show only 10 rows when space is available for 10.5 rows. But instead of leaving the remaining space blank, we can re-distribute the remaining space between the 10 rows to avoid the blank space. We can work on this along with Cypress tests in about a day.

**Comment by somangshu** [comment]
@sbalaji1192 this does not affect our pagesize or cell wrapping logic right?

**Comment by sbalaji1192** [comment]
@somangshu This will affect our page size in the existing apps, Most of our tables in the existing apps where we are seeing the scrollbar, will show one less row once we push this change. 
will not affect the cell wrapping feature.

**Comment by somangshu** [comment]
How does that affect the end user experience? Is it going to be surprising in any way?

Also, what does the effort required look like right now @sbalaji1192

**Comment by sbalaji1192** [comment]
@sbalaji1192 It shouldn't surprise most of our users in my opinion. Our user will see n - 1 rows instead of n rows. Which should not create any technical issues for them for the majority of use cases.

Effortwise, Should not be much. Today we have a static row height, which should be calculated dynamically. There will be some implication on the dynamic height feature later.

**Comment by ankitakinger** [comment]
This is still reproducible at times. Not completely resolved.

**Comment by eedwardsSGS** [comment]
This problem still persists if an icon button is used as a column type.
