### ISSUE TITLE
[Bug]: App copies cannot be accessed

### ISSUE THREAD

**Issue by alinaepanaite** [appsmithorg/appsmith#17864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, 
We have duplicated an app, and the copies can't be accessed. 
for one duplicate app we get the 'internal server error', and the other duplicate just doesnt open. We want to perform changes on the initial app, but as we cannot save the initial version in a duplicate , it is a major issue for us. Please support.

Morph_Parked  - was a firts duplicate that we created from Morph_v0
Moprh_v0 copy - is a second duplicare.

Uploading Screen Recording 2022-10-25 at 10.58.34.mov…

both can't be accessed.

Thanks,
alina

### Steps To Reproduce

Go to app.  'Moprh_parked' or "Morph_v0 Copy"
click Edit
error-or no rosponse

### Version

Appsmith v1.8.6-SNAPSHOT

**Comment by rohan-arthur** [comment]
@alinaepanaite sorry you're facing this problem. Would you please share more details so that we can investigate this quicker? 
1. The screen recording seems like it failed in attachment, would you please re-attach it?
2. Are you duplicating the app in the same workspace? 
3. Would be great if you can share a screenshot from the browser console when the error occurs.

**Comment by alinaepanaite** [comment]
![image](https://user-images.githubusercontent.com/115975936/198220394-681b79fa-d9e1-48ff-ba82-9176c906bc01.png)

https://user-images.githubusercontent.com/115975936/198220440-86dc6ee2-3880-4499-a0b1-c2ad7ee3621e.mov

attached logs and screen rec.
Are you duplicating the app in the same workspace? - **yes**
Thank you,
Alina

**Comment by kocharrahul7** [comment]
Hey @alinaepanaite Thanks for reporting this. We are working on this issue, and will try and get it fixed as soon as possible

**Comment by ginilpg** [comment]
@alinaepanaite We are extremely sorry for the difficulty you were experiencing. Unfortunately, we debugged the problem and were unable to reproduce it. We'd like to speak with you about this issue in order to learn more about it. It would be preferable if you could schedule a call with us. My calendly link is provided below. 
https://calendly.com/ginil-pg/60min

**Comment by ginilpg** [comment]
Looks like a temporary issue happened due to API failure. We are unable to reproduce it. @NilanshBansal Try to Check the logs and find out more details

**Comment by Nikhil-Nandagopal** [comment]
We're closing this since we haven't heard back from you. Do re-open it if you'd like us to help debug this issue
