### ISSUE TITLE
[Feature]: make step up/down arrows in input Number and Currency widgets optional

### ISSUE THREAD

**Issue by yan-hic** [appsmithorg/appsmith#18041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The arrows to in-/decrease a number or currency value is currently always displayed.
![image](https://user-images.githubusercontent.com/25224265/199349292-80facaa7-9ae8-45b0-8d3c-572d5d6d31fe.png)

User should have the option to disable that overlay.

This also prevents right-aligned icon to show up in Number input widget ie. in above, there should be a **%** according to styling settings.

### Why should this be worked on?

Rates are formatted as #.## %, not with % as prefixed. Also, rates are numbers so using Text is not an ideal workaround, especially for validation. 
Lastly, a number or currency is not always incremental - by default, the overlay should be hidden and enabled by the user for the few cases where increasing / decreasing by one unit is useful.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5kudo)

**Comment by dilippitchika** [comment]
Thanks for bringing this to our notice @yan-hic, we will take a look at it and make necessary changes.

**Comment by dilippitchika** [comment]
For percentage, it's better to add a new widget or a new mode in the input widget

**Comment by yan-hic** [comment]
No sure. The Number type in Input serves well and offers the % icon already. User may decide to show or not.

Ideally you make the stepping arrows optional while keeping the right-aligned icon (any) visible if selected.
Does not have to be either/or.

**Comment by SourabhKolekar** [comment]
I have put up the same widget for my search screen and userIds which I have search functionality for are usually 4-6 digits. In such scenarios, having up and down arrows are rarely useful and having plain clear text box of type number (as it automatically provides validations for Number data type) is more welcome.

**Comment by dilippitchika** [comment]
Objective
Allow users to control the visibility of step arrows in number and currency inputs

Changes to be made
1. Add a new property for "Show step arrows" as a switch input type with the tooltip "Show arrows to increase or decrease values" in input widget -> number data type and currency input
2. Add this property to "General" section in content tab below Placeholder field
3. Allow this property to be JS controlled
4. When turned off/set to false the arrows should be hidden in the widget
5. For existing widgets, the value for "Show step arrows" should be set to true so that there is no change in functionality for current widgets.
6. For new widgets being dragged, the value for "Show step arrows" should be set to false
