### ISSUE TITLE
[Task]: [Custom JS Lib] Enable git sync flow with custom JS lib.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#18228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Ref: https://github.com/appsmithorg/appsmith/pull/18219

**Comment by subrata71** [comment]
While communicating with the remote repository it succeeds for the first time only. In the subsequent communication, it fails to communicate with the remote repository. It fails with a message `"....Invalid Private Key....."`. 

### RCA
The issue is kind of sneaky. The private key was getting changed at some point. The private key is required to communicate with the remote repository and it's stored in DB being encrypted. There's an event listener which listens on saving documents into the DB event. It encrypts any field in the document if it's annotated with `@Encrypted` annotation.

The `Application.java` class contains this private key in a nested field. The application object was saved twice in two different areas of the codebase and that resulted in the double encryption of the private key.


### Solution
Converting the second save operation to an update solves the issue.
