### ISSUE TITLE
[Feature]: Custom Charts using thrid party libraries such as Apache Echarts

### ISSUE THREAD

**Issue by SDAravind** [appsmithorg/appsmith#18370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I come from a data background, meaning I love to use and tell stories about data using machine learning and BI. Teams building frontend takes ages but I see this gap can be closed with Appsmith if we can build BI/ML apps pretty quickly to showcase the demo. Hence requesting this feature out of the box supporting third-party libraries.

I see there is support for fusion charts out of the box. Would there be support for third-party libraries such as [Apache Echarts ](https://echarts.apache.org/examples/en/index.html) - OSS has tons of custom charts out of the box easily customizable. 
Also, It would be awesome if there are cross-filters applied from one chart to charts on the dashboard.

### Why should this be worked on?

Generalizing the use of third-party charting libraries would enable statistical charts with help of other charting libraries such as [Apache Echarts](https://echarts.apache.org/en/index.html), [Vega](https://vega.github.io/vega/), [D3JS](https://d3js.org/) and [Plotly](https://plotly.com/javascript/) would take Appsmith to next level in BI world. 

Tools such as MS Power BI and Tableau are just not enough, they are slow and don't have native support for custom charts.

**Comment by Nikhil-Nandagopal** [comment]
Thanks for the feature request @SDAravind !

**Comment by dilippitchika** [comment]
My thoughts on this before i forget, this is definitely needed to scale well but the challenge i see each new library has it's own set of rules which not everyone is comfortable with similar to fusioncharts. 

I wish we could be more modular and allow devs/admins to choose which all packages they need as their preferred charting library rather than adding all the libraries which might increase the build size of Appsmith considerably. For self-hosted users, it could be game-changing to integrate with new charting libraries. 

Probably what we need is a chart wrapper logic on the chart widget which works with custom JS libs for a quick win while longer term integration is to try and make these options native.

**Comment by dilippitchika** [comment]
CC @momcilo-appsmith

**Comment by dilippitchika** [comment]
Closing in favor of #4437
