### ISSUE TITLE
[Feature] Source Maps for sentry

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#1839]
## Summary

Add source maps to simplify reading sentry errors.

## Motivation

Source maps will help make sense of the trace that we see on sentry

## Additional Context

Steps: https://docs.sentry.io/platforms/javascript/sourcemaps/

**Comment by Nikhil-Nandagopal** [comment]
@ofpiyush this was working before. It broke when we moved away from netlify
@mohanarpit can you add some context here

**Comment by mohanarpit** [comment]
This has been resolved. The issue was:
1. The Github Action didn't have the secret key SENTY_AUTH_TOKEN to upload the source maps
2. The React environment being used to build the production build was set to DEVELOPMENT instead of PRODUCTION. Hence new source maps weren't getting uploaded to Sentry.

This is resolved and new issues on Sentry will contain the source map.
