### ISSUE TITLE
[Bug]: The edit button should be disabled when user doesn't have edit access for datasources

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The edit button should be disabled when user doesn't have edit access for datasources
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/204206599-7c68348c-ba37-449f-a7e1-172b66ff52b0.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/204206621-2c4454cb-f408-40d2-82ff-79a3f559c32e.png">

### Steps To Reproduce

1. Go to admin setting
2. click on roles tab
3. Create a new role
4. check on Create in application resource tab click on save
5. Now go to datasource & queries tab
6. Click on create,execute and view roles and save it
7. Now assign it to [user1@appsmith.com]
8. Now login as a user 1
9. Go to datasources section in context menu click on it
10. The edit button should be in the disabled state

### Version

localhost

**Comment by ankitakinger** [comment]
@RakshaKShetty this is because the user has `View` access. They should be able to `View` settings of this datasource in this case, which can be seen only if the edit button is clickable. They won't be able to save any changes on the edit page if they don't have `Edit` access. Could you confirm if it works this way on your side or not?

**Comment by berzerkeer** [comment]
@ankitakinger @RakshaKShetty I just checked, even when the user don't have `EDIT` permission, the server is still sending edit permission for that datasource. Because of that , the `SAVE` button inside edit datasource page is not getting disabled.
https://www.loom.com/share/071e14a19d634b4c9fe67bb49d14c630

cc: @nsarupr

**Comment by berzerkeer** [comment]
Can we close this ? @RakshaKShetty @ankitakinger

**Comment by ankitakinger** [comment]
It is marked fixed on the rbac_coverage spreadsheet. I think we can close this. @RakshaKShetty could you confirm?
