### ISSUE TITLE
[Feature]: App loading speed optimization

### ISSUE THREAD

**Issue by kt3721** [appsmithorg/appsmith#18602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

App loading speed optimization

Create a new page, including adding, deleting, searching, and modifying functions. The components and quantities used are shown in the following table:

![image](https://user-images.githubusercontent.com/16112889/204997182-898fa27b-bb8e-46c8-b6d7-1b44b3fe1d13.png)

Record the time from refreshing the page to the completion of rendering of the first component in the page, which is about 3.5 seconds.

If the number of pages in the application increases, the corresponding load time will be longer.

Is it possible to optimize the performance problem when the application loads?

This is the data exported by a test application, it can be tested after decompression and imported.
[demo.zip](https://github.com/appsmithorg/appsmith/files/10130694/demo.zip)

### Why should this be worked on?

App takes too long to load, poor user experience

**Comment by kt3721** [comment]
This is the data exported by a test application, it can be tested after decompression and imported

[demo.zip](https://github.com/appsmithorg/appsmith/files/10130679/demo.zip)

**Comment by jacques33** [comment]
We‘ve encountered this problem too, especially when the application has large number of pages.

**Comment by linleisky** [comment]
We also encountered this problem, when there are many components, the page rendering is slower！

**Comment by SatishGandham** [comment]
@kt3721 , @jacques33 When you say large number pages, are these Appsmith pages or widgets split into multiple virtual pages using tabs widget?

@linleisky , How many widgets are you having on the page?

**Comment by xianyuruhua** [comment]
NEW BEE

**Comment by kt3721** [comment]
> @kt3721 , @jacques33 When you say large number pages, are these Appsmith pages or widgets split into multiple virtual pages using tabs widget?
> 
> @linleisky , How many widgets are you having on the page?

Yes, tabs are used

**Comment by xianyuruhua** [comment]
您好，QQ960298035已收到您的邮件，谢谢！

**Comment by Z-Champion** [comment]
This is the standard version that we created in the appsmith：
url: https://app.appsmith.com/app/example-1/page1-63889e63a39c830902347aea
source code: [example.zip](https://github.com/appsmithorg/appsmith/files/10132491/example.zip)
Here are some details about this application.
![image](https://user-images.githubusercontent.com/33289026/205057760-e6840f2e-d93e-434d-80c1-efdf3bcc964a.png)

**Comment by SatishGandham** [comment]
@kt3721,
I appreciate you getting back with more info. 
As our team has been continuously working to improve performance, you'll see gradual performance gains after our latest and a couple of upcoming releases planned this month.

Regarding the performance of your app, with tabs, if you have 10 pages with 60+ widgets each, thats about 600 widgets that are being instantiated on page. Even though tabs give an impression of different pages, it's one widget  containing 600 widgets on a single page. This is one of the primary reasons for the performance hit. I recommend splitting your app into separate pages instead of tabs, this will lead to direct performance improvement without needing any fix from our side.

Furthermore, slow page loads are a combination of multiple issues. This means there could be unintended consequences not just related to performance and overall platform. My team has yet to set a target deadline, although the work continues behind the scenes. So, I'd like to ask for your patience and support until we get to the bottom of this.

**Comment by SatishGandham** [comment]
@Z-Champion , Will review your app and get back to you. Can you please share your application with support@appsmith.com

**Comment by SatishGandham** [comment]
@jacques33 , because of the amount of data table widget renders, it will be slower compared to other widgets on any platform. Not just Appsmith.

We worked around these limitations to make it performant enough that you won't notice a lag when using it.

Can you please share some details on how you are using the table widgets

- Amount of data your loading, rows and columns
- Does it have server side pagination enabled
- How many table widgets are you using
- What part feel slow, is it the page load, interacting with the table or overall interactions in the application.
- Is it in edit mode or view mode.

**Comment by kt3721** [comment]
> @kt3721, I appreciate you getting back with more info. As our team has been continuously working to improve performance, you'll see gradual performance gains after our latest and a couple of upcoming releases planned this month.
> 
> Regarding the performance of your app, with tabs, if you have 10 pages with 60+ widgets each, thats about 600 widgets that are being instantiated on page. Even though tabs give an impression of different pages, it's one widget containing 600 widgets on a single page. This is one of the primary reasons for the performance hit. I recommend splitting your app into separate pages instead of tabs, this will lead to direct performance improvement without needing any fix from our side.
> 
> Furthermore, slow page loads are a combination of multiple issues. This means there could be unintended consequences not just related to performance and overall platform. My team has yet to set a target deadline, although the work continues behind the scenes. So, I'd like to ask for your patience and support until we get to the bottom of this.

thank you for your reply.

I misunderstood, I thought the tabs you mentioned meant the tab menu at the top of the page. As shown below:
![image](https://user-images.githubusercontent.com/16112889/205306704-368ace76-b75c-431e-a73f-907fbb99e75e.png)

Actually I'm not using the tabs widget, I'm using a separate page.

My main problem is that the application takes a long time to load, and I look forward to a stronger performance in the new version

**Comment by somangshu** [comment]
@SatishGandham can this issue be closed now?

**Comment by xianyuruhua** [comment]
您好，QQ960298035已收到您的邮件，谢谢！
