### ISSUE TITLE
[Task]: How many times a PR was re-run because the tests were flaky

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#18612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

task coming from sprint review: https://www.notion.so/appsmith/Sprint-reviews-727531750e73490a92e1f7c091bbdf11?p=0b50ea57e3bb4262a2f2348972e1e462&pm=s

**Comment by sneha122** [comment]
As per discussion with @hetunandu We can track the flaky tests that were rerun on cypress dashboard but they do not show PRs. But we can go to github actions, filter by the branch name and check how many times `Appsmith client build workflow` was triggered. For eg: https://github.com/appsmithorg/appsmith/actions?query=branch%3Afix%2Fgsheet-discard-popup-text-updates But this still does not give us the information about whether those runs were triggered due to flakiness or some other reason. Also for each run we cannot see how many times it was rerun. We can take this discussion up with other pods and see if they have also faced similar problems and if they have any better approach for this problem. Hence closing this task
