### ISSUE TITLE
[Feature]: Dynamic number of tabs

### ISSUE THREAD

**Issue by satya-ashok** [appsmithorg/appsmith#18634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I'm telling you about one use case (My use case). In a API response for KYC documents verification. each document can have multiple attempts. If there's a way to see each attempt in a sub tab. It would be great. Every customer will have various number of attempts.  With the current Appsmith Version, we can't set any dynamic tabs. 

### Why should this be worked on?

It would bring a wide range of possibilities.

**Comment by dilippitchika** [comment]
@satya-ashok in this scenario, can you explain what will be the content in each subtab will be, since tab widget will only work dynamically when there is content inside it. 

This ideally looks achievable from a list widget and a container. In the list widget you can have all the names of your tabs and in the container based on the item selected in the list you can change content. Also this is better suited if you have a navigation widget.
