### ISSUE TITLE
[Bug]: In page setting, there is an Inconsistency in the Home page toggle color

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#18696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In page setting, there is an Inconsistency in the Home page toggle color
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/45958978/205640990-78151207-e41c-4551-b8c1-449d207e84b0.png">

### Steps To Reproduce

1. go to editor
2. on the right pane click on app setting
3. check the home page toggle
4. It looks like its in disabled state

### Version

release

**Comment by eco-monk** [comment]
@RakshaKShetty, this is intentional and by design.
If we allow the user to un-set a home page, then some other page needs to become a home page automatically.
The system cannot assume a home page, the user has to actively make this decision.

So, We've added tooltips explaining why this is disabled and what the user can do about it.
<img width="340" alt="image" src="https://user-images.githubusercontent.com/66776129/205829085-5742d05f-0087-4be8-ba25-d43a08a10914.png">

cc: @RoopKrrish9696 @kocharrahul7
