### ISSUE TITLE
[Feature]: Allow override of mongo & redis helm init image

### ISSUE THREAD

**Issue by ps-xaf** [appsmithorg/appsmith#18833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently image values for redis and mongo init container are hard coded in the helm chart files.

https://github.com/appsmithorg/appsmith/blob/aafaa8abfaac11534cadaf5b1e532fef20efbc56/deploy/helm/templates/statefulset.yaml#L49
https://github.com/appsmithorg/appsmith/blob/aafaa8abfaac11534cadaf5b1e532fef20efbc56/deploy/helm/templates/statefulset.yaml#L53

Besides best practice not pull images directly from a public place, many companies have internal registries or restrict access where images can be pulled from. The feature would allow to override the soure and provide more flexibility in using this helm chart as an upstream helm chart.

### Why should this be worked on?

Provide an out of the box helm chart with flexibility for image sources

**Comment by Nikhil-Nandagopal** [comment]
@ps-xaf thanks for raising this and a supporting PR.
@sharat87 could you please review if this makes sense?

**Comment by pratapaprasanna** [comment]
@ps-xaf thanks for pointing this out and raising a PR for the same. I understand the problem you are addressing.

The context for hard-coded the images is as below.

If the user who deploys appsmith helm chart gives a different image other than
alpine for redis 
mongodb:4.4.11-debian-10-r12 for mongo
then the command [key](https://github.com/appsmithorg/appsmith/pull/18834/files#diff-58ba2866b40688c464b75a1e2b79b702ef338a9eacc84170aa9dcde3a4c331e6R50) 
also has to change accordingly. So, we went with defining the image values hard-coded.

**Comment by pratapaprasanna** [comment]
@ps-xaf  the issue looks relevant. PR is currently a draft we shall review once it is ready

**Comment by ps-xaf** [comment]
@pratapaprasanna thx, i've created a simple PR and removed the draft status.

**Comment by sharat87** [comment]
Hey @ps-xaf, sorry, missed this earlier. Thanks for raising this issue and including a rationale.

The reason they are hard-coded, is so that we can pin the version of MongoDB to a version that Appsmith is known to work well with. In the future, when we say, upgrade to start using MongoDB v5, we'll update the Helm Chart as well to pin to version 5.

If you are going to be setting the image yourself, you'll need to make sure you are running the recommended version of MongoDB.

While I'm not opposed to making them configurable, I just want to point out that there will be some maintenance cost for you due to this.
