### ISSUE TITLE
[Enhancement]: Styling options for Table column headers

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#18916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Today, only the alignment options affect the table headers. It would be nice to be able to  apply other available styles to the table column headers. Eg: Text Size, Emphasis, Cell Background, Text Color, etc.

### Why should this be worked on?

Column headers should support styling. https://discord.com/channels/725602949748752515/1051899061197873204/1051899061197873204

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_69yx8)

**Comment by somangshu** [comment]
@sathishvenkataraman right now we are working on a major re-haul of widget to adhear better to theming so that they look good out of the box. Our approach is to make it good look out of the box, rather than give that control to the users. 

Does this sound good to you? Do you have any use cases where you would rather control this your self. 
cc @ichik @jsartisan @KelvinOm

**Comment by Ronaldvm79** [comment]
Styling out of the box would be better, at the end I prefer maximum control. Main issue now is the sizing, I having quite a lot of columns in a table, therefor I styled the rows to smalle size, but the titles does not size with the content, so it's getting unclear for my users what column they are looking at.

**Comment by amelia-c0n** [comment]
[Another user](https://discord.com/channels/725602949748752515/1051899061197873204/1378014095390801963) requested this feature.
