### ISSUE TITLE
[Bug]: Not able to execute or edit JSObject when user has edit and execute permissions for it.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#18928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When user has edit permission at workspace level as well as execute permission for JSObject, on trying to edit the JSObject  throws resource not found error,  Run button is disabled too.
<img width="1440" alt="Screenshot 2022-12-13 at 10 05 40 PM" src="https://user-images.githubusercontent.com/80334441/207390991-cacb7342-7a00-4fee-898c-4db6e26c5584.png">
<img width="1434" alt="Screenshot 2022-12-13 at 10 00 57 PM" src="https://user-images.githubusercontent.com/80334441/207389898-baf6d262-f05d-405c-95d3-541e5f53deaf.png">
<img width="1434" alt="Screenshot 2022-12-13 at 10 01 12 PM" src="https://user-images.githubusercontent.com/80334441/207389966-b2a8e702-dcd0-413e-9945-fbf0eb262842.png">

### Steps To Reproduce

1. Login as admin, create new Role with edit permission at workspace level  from application resources tab and execute permission for same workspace from datasources & queries tab.
2. Assign this role to test user
3. Login as test user and open the app
4. Try to edit jsObject and observe.

### Version

http://65.0.99.89/

**Comment by Parthvi12** [comment]
Attaching screenshot :
<img width="1434" alt="Screenshot 2022-12-14 at 5 32 21 PM" src="https://user-images.githubusercontent.com/80334441/207591856-41beba8f-5c80-4cdc-8888-86dc5d3c0492.png">

**Comment by berzerkeer** [comment]
Tried again, not reproducible for me, looking at the network log from @Parthvi12 looks to be an BE issue. This was the endpoint PUT `http://localhost/api/v1/collections/actions/6399bbd6f46f8b2a84a4be14` 
![Screenshot 2022-12-14 at 7 13 11 PM](https://user-images.githubusercontent.com/74818788/207611238-e9cb9e80-6809-4d37-b438-c7f76c370c13.png)

Note: Page not found  happens when the page doesn't have edit permission, though in here page had edit permission. This issue goes away when we give all the permission for the said page. 
@trishaanand  @nsarupr
