### ISSUE TITLE
[Task]: Performance audit - Table widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#19182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

We should make a 50*25 table render in under 200ms.
We need to audit the table for finding performance problems.

**Comment by SatishGandham** [comment]
We found the table to be 4-6 times slower when compared to showing the same data in a standalone react table.
While some overhead is expected because of the features we add on top of the react table, 4-6 times slower means there is scope for improvement.

For example, spreading the properties on a table cell, use of styled components for rows,cells,tooltip seem to contribute to the overhead, and are easy fixes
