### ISSUE TITLE
[Bug]: RBAC UI issues

### ISSUE THREAD

**Issue by shadabbuchh** [appsmithorg/appsmith#19263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. The search component has a shadow.
<img width="439" alt="Screenshot 2022-12-28 at 11 26 14 AM" src="https://user-images.githubusercontent.com/39921438/209764963-8c874db7-4c9a-4553-a794-e736bd39e5d3.png">

2. Irrelevant tooltip observed for the `Groups` column in `Users` screen. Also this tooltip does not follow the design system
![image](https://user-images.githubusercontent.com/39921438/209765247-5fd51049-960b-46cc-b973-1e928d952b44.png)

3. When we rename a new group and press Enter, the page refreshes but the name is not saved. It only save after we press Enter the second time.
https://www.loom.com/share/cbda20fcd75849eb841f32cba8eab70a

4. Dropdown for adding Users does not behave like it does everywhere else in the platform.
https://www.loom.com/share/39591cfd5bb043d798f36543a596920e

5. On hover cursor turns into a CTA even when the icon is not clickable.
https://www.loom.com/share/48d77545c90e4e338a654b7bf58951eb

### Steps To Reproduce

1. Go to the Access Control page

### Version

Cloud

**Comment by ankitakinger** [comment]
@shadabbuchh  For point 4, the dropdown showing `3 selected` instead of tag names was part of the design. Plus it won't make sense for a user to scroll and read the content, instead, it's better we tell them how many options are selected and they can open the dropdown and check which ones are selected.

Will look into other things pointed out by your here.

**Comment by ankitakinger** [comment]
Point 2 needs to be handled in `design-system` repo. Will do the needful.
<img width="558" alt="image" src="https://user-images.githubusercontent.com/28362912/209795740-87bc742c-750f-4c87-83da-333600babdd6.png">

**Comment by ankitakinger** [comment]
@shadabbuchh For point 4, the positioning works fine on GSheets because the container is the full height of that page. While this doesn't work on the invite modal which cannot be of full height. This will require some help from the design-system team and this positioning of the dropdown on the invite modal is a known issue to the design-system team.
cc: @albinAppsmith

**Comment by shadabbuchh** [comment]
Verified the above issues in release. All seem to be working fine.
Will raise a separate issue for #4.

**Comment by RakshaKShetty** [comment]
Closing this issue as only 1 issue is pending from the list this will be filed seperatly
