### ISSUE TITLE
Task: Retain the PrimaryKey dropdown and Selection in PropertyPane

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#19299]
The primary key gets deselected when the last page is reached but when we do the JS toggle, the reference seems to be there.

Retain the PrimaryKey dropdown and Selection when there's no data
https://www.loom.com/share/8abbe114318a4f649b92d8c55785d7a2

**Comment by ashit-rath** [comment]
The issue can be resolved only if we store the `listData` in some other property like `cachedListData` after the `listData` is updated.
Right now in order to do this, we would have to call `updateWidgetProperty` and update whenever the `listData` changes. This will cause 2 problems
1. Triggers another evaluation which is quite un-necessary 
2. It will take the user twice to undo the changes they made on list data as internally it now becomes a 2 step operation.

The ideal solution would be to develop an enhancement that the widgets can use to cache data with a property is updating or a new API which updates the widget property without triggering an evaluation or some other solution.

Right now this feature does not seem to out weigh the importance of the above mentioned point so I recommend to deprioritise this issue for List v2.0 and to be considered in List v2.1

Please advise @dilippitchika @somangshu
cc: @kamakshibhat-appsmith @chandannkumar @Tooluloope

**Comment by somangshu** [comment]
Is this problem related to the discussion where we tried to figure how can the primary key be set without any implication from the list data? How is the primary key set right now and why is it not available only when we are on the last page?

**Comment by Tooluloope** [comment]
@somangshu

> How is the primary key set right now 

The `primarykey` options are obtained from the unique keys within the data, similar to the columns within the table widget. So the user could either set it from the dropdown or make a complex `primarykey` using the JS toggle.

> why is it not available only when we are on the last page

It happens when the user navigates to a page without data in serverside pagination.
Since the Options are gotten from the keys within the data, once we arrive at a page without data, the options would also be empty. However, if the user returns to the previous page, the last chosen` primarykey` remains selected. If the `primarykey` is in JS, this is preserved even with no data.

Here is a video explaining the issue. https://www.loom.com/share/8abbe114318a4f649b92d8c55785d7a2

**Comment by dilippitchika** [comment]
This is a symptom of not having total record count in list #14551, when data is not available we can't make a selection here. Once we add total record count, we can nudge users who face this issue to configure it. Let's not work on this for now

**Comment by ashit-rath** [comment]
Moving this issue to v2.1 epic.

**Comment by Tooluloope** [comment]
Fixed in https://github.com/appsmithorg/appsmith/pull/20265
