### ISSUE TITLE
[Task]: Deduplicate components & Grayscale/theming support in template details page

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19388]

**Comment by laveena-en** [comment]
Issues with template details page:

1. Space required after `Note:`
<img width="883" alt="image" src="https://user-images.githubusercontent.com/109572422/233541723-b682f448-5785-47d3-b50f-d75ac5b79d7a.png">

2. Modal isn’t getting dismissed as expected https://www.loom.com/share/d7030d113b694edfa33e7eca9a4d343b

3. Change `View Templates` to sentence casing
![image](https://user-images.githubusercontent.com/109572422/233541813-defa95d5-885d-4d20-adad-508ce629e702.png)

4. Button component is used instead of link for `Go back` and `View Templates`
