### ISSUE TITLE
[Task]: Deduplicate component & Grayscale/theming support in application page

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#19386]

**Comment by laveena-en** [comment]
Issues with workspace settings:

1. ADS v2 component hasn’t been used here
![image](https://user-images.githubusercontent.com/109572422/233545388-17fc3a3c-4691-4a30-a43b-e3deb1692c0d.png)

2. Unintended white block is seen behind the toast
![image](https://user-images.githubusercontent.com/109572422/233545512-8bd3beae-e053-4f57-87c6-318490368a43.png)

3. `Display name` to be changed to `Worksapace name`

4. Layout of users list is broken
![image](https://user-images.githubusercontent.com/109572422/233545706-274aff54-6444-4cca-90db-ac3403dc02e5.png)

5. Position of remove and cancel are interchanged. Also, can we use a primary version of button for `Remove`
![image](https://user-images.githubusercontent.com/109572422/233545817-a4380354-858a-401b-a8d7-2ebf625fb9a4.png)

6. We seem to have changed the layout of the settings page. Is this intentional?
![image](https://user-images.githubusercontent.com/109572422/233546098-9c471209-e7d1-4c0c-9d63-31075e590cd6.png)
![image](https://user-images.githubusercontent.com/109572422/233546106-422570f2-77eb-4b50-aa18-1086b5464451.png)
