### ISSUE TITLE
[Bug] REST datasources don't show up in the entity explorer if they don't have any actions using them

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#1942]
## Description

REST datasources usually show up in the entity explorer under the APIs section. However, if no API action is using a particular REST datasource, that datasource does NOT show up in this list. This is confusing because it leads the user to believe that there is no such datasource. For example, I have stored a datasource named `httpbin`, but it doesn't show in the entity explorer since there's no actions associated with this datasource. So, coming back to this a couple days later, I think there is *no* such datasource and I attempt to create it again, but it fails because there's already a datasource named `httpbin`.

## Steps to reproduce the behaviour

1. In a brand new organization, create a new API action pointing to `http://httpbin.org/get`.
1. Click on the triple-dot menu and select "Store as datasource".
1. This will create a datasource, name it `httpbin` and click on the `Save` button.
1. Notice that the `httpbin` datasource now shows up in the entity explorer.
1. No go back to the action created in step 1 and delete it.
1. Notice that the `httpbin` datasource has disappeared from the entity explorer.

At this stage, there is no way to edit the default headers or other configuration on the `httpbin` datasource.

1. Create a new API action and click on the URL input box. This should produce a dropdown with `http://httpbin.org` in it.
1. Select the `http://httpbin.org` option.
1. Notice that the `httpbin` datasource has reappeared in the entity explorer, as noticed in step 4. This datasource can be edited again, but only until this action exists.

## Expectation

I should be able to edit the REST datasource's configuration, irrespective of whether there's any actions using it or not.

### Important Details
 - Version: Cloud
 - OS: macOS
 - Browser: Firefox

**Comment by aakashDesign** [comment]
Hey folks,

Sharing two ideas with mocks towards solving this problem.

### Idea 1:

Redesign "Create new API" page to mention REST datasources alongside Blank API and curl import.
<img width="1474" alt="Screenshot 2020-12-14 at 1 16 21 PM" src="https://user-images.githubusercontent.com/65771350/102053936-911d1a80-3e0e-11eb-98ff-1568567c41aa.png">

This flow is consistent with our Create New Query flow, where users can hit "+" button entity explorer to see a list of all their datasources.

<img width="1484" alt="Screenshot 2020-12-14 at 1 18 45 PM" src="https://user-images.githubusercontent.com/65771350/102054126-e6f1c280-3e0e-11eb-805a-b1453ecb2a17.png">
<img width="1415" alt="Screenshot 2020-12-14 at 1 19 18 PM" src="https://user-images.githubusercontent.com/65771350/102054183-fe30b000-3e0e-11eb-80ff-f8344270f8d4.png">

Pros with this idea -
- Consistent with the current implementation and solves problems in the short term.

Cons -
- Editing a datasource by tapping on the "+" button isn't intuitive, because it's consistent with Create query flow, this solution inherits its flaws.
- Does not clarify the relationship between datasources and their APIs
- Does not create much long term value for users in terms of ease of use. 
### Idea 2:

Create a home where users can view all their APIs and REST datasources outside of the entity explorer.
Loom explainer video: https://www.loom.com/share/9a69787ab85d4791aefd2de22fd94c52

<img width="1478" alt="Screenshot 2020-12-14 at 1 26 02 PM" src="https://user-images.githubusercontent.com/65771350/102054795-ead21480-3e0f-11eb-8a19-1a1e9b72690a.png">
<img width="1405" alt="Screenshot 2020-12-14 at 1 26 28 PM" src="https://user-images.githubusercontent.com/65771350/102054834-fa515d80-3e0f-11eb-8e8a-f483aee15ab2.png">
<img width="1419" alt="Screenshot 2020-12-14 at 1 26 58 PM" src="https://user-images.githubusercontent.com/65771350/102054880-0ccb9700-3e10-11eb-9f38-3258aa83f8ce.png">


Pros-
- Explains API and datasource relationship while simplifying the entity explorer.
- One step closer to app-level API and queries instead of page-level.

Cons-
- Entity explorer has too many actions now, speedy navigation can be harder for advanced users.

**Comment by aakashDesign** [comment]
Hey there!
Sharing a new Prototype for API creation and import flow
Loom video: https://www.loom.com/share/122aa58c93184c998feb2b1df85c5e40
Figma link: https://www.figma.com/proto/hgajJkKSuY4kVxWemlAyYu/Appsmith-wireframes?node-id=60%3[…]A4375&viewport=789%2C883%2C0.2484671026468277&scaling=min-zoom

To simplify API creation and import we've come up with a new flow-

- When a user hits "+" on the entity explorer, we show them a blank form, and create a temporary "New Request 1" file for them.
the new request file is saved only when the user adds some data to the form, or else it goes away.
- There is an import sidebar from where users can import CURL, choose a datasource. In the future, we can use this space for postman import as well

Latest screens -

<img width="1616" alt="Screenshot 2021-01-04 at 10 43 51 AM" src="https://user-images.githubusercontent.com/65771350/103503281-c0590180-4e79-11eb-9d95-c4c2a4c09588.png">
<img width="1615" alt="Screenshot 2021-01-04 at 10 44 09 AM" src="https://user-images.githubusercontent.com/65771350/103503289-c8b13c80-4e79-11eb-8222-0c769de6fd7a.png">
<img width="1505" alt="Screenshot 2021-01-04 at 10 44 45 AM" src="https://user-images.githubusercontent.com/65771350/103503308-de266680-4e79-11eb-9b23-922c54c928ea.png">


This flow solves most of our problems with regard to datasources and API. It should have a high impact on users creating actions and thus improve onboarding and retention.

**Comment by Nikhil-Nandagopal** [comment]
@aakashDesign @trishaanand we need an explicit save CTA for datasources because when a datasource changes, it reflects even on existing applications today. So as a user is typing, he will be breaking all deployed applications

**Comment by aakashDesign** [comment]
Added Save button to datasource.
<img width="1514" alt="Screenshot 2021-01-11 at 11 15 51 AM" src="https://user-images.githubusercontent.com/65771350/104150016-78e4ef00-53fe-11eb-82ea-3db59253dd9d.png">

**Comment by arunvjn** [comment]
Will be closed along with [https://app.zenhub.com/workspaces/appsmith-actions-pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/4567](url)

**Comment by Nikhil-Nandagopal** [comment]
Closing this as rest datasources are now shown in the API as well as in the active datasources page
