### ISSUE TITLE
[Bug]:  Unable to add an editable custom column

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#19447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

<img width="847" alt="Screenshot 2023-01-03 at 12 48 11 PM" src="https://user-images.githubusercontent.com/13262095/210314105-84cf5c70-f9a9-4f9a-b0c4-33116709494e.png">
The option to make the column editable is disabled for me when I add a new column to a table.

Raised by a community user - https://community.appsmith.com/t/not-able-to-make-custom-column-editable/1817

### Steps To Reproduce

1. Drag a table
2. Add a new column by clicking on `add a new column`.
3. Try to make that column editable

### Version

v1.8.16

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6jfws)

**Comment by dilippitchika** [comment]
Duplicate - https://github.com/appsmithorg/appsmith/issues/14893

@pranavkanade the idea behind custom columns is they are derived from other columns, if the column is allowed to be editable then we were unsure of how the save and retrieve logic will work in such cases.

The workaround is to simply make sure you are passing the custom column directly in table data rather than computing in the table.
