### ISSUE TITLE
[Bug]-[24]:SQL Syntaxis on simple calls to Store Procedures MySQL.

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#19812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When executing a call to a procedure with the where false statement, the execution of this query fails
I attach conversations with two users who have this problem
1. https://app.frontapp.com/open/cnv_vl8t0p8?key=7dXh_QCblwG274PPOPWKVta_NxhzCmCa
2. https://app.frontapp.com/open/cnv_tjj4wzw?key=rN0mZKGKhwTf0wa5nRUzUy-9um-Nz3Mz

bug capture

![image](https://user-images.githubusercontent.com/114161539/212757970-6ebc0b9e-17e8-442f-a8e4-596d30fbe077.png)

### Steps To Reproduce

1. Connect to a MySQL database you can use this resource to build one with docker: [service](https://github.com/felix-appsmith/appsmith-quick-datasources#-mysql)
2. Create a table in MySQL you can use this query
   ```sql
   
   CREATE TABLE employees (
     id INT(11) NOT NULL AUTO_INCREMENT,
     name VARCHAR(255) NOT NULL,
     salary DECIMAL(10,2) NOT NULL,
     PRIMARY KEY (id)
    );

   ```
  3. Now create a procedure for this table, you can use this query.
  ```sql
   
      CREATE PROCEDURE test21i (IN parametro1 VARCHAR(255))
      BEGIN
           SELECT * FROM employees WHERE nombre = parametro1;
      END;
   
  ```
  
  4. Executes a procedure call query 
  ```sql
  call GetEmployeesBySalary (5000) ;
select "dummy" as dummy where false;
  ```
  
  When executing step 4 we will get the error as workaround if we remove the `where false` the query will work correctly.
 

### Version

Appsmith v1.9

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6u0cs)

**Comment by rohan-arthur** [comment]
MySQL usage in 6m: 2131
Out of these, [only 4 users](https://mixpanel.com/project/2032485/view/178891/app/boards#id=4172284&edited-bookmark=LVdGwhPwp8vR) used `where false`


## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 4 |
| Effort (months)  | 0.5 |

**Comment by pchambless** [comment]
![image](https://user-images.githubusercontent.com/44928133/212952522-cdcde1df-e416-46e2-b007-5a8cdbf65437.png)
My observations

**Comment by sumitsum** [comment]
Re-applying the `critical` tag since this is something that used to work before and has broken now (based on the farmework mentioned here: https://www.notion.so/appsmith/Issue-Labeling-and-Prioritization-0072175fd0f54983bf5b499895c7315e)

**Comment by pchambless** [comment]
I've gone through process of figuring out how to fix all the queries by:

1. Identifying queries that need converting
2. Turning Prepared Statement off
3. inserting tic marks around text parameters on the Appsmith side.
4. Trial and error and calls from Client on queries not converted correctly.

Essentially I've moved on from whatever happened January 12 out of necessity.

**Comment by PiyushPushkar02** [comment]
## Bug Analysis ##
As per our analysis, the issue is in the select statement used to fetch the stored procedure result set. For the above, we tested the same with 5.x and 8.x versions of MYSQL. The issue is limited to 5.x version. The reason for the same is described below.
``` 
MySQL 8.x does not throw a syntax error for the statement "SELECT 'dummy' as 
dummy where false" because it has more relaxed parsing rules and can handle more 
flexible syntax. In MySQL 8.x, the WHERE clause can appear before the FROM clause in a 
SELECT statement, and the query will still be valid.

In MySQL 8.x, the original statement "SELECT 'dummy' as dummy where false" is valid 
and will return no rows, just as in previous versions of MySQL where the statement had 
to be written with the FROM clause and a dummy table, such as FROM dual. The more 
relaxed parsing rules in MySQL 8.x allow for more flexible and concise query writing, 
which can simplify some SQL statements and make them easier to read.
```
## Workaround ##
Changing the select query for 5.x version would solve the above issue.
```
SELECT * FROM (SELECT 1 as dummy WHERE false) subquery;
```
## Testing ##

MYSQL Version: 5.x (With new select query provided as a workaround)
![Screenshot 2023-01-31 at 3.13.16 PM.png](https://images.zenhubusercontent.com/637b06255553bbc156f20882/3ec8ad50-3ee7-401f-80a7-f8fce21ff6df)

MYSQL Version: 8.x (With new select query provided as a workaround)![Screenshot 2023-01-31 at 3.15.02 PM.png](https://images.zenhubusercontent.com/637b06255553bbc156f20882/c65c7ec6-8b13-4956-9bec-874a6f9294a9)![Screenshot 2023-01-31 at 3.16.07 PM.png](https://images.zenhubusercontent.com/637b06255553bbc156f20882/ec6df320-de35-4761-b1db-ec1fec445310)

MYSQL Version: 5.x (With old select query provided by user)
