### ISSUE TITLE
[Bug]: Git Connect CTA is not visible on the first fold

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#19869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

**Steps to reproduce**
1) Open any application on edit mode & click on Connect Git at bottom left
2) Enter repository url 
3) No CTA's shown to the user at this point. User need to scroll down to see the CTA. Ideally screen should auto scroll and shown the CTA

![Untitled 2](https://user-images.githubusercontent.com/8299030/220635708-46f45902-461f-4751-89b0-03b33a1a5ca3.jpg)

![image](https://user-images.githubusercontent.com/8299030/213145316-ef1da847-e9bb-4011-8fe7-b8541b8a1459.png)

**Comment by sharat87** [comment]
> Ideally screen should auto scroll and shown the CTA

I don't think we should auto-scroll. A better option would be one of

1. Have the Connect button show irrespective of the scroll position. Like how the "Git Connection" title is visible even if I scroll, this button should also be visible always.
2. Just _don't_ hide the scrollbar. Make it drop-dead apparent that there's more content, and the scrollbar's size indicates how _much_ more content there is.

I'd personally pick the second one, cause in my opinion, hiding scrollbars because they look ugly is like denying crutches because they look ugly. 😬

**Comment by infinitetrooper** [comment]
https://theappsmith.slack.com/archives/CNQ9Q91C0/p1674031382230829

**Comment by ginilpg** [comment]
Team, We aligned on the following changes with @infinitetrooper @vinay-appsmith @Debsourabh @vasanth-appsmith 
- Use dynamic height for the modal content instead of fixed height . This will avoid scroll bars 
- Show the SSH key and git credentials with an animation if the SSH URL format is valid

**Comment by akash-codemonk** [comment]
We will be solving this by updating spacing of the existing elements for now. https://theappsmith.slack.com/archives/C04HERDNZPA/p1678950171861909?thread_ts=1677172966.286229&cid=C04HERDNZPA
