### ISSUE TITLE
[Bug]-[3250]:GraphQL | Unable to re-write the Authenticated GraphQL API fields

### ISSUE THREAD

**Issue by Aishwarya-U-R** [appsmithorg/appsmith#19893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/91450662/213379350-69c69581-a295-4ed6-b12c-779cf1109232.mov

### Steps To Reproduce

1. Create a new Authenticated GraphQL datasource
2. Give a url value
3. Try to edit the field value
4. **Observe: The control is taken to end of line & user is not able to edit the field with ease (All fields in the datasource page has same behaviour - Headers, Query Parameters)**
5. **Expected: User should be able to edit fields with ease**

### Version

Cloud / v1.9.3.2

**Comment by rohan-arthur** [comment]
https://user-images.githubusercontent.com/94514895/213404633-e9029006-0411-4d41-a030-a936239d004d.mov

also happens for REST API

**Comment by rohan-arthur** [comment]
6m usage of REST+GraphQL: ~6500
Assume 25% of users attempt to edit the URL string (excluding cases of appending to the end of the string) 1625

reducing severity to high because most likely use-case is copy-paste, and if that doesn't work, there are easy workarounds. This issue is super annoying at best. 

## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1625 |
| Effort (months)  | 0.25 |
