### ISSUE TITLE
[Bug] NGINX throwing 405 status code error on Kubernetes deployment

### ISSUE THREAD

**Issue by harshit98** [appsmithorg/appsmith#1990]
## Description

NGINX throwing 405 status code error on Kubernetes deployment. 

### Steps to reproduce the behavior:

1. Run the K8s script to make sure every service is up and running in the K8s namespace.
2. Redirect to the application ingress or pod IP.
3. /user/login page comes up. Go to the "sign up" section since the application will be used for the first time.
4. On the sign-up form submit, an error page will come and Nginx will throw 405 status code error.

### Important Details
 - Version: Hosted on Kubernetes.
 - OS: MacOS
 - Browser: N/A

**Comment by usr9** [comment]
+ @mohanarpit 

-added proxy pass to get past nginx 405 error
-added upstream resolver, but no luck 
-UI via  kube port-fwd `appsmith-editor` service to `localhost:7080` 

Message on UI
`Appsmith server is taking too long to respond. Please try again after some time`

Appsmith-editor pod ( nginx ) log 
```
"12/Dec/2020:09:11:32 +0000" client=127.0.0.1 method=GET request="GET /api/v1/applications/new HTTP/1.1" request_length=1090 status=502 bytes_sent=716 body_bytes_sent=559 referer=http://localhost:7080/applications http_x_forwarded_for=- user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" upstream_addr=- upstream_status=- request_time=0.000 upstream_response_time=- upstream_connect_time=- upstream_header_time=-2020/12/12 09:11:32 [error] 23#23: *189 no resolver defined to resolve appsmith-backend-service, client: 127.0.0.1, server: , request: "GET /api/v1/applications/new HTTP/1.1", host: "localhost:7080", referrer: "http://localhost:7080/applications"
```

### Setup
0. Kube cluster  v1.18 + FQDN/TLS Cert Available. 
1. install.k8s.sh produced files + additional changes
- nginx-configmap.yaml  
https://github.com/appsmithorg/appsmith/blob/6e58258f67f81c69e3f9926e5983092cb6335c30/deploy/k8s/scripts/nginx-configmap.yaml#L7-L9
https://github.com/appsmithorg/appsmith/blob/6e58258f67f81c69e3f9926e5983092cb6335c30/deploy/k8s/scripts/nginx-configmap.yaml#L49-L59
- `ingress-template.yaml`
1. additional snippet for private ALBs
1. custom hostname
1. as debug ( skip ingress, skip https) ,Removed TLS, to make it work with http for now. 
- `issuer-template.yaml`
1. skipping this as egress is blocked
- `imago-template.yaml` ( not pertinent to issue at hand ) 
1. dedicated namespace
1. `rolebinding` instead of `ClusterRole`
1. `ClusterRole:edit` mapped to ServiceAccount

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit @sharat87 is this still happening?

**Comment by mohanarpit** [comment]
Closing this for now because Appsmith deployments are designed to work with the Ingress controller & support SSL.
