### ISSUE TITLE
[Bug]: Google OAuth 2.0 cannot re-authorize

### ISSUE THREAD

**Issue by onomou** [appsmithorg/appsmith#19933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In Edit Datasource, I try to click Save and Re-Authorize, but the button is disabled.

### Steps To Reproduce

I added a datasource for Google Classroom, using Google OAuth 2.0 granting an authorization token. When I save and re-authorize, it works as expected. However, if I wait a few days, it appears that the authorization expires and I need to re-authorize. A few weeks ago I could go into Edit Datasource, scroll to the bottom, and click Save and Re-Authorize. When I tried today, the button is disabled unless a change is made to the configuration.

### Version

Cloud

**Comment by sneha122** [comment]
During datasource autosave, we had decided to disable the save button if there are no new changes in the datasource form, this issue came up due to that change. For some users who have already created Auth API Datasource, if they just want to re-authorise the datasource, they have to make some change and enable the button. To solve this issue, as discussed with @rohan-arthur, we would keep this button enabled all the times, so that user can go ahead and authorise the datasource, without making any new changes. This will unblock the users for now, but we would tackling this issue in depth with datasource validity project CC: @rohan-arthur @sumitsum

**Comment by prapullac** [comment]
Completed testing on the local and works well
