### ISSUE TITLE
[Bug] When results from multiple table are queried in MySQL, only the result from 1st table is displayed. 

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#2005]
## Description
1. On query statements like "select * from table1; select * from table 2; ..." only the result from table1 is displayed in tabular form, even though all the results are obtained successfully. 

![Screenshot 2020-12-02 at 12 47 05 PM](https://user-images.githubusercontent.com/1757421/100958207-ebca9280-3541-11eb-9556-8fcb00aa1222.png)

### Steps to reproduce the behaviour:
1. Create mysql datasource.
2. Write select query : "select * from table1; select * from table2;"

### Important Details
 - Version: Any
 - OS: Any
 - Browser: Any

**Comment by Nikhil-Nandagopal** [comment]
@sumitsum this seems like it might be something specific to MySQL. This doesn't happen in postgres and the backend is only returning the first statement. I believe the contract is only for single statements so unless there is a use-case for multi statements, can we close this?

**Comment by sumitsum** [comment]
Hi @Nikhil-Nandagopal , the mysql returns multiple results as per the latest code in release branch - as shown in the image - result body has two results mapped against indexes 0 and 1 but the result from 0 is only displayed. I had checked with @riodeuno on this. He said that ideally both the results need to be displayed with some kind of join operation.

**Comment by Nikhil-Nandagopal** [comment]
I understand that but is this expected to happen in every database? If no
then why should we support this? I tried this in postgres and it doesn't
work. Also sending the rows combined is not a join operation and the user
should explicitly write a join statement to achieve this. Does this
multiple statement syntax work in any MySQL tool?

**Comment by sumitsum** [comment]
Hi @Nikhil-Nandagopal, I am not aware whether chaining of sql queries is allowed by design. I had assumed so after my conversation with @riodeuno . In case it is not, then yes the bug report needs to be closed.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit can you shed some light here. AFAIK only single statements are supported from backend and this is probably an unexpected side-effect

**Comment by mohanarpit** [comment]
I don't think both results should be displayed in the UI in any kind of join operation. This goes against what a "Join" is and will only confuse the users. From all DB management software (pgAdmin, Robo3T etc), the last operation's results are displayed instead of the first ones. So if I have chained 3 SQL queries, the UI should display the results of the 3rd one instead of the 1st one.

Having said this, @sumitsum, I'm intrigued by the screenshot that you pasted. Since each plugin returns an array of objects, what happens if each query has multiple rows instead of single rows. Is it even possible to distinguish between the output of the 1st query and the 2nd query within the plugin?

This can be resolved by either:
1. The server only returning the last object in the array so that the client doesn't have to take a call on what data to show. 
2. The client only displays the last result in the UI and binds it to other parts of the data tree.

**Comment by sumitsum** [comment]
Hi @Nikhil-Nandagopal @mohanarpit , I am closing this bug report in favor of a new one: https://github.com/appsmithorg/appsmith/issues/2028
