### ISSUE TITLE
[Feature]: Add internal SQL database (Postgresql) to Appsmith Docker container

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#20107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith Docker container should have a Postgresql daemon running inside it by default. All queries to our mock dbs will then be directed to the local DB instance instead of the hosted one. The tasks that would be required to fulfill this would be: 

1. Install Postgresql in the Docker container using Dockerfile
2. Add provision to stop/disable Postgresql from booting based on an environment variable
3. Seed data into the Postgresql DB during first container startup. This ensures that we don't have to ship the Docker container with data & bloat it unnecessarily. 
4. Persist the Postgresql data in `/appsmith-stacks`. This ensures that the data is persisted across version upgrades. 
6. Update the mock db endpoint in the product to use the local DB by default instead of the hosted DB for self-hosted instances. The cloud instance should still use the hosted DB.

### Why should this be worked on?

This should be worked on because the hosted mock databases get overloaded and this leads to a poor experience for our users. The mock db is used heavily by first-time users/explorers of Appsmith and seeing errors in the app leads to a poor first impression. 

From a cost optimization perspective as well, we can reduce the size of our hosted mock db to be only available for Appsmith cloud and not from self-hosted instances. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_71558)

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit along with this, we'll also need to load the movies db onto the mongo container that we ship right?

**Comment by mohanarpit** [comment]
@Nikhil-Nandagopal Yes. That is correct. The Postgresql will be a new addition to the Docker container. MongoDB service is already present. The startup script will have to seed the data in both Postgresql and MongoDB.

**Comment by Nikhil-Nandagopal** [comment]
We also need to change the CTA on clicking the mock dbs to connect to these databases now

**Comment by sum35h** [comment]
@sharat87 According to point 2, I understand that we will not be running Postgres via Supervisor.

**Comment by sharat87** [comment]
@sum35h,

- We _will_ be using supervisor to run Postgres. I'm not sure why you get that impression? 🤔
- No. Just like:

https://github.com/appsmithorg/appsmith-ee/blob/ba3ea42057eeb903b430148473ce119398dbe4e4/deploy/docker/entrypoint.sh#L366-L368


Also @mohanarpit, regarding the third point, in order to restore the data in Postgres on first-startup, the data will be stored as an SQL file _in the container_. So the Docker image will indeed have to bear this size nonetheless.

**Comment by sum35h** [comment]
I don't think the dump would bloat up the size since currently, it's about 900KB, but since the data is tied to the image, users will only get the new data if they pull the latest image. Is this expected ?

**Comment by sum35h** [comment]
@GreenFlux We’ll be migrating the postgres mockdb that’s hosted in AWS RDS, to an embedded postgres running in the Appsmith FAT container.
This means the sql dump for the data will be baked in to the container image, and any subsequent update (new template tables) will only be reflected when the user updates their Appsmith release.
Would this be acceptable? OR would we want to keep the templates postgres data independent of the container image?

**Comment by sharat87** [comment]
@sum35h, let's have the mock data be included in the Docker image, but the template apps' tables and data, let's have them come from a common external source, like an S3 bucket. This is so that, just like template apps are updated separately from Appsmith, their data is also updated alongside, and isn't tied to Appsmith versions.
