### ISSUE TITLE
[Bug]: Firestore DB - Env variables are shown in the following scenario even if particular env not configured

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#20154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Configure only Staging env for Firestore DB, and note that all bound values are getting copied for Prod also.

### Steps To Reproduce

1. Create a firestore db, and go to manage env
2. Configure only staging env
3. Now after test configuration succeeds, try to change env to prod on the DS page
4. Note that though Prod was not bound to any env variables, the DB url and service account credentials are showing up the same env variables as on Staging

https://ddpa7mfuvv.vmaker.com/record/Um2vKEeNWymMojNd

### Version

EC2 instance

**Comment by ayushpahwa** [comment]
Hey @btsgh this is not a bug. You entered the URL value and it will be copied over to both environments on creation of a new variable as per RBAC. As for the rest of 2 variables, there is no value there as seen. If you open the manage env page, you won't find any values for these two. The service account value is masked because it is a protected field.

**Comment by btsgh** [comment]
Ok @ayushpahwa - in that case, the Service Account Credentials also should not be coming up as masked on this page. That is misleading. Seems like it is already configured, but we actually did not configure it on Prod.
