### ISSUE TITLE
[Bug]: Popover not closing for large text for table widget

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith#20213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Adding a large text in the table and then hovering over it's cell, opens a tooltip that cannot be closed until the page is refreshed.
![image](https://user-images.githubusercontent.com/14138515/215452193-545e0471-109a-402c-b1c3-773d907ebc0e.png)

### Steps To Reproduce

1. Dnd Table widget
2. Add a really large text in one of the cell.
3. Hover over this large text.
4. Observe that the popover does not close. Only closes on page refresh

### Version

Cloud

**Comment by hhvys** [comment]
Found that #7849 is a related issue as well. This [PR](https://github.com/appsmithorg/appsmith/pull/20300) should close both the issues.

**Comment by GreenFlux** [comment]
@keyurparalkar @dilippitchika could we get an update on this issue please? The PR above was closed, but the issue is not resolved. The app becomes unusable until you refresh. This makes large text columns incompatible with the table widget and I have to hide the column to work around it. 
![Screenshot 2023-12-15 at 7 21 32 AM](https://github.com/appsmithorg/appsmith/assets/24459976/c1b09487-adb3-4204-bb3b-05b20a5a50e1)
