### ISSUE TITLE
[Task] Improve CodeMirror addons with multiplexer.

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#2025]
Code mirror addons don't support multiplexed modes.

As a result, we're left with hacking our way around them to get our desired behaviour.

Potential solutions:
- Contribute to codemirror with multiplexer aware addons.
- Write and maintain our own set of codemirror addons.

**Comment by ofpiyush** [comment]
What do you think @riodeuno @hetunandu?

**Comment by hetunandu** [comment]
Contributing to the same add-ons would not help a lot since they are in the process of rewriting the whole thing in codemirror 6 anyways.

Seems to me, having our own addons for these is a better way to go as code editing is a critical part of the app. This will give us more control over this part of the codebase

**Comment by Nikhil-Nandagopal** [comment]
Not picking it up in light of implementing it ourselves
