### ISSUE TITLE
[Bug]: SMTP : Inappropriate spacing is displayed to user on datasource preview page

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#20332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the datasource is added without the variable the datasource details are displayed to user with large spacing 

### Steps To Reproduce

1) Add Datasource details
2) save the datasource
and observe the review page
<img width="1277" alt="Screenshot 2023-02-02 at 9 34 34 PM" src="https://user-images.githubusercontent.com/71753653/216377778-e293fdd5-21c6-41ae-a71e-d9b2c4c9adaa.png">

### Version

DP

**Comment by rohan-arthur** [comment]
![Screenshot 2023-02-27 at 16 24 16](https://user-images.githubusercontent.com/94514895/221545403-032722ee-05c3-4b5b-826f-561268e20939.png)

refer screenshot from release:
1. space between fields is too large
2. space between label and value is too large
3. font of label should be different from value

**Comment by btsgh** [comment]
The issues have been addressed, but it still is not the same as on Release. Looping in @parth-appsmith @shadabbuchh to comment here please, so that I can take an appropriate call on the issue. 
![DSSave_Multienv.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/052ebc51-a66b-4647-a603-8beb5e9c872f)
![DSSave_release.jpeg](https://images.zenhubusercontent.com/6242f2f59960209e891f50ec/cf26b8a4-eed5-4f27-888e-0a37ebbd1a83)

**Comment by shadabbuchh** [comment]
> The issues have been addressed, but it still is not the same as on Release. Looping in @parth-appsmith @shadabbuchh to comment here please, so that I can take an appropriate call on the issue. 

@btsgh yes, these both things do not look consistent with what we have on release. This can cause that datasources pages to not look uniform throughout.

**Comment by btsgh** [comment]
As per the above comment from @shadabbuchh - moving it back to InProgress

**Comment by btsgh** [comment]
Fixed.
