### ISSUE TITLE
[Task]: Create a hotkey to bring up widget list

### ISSUE THREAD

**Issue by kocharrahul7** [appsmithorg/appsmith#20427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

- Create a hotkey [we are thinking of `Shift w`, `CMD +`, `CMD I`, `Double click w` or `CMD E`

`CMD +` is already used for creating a new file
`CMD E` since the action is "cr**E**ate new widget", and `CMD c` and `cmd r` are common patterns 
`CMD I` since the action is "w**I**dget", and `CMD W` is a typical pattern

Decision to be taken, and issue to be updated

**Comment by akash-codemonk** [comment]
https://appsmith-m0otx205m-get-appsmith.vercel.app/ using ctrl/cmd + e.  

- I doubled tap w unintentionally so the widget pane opened and search had W since the input is focused. Hence skipped just characters W and double W.
- Occasionally I was pressing cmd w instead of w only since most shortcuts have a modifier before. Hence skipped all W shortcuts.
- Cmd + e since e is closer to the left than I in a standard keyboard. Just felt it to be more intuitive with the right hand on mouse for drag and drop.

**Comment by kocharrahul7** [comment]
No longer relevant
