### ISSUE TITLE
[Bug]: Discard is getting stuck for git connected application 

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#20458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/217330631-87dbde90-0aea-4e53-be37-40b6530a3dcf.mov

### Steps To Reproduce

1. Go to this application and try discarding https://appsmith-nmo0ou7xt-get-appsmith.vercel.app/app/test-discard/page1-6261186c81a4732e34a5b736/edit?branch=master

### Version

Release

**Comment by AnaghHegde** [comment]
@Parthvi12 
https://github.com/Parthvi12/testst/commit/23ba2ddbdc44ef873c3f72a93c10aef16a1ee878
This was the last commit and the data in the repo is corrupted
I think it is because of bug which we introduced only in release during last year. This was part of page order refactoring that i did and hence for few days the app connected to git from our release environment had missing reference to the page. The application json has missing reference to page and the last commit was on April 2022.
https://github.com/Parthvi12/testst/commit/b2589de3f61697c7e4faa8b2d8207df1f7581e98
This is the latest commit and this commit adds the page referefence in json file.

Hence closing this issue.
