### ISSUE TITLE
[Bug]: Review screen: host name and port number coming in the same lines across datasources.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On the review screen, host name and port number coming in the same lines across datasources unlike design.

### Steps To Reproduce

refer to the design screenshot
<img width="1123" alt="design" src="https://user-images.githubusercontent.com/119847783/217444460-cfa29bec-1b65-4180-a487-115e0115d17a.png">
<img width="1440" alt="bug" src="https://user-images.githubusercontent.com/119847783/217444530-c505cc8c-2df1-401f-aadf-009a39bdf1d6.png">

### Version

1.9.6

**Comment by ayushpahwa** [comment]
This is to maintain the same design for multiple host addresses. @parth-appsmith @sribalajig

**Comment by parth-appsmith** [comment]
@ayushpahwa but why do we need to change the structure? Can we accommodate multiple host and post values within the same structure. 
The above screenshot seems out of order and what happens when host address are long, this will cause the port to be pushed to the right our of alignment with another host address with smaller value.

Can't we do something like this.
![image.png](https://images.zenhubusercontent.com/63bbaa58bbeaf08380c04053/821696fb-dc6b-41a4-87a5-6535ca2ac124) 

Figma Link: https://www.figma.com/file/FC5XY2B57Fu41s0a0Wz93g/Multiple-Environments?node-id=3596%3A282215&t=j5pDeVsnzNhZ5uzb-4

PS: Adding the same to zeplin as well.
