### ISSUE TITLE
[Bug]: Help and resources icon missing

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#20549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Help and resources icon missing throughout

### Steps To Reproduce

refer to the screenshot

<img width="1440" alt="DP" src="https://user-images.githubusercontent.com/119847783/218000069-c75ab875-bd68-4e14-b392-ad9e5fc00d98.png">
<img width="1439" alt="release" src="https://user-images.githubusercontent.com/119847783/218000078-e92455b1-cb86-4224-84ff-2764a31146c7.png">

### Version

1.9.6

**Comment by ayushpahwa** [comment]
This is a new feature and resolved by the latest release merge. @parth-appsmith please verify if the following update to design is okay?

![image.png](https://images.zenhubusercontent.com/60d04e24be9e2f34b7493dfb/88cf1b05-9ea5-4ef7-a8b5-c656b3eb1b2d)

**Comment by parth-appsmith** [comment]
The **resource and help icon** is supposed to be part of the footer, this got missed to be presented in the designs since our footer component probably wasn't updated and I missed on explicitly adding it. 
To confirm @ayushpahwa @AnandShahs123 the icon should be visible since it is already there in the prod.

**Comment by AnandShahs123** [comment]
Help and resources visible now.
