### ISSUE TITLE
[Bug]: Form login disabled after user uses OAuth login method

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#20661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

form login disabled after user uses OAuth login method
![image](https://user-images.githubusercontent.com/45958978/219276753-5073f9c8-9884-421d-9948-9b19766a8314.png)

### Steps To Reproduce

1. Login with an Email id 1 using a form login
2. Now signout and with the same email id login with a Google 
3. signout again
4. and try to login with the same  email id with form login the error message will be displayed

### Version

prod

**Comment by infinitetrooper** [comment]
@RakshaKShetty - to clarify

1. Sign Up with Form Login
2. Sign In with Form Login
3. Sign Out
4. Sign In with Google OAuth (same email as above)
5. Sign Out
6. Sign in with Form Login (Error Shown)

Are these the exact steps to reproduce this?

**Comment by infinitetrooper** [comment]
@sharat87 @abhvsn @trishaanand - Is this by design, that we stop form login once a user uses the same email with any of the SSO auth methods?

**Comment by sharat87** [comment]
This is expected behaviour, and I'd even say we should be testing to assert this failure. Yes, this is by design.

Why? This is a security protection against account takeovers. For example, since we don't have email validation for users who signup, I'll go signup as `trump@gmail.com`, with a password. Then, the real owner of `trump@gmail.com` will signup with OAuth, but will instead see the account I previously created. Not realizing that I, the imposter, have already done this, the real owner goes on to creating apps and other normal activity.

Now, if my password-based access is still working, I can still login to this real owner's account, and see their activity. I have no business doing that, and I shouldn't be allowed to do that.

This is why when there's an OAuth login for a user who signed up with password, we disable their form-based login, and they can only use OAuth after that. Because emails in form signup are not verified, but coming from OAuth are indeed verified.

**Comment by infinitetrooper** [comment]
Okay, that makes a lot of sense. @RakshaKShetty - Is there a way we can add this to our test suite? (or are you not the right POC for this?)

**Comment by RakshaKShetty** [comment]
same issue is tracked here https://github.com/appsmithorg/appsmith/issues/13518, so closing the issue
