### ISSUE TITLE
[Bug]: Spaces within data gets stripped out when rendered in Table widget

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#20773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

has data been pulled from a datasource and displayed in a table widget, it is noticed that regardless of the number of spaces in the data, there's only one space in the table widget.  For example, TEST    INTO  gets displayed as  TEST INTO .

### Steps To Reproduce

1. Create a datasource that contains a data with multiple spaces within the data
2. Pull the data and display it on a table widget, all the spaces gets stripped out remaining just one

### Version

> 1.8.7 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7ktn0)

**Comment by vsvamsi1** [comment]
It looks like its because of html's whitespace collapsing.
We can disable it but it would affect how existing tables appear. If our users don't strip off the extra spaces from their data set, then their tables would look completely different after us disabling this behaviour.
Should we expose a toggle property to disable this behaviour?
Another solution is to use this character instead of whitespace "\u00A0".

**Comment by Nikhil-Nandagopal** [comment]
The solution isn't clear and the problem doesn't seem severe so I'm closing this
