### ISSUE TITLE
[Bug]: Email is not getting sent to the reply-to address when logged in as a different instance admin

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#21053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Email is not getting sent to the reply-to address when logged in as a different instance admin.

### Steps To Reproduce

1. Take a release-ce pull and and run the docker instance locally
2. Follow the welcome screens and create a user say demo@appsmith.com in this process
3. Now go to Admin settings
4. In the Email section here, configure email with following details:

SMTP Host - smtp.sendgrid.net
SMtP Port - 587
From Address - yatinabcd@gmail.com
To Address - aparna@appsmith.com
SMTP Username - apikey
SMTP Password - {{removed key}}

Click on Send test email

5. Note that the toast appears to the effect that email has been sent to demo@appsmith.com
![emailissue](https://user-images.githubusercontent.com/101863839/221905341-f11bee7c-731d-4758-9454-29e6479cf565.jpeg)

### Environment

Release

### Version

Release

**Comment by sharat87** [comment]
The test email is _always_ sent to the user who's currently logged in. This is by design, and hasn't changed. So not able to understand what's the unexpected behaviour here?

**Comment by sharat87** [comment]
Nope. The `Reply To` field only set the `Reply-To` header in the email that is sent. So that when the receiver of the email hits the `Reply` button, they'll be writing to that `Reply-To` address.

But the test email is always sent to the currently logged-in user. This is so that this user is testing the email functionality, and if they're not the recipient, they'll have to get in touch with the receiver of the email and confirm if the mail was sent or not. Which is more work for little value. So we always send the test email to the logged-in user only.

**Comment by btsgh** [comment]
Got it - thanks for the explanation @sharat87 . I will close out this issue as this is not a bug.
