### ISSUE TITLE
[Feature] Show Table page size for server side pagination

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2107]
## Summary
We don't show any information about row count on the table for server side pagination. 

## Motivation
Need to understand that we have reached the end of results

## Additional Context
For server side pagination, we do not show any record info
<img width="267" alt="Screenshot 2020-12-09 at 10 17 40 PM" src="https://user-images.githubusercontent.com/12022471/101659721-60cf2800-3a6c-11eb-8168-23f7d0a7b389.png">
For client side we show this
<img width="265" alt="Screenshot 2020-12-09 at 10 17 30 PM" src="https://user-images.githubusercontent.com/12022471/101659732-63318200-3a6c-11eb-9b56-86f8101ee491.png">

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu we don't do this because this is the total number of records in the table not just the records on the first page. In serverside pagination this information doesn't make sense

**Comment by notacouch** [comment]
@Nikhil-Nandagopal  Right now there is no way to know how many records are even being displayed. If the table can show 100 records, but the query only returned 99 for this page, we have no way of knowing. If this page returned 100, we know there's a _chance_ there's another page. But if we have no idea of the records being shown, we don't know whether to paginate or not or if we missed to scroll down, nothing. I don't want to make a made up column as part of my queries just to show this.

**Comment by Nikhil-Nandagopal** [comment]
@notacouch to understand your request correctly, you are looking for a feature to see the number of records per page because you want users to know whether they should go to the next page or not. Is this correct?

Today we show the **total number of records** in the table rather than **records per page** because most tables with multiple pages will show the same information except for the last page.
To solve your problem, do you think it would be more useful for us to allow you to configure a total number of pages property that will automatically disable the next/previous button if the last page is reached?

As a workaround for now Instead of another column, you could use a text widget and bind it to `Records: {{Table1.tableData.length}}` to show this information

**Comment by notacouch** [comment]
@Nikhil-Nandagopal  Good questions.

> Today we show the total number of records in the table rather ...

By this do you mean the property you later mentioned, i.e. `{{Table1.tableData.length}}`?

> To solve your problem, do you think it would be more useful for us to allow you to configure a total number of pages property that will automatically disable the next/previous button if the last page is reached?

That's quite alright, because for server side pagination if we're limiting the query and with an offset, we won't know the actual total number of results/pages (I guess unless we provide that via separate query just for counting).

It would be nice to display just the number of records in table as done with clientside instead of having to show this elsewhere. But it's good to know there is a property I can use. What I can do is adjust the layout, put a container beside the table to show details and actions.

Thanks for the workaround suggestion!

**Comment by Nikhil-Nandagopal** [comment]
@notacouch so then maybe a feature to mention the number of records / page. If fewer records than what is configured are returned, we can disable the next page button

**Comment by notacouch** [comment]
@Nikhil-Nandagopal That sounds like a pretty good idea, thank you!

**Comment by Nikhil-Nandagopal** [comment]
Closing this in favor of #2230
