### ISSUE TITLE
[Bug]: OAuth2.0 connection created from a Git branch brings it back to master branch on authorization

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#21188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

OAuth2.0 connection created from a Git branch brings it back to master branch on authorization

### Steps To Reproduce

1. Create a git connected app and create a new branch say test
2. Switch to that branch - test
3. From the branch , Create an OAuth connection to Dropbox. [Ping @btsgh for details of Oauth connection]
4. Save and Authorize. 
5. Note that after saving and authorizing successfully, the branch gets changed back to master. 
Expected behavior - the branch should be retained to test.

### Environment

Production

### Issue video log

https://ddpa7mfuvv.vmaker.com/record/ZRCIvel8ys961opD

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
This is more a problem of the OAuth redirect taking in the branch into account

**Comment by btsgh** [comment]
Video rerecorded. @NilanshBansal -
https://github.com/appsmithorg/appsmith/assets/101863839/be94da74-a4c2-4e4e-9b72-dd497b3aab7f

**Comment by NilanshBansal** [comment]
This issue is because, when we have an authenticated API, after successful oauth, it redirects to the <base_url>/applications/<applicationId>/pages/<pageId>/edit/datasource/<datasourceId>, it doesn't consider the query parameter `?branchname=<>`. 

To fix this, as part of /v1/datasource/authorize API, we need to add `branchname` in the state parameter alongwith the applicationId, pageId and datasourceId which is already added. 

<img width="1051" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/2ae2c6b4-e149-46b3-ae6e-70d48bf1eaee">
