### ISSUE TITLE
[Bug]: Error messages are unclear when the SSH key is removed from the remote repo

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

For the git connected apps , which were throwing internal server error, com initially fails for them now with following error

https://user-images.githubusercontent.com/80334441/224343664-37aa39b5-2629-4c35-b392-130a2a1c631f.mov

### Steps To Reproduce

1. Go to this app https://release.app.appsmith.com/applications/62406e2e6c86dd5be6fdd2e5/pages/62406e2e6c86dd5be6fdd2e8/edit?branch=main and try to commit changes
2. Observe error is thrown 

Github repo : https://github.com/Parthvi12/gittesting123

### Environment

Release

### Version

Release

**Comment by NilanshBansal** [comment]
This occurred because the SSH public key that was present in the database and the git connection was deleted from the github repository. 

**Git Connection Shows Deploy key added** 

<img width="536" alt="image" src="https://user-images.githubusercontent.com/25542733/229507852-9f6796fd-0740-4e41-a8ba-a8da2d3596be.png">

**Git Repository Doesn't have any deploy key**

![Screenshot 2023-04-03 at 5 47 22 PM](https://user-images.githubusercontent.com/25542733/229508000-dbd1395a-790a-4b44-bd66-41f883b5cb95.png)

**Comment by NilanshBansal** [comment]
Closing this issue as it is the intended functionality. Discussed with @Parthvi12

**Comment by AnaghHegde** [comment]
Yes, we should improve the error message. @NilanshBansal Can you raise a fix for this? While you are on this, please verify the error message for other cases as well and improve them.
