### ISSUE TITLE
[Bug]: On changing home page's name, the git sync modal shows 1 extra page modified.

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On changing only the home page's name, git sync modal shows 2 pages modified.
Note: This happens only for the home page and not any other page.

https://user-images.githubusercontent.com/80334441/224651353-3203f2d2-a27c-49f0-b46a-bf9ff032ed81.mov

### Steps To Reproduce

1. Go to an app, connect it to git.
2. Rename the homepage.
3. Open git sync modal and observe.

### Environment

Production

### Version

Cloud

**Comment by AnaghHegde** [comment]
@Parthvi12 This is an expected behaviour. When the page is renamed and the same has to be updated in the file system. But the problem with that is that we don't have a reference to the old name, so we write the content to a new file. Hence you would see two pages updated.  
If you have a query or JS Object associated with that page, you will see those queries updated in the change log. Unfortunately, we don't have a solution for this bad experience. Let's keep this ticket open and work on it in the future.

**Comment by infinitetrooper** [comment]
Added the note in documentation in the meantime - https://github.com/appsmithorg/appsmith-docs/pull/987

**Comment by AnaghHegde** [comment]
Closing this as it is expected behaviour.
