### ISSUE TITLE
[Task] UI to code conversion

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#21392]
- [x] Page-level entities are showing up as global entities
![image](https://user-images.githubusercontent.com/79509062/227846360-c106f638-6921-4d69-bb29-f9ef28b9d159.png)

- [x] `Actions` keyword on all tooltips should be in all lowercase
![image](https://user-images.githubusercontent.com/79509062/227846797-ad35fdb0-a64b-4a8e-a43f-14fe7926d2f2.png)

- [x] Distance between fields and their respective dropdowns differ throughout
![image](https://user-images.githubusercontent.com/79509062/227848737-fced0482-eee4-4bf6-a32f-da936c202c5b.png)
![image](https://user-images.githubusercontent.com/79509062/227848790-3c371baf-983d-405b-a0dd-b1b6464f8f35.png)
![image](https://user-images.githubusercontent.com/79509062/227849469-eacfdb91-9bc2-43eb-9805-c5ebe2592280.png)

- [ ] #21785
![image](https://user-images.githubusercontent.com/79509062/227849035-ac32644c-8535-49c2-886c-9d1021b4f086.png)

**Comment by arunvjn** [comment]
Check point DP - https://appsmith-os11uxxpb-get-appsmith.vercel.app/

**Comment by shadabbuchh** [comment]
1. Can we please add the `x` icon in the search input in order to make it easier to delete the entered text.![Screenshot 2023-03-27 at 10.25.29 AM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/24ea3574-5f4f-443e-9475-879eaf368031)

2. Need a period (`.`) after Actions![Screenshot 2023-03-27 at 10.24.49 AM.png](https://images.zenhubusercontent.com/6278b12bad578328630ba2e7/cd922120-3b9d-4fee-ad5e-5e60d34b6568).

3. Double clicking inside the search input erases the entered text
4. On scrolling the tree dropdown for some actions moves on the screen. 
https://www.loom.com/share/5f4f5f9a1390440b9dc17c56f9c39ed7
5. 

- Select the `Show Modal` option & then select `New Modal` for Modal Name. 

- Now delete the Modal1 from the entity explorer. Notice that we are still able to see the `Modal1` in the action selector even though it got deleted.
https://www.loom.com/share/552975676d6740d5b37c8e514504af0e

6. Can we please have similar tooltips for `On Success` & `On Failure`(The first sentence).
7. No tooltip for `Callbacks`.
