### ISSUE TITLE
[Bug]: Launching forked/duplicated application shows all pages of an app even when the app is not deployed

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#21421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://user-images.githubusercontent.com/80334441/225245375-792a0462-7fd6-4076-82cb-f10ea8344172.mov

### Steps To Reproduce

1. Create an app add some widgets
2. Go back to application page and duplicate that app
3. Launch duplicated app from application page and observe
ideally it should show 'This page seems to be blank'

### Environment

Release

### Version

Release

**Comment by nayan-rafiq** [comment]
@Parthvi12 This is the expected behavior. To fix this issue https://github.com/appsmithorg/appsmith/issues/21309 we're automatically publishing the application when they are duplicated. As a result, the unpublished pages from the source application are published in the duplicated application. 

To solve this, we can skip publishing the application. If we do that, opening the duplicated application in view mode will show a 404 Not found error because the application is available in view mode only when it's published.
