### ISSUE TITLE
[Feature]-[70]:It would be great if you could set the default Camera View for this widget.  This may need to be able to toggle between laptop camera and phone camera.

### ISSUE THREAD

**Issue by pchambless** [appsmithorg/appsmith#21554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

My client wants to have field personnel snap pictures of their assigned projects, equipment, and other aspects of their business.  Almost never would this involve a selfie view which is the default.  Being able to assign a default view would be the ideal in case some use cases call for a selfie view most of the time.

### Why should this be worked on?

My client needs to cut down on the complexity of taking field pictures.  With the current version of the Camera widget, users have to select the 'back view' every time instead of having it as the default.

**Comment by dilippitchika** [comment]
@dhruvikn do we have this kind of information on which is front and which is back in the camera widget/code scanner widget?

**Comment by dhruvikn** [comment]
No @dilippitchika, there is no solid/bulletproof way of doing this. We tried using [facingMode](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/facingMode) but it's behavior is sketchy. We couldn't produce stable results on laptop and mobile.

**Comment by dhruvikn** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 21.2 |
| Effort (months)  | 0.5 |

**Comment by AndreasEmmel** [comment]
Hi,

I just wanted to second that request.
We use handheld devices with two cameras (Zebra TC53) and upon opening the camera widget, its always the "selfie" camera activating.
This is very annoying for the operators, because they never use this camera, always the backfacing camera.

Best option would be to deacivate the "selfie" camera.
I can think of some more possible solutions: 
- set a default camera. (at runtime or programmed)
- select the correct camera via code or an option in the widget.

Thanks for your hard work!
