### ISSUE TITLE
[Bug]: Authenticated API not correctly attaching self-signed certificates

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#21608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, when we have an API that requires authentication through self-signed certificates, even if we attach our PEM file, Appsmith is not able to read it and displays the following error:

```bash
org.springframework.web.reactive.function.client.WebClientRequestException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.

```

Example video:

https://user-images.githubusercontent.com/114161539/226468450-24550d06-1107-422b-a0e2-ed270b90ce3f.mp4

### Steps To Reproduce

 1.  Connect to a self-signed certificate API. You can use this Python script to generate the server with its PEM certificates.
    
 ```py
    
 from flask import Flask, request, jsonify
import ssl
import os
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives import serialization
from datetime import datetime, timedelta
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.backends import default_backend

app = Flask(__name__)

cert_path = os.path.join(os.path.dirname(__file__), 'cert.pem')
key_path = os.path.join(os.path.dirname(__file__), 'key.pem')
if not os.path.exists(cert_path) or not os.path.exists(key_path):
    print("Generando certificado y clave...")
    
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048
    )

    subject = issuer = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, u"localhost")
    ])
    cert = x509.CertificateBuilder().subject_name(
        subject
    ).issuer_name(
        issuer
    ).public_key(
        private_key.public_key()
    ).serial_number(
        x509.random_serial_number()
    ).not_valid_before(
        datetime.utcnow()
    ).not_valid_after(
        datetime.utcnow() + timedelta(days=365)
    ).add_extension(
        x509.SubjectAlternativeName([x509.DNSName(u"localhost")]),
        critical=False,
    ).sign(private_key, hashes.SHA256(), default_backend())

    with open(cert_path, 'wb') as f:
        f.write(cert.public_bytes(encoding=serialization.Encoding.PEM))
    with open(key_path, 'wb') as f:
        f.write(private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption()
        ))
    print("Certificate and key generated at the following location:")
    print(cert_path)
    print(key_path)

context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
context.load_cert_chain(cert_path, key_path)

users = [
    {"username": "user1", "password": "pass1"},
    {"username": "user2", "password": "pass2"}
]

def authenticate(username, password):
    for user in users:
        if user["username"] == username and user["password"] == password:
            return True
    return False

@app.route('/protected')
def protected():
    auth = request.authorization
    if not auth or not authenticate(auth.username, auth.password):
        return jsonify({'error': 'Unauthorized access'}), 401
    return jsonify({'message': 'Welcome to the protected area!'})

if __name__ == '__main__':
    app.run(ssl_context=context)
```
    
Note: install these libraries: pip install flask  &&  pip install cryptography
2. Run this curl command from the directory where you executed the Python code to verify a successful connection.
3. Expose port 5000 through Ngrok to connect to it from Appsmith.
4. Create your data source in Appsmith with an authenticated API.
5. In the URL field, put the URL that Ngrok gave you, plus this endpoint: /protected.
6. Attach the cert.pem certificate generated by the Python code.

### Environment

Production

### Version

Appsmith v1.9.12-SNAPSHOT/ Cloud Appsmith Community v1.9.12

**Comment by sumitsum** [comment]
This issue does not seem valid with v1.9.19. To verify I have followed all the steps as provided in the description. I think there is a minor error in the way the test is described. Apart from attaching the self signed certificate we also need to provide the username and password info via the REST API header which turns out to be `Authorization: Basic dXNlcjE6cGFzczE=` , e.g. the curl request would look like: 
```
curl --cacert cert.pem --header "Authorization: Basic dXNlcjE6cGFzczE=" https://localhost:5000/protected 
```

The same works with Appsmith as well: 
![Screenshot 2023-05-15 at 4 55 19 PM](https://github.com/appsmithorg/appsmith/assets/1757421/006b8c5e-bf99-4df9-abfe-290fc921995d)

**Comment by sumitsum** [comment]
This issue does not seem valid with v1.9.19. To verify I have followed all the steps as provided in the description, except Appsmith instance was running on my local. I think there is a minor error in the way the test is described. Apart from attaching the self signed certificate we also need to provide the username and password info via the REST API header which turns out to be `Authorization: Basic dXNlcjE6cGFzczE=` , e.g. the curl request would look like: 
```
curl --cacert cert.pem --header "Authorization: Basic dXNlcjE6cGFzczE=" https://localhost:5000/protected 
```
Also, as per my understanding, we cannot use ngrok with the python server since ngrok would expose a different endpoint for which we don't have the self signed certificate (the Python script provided creates the self signed certificate for the localhost endpoint). 

The same works with Appsmith as well: 
![Screenshot 2023-05-15 at 4 55 19 PM](https://github.com/appsmithorg/appsmith/assets/1757421/006b8c5e-bf99-4df9-abfe-290fc921995d)
