### ISSUE TITLE
[Bug]Issue with the right hand side padding in container-type widgets in auto layout mode

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21658]
![Image](https://user-images.githubusercontent.com/113327629/226706413-32bc5af7-f512-4360-9bba-1ad2428c8d51.png)

**Comment by aswathkk** [comment]
@yaldram Can you check why the icon in the statbox widget in deploy mode is behaving like this?

**Comment by yaldram** [comment]
On the latest pull of `mobile/v1/qa` I am unable to re-produce this issue, @kamakshibhat-appsmith can you please verify thanks

**Comment by yaldram** [comment]
The `transform: translate3d()` property used in the `FlexComponent` is the root cause for this issue. We can observe the same behavior for other widgets like the `Button` widget for example.
![image](https://user-images.githubusercontent.com/13429535/227933302-3f702647-bc1d-498e-b6b2-26794cd64750.png)
