### ISSUE TITLE
[Enhancement] Autocomplete should work with local variables

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#2174]
## Summary

In JS, when we create new objects which are references to data within entities. Autocomplete does not work.

https://media.discordapp.net/attachments/760761686549463060/787294091758272591/autocompleteNotShowing.gif

Additional information 
- Demo of codemirror and tern supporting local variable autocomplete https://codemirror.net/5/demo/tern.html
Code - https://github.com/codemirror/codemirror5/blob/master/demo/tern.html

**Comment by rohan-arthur** [comment]
1. _When I am typing js, the local variables should show in the autocomplete based on the matches_
Currently, they don't. In the case below, `a` should be suggested on top because I entered `a`:
![Screenshot 2022-06-27 at 13 44 34](https://user-images.githubusercontent.com/94514895/176396530-78fa3576-40f8-4d4e-bf04-78ccd8b2baf3.png)

2. _When I am typing js, the function parameters should show in the autocomplete based on the matches_
Currently they don't. In the case below `temp` should be suggested on top because I entered `tem`:
![Screenshot 2022-06-27 at 13 45 51](https://user-images.githubusercontent.com/94514895/176396701-909bec6d-13cd-47c7-bc57-863b3ef60f9e.png)
