### ISSUE TITLE
[Bug]: Arango: Error message has no mention of host address when the host address is wrong.

### ISSUE THREAD

**Issue by AnandShahs123** [appsmithorg/appsmith#21782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

If the user tests the arrango datasource validity with a wrong host address, there is no mention indicating the host address might be wrong in the error message.
Error message -  
"Could not find required authentication info. At least one of 'Username', 'Password', 'Database Name' fields is missing. Please edit the 'Username', 'Password' and 'Database Name' fields to provide authentication info."

### Steps To Reproduce

1. Add a new ArrangoDB datasource
2. Enter a wrong host address
3. Enter a valid port number
4. Enter valid database name, username and password
5. SSL mode - Enabled
6. User CA certificate - Disabled
7. Click on Test

Observe - The error message has no mention of the host address 
"Could not find required authentication info. At least one of 'Username', 'Password', 'Database Name' fields is missing. Please edit the 'Username', 'Password' and 'Database Name' fields to provide authentication info."

### Environment

Production

### Version

1.9.12

**Comment by sumitsum** [comment]
Hi, this issue is not valid. The error that Anand has reported comes because the username and password fields have been left blank - in which case the code flow doesn't reach URL test point. In case they are filled and the URL is incorrect then `UnknownHostException` is thrown. However, the error message could be improved. I will be working to fix that. Also, the SSL feature seems broken, will investigate that separately. 

![Screenshot 2023-05-10 at 10 42 59 AM](https://github.com/appsmithorg/appsmith/assets/1757421/38839c65-a8c8-4303-9dc8-841da20057c0)

**Comment by btsgh** [comment]
Tested and found to be fixed on release
