### ISSUE TITLE
[Bug]: Font style varies with comparison of Master and release  

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#21800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When the font style is compared on release and prod it is observed that they vary 
Attaching the screenshot for clarity 
<img width="1280" alt="Screenshot 2023-03-27 at 5 38 48 PM" src="https://user-images.githubusercontent.com/71753653/228003286-85193230-503a-4c88-bab5-b840c47ecad7.png">

### Steps To Reproduce

<img width="1279" alt="Screenshot 2023-03-27 at 5 38 56 PM" src="https://user-images.githubusercontent.com/71753653/228003312-44eb15fd-b981-4ea8-8b0a-ea3aeaf94433.png">

### Environment

Release

### Version

Release

**Comment by somangshu** [comment]
@prapullac are these different machines by any chance, Maybe we load the default system font for this. 

cc @albinAppsmith @tanvibhakta please check what is happening here!

**Comment by vinay-appsmith** [comment]
@prapullac This is not a bug. 'ui-sans-serif' is a label to load the system's default font instead of writing all the font names available across Windows, Mac OS and Linux. Sadly, it has no browser support except in Safari. 

https://caniuse.com/?search=ui-sans-serif

In the current state, it is redundant which doesn't have any negative behaviour on how the fonts look.
