### ISSUE TITLE
[Bug] [Table Widget] Selected Row not getting reset when the table data changes

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2193]
## Description
If a table already has a row selected and if the data changes, the previous row index still shows selected. We should be clearing out selected row if table data has changed

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu Can you add the steps for this?

**Comment by tazmaniax** [comment]
Steps to reproduce:
1.  Run a query that only returns one row
2. Select the one row
3. Re-run the query with different input so that replaces the one data row content
4. The row remains selected so no way to select the new row and trigger any associated handlers

This is quite a common scenario for me so definitely looking forward to this being fixed, thx!

**Comment by vicky-primathon** [comment]
@hetunandu  this seems to be working on release. Please check the loom video
https://www.loom.com/share/233d17c7d01e43da8c5214cd8d1a8e67

**Comment by tazmaniax** [comment]
I recorded this yesterday https://www.loom.com/share/5b0fe8fa59574e8080d9d6aa0ed04279
