### ISSUE TITLE
[Bug] Consider the app is in auto layout mode, the canvas is forced to go into fixed mode , when you change anything in APP NAVIGATION settings

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#21962]
https://www.loom.com/share/af94780028f3458fa92210de2e106644

**Comment by Sripriya93** [comment]
The issue seems to be working fine now as expected, but we we do this flow once or twice, we are seeing the List widget got bigger in size moving out of the canvas CC @kamakshibhat-appsmith @aswathkk 



![Image](https://user-images.githubusercontent.com/104895602/229474252-957a9cd0-1b3c-4353-8394-db0d7fff5779.png)
