### ISSUE TITLE
[Bug]: In a git-connected app when user has a  app level developer access and tries to add a page from a template the "oops something went wrong" error is displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#22043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In a git-connected app when user has a  app level developer access and tries to add a page from a template the "oops something went wrong" error is displayed
https://www.loom.com/share/0ee29cdc5d7149119f8cb8201de82b49

### Steps To Reproduce

1. Login to https://ee-1242.dp.appsmith.com/
2. create a new workspace/app
3. now connect app to the git
4. Now  share this app with a app developer access to user 1
5. now login as user 1
6. checkout to a new branch 
7. and now try to create a template
8. the oops something went error will be displayed

### Environment

Deploy Preview

### Version

deploy preview

**Comment by nsarupr** [comment]
This seems like a performance issue with the DP.
The API returns an error response on the DP, but can be tested on local to give proper results.
And once the page is reloaded again, we begin to see the pages generated via the template.
@RakshaKShetty can you test this on any other existing DP, so that we can rule out that it's a bug which was introduced because of the new code changes existing on the DP.

**Comment by nsarupr** [comment]
Can we check and update the issue on https://ee-1268.dp.appsmith.com/applications once, and update the issue to contain the updated error messages, screenshots and reproduction steps

**Comment by nsarupr** [comment]
Can we check and update the issue on https://ee-1268.dp.appsmith.com/applications once, and update the issue to contain the updated error messages, screenshots and reproduction steps

**Comment by RakshaKShetty** [comment]
This is fixed in release
