### ISSUE TITLE
[Bug][Widget Responsiveness] the width of the dropdown of select widget is not coming as expected after conversion

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#22344]
This is happening in deploy mode, and in mobile viewport
I could see this issue with one app only

https://www.loom.com/share/76abeadc3e924a588899c2ca78da668d

Link to app https://ce-21386.dp.appsmith.com/app/appsmith-regression-app-2/dashboard-64366e8b8381eb4a87912e66

APP JSON

[Appsmith Regression App.json.zip](https://github.com/appsmithorg/appsmith/files/11213381/Appsmith.Regression.App.json.zip)

**Comment by aswathkk** [comment]
This can be reproduced easily by dropping some select widgets and then some button widgets next to it so that select widget won't take up entire width of viewport.

<img width="467" alt="Screenshot 2023-04-13 at 1 19 03 PM" src="https://user-images.githubusercontent.com/10436935/231690852-f905372d-0e3d-4582-afce-6ce029f3a422.png">

This issue won't happen when we reach the mobile break point since at that point, the widgets will wrap and select widget will take up entire width.

This issue happens only in a width that is slightly greater than mobile breakpoint.

We need a product decision on how we should tackle these kind of cases. One way would be to increase min-width of select widget.

cc: @shastry-gg

**Comment by kamakshibhat-appsmith** [comment]
@aswathkk I tried in actual mobile devices where width is within mobile breakpoint , still happening .

**Comment by aswathkk** [comment]
Updated steps to reproduce this issue:
- Import the application
- Convert to auto-layout
- Go to "Issue List" page
- deploy application
- open deployed app in mobile viewport without doing any viewport resizing
- click on search dropdown to see the issue
<img width="449" alt="Screenshot 2023-04-13 at 4 18 29 PM" src="https://user-images.githubusercontent.com/10436935/231736373-179bb911-1cb0-404a-bd08-574ab5dfe9f5.png">
