### ISSUE TITLE
[Task]: Solve for email template images in airgap

### ISSUE THREAD

**Issue by berzerkeer** [appsmithorg/appsmith#22353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by abhvsn** [comment]
Whenever user updates the brand logo, it gets stored in the `Asset collection` within DB and will have no external internet dependency. Also for email templates we are referring to the same entry in DB and instead of url actual binary is added to the template. Considering the customers will be updating the logo and favicons etc IMO users won't end up in a situation where images in emails will be broken.

Closing this with above reason.

**Comment by abhvsn** [comment]
After the discussion, we still want to resolve the internet dependency so reopening this again
