### ISSUE TITLE
[Bug]: AirGapped instance - Clicking on Edit Profile - Upload display picture - brings up no internet connection

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In an airgapped instance, when I click on Edit Profile,  Upload display picture - it gives a message here to the effect - no internet connection

### Steps To Reproduce

1.  Pull the image with the command docker pull ankitakinger/appsmith:airgap
2.  Switch off internet and execute the following:
docker run -e APPSMITH_AIRGAP_ENABLED=true -e KEYGEN_LICENSE_VERIFICATION_KEY=b2b98c313548c14cb22ddb4afb9124553c4c829c290d8a3cbf01ff8ee57624dc -d --name appsmith-airgap -p 80:80 -v "$PWD/stacks:/appsmith-stacks" ankitakinger/appsmith:airgap
3. Now do the set up
4. Add air gapped license key
5. On the home page, top right, click on user icon -> Edit Profile -> Upload display picture
6. Here we see a message "No internet connection"

This should not come
<img width="999" alt="Airgapbug_EditProfile_UploadPicModal" src="https://user-images.githubusercontent.com/101863839/231718509-65506a27-0da1-4cc2-82f2-6b8e7f924af2.png">

### Environment

Release

### Version

Self Hosted

**Comment by berzerkeer** [comment]
This has a dependency in our `design-system-old` package. We use `uppy` inside DS for this component, but DS doesn't expose any api for us to pass custom uppy options. And since the `No internet connection` informer is part of uppy , we can't control it from our codebase. So I will make the necessary change in DS and will update.Changing the initial estimation from 0.5 to 1.
