### ISSUE TITLE
[Task]: Deduplicate components & Grayscale/theming support in Header

### ISSUE THREAD

**Issue by rohitagarwal88** [appsmithorg/appsmith#22449]

**Comment by laveena-en** [comment]
Issues with header:

1. Can we move pop up position to the left. The right end is getting clipped 
![image](https://user-images.githubusercontent.com/109572422/233829654-0b61aa41-d3be-4c61-8eff-a555a82f5653.png)
2.Hover state should not be present for the user details since it isn’t a clickable element
![image](https://user-images.githubusercontent.com/109572422/233829667-7a8cc254-1890-4388-8f4b-d8fb93bab08f.png)
3. Cursors aren’t as per release: Ideally it must be pointer cursor on hover, default cursor on profile image and text cursor on user details https://www.loom.com/share/8b9204f304814d309ab97df5ff8cb328. Also should we change the tooltip over profile image to be Your account as on release?
4. Preview is disabled 
![image](https://user-images.githubusercontent.com/109572422/233829682-6340c990-8824-4647-8004-ea06354f1c8b.png)
5. Tooltip is seen as soon as the app is deployed and isn’t getting dismissed. Also do we need this tooltip as we don’t have it on prod/release 
![image](https://user-images.githubusercontent.com/109572422/233829699-8282c795-bdd7-465e-a939-fb524500f717.png)
6. Hover state and tooltip are missing over renaming the app
7. Toast texts are broken on undo and redo actions
![image](https://user-images.githubusercontent.com/109572422/233829730-312ed507-9294-4df6-b108-bc561224e2df.png)
![image](https://user-images.githubusercontent.com/109572422/233829736-d337671a-f7f6-4830-b3bb-5879732763d2.png)
8. Arrow for close side bar should turn towards the left 
![image](https://user-images.githubusercontent.com/109572422/233829764-f29e1abb-33ee-41bf-884b-2d5afbd283f4.png)
9. Arrow for lock sidebar open should turn towards the right
![image](https://user-images.githubusercontent.com/109572422/233829775-a0539135-236a-4682-b217-1f56f4efa6a3.png)
10. Sub menus aren’t getting dismissed on moving away https://www.loom.com/share/4e8e0907515644c7a4d8553a6b787a1a
11. Extra padding is seen on deleting an application
![image](https://user-images.githubusercontent.com/109572422/233829799-2d282680-b2e5-45f9-85fc-bc387f7817e8.png)
12. Unable to scroll to the bottom of the list 
![image](https://user-images.githubusercontent.com/109572422/233829814-1c42e16b-2e1f-4ce4-b165-43b423c80d28.png)
13. Can we add a hover state to reset filter 
![image](https://user-images.githubusercontent.com/109572422/233829834-41755f1c-b5da-4fdc-97a0-4907fc157740.png)
14. The right icon is different from release, is this intended?
![image](https://user-images.githubusercontent.com/109572422/233829847-68b6a2da-ed28-4e61-9db5-f7ca61dc0340.png)
![image](https://user-images.githubusercontent.com/109572422/233829856-b7d42101-7e7b-4351-841b-b1fd495d532b.png)
