### ISSUE TITLE
[Feature] Ability to hide pages in publish mode

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#2244]
## Summary
Need a way to hide pages and not show them in the page tabs on the published mode

## Motivation
- Hide WIP pages
- Don't show certain pages before auth

**Comment by hetunandu** [comment]
@mohanarpit We will need a new property in the Pages object

**Comment by mohanarpit** [comment]
@trishaanand Can you please add a property called `isVisible` to the Pages object? Also, when defining this field, is it possible for us to keep in mind the scenario that in the future, this field can be set via a dynamic binding?

**Comment by areyabhishek** [comment]
Is this the same as: https://github.com/appsmithorg/appsmith/issues/1092?

**Comment by mohanarpit** [comment]
It is similar-ish. #1092 is a full implementation for dynamic visibility of the page. This issue is a simpler form with static true/false rules which will help users decide visibility. There is no dynamic binding or code level decision making supported here.

**Comment by trishaanand** [comment]
Since pages' dynamic bindings are resolved by the client, should I introduce this field as String under layout? In that case, the responsibility of understanding this would rest on the client. As String, it would be able to store boolean as well as dynamic bindings.
One major problem that I see with this as of today is that the client reads from different APIs to ascertain the page names and page DSL. When fetching the page layout, you would find out about the visibility of the page. When fetching the application, we find a list of all the pages with their names and if the page is default. We need to be cognizant of this to ensure a bug free implementation.

**Comment by sharat87** [comment]
@Nikhil-Nandagopal, this is completed right?

**Comment by Nikhil-Nandagopal** [comment]
Yup!
