### ISSUE TITLE
[Bug]: Air gapped instance - Audio and Video widget brings up Please provide a valid url message.

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I dnd an Audio widget, it brings up Please provide a valid url message.

### Steps To Reproduce

1. Pull the image docker pull sangeethsivan/appsmith-multiarch:airgap
2. Now switch off the internet and do a docker run
3. Setup the instance
4. Go to the application and drag and drop an audio widget. It shows "Please provide a valid url" message. The link in the URL - http://localhost/birds_chirping.mp3 - is this.
5. Similar issue observed for video widget also. 
<img width="921" alt="Screenshot 2023-04-17 at 5 24 36 PM" src="https://user-images.githubusercontent.com/101863839/232478452-eebf3de4-b980-4f14-b84a-c7b924b1bc68.png">

### Environment

Release

### Version

Self Hosted

**Comment by berzerkeer** [comment]
It will work if we pass a valid url , since its localhost it is not working. It expects a URL which has `.com, .whatever` after the domain. So since lochalhost doesn't have one it didn't work. 

https://user-images.githubusercontent.com/74818788/232967699-ed5af4a6-7703-4b21-bd79-dc1de3b8ca19.mov

Here is a screen recording of the same thing on `dev.appsmith.com` since its dev.appsmith.com a valid url it will work. And we put the current origin as the default URL.
So let me know if we still need to solve for this , meaning should I just allow any urls even when it doesn't end with a valid extension like .com etc. @infinitetrooper

**Comment by infinitetrooper** [comment]
Not an issue, this is a widget-level requirement, it's up to the user to use the correct URL. Closing this as this is working for a local valid URL.
