### ISSUE TITLE
[Bug]: AirGappedinstance - Chart widget - FusionCharts clickable link present 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#22522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I drag and drop a chart widget, I see a Fusion Charts clickable link in the widget. This is not present in release.

### Steps To Reproduce

1. Pull the image with the command docker pull ankitakinger/appsmith:airgap
2. Switch off internet and execute the docker run command
3. Now do the set up
4. Add air gapped license key
5. Go into the application and drag and drop a chart widget
6. Note that a link is present in the widget "Fusion Charts Trial" - This overlaps the chart widget text. Also, this link is not present in release.
 
<img width="726" alt="Screenshot 2023-04-18 at 7 11 58 PM" src="https://user-images.githubusercontent.com/101863839/232797773-cfabcee9-b3aa-448c-aa1f-639d436e2c31.png">

<img width="773" alt="Screenshot 2023-04-18 at 7 12 05 PM" src="https://user-images.githubusercontent.com/101863839/232797114-5a3a5375-877a-4c2e-91ae-747aae36a70c.png">

### Environment

Release

### Version

Self Hosted

**Comment by berzerkeer** [comment]
This is expected AFAIK. So the fusion charts needs a license key to hide the `Fusion charts Trial` thing. And we only burn in the license key when the image is built on CI. Since we are currently building the docker image locally without the license key, you are seeing this. This is not an issue. 

cc: @infinitetrooper @sharat87 @abhvsn

**Comment by btsgh** [comment]
Tested and works fine in the latest appsmith pull built on CI
