### ISSUE TITLE
[Bug]: App becomes very slow when typing text in widgets

### ISSUE THREAD

**Issue by timdid** [appsmithorg/appsmith#22527]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

Issue : At first glance the app seems to be working good. But whenever you start typing a few texts it becomes very slow and it is slower and slower the more you type text in input fields or in richtext editor (or even when you select dropdown menu).

### Steps To Reproduce

- Create an app with a list widget that fetch data from API Query
- Populate the list widget with container widget that contains itself a few widgets (6-10 inputs, checkboxs, dropdown menus...)
- On production, try to write at human pace (fast one) some texts in inputs, rich text editor.. Slow typing often happens when you try to type in a widget of first list's item then quickly try to type in other item's widget

### Public Sample App

https://app.appsmith.com/app/outils-xmind-copy/gamemap-643ea052687d2c3120d3d653

### Environment

Production

### Issue video log

https://www.loom.com/share/61b6f6ebfb2741cc9f04668a1d8d1d91

### Version

Cloud - Appsmith v1.9.15-SNAPSHOT

**Comment by rajatagrawal** [comment]
@timdid 

Thank you for reporting the issue. We are sorry that you have to facing this issue.

We have tried to triage the performance profiles that you have attached and also tried to reproduce this issue on a dev setup, but however we have been unable to get the performance hit that you are experiencing.

We think that this is a really important issue that needs to be fixed. Would you mind giving us an edit access to this app so that we can closely inspect the app setup and try to find out the cause of the issue ?

You can share the app to `support@appsmith.com`. Thank you for your understanding and patience.

cc : @somangshu @ashit-rath

**Comment by timdid** [comment]
Hi @rajatagrawal,

Thanks for your feedback, I just shared access to support@appsmith.com right now.

To reproduce the issue, I type text in a field then quickly click on another field where I also type text then I click on another field again and after 5 or 6 times the app becomes very slow.

**Comment by rajatagrawal** [comment]
Created a sample app that repros this issue on prod setup but not on dev setup 
[Untitled application 2 (1).json.zip](https://github.com/appsmithorg/appsmith/files/11350899/Untitled.application.2.1.json.zip)

**Comment by rajatagrawal** [comment]
@timdid This bug has been fixed and released in the latest build. Please verify that it is fixed for you as well and let us know as well.

You can also stop sharing the app with us on `support@appsmith.com` if the bug is fixed for you. Thanks!

**Comment by timdid** [comment]
Thanks @rajatagrawal, the issue is totally fixed ! 👏
