### ISSUE TITLE
[Bug]: Sentry exception in ApiPaneSagas.ts APPSMITH-5HD

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#22944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/3796595216

### Steps To Reproduce

NA

### Environment

Production

### Version

Cloud

**Comment by sneha122** [comment]
Related issue: https://github.com/appsmithorg/appsmith/issues/19214

**Comment by sneha122** [comment]
The above sentry error occurs because when we use curl import to create API, headers are not present like shown below:
<img width="797" alt="Screenshot 2023-05-29 at 12 44 29 PM" src="https://github.com/appsmithorg/appsmith/assets/30018882/1c3c0f9c-4a3b-44de-8fd8-035df93f0ce9">
which eventually causes one of the functions in ApiPaneSagas to throw this error.

While investigating the issues, I found a couple of inconsistencies and wanted to know if there was any reason for designing action apis in such way:
1. When we create a new REST API, the action creation post api request looks as below, and we can see that headers is sent as empty key value pairs. Is there a reason why we store these empty key value pairs for headers, should we not remove it while calling action creation api? Now in contrast if we observe the action updation put api, we remove these empty key value pairs for both headers and queryParameters, shouldn't this behaviour be consistent with action creation api?
<img width="1181" alt="Screenshot 2023-05-29 at 12 46 52 PM" src="https://github.com/appsmithorg/appsmith/assets/30018882/8b0110e7-c642-4fb1-a776-cfbb6fae8a32">
<img width="1178" alt="Screenshot 2023-05-29 at 12 48 43 PM" src="https://github.com/appsmithorg/appsmith/assets/30018882/aa959575-9ded-41f3-8550-a5468ce21f5a">


2. When we use curl import, the request response looks like below, as we can see there is no headers property present in `actionConfiguration` but queryParameters is present with empty array, is there any reason headers is not present at all?
<img width="1046" alt="Screenshot 2023-05-29 at 12 52 07 PM" src="https://github.com/appsmithorg/appsmith/assets/30018882/4ccb0ee0-0056-4f0b-a41f-84656c2ad24a">


Solution:
- In order to fix the sentry issue, we may have to pass headers as [], in case of curl import, when no headers are present in curl request, so that frontend can populate the headers section with default values.


CC: @sumitsum @AmanAgarwal041 @Irongade

**Comment by AmanAgarwal041** [comment]
> The above sentry error occurs because when we use curl import to create API, headers are not present like shown below: <img alt="Screenshot 2023-05-29 at 12 44 29 PM" width="797" src="https://user-images.githubusercontent.com/30018882/241670831-1c3c0f9c-4a3b-44de-8fd8-035df93f0ce9.png"> which eventually causes one of the functions in ApiPaneSagas to throw this error.
> 
> While investigating the issues, I found a couple of inconsistencies and wanted to know if there was any reason for designing action apis in such way:
> 
> 1. When we create a new REST API, the action creation post api request looks as below, and we can see that headers is sent as empty key value pairs. Is there a reason why we store these empty key value pairs for headers, should we not remove it while calling action creation api? Now in contrast if we observe the action updation put api, we remove these empty key value pairs for both headers and queryParameters, shouldn't this behaviour be consistent with action creation api?
> 
> <img alt="Screenshot 2023-05-29 at 12 46 52 PM" width="1181" src="https://user-images.githubusercontent.com/30018882/241671240-8b0110e7-c642-4fb1-a776-cfbb6fae8a32.png"> <img alt="Screenshot 2023-05-29 at 12 48 43 PM" width="1178" src="https://user-images.githubusercontent.com/30018882/241671753-aa959575-9ded-41f3-8550-a5468ce21f5a.png">
> 2. When we use curl import, the request response looks like below, as we can see there is no headers property present in `actionConfiguration` but queryParameters is present with empty array, is there any reason headers is not present at all?
> 
> <img alt="Screenshot 2023-05-29 at 12 52 07 PM" width="1046" src="https://user-images.githubusercontent.com/30018882/241672486-4ccb0ee0-0056-4f0b-a41f-84656c2ad24a.png">
> Solution:
> 
> * In order to fix the sentry issue, we may have to pass headers as [], in case of curl import, when no headers are present in curl request, so that frontend can populate the headers section with default values.
> 
> CC: @sumitsum @AmanAgarwal041 @Irongade

I think we need to add the support for the headers resolution from curl command to api action. Can we close the duplicate issue ? @sneha122

**Comment by rohan-arthur** [comment]
less than 300 events, won't fix
