### ISSUE TITLE
[Bug]: Country flag emojis are not working in chromium browsers on windows for airgapped instances

### ISSUE THREAD

**Issue by berzerkeer** [appsmithorg/appsmith#23092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we use phone input or currency input widget, the country flags are not displaying.

### Steps To Reproduce

1. Pull appsmith airgap image
2. Run it on a chromium browser on windows
3. Drag and drop phone input widget or currency input widget
4. The flags won't get displayed, it will just be the country code.

### Environment

Release

### Version

Self Hosted - 1.9.18

**Comment by Harshask93** [comment]
The issue is resolved for "Phone number" widget however the observation is still made for "Currency" field. Please refer the attached screenshot.

Observation is made on chromium, chrome and firefox browsers. 
The behaviour is same on the release app aswell.

![Airgap](https://github.com/appsmithorg/appsmith/assets/132880870/7f4a3167-b2ce-4c36-b2d9-a713b561b608)
