### ISSUE TITLE
[Bug]: Container need python requests module for supervisor event listener

### ISSUE THREAD

**Issue by sh-TU** [appsmithorg/appsmith#23154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Containerized install are stuck in Appsmith is starting page due to an error in `supervisor_event_listener.py`. It cannot find request module to perform a healthcheck. 

```bash
root@b44368b2d405:/opt/appsmith# tail -f /appsmith-stacks/logs/appsmithctl/eventlistener.log
    from requests.exceptions import ConnectionError
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/opt/appsmith/supervisor_event_listener.py", line 1, in <module>
    from requests.exceptions import ConnectionError
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/opt/appsmith/supervisor_event_listener.py", line 1, in <module>
    from requests.exceptions import ConnectionError
ModuleNotFoundError: No module named 'requests'
```

### Steps To Reproduce

1. Update Appsmith to v1.9.17
2. docker-compose up

### Environment

Release

### Version

Self Hosted - CE v1.9.17

**Comment by sharat87** [comment]
Hey @sh-TU, thank you for raising this, sorry for the trouble here. Can you confirm what host platform you are running on? I tried running the `appsmith/appsmith-ce:v1.9.17` image locally, and I don't see this error, and the `requests` package is indeed available. Can you also confirm if the package `certbot` is installed in your container? Asking because that's what depends on `python3-requests`, and that's where we get it from. You can check this by running `docker-compose exec appsmith apt -qq list certbot`.

**Comment by sharat87** [comment]
Hey @sh-TU, when you get a chance, can you share details requested above please? 🙏
