### ISSUE TITLE
[Bug]: Slow JS saves on property bindings and JSObjects

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#23213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I write a 45-line JS expression to return a formatted string with dynamic values, I experience slow saves and sometimes failures in saving. This is experienced both on the property pane and JSObject.

### Steps To Reproduce

[Instructions](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1683793508379439?thread_ts=1683793272.987829&cid=C02K0SZQ7V3)

### Environment

Production

### Issue video log

https://www.loom.com/share/c0244cd33c47447d987523edc94fd807

### Version

Cloud

**Comment by bharath31** [comment]
@Druthi could you please add an RCA here? Also, will the fixes go out in v1.9.21? Asking because we need to communicate this to the user.

**Comment by bharath31** [comment]
@Druthi could you please add an RCA here? Also, will the fixes go out in v1.9.21? Asking because we need to communicate this to the user.

**Comment by Druthi** [comment]
So this is an issue where the UI was updating the wrong message while in the background the operation was happening successfully. 

When we have multiple update calls fired, 
1. we cancel any previous update calls that are made and that did not get resolved yet 
2. the latest update api call updates the backend and gets resolved and the latest state is saved. 

However, in our case, whenever a call was cancelled, instead of showing `saving` state in the UI it would show `save failed` even though the latest update call is fired and getting resolved. 

Therefore, I made a fix to not show the `save failed` when we cancel a call.

**Comment by Druthi** [comment]
And yes it would go out in ` v1.9.21`
