### ISSUE TITLE
[Feature] storeValue needs a callback function

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#2334]
Steps to reproduce:

set on click method of a button to following:

```
{{
(() => {
 storeValue("someValue","Pawan");
console.log({ appsmith.store.someValue });
)()
}}
```

The console gives the value "undefined".

Sometimes, we want to clear/reset values in store and want to run an API after clearing. Since storeValue is an async function, we can't use API right away. For e.g:

```
 {{
    (() => {
      storeValue('offset','');
      API_Issues.run(() => storeValue('offset',API_Issues.data.offset), () => {});
    })()
    }}
 ```
 
 Is it possible to do something after value is updated in store?

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu is storeValue async? We should update the docs and provide callbacks if this is the case

**Comment by hetunandu** [comment]
It is async in the same way all trigger actions are async like navigate and download. 

Trigger actions dont get executed in the evaluation context. Their payload is sent back and then executed down the line.

The reason console.log does not work as expected in the above example is because storeValue trigger has not yet be executed and console log is called before it.

We should update the documentation but as I mentioned above similar problem would occur for all kinds of trigger actions and we should document this as a global action level concept.

We should also think of the callback signature that works for all such actions as well

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu 
another reason to do object-based signatures since it will be cleaner when there are 4 - 5 args like this

**Comment by hetunandu** [comment]
Fixed this by making the store value sync
