### ISSUE TITLE
[Task]: Fix path for cypress binary for running cypress test suite locally

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#23428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

`yarn install` isn't able to symlink cypress binary to `node_modules` folder inside `app/client` folder. Thus a developer is unable to run `yarn run cytest` command to run the cypress test suite.

`yarn install` should ideally create a binary for cypress inside `node_modules` as it is added as a dependency in package.json file.

Currently, cypress may have been installed globally on developer system which might be getting invoked when a developer runs `yarn run cytest`.

A new developer who setups up their project from scratch won't be able to run the test suite locally since cypress binary is unavailable in node_modules folder inside client folder.

To find out if cypress is installed globally, run : `npm list -g | grep -i cypress`

Check this link for documentation of workspaces setup for npm packages : https://classic.yarnpkg.com/lang/en/docs/workspaces/

Sample project to demonstrate cypress binary working in workspaces setup

[workspace-exp.zip](https://github.com/appsmithorg/appsmith/files/11496573/workspace-exp.zip)

**Comment by KelvinOm** [comment]
After merging [this PR](https://github.com/appsmithorg/appsmith/pull/23395), cypress became available from the client folder. Therefore, I would suggest closing this ticket. But we definitely need to move cypress to packages so that everything works according to the general rules of the workspace. This way we can clear the root `package.json` from cypress dependencies, optimise the script launch for tests and make our code base a bit cleaner. 

Let's get a separate ticket for this.

@rajatagrawal @SatishGandham

**Comment by rajatagrawal** [comment]
As per @KelvinOm 's comments, closing this ticket.
