### ISSUE TITLE
[Bug]: Failed to excute function when JSboject is deleted

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#23494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On page load function is added on page, Delete the JSobject after single run, Navigate from one page to another error is displayed that Filed to execute function - 

https://github.com/appsmithorg/appsmith/assets/80756091/8dc04bf5-6a7a-4db8-b93b-886961bd25a1

### Steps To Reproduce

1. Add app
2. Add below code with setting as "Onpage load" = Yes
3. Create another Page and copy the JSobject from one page to another, Update the setting as Onpage load Yes
4. Verify Function runs on Page load
5. delete the copied JSobject and Navigate from One page to another - error is displayed 

### Environment

Production

### Version

cloud

**Comment by bharath31** [comment]
@AnandiKulkarni could you please add a loom video?

**Comment by bharath31** [comment]
@Druthi could you please run an RCA here? We're trying to execute a deleted function onPageLoad

**Comment by Druthi** [comment]
Sure taking a look!

**Comment by Druthi** [comment]
Looked into this. There seems to be two 
1. A null check is missing in case the collection is not found which is causing the error to be thrown
2. The pageActions still has a collection even though the collection was deleted. 

Will pick these up and fix the issues.

**Comment by subrata71** [comment]
## RCA
The issue is happening for JS objects only. When we delete a query or an API, we update the layout DSL upon successful deletion of the query or API. In this process, the `layoutOnLoadActions` attribute of the respective page is also updated accordingly. Thus it doesn't keep storing **stale/invalid** action references in the `layoutOnLoadActions` attribute.

In case of deleting a JS object, we don't update the layout DSL and that's why the state reference is present in `layoutOnLoadActions` attribute.

### Workaround 
If the user falls into such an issue, one way to overcome it is to make any change (e.g. resize a widget) in the respective page which basically triggers an update layout call from the client side. After the successful update layout call, the stale references from `layoutOnLoadActions` attribute would be removed.

cc: @riteshkew 

TODO: Add a Loom video to demonstrate the workaround

**Comment by Druthi** [comment]
@subrata71 Thanks for the RCA!

Quick question on the workarounds
1. Can we not update the DSL when a Js object delete operation is done?
2. If the 1st is not possible, can the front just trigger the updateLayout call right after the Js object delete api is called to solve for the above issue?

**Comment by subrata71** [comment]
Hey @Druthi 
> 1. Can we not update the DSL when a Js object delete operation is done?

I would like to request @riteshkew to take the request with respect 1.

> 2. If the 1st is not possible, can the front just trigger the updateLayout call right after the Js object delete api is called to solve for the above issue?

Yes, that will solve the problem and it seems like an easier way to tackle this problem.

**Comment by ramsaptami** [comment]
Is the solution here going to fix #21189 as well? The issues seem similar 
cc: @Druthi

**Comment by Druthi** [comment]
Yes! Looks like the same issues.

**Comment by ramsaptami** [comment]
Could we, in that casem cover the additional scenarios mentioned in that bug and add it to the fix list @Druthi ?

**Comment by Druthi** [comment]
Do you mean adding it to the PR description?
