### ISSUE TITLE
[Bug]: S3 account credentials in Fundraising CRM no longer valid

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#23591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The Conversations page throws this error when you list the records from the S3 datasources

`InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`

https://theappsmith.slack.com/archives/C02RCR2PURZ/p1684748418305929

### Steps To Reproduce

na

### Environment

Production

### Version

v1.9.20

**Comment by abm17** [comment]
This is blocked as currently the S3 datasource needs the ListBuckets permission. However, since the bucket we use as the mock datasource resides in our main AWS account, we can't grant this permission.
So we can do one of the following:
- Set up the mock bucket in a different AWS account
- Remove the List Buckets permission from the configuration check
