### ISSUE TITLE
[Enhancement] Allow dynamic bindings inside datasources

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#2372]
## Description

Users need a way to send accessTokens from the store along with every API call to a particular domain.
This should ideally be a part of the datasource so that all APIs can be authenticated

**Comment by trishaanand** [comment]
Note : Today, backend supports any moustache binding replacements inside datasourceConfiguration object. As long as the new flow uses the datasourceConfiguration object to store any dynamically bound relationship, this should work out of box.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand but the replacement needs to happen at the time of action execution. i.e datasource has 
key                          value
accessToken       {{appsmith.store.accessToken}}

Now this needs to be returned in every action this datasource is tagged in and should be replaced with the correct value at the time of execution of the action

**Comment by trishaanand** [comment]
So, I see two changes required for this :
1. For actions, when we compute the dynamic binding keys, we should also include the datasource's because today, we ONLY store the dynamic bindings used in the action.
2. The client uses the above list to set execute action parameters including the datasource dynamic bindings. The current execute function already takes care of replacing with the values for both action and its underlying datasource. Once it starts sending the datasource keys and values as well, this would work without any changes.

**Comment by Nikhil-Nandagopal** [comment]
Closing this since it apparently works but there is a minor bug on the client which confuses this

**Comment by Nikhil-Nandagopal** [comment]
Opened another issue for this bug #2373
