### ISSUE TITLE
[Bug]: Git connected apps containing datasource & queries, shows uncommitted changes with all datasource and queries modified

### ISSUE THREAD

**Issue by Parthvi12** [appsmithorg/appsmith#23822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 Git connected apps on release which contain datasources & queries, shows uncommitted changes with all the datasource & queries modified , ideally if users have not made any change to the app we should not show these changes, or should notify them about the migration/appsmith related changes.
<img width="1440" alt="Screenshot 2023-05-29 at 12 39 28 PM" src="https://github.com/appsmithorg/appsmith/assets/80334441/1f7b0049-c98a-4b17-b4ab-2bc6f469d91a">
 
Commit : https://github.com/Parthvi12/testGitMigration/commit/46d009b72010934938f5b12eded3513b8bb3079d

### Steps To Reproduce

1. Open any git connected app with datasource and queries on release.
2. Observe it shows uncommitted changes in git sync modal with all queries and datasource modified.

### Environment

Release

### Version

Release

**Comment by gzarruk** [comment]
We are also experiencing this every day and is preventing us from deploying to different environments in a an efficient way. 
We have to disconnect to GIT and then reconnect in order to have the latest changes pulled. 
This became a critical roadblock for our team. 

Is there a timeline to fix this bug?
