### ISSUE TITLE
[Bug]: buttongroup - Invalid url displayed while navigating from debugger for buttongroup widget

### ISSUE THREAD

**Issue by AnandiKulkarni** [appsmithorg/appsmith#24201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add buttongroup and add action - setinetrval -console log
Verify the log and navigate to button group from link provided in debugger - error is displayed

https://github.com/appsmithorg/appsmith/assets/80756091/49708404-423b-4209-ba95-0fd783f24454

### Steps To Reproduce

1. Add buttongroup 
2. Add Setinterval => setinterval(()=>{console.log("test")}) for Add 
3. Click on add and verify log in debugger
4. Click on buttongroup link to navigate to button group

Error is displayed

### Environment

Production

### Version

cloud

**Comment by dhruvikn** [comment]
## Findings after triaging the issue - 

We have the following types of links in the debugger mentioned at `appsmith/app/client/src/components/editorComponents/Debugger/EntityLink.tsx`
```js
const entityTypeLinkMap = {
  [ENTITY_TYPE.WIDGET]: WidgetLink,
  [ENTITY_TYPE.ACTION]: ActionLink,
  [ENTITY_TYPE.DATASOURCE]: DatasourceLink,
  [ENTITY_TYPE.JSACTION]: JSCollectionLink,
};
```

In the case of a regular widget action that is logged, we have EntityLink's prop type set to ENTITY_TYPE.WIDGET

![CleanShot 2023-06-21 at 16 19 53@2x](https://github.com/appsmithorg/appsmith/assets/22471214/589ec50d-1bdc-4bd3-bf4e-0d391369e448)

However, in case of this log triggered by an action, we have EntityLink's prop type set to ENTITY_TYPE. JSACTION

![CleanShot 2023-06-21 at 16 20 20@2x](https://github.com/appsmithorg/appsmith/assets/22471214/50b13dcf-c382-41d7-9b05-5f709cdc8733)

The type should have been ENTITY_TYPE.WIDGET here since we want to navigate to the widget, not a JS object. Because of this, we are appending "jsObjects" in the URL instead of "widgets".

![CleanShot 2023-06-21 at 16 24 52@2x](https://github.com/appsmithorg/appsmith/assets/22471214/0992363f-00fd-4a5a-bd6f-007a81a9c3bd)

![CleanShot 2023-06-21 at 16 25 38@2x](https://github.com/appsmithorg/appsmith/assets/22471214/3587d768-4dc7-4ec5-8277-4300aa2793e2)

**Comment by dhruvikn** [comment]
Hey @bharath31, please take a look at this issue. We have triaged it and posted our findings above. Thanks!

**Comment by dhruvikn** [comment]
PS - The issue can also be replicated on other widgets such as the button or a checkbox. It does not only exist in the button group. Video log here - https://lcixo7xrxt.vmaker.com/record/FlgzdtHYeWibJZIZ

**Comment by bharath31** [comment]
@dhruvikn thanks for sharing your findings! 

@Rishabh-Rathod could you please investigate the root cause for this issue?

**Comment by rohan-arthur** [comment]
this is not reproducible anymore
