### ISSUE TITLE
[Enhancement]: Fix UX issues on the Action Selector

### ISSUE THREAD

**Issue by bharath31** [appsmithorg/appsmith#24251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Feedback from @aakashDesign 
- I had trouble spotting the OnClick(JS) section on the button widget. This could be because on every other widget the action selector is under the Events accordion. This is breaking the property pane information architecture.
- For a button, the default state could be the "No action selected" state. The Plus icon is useless here as you can only add one event to a button.
- Once the widget is selected, callbacks aren't visible till the user clicks on Event card. Could this be a discovery bottleneck?
- Can we mark the Params input as optional? In my case, I did not need params to run a query but it caused confusion.
- The event card is missing a hover state.

Feedback from @ramsaptami 
User flow should instead be augmented to:
- First click on parent action: unfurl callback showing onSuccess/onFailure titles with total count under each action and make the title elements clickable
- Second click on either success or failure child action: unfurl only the section selected by the user

### Steps To Reproduce

- 

### Environment

Production

### Version

Cloud
```[tasklist]
### Tasks
- [ ] https://github.com/appsmithorg/appsmith/issues/22223
```

**Comment by ayushi-appsmith** [comment]
@aakashDesign Thank you for the feedback.
1. "I had trouble spotting the OnClick(JS) section on the button widget. This could be because on every other widget the action selector is under the Events accordion. This is breaking the property pane information architecture." - @momcilo-appsmith this was done in accordance with the property pane structure discussed earlier. Any thoughts?
2. "For a button, the default state could be the "No action selected" state. The Plus icon is useless here as you can only add one event to a button." - You can add more than one action to an event like onClick. The plus icon was put in place so that the user can follow the same pattern when adding another action to the same event. We can start with a blank 'no action' block along with the plus icon, the tradeoffs then would be: (a) Clutter in an already full property pane. (b) User not being able to discover the plus button as the first step and may not knowing that more actions can be added on clicking plus. (This is an assumption that can be tested) @bharath31 
3. "Once the widget is selected, callbacks aren't visible till the user clicks on Event card. Could this be a discovery bottleneck?" - Great catch! I've updated a prototype [here](https://www.figma.com/file/H0JoYA4tmfc5pVOcbnC0Ga/Action-Selector-redesign-2?type=design&node-id=4780%3A430202&mode=design&t=RUSOI4Cycs6g03VT-1)
4. "Can we mark the Params input as optional? In my case, I did not need params to run a query but it caused confusion." - Yes, this is the ideal behaviour. View updated screen [here. ](https://www.figma.com/file/H0JoYA4tmfc5pVOcbnC0Ga/Action-Selector-redesign-2?type=design&node-id=4783%3A427105&mode=design&t=RUSOI4Cycs6g03VT-1)
5. "The event card is missing a hover state." - Added the updated [action block component here](https://www.figma.com/file/H0JoYA4tmfc5pVOcbnC0Ga/Action-Selector-redesign-2?type=design&node-id=4742%3A413043&mode=design&t=RUSOI4Cycs6g03VT-1), please try changing the component in figma to see its various states.

@ramsaptami that's a good idea! I've explored [unfurling actions here.](https://www.figma.com/file/H0JoYA4tmfc5pVOcbnC0Ga/Action-Selector-redesign-2?type=design&node-id=4780%3A430202&mode=design&t=RUSOI4Cycs6g03VT-1) Let me know if this interaction is any easier?

**Comment by ramsaptami** [comment]
@ayushi-appsmith can we list number of actions under success and error blocks and unfurl only either success or error depending what the user chooses

Essentially, the flow would be:
**adding points only and not design aspect assuming 4 interactions under each section**
1. Opening property pane shows parent block with `Callbacks 8nos`
2. Clicking on callback, unfurls to show `on success 4` and `on failure 4`
3. Clicking on success, unfurls to show 4 child actions
4. Clicking on success again, collapses `on success`
5. Similarly, clicking on error, unfurls to show 4 child actions on error etc...

Point is that, currently with the example of 8 child actions, clicking on callback causes all 8 to be displayed when users' intention could only be to view `onFailure` block but needs to scroll past `onSuccess` configuration to get there.

**Comment by ayushi-appsmith** [comment]
@ramsaptami let's collect more user data before we take this up as hiding the onSuccess and onFailure blocks behind a click is useful if the number of callbacks are mostly high. However, it will be annoying if users generally add only a few callback actions.

**Comment by bharath31** [comment]
the UX issues have been fixed. tacking callback configuration on #27235
