### ISSUE TITLE
[Bug] A query with the Mock Database fails to execute

### ISSUE THREAD

**Issue by akash-codemonk** [appsmithorg/appsmith#2426]
## Description

Running a query with the default "Mock Database"(which exists while signing up) fails to execute. 

<img width="938" alt="mockdb" src="https://user-images.githubusercontent.com/67054171/103514570-e63ed000-4e92-11eb-999e-d5d0e585b2c2.png">

### Steps to reproduce the behaviour:
1. Signup
2. Edit Application
3. Run existing query
4. The error `Failed to initialize pool: FATAL: remaining connection slots are reserved for non-replication superuser and rds_superuser connections` is shown.

Running a query with any other postgres datasource seems to work fine.

**Comment by mohanarpit** [comment]
This happened because the number of connections to the Mock database spiked. We've done the following: 
1. Increased the max connections on the Mock database to ensure that Appsmith Cloud stays under the limit. 
2. Limited the number of concurrent connections created by the Hikari connection pool for a particular datasource to 5. 

Closing this issue now. Will re-open if this surfaces again.
