### ISSUE TITLE
[Bug]: Table default selected index doesn't show up when generate CRUD app feature is used with TableV2

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#24344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This issue is required for unblockling CRUD TableV2 PR.

### Steps To Reproduce

1. Generate a CRUD app using GenerateCRUDApp feature using TableV2.
2. Notice that the default selected index row at default selected index doesn't show up.

Expected behavior : The default selected row should show up.

This issue can be tested using cypress tests that are present. It may be difficult to verify this manually in QA Process since CRUD TableV2 changes aren't merged into release yet cc : @laveena-en 

### Environment

Production

### Version

Cloud

**Comment by keyurparalkar** [comment]
@rajatagrawal While running the test it is observed that `MySQL2_spec.ts` is failing. It is failing because once the row is deleted, it is expected that the default row should get selected but that's not happening. Once the row is deleted the selected row persists.

**Comment by keyurparalkar** [comment]
@rajatagrawal I have checked all the spec files that are failing in the cypress run: https://cloud.cypress.io/projects/eyxvp8/runs/8dfdb242-d42d-4b3e-a046-68b075277e5f/test-results/916e8664-122e-4122-90e2-56ee425fac9d

The issue mentioned in the above comment exists on `MySQL2_spec.ts` and `Postgres2_Spec.ts` i.e. the selected row is getting persisted. 

Rest all the specs files are failing due to unable to create Mongo as a data source, flakyness and needs some changes in the spec file itself.
