### ISSUE TITLE
[Bug]: Code scanner camera is not operating when user switches from laptop camera to code scanner camera

### ISSUE THREAD

**Issue by kavitasmoolya** [appsmithorg/appsmith#24379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Code scanner camera is not operating when user switches from laptop camera to code scanner camera.

Expected Result  : Code scanner camera should be functioning once we close the system (laptop) camera.

 EE DP: https://ee-1615.dp.appsmith.com/

### Steps To Reproduce

**Steps to reproduce :** 

- Add code scanner widget to the canvas
- Click on scanner > camera opens up >  close the camera from canvas
- and open camera in the system (laptop) and go back to the appsmith canvas and click scanner >> it says camera cant be open up which is expected
- Now close laptop camera and go back to appsmith and click scanner >> It still says camera cant be open up.

Issue ref screen shot : 
![image](https://github.com/appsmithorg/appsmith/assets/134914630/e9c59fb5-d735-40f9-95bd-652408798941)

Actual result : Code scanner camera shows error message "could not start video source"

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.22-SNAPSHOT

**Comment by kavitasmoolya** [comment]
@dilippitchika please find the recording video where code scanner widget camera is not refreshed automatically when system camera is turned off.
 
[screen-capture (2).webm](https://github.com/appsmithorg/appsmith/assets/134914630/147272a0-b196-45cb-a8a4-b522e37b55f7)

do let me know if you need any further details on the same.

**Comment by somangshu** [comment]
@dhruvikn do you have some context here? I remember that we introduced some limitation that comes up with iPhones. 
Cant put my finger on it.

**Comment by upbound-web** [comment]
Yeah I am the user that is having problems on IOS. The issue is you can change camera using the camera icon but when front camera is selected it is still displaying back camera. I have tried on multiple apple devices same issue. I tried in a different online camera display and it allowed me to use the front camera for that

**Comment by dhruvikn** [comment]
I tried to reproduce the issue, but couldn't on my mac. I tried streaming on https://webcamtests.com/ and the Photo Booth app and I was able to stream video in the widget.  [[See video here](https://github.com/appsmithorg/appsmith/assets/22471214/152159c4-caaa-4513-9a14-d2fc37f3d980)] 

On @kavitasmoolya's end, it looks like it could be an issue where the browser isn't able to access the webcam stream when the camera app on Windows is open. The camera app could be disallowing the webcam video stream while it's open. @kavitasmoolya - can you please try to recreate this once again, but this time instead of the camera app, can you open https://webcamtests.com?

Moreover, I'm able to use all the cameras on iOS and they are working as expected. [[See attached video](https://github.com/appsmithorg/appsmith/assets/22471214/a31fcbe1-d090-4442-b226-a6020511e746)]

@upbound-web - Can you please try again on the latest version of Appsmith and share a recording if possible? Also, please share your iOS version and iPhone model.
