### ISSUE TITLE
[Feature]: Database Management features

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith#24476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I just managed to create a Docker container with AppSmith, MongoDB & PostgreSQL and got it running on my private VPS.

But creating databases and tables is another task altogether, which requires one to install a variety of software and libraries. It would be great if AppSmith provided essential support for creating and deleting Databases, Tables, Fields, Records, etc.

This should be provided for all the Data sources natively supported by AppSmith

### Why should this be worked on?

This would give users the ability to manage their database from within Appsmith.

**Comment by yogeshvachhani** [comment]
I read somewhere that is an Admin panel project in AppSmith that allow one to connect and manage MongoDB/Posgres/etc. data.

I think this can be an exercise to build a complete database manager by extending this project so that everyone involved with and using AppSmith can learn from it.

This is just my suggestion. I don't know how practical it is.

**Comment by arumugamtp** [comment]
Ideally, this should be and Admin or equivalent user level feature. Since this feature will have an impact on production, ideally this should have some form of validations, approvals, and pre/post verification steps to ensure only required data gets deleted.

**Comment by Nikhil-Nandagopal** [comment]
This feature has been recorded as #2506. Please leave your comments there
