### ISSUE TITLE
[Bug]: git checkout remote branch is not working

### ISSUE THREAD

**Issue by AnaghHegde** [appsmithorg/appsmith#24485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When checking out. a branch from the remote flow, the create branch flow fails. 

### Environment

Production

### Version

Latest

**Comment by infinitetrooper** [comment]
Customer issue - https://www.loom.com/share/7db448dec2124fd8aa6264c16339ffe0

**Comment by nayan-rafiq** [comment]
Failed to reproduce this. This can happen if the application data is corrupted in the remote. As a result, import application will fail and this can lead to the reported state.

In order to debug what actually happened, we need files from the branch where the problem is there. Also need logs for this.
