### ISSUE TITLE
Default message for when programmatic access control is off

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#24606]
When the Programmatic access control is switched off, we should show the 2 parameters(roles & groups) in `appsmith.user` and for roles and groups show the message ["Enable Programmatic access control in Admin Settings"].

**Comment by trishaanand** [comment]
Context : 

{{ appsmith.user }} object on the client side gets populated with the response of `/users/me` API endpoint.
Also, this feature discovery method should not get exposed on cloud since cloud is supposed to only expose community features. Please use `isCloudHosting` variable available on the backend to track this.

**Comment by trishaanand** [comment]
As part of this issue, lets also make programmatic access control discoverable in Community edition. Lets also introduce roles and groups in Community and add the following message there : "Upgrade to business edition to access roles and groups for conditional business logic"

**Comment by infinitetrooper** [comment]
[Another Customer Confusion](https://app.intercom.com/a/inbox/y10e7138/inbox/conversation/164629100281616?source=Slack-1350cc6546e54c64a9ce5738f559e41e)
