### ISSUE TITLE
[Feature]: User should be able to configure default git branch at the app level

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#24879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

A user wants to use git-sync to facilitate multiple environments. We only support changing the default branch from git-repo and then syncing it back in Appsmith. Although, the user needs to be able to change the default branch at the app level regardless of the default branch set at the repository level.

### Why should this be worked on?

This will allow the user to have different applications - prod, qa, dev with separate default branches.

**Comment by pranavkanade** [comment]
Related article - https://community.appsmith.com/solution/how-change-default-branch-appsmith-app

**Comment by infinitetrooper** [comment]
This is being worked on in the epic #26530

**Comment by rhuanbarreto** [comment]
This is very much important for us! One use case:

We normally merge all things to the `main` branch. But sometimes we need to do a hotfix on it without changing the history of the `main` branch. So we create a `hotfix` branch and we want this branch to be the one that the user launches when they press the "Launch" Button.

This feature of changing the default branch would be very important so we can point the users to the right branch when using the application.

**Comment by infinitetrooper** [comment]
This was released on Appsmith Enterprise v1.9.46

**Comment by rhuanbarreto** [comment]
@Nikhil-Nandagopal any reason this didn't come for business edition as well? We discussed this recently and I was ready to give it a try.

**Comment by Nikhil-Nandagopal** [comment]
@rhuanbarreto I spoke to @infinitetrooper and this feature was planned as part of our epic to support multi-instance deployments for enterprises. I believe your use case was 
- Take the default branch set in the git repository (main instead of master)
- Deploy a hotfix branch of an application

I believe point #1 should be working once you set it in your repo settings.
For point #2:
I think deploying a hotfix branch isn't the purpose of this feature because the URL will change and so users will end up getting confused if they have the application URL bookmarked or they had the application open already.

Is there a reason your hotfix isn't going to the master branch? Because that should solve this problem
