### ISSUE TITLE
[Bug] Circular dependency puts all widgets into an error state

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#2487]
## Description

Reference a widget in its own data field, notice that all other widgets stop working. 

https://www.loom.com/share/de6856014a9e4860b7354322f743110b

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek this is expected because although your video is a simple scenario so it seems like it should only affect that widget, circular dependencies can span across multiple widgets and we don't know how large the cycle is so we have no way to handle it today. Something we can do is have a better UX for this error and highlight the widgets / actions that are part of the cycle and log the cycle in the debugger. 
@hetunandu any other thoughts?

**Comment by hetunandu** [comment]
Since we evaluate the page's layout as a whole and not each widget in sandbox of sorts, this is how it will crash. This is similar to normal programming where they also wont build/compile if there is a circular dependency. As Nikhil said, the best we can do is improve the experience to help a dev resolve this dependency error.

**Comment by areyabhishek** [comment]
Understood. A better experience in the debugger would make sense.

**Comment by areyabhishek** [comment]
A few more questions:
1. Why don't we know how large the circular dependency is? Don't we know the dependencies in each JS function?
2. Why does the entire page get evaluated and reload if I'm only changing one widget's logic which doesn't affect any other widget?

I've seen circular dependencies with spreadsheets, where one error only disables that particular cell but not the entire spreadsheet.

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek 
1. we know how large the dependency is at the time it occurs not before it so we can't add the logic to only disable this widget, we have to disable every item in the circle as well as any item that refers to an item in the circle.
2. This is the problem we're solving with #1841 so that we have performance benefits
