### ISSUE TITLE
Homepage not resetting in scenarios when app was opened from filtered apps

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#24972]
Replication
1. Search for an app on the Appsmith homepage
2. Open the app from searched results
3. Go back to homepage by clicking the homepage button
4. The search is off but, the filtered results still show up

![Capture-2023-06-30-142753.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/3bc3e0d2-33fc-4d8a-8392-db3639e00bd2)![Capture-2023-06-30-142815.png](https://images.zenhubusercontent.com/63971d663d1ad1e0572bf56c/98f44b6c-c6ff-4a79-8f8b-4186d28059b2)

**Comment by RakshaKShetty** [comment]
The issue is not fixed, the filter is retained here wven when i go back but the text is not displayed on the search filed
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/fb9cf73a-f6eb-447e-a280-ab97679f1ad2">

**Comment by ankitakinger** [comment]
@RakshaKShetty seems like release.app.appsmith hasn't been updated since 12 days. Could you test this on release-ee till release.app is updated? It seems to be fixed there.
<img width="447" alt="image" src="https://github.com/appsmithorg/appsmith/assets/28362912/2a906854-2a8e-4675-b7db-d657db17c26e">

**Comment by ankitakinger** [comment]
@RakshaKShetty Could you re-test this on release.app as well? Seems like its updated now.

**Comment by RakshaKShetty** [comment]
This is fixed
