### ISSUE TITLE
[Bug]: Image is not changing its fit on selecting Object fit value in radio group

### ISSUE THREAD

**Issue by kavitasmoolya** [appsmithorg/appsmith#25033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

1. Bind object fit data to radio group button and on selecting AUTO it gives error "unable to load image"
2. Bind object fit data to radio group button and on selecting COVER/CONTAIN option nothing happens

Attached video : 

https://www.loom.com/share/8f00050e667c456bbd544a9ddba9d768?sid=7d2d914f-b089-4353-b703-ab355b12e838

Expected Result : 
On selecting any value (cover/contain/auto) in radio group button, Image should change it's fit accordingly.

### Steps To Reproduce

1. Drag and drop image widget
2. Set` DEFAUTL IMAGE `field = https://assets.appsmith.com/widgets/default.png
3. Drag and drop radio group button
4. Set the values in radio button property as shown below 
![image](https://github.com/appsmithorg/appsmith/assets/134914630/e867bd38-913a-41f9-95e8-b76ba11156fe)
5. Set the `IMAGE` value = {{RadioGroup1.selectedOptionValue}}
![image](https://github.com/appsmithorg/appsmith/assets/134914630/6bc93444-faed-42fd-98a2-59d5a01f4bc6)
6. Now select cover/contain in radio button and observe nothing happens
7. Now select auto in radio button and observe "Unable to load image"

### Environment

Production

### Issue video log

https://www.loom.com/share/8f00050e667c456bbd544a9ddba9d768?sid=7d2d914f-b089-4353-b703-ab355b12e838

### Version

Appsmith v1.9.25-SNAPSHOT

**Comment by somangshu** [comment]
> Expected Result :
On selecting any value (cover/contain/auto) in radio group button, Image should change it's fit accordingly.

I find this to be an invalid issue @kavitasmoolya. You expectation is not tested properly and that is what I am challenging 

The error you are seeing is because a malformed URL is created, check the image
![Screenshot 2023-07-05 at 2 55 00 PM](https://github.com/appsmithorg/appsmith/assets/11089579/12a7c3cd-b404-4247-a6e1-b296e78bd3af)

Here is how you should have tested it:

https://github.com/appsmithorg/appsmith/assets/11089579/0c3f7173-6940-4e9b-a467-1a084396878b


Closing this
