### ISSUE TITLE
[Bug]: CurrentBSONType Error: DOCUMENT instead of NULL in deploy mode

### ISSUE THREAD

**Issue by felix-appsmith** [appsmithorg/appsmith#25088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, a user has an insert query for MongoDB. When they execute this query in development mode, it works fine. However, in deploy mode, it fails with the error: `Error while inserting resource! readStartDocument can only be called when CurrentBSONType is DOCUMENT, not when CurrentBSONType is NULL.`

Performance: 
[Appsmith.txt](https://github.com/appsmithorg/appsmith/files/11952607/Appsmith.txt)

Remember to change the file format to `.json`.

### Steps To Reproduce

1. Open the user's application using the support account.
2. Click on the large `More` button.
3. Fill out the form and attach a couple of images.
4. Click on `Submit` (You will notice that in edit mode you don't have any errors, but in deploy mode, you do).

### Public Sample App

https://app.appsmith.com/app/allyworkspaces/workspaces-63e254236b8ca42af5ad8a06?branch=master

### Environment

Production

### Version

CLoud: Appsmith v1.9.25-SNAPSHOT

**Comment by incrediblezayed** [comment]
Hello, any updates on this? We're facing issues in production, please help asap. Thanks

**Comment by incrediblezayed** [comment]
Hello team please respond asap. Is this isn't resolved soon, we might have to move away from appsmith

**Comment by sumitsum** [comment]
Hi @incrediblezayed can you please check if re-deploying the app helps ?

**Comment by incrediblezayed** [comment]
> Hi @incrediblezayed can you please check if re-deploying the app helps ? 

I did that already before contacting appsmith

**Comment by sumitsum** [comment]
Hi @incrediblezayed asking this just to make sure and cut down any mis-understandings, can you please share steps for how  you deployed (i.e. re-published) the app ?

**Comment by incrediblezayed** [comment]
> Hi @incrediblezayed asking this just to make sure and cut down any mis-understandings, can you please share steps for how you deployed (i.e. re-published) the app ?

I haven't specifically "re-published" the app, what I did is, I went to deploy button top right corner and from there I created a commit and pushed

**Comment by sumitsum** [comment]
This does not seem like a plugin specific issue because the query seems to be working on the edit mode. This seems like a core query execution issue. @riteshkew can you please check.

**Comment by incrediblezayed** [comment]
Any updates?

**Comment by riteshkew** [comment]
Hey @incrediblezayed, we are still triaging the issue, please give us till next week and we will get back with resolution.

**Comment by incrediblezayed** [comment]
> Hey @incrediblezayed, we are still triaging the issue, please give us till next week and we will get back with resolution.

It has been 16 days, our clients are waiting can you guys please do it faster?

**Comment by tkAppsmith** [comment]
Updates: This seems to be happening due to a query expected to be executed to be null rather than "{}". I am debugging further and expecting to reach the root cause in some time.

**Comment by incrediblezayed** [comment]
@tkAppsmith Okay, I'll do it again

**Comment by tkAppsmith** [comment]
@incrediblezayed Was there a successful repro on app hosted on app.appsmith.com??

**Comment by tkAppsmith** [comment]
The api is returning 200 even if it an error. The response has error code and error description but the http code is 200. This will be copied to new issue.

**Comment by tkAppsmith** [comment]
In the insertQuery, it calls a script onto the formatedData.insert(), which runs ok if images are attached, and if images are not attached, the script return an empty object or a malformed one and that causes the "readStartDocument can only be called when CurrentBSONType is DOCUMENT, not when CurrentBSONType is NULL." . Can the customer correct their script to either cancel the call when images are not available or make the images optional and let the remaining part of script return a well formed json. I am still checking how can a wrong script is triggering an action execution with datatype as null instead of catching the error in UI itself.

**Comment by tkAppsmith** [comment]
Running a mongo query (update/create) with "null" keyword in documents field causes this error to occur. We need to make the input coherent with mongo standards. Issuing a null keyword in compass creates an empty document with an _id. Meanwhile these changes are made, can the user return an {} (empty object) in following clause of the used script: ie comment out lines 5-12. This will essentially insert an empty object which will be the default use case when we handle null keyword in our UI.
OR change the whole flow by attaching a script to the submit button and call the create query in the script rather than attaching create query execution to submit button and handle the error cases viz formdata and images being empty by showing error and then not calling the query.

**Comment by tkAppsmith** [comment]
Im able to upload images both in deploy and edit mode. I also got a successful signed url in response which is of an image belonging to "ally-bucket.s3.ap-south-1.amazonaws.com/workspaces_bucket" bucket. Can we get on a call with the customer and get a live repro of this error and debugging??

**Comment by incrediblezayed** [comment]
Hi
Yes, we can have a call, and please checkout the screen record so you can get the idea of what's wrong.

https://github.com/appsmithorg/appsmith/assets/22563711/0a751a6a-e472-4d31-aa4b-91118d24329d

**Comment by tkAppsmith** [comment]
I was able to repro the above by disconnecting the internet while uploading images so that the upload fails and then reconnecting and submitting the form. My guess here is that when you are uploading the 12 images, the xhr call might be getting timedout and then when you submit the form, the script returns a null as there is a check for images successful upload and then the currentBSONError happens. I need following info:
1. What are the size of images you uploaded when you uploaded 12 images.
2. Can you check if the upload call fails. If not then we can get on a call together and check it. Please provide us with your availability.
3. I saw that when you uploaded only 2 images, the record was updates successfully without the BSON error. Can you confirm if this is the case??

@incrediblezayed

**Comment by incrediblezayed** [comment]
> I was able to repro the above by disconnecting the internet while uploading images so that the upload fails and then reconnecting and submitting the form. My guess here is that when you are uploading the 12 images, the xhr call might be getting timedout and then when you submit the form, the script returns a null as there is a check for images successful upload and then the currentBSONError happens. I need following info:
> 1. What are the size of images you uploaded when you uploaded 12 images.
> 2. Can you check if the upload call fails. If not then we can get on a call together and check it. Please provide us with your availability.
> 3. I saw that when you uploaded only 2 images, the record was updates successfully without the BSON error. Can you confirm if this is the case??
> 
> @incrediblezayed 

Yes, with less images, the document is getting created, and I'll check the same and let you know

**Comment by tkAppsmith** [comment]
Any updates here? @incrediblezayed . Is the user able to change the script to handle errors before calling db query??

**Comment by incrediblezayed** [comment]
> Any updates here? @incrediblezayed . Is the user able to change the script to handle errors before calling db query??

I'll update you by eod today

**Comment by incrediblezayed** [comment]
@tkAppsmith The size of images is around 46 MB
Still Facing the same issue, where I didn't got any timeout error, check the screenshot

<img width="1792" alt="Screenshot 2023-08-01 at 1 48 28 PM" src="https://github.com/appsmithorg/appsmith/assets/22563711/47e6973a-27cb-41e1-a1fd-d26aba286d50">

**Comment by tkAppsmith** [comment]
@incrediblezayed The "uploadImages" query of the "ally_bucket" is set to be a "list files in bucket" command whereas it should be a "create multiple new files" when I checked on their public app in edit mode. Can you confirm if this is also the case for them and if so then let them change it to correct command and try running the flow again.

**Comment by incrediblezayed** [comment]
> @incrediblezayed The "uploadImages" query of the "ally_bucket" is set to be a "list files in bucket" command whereas it should be a "create multiple new files" when I checked on their public app in edit mode. Can you confirm if this is also the case for them and if so then let them change it to correct command and try running the flow again.

Sure I'll check it out

**Comment by incrediblezayed** [comment]
Now I'm facing this 
main.c8363dd0.js:2 Error: Failed to upload file with error: Form field value exceeded the memory usage limit of 262144 bytes
