### ISSUE TITLE
[Bug]: The SCIM user should not have a delete permission on the users Tab

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#25327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The SCIM user should not have delete permission on the users Tab
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/225fd6fd-d1e2-4919-9775-98dbd4cfa058">

### Steps To Reproduce

1. Login to https://ee-1822.dp.appsmith.com
2. Go to admin setting
3. Click on users tab
4. Have some SCIM synced user emails
5. Now click on 3 dot icon the dlete menu is displayed
6. Now click on delete
7. we are able to to delete scim synched users

### Environment

Deploy Preview

### Version

v1.9.27

**Comment by nsarupr** [comment]
Currently there is a permission check to show or hide the Users tab.
But there are no user permissions which are sent via the backend for individual users and so none are handled on the frontend as well.
In order to fix this, we will need to send the User Permissions for user resource from backend, and have frontend use them.

So, basically 2 tasks: 
1. Frontend: Use user permissions to show CTA
2. Backend: Send User permissions on user resource
