### ISSUE TITLE
[Bug]: JS bindings no longer work in Datasource configurations

### ISSUE THREAD

**Issue by GreenFlux** [appsmithorg/appsmith#25537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Previously, JS bindings could be used in the datasource configuration, even though this wasn't an officially supported feature. The syntax highlighting and auto-complete do not work because JS is not meant to be used in the datasource form. However, some users found that they could still reference the appsmith store and use this for adding headers and parameters. 

A recent update has changed this behavior and broken a user's app on Discord. Although we discourage the use of JS in datasource configurations, this was a breaking change for some users, and so it should be corrected. 

### Steps To Reproduce

1. Create an Authenticated API datasource with a JS binding in the header, such as {{appsmith.store.token}}. 
2. Add an API that uses this datasource and run it
3. Check the Audit Logs and see that the string `{{appsmith.store.token}}` was used as the parameter, instead of the evaluated value

### Environment

Production

### Version

Appsmith v1.9.29-SNAPSHOT

**Comment by m1ker1n** [comment]
We are using it in old version of appsmith, I thought that was intended behaviour. We have 100+ queries with this header, so it's pretty useful

**Comment by tazmaniax** [comment]
I also need this functionality because I'm generating a custom JWT so I would like to understand why this behaviour is not supported. Thanks!

**Comment by riteshkew** [comment]
I'm pleased to inform you that this issue has been resolved. The root cause was an oversight during a recent infrastructure change on our end, and we have taken steps to rectify it.

We understand how frustrating and disruptive such issues can be, and we sincerely apologize for any inconvenience this may have caused. Rest assured, the fix will be included in our next release. Your patience and understanding are greatly appreciated, and we are committed to ensuring a smoother experience moving forward.
