### ISSUE TITLE
[Task]: Add try/catch around GoogleMaps API to check for invalid license key in MapWidget

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith#25559]
We can have a try/catch around the Google Maps API code when the api key is invalid for when the error happens the first time.  We can then show a relevant error message UI to the user within the map widget from the catch block. The error message UI can also have appropriate remedial steps mentioned in it, for instance a refresh widget button.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### SubTasks

Relevant Slack thread : https://theappsmith.slack.com/archives/C02JV8G1MP0/p1689740931583169

**Comment by dhruvikn** [comment]
We tweaked around and [were able to do this POC](https://codesandbox.io/s/xenodochial-haslett-v6fv6j?file=/src/App.js) which is a workaround.

However, js-api-loader (the official package we use to load Google Maps) doesn't recommend doing this since it "might" result in incorrect/duplicate billing. [Here's the GitHub thread](https://github.com/googlemaps/js-api-loader/issues/100). The maintainer of the library has raised the incorrect/duplicate billing concern in multiple discussions and that's the reason why js-api-loader doesn't have a dynamic way of changing language/api key/or anything today. 

Once the script is loaded, the best bet is to refresh the page, which we are already doing. Therefore, closing this issue and the dependent #25560.

PS - [Here's an official Google Maps demo](https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/demos/localization?language=af) where they are changing the language by refreshing the page.

cc: @sharat87
