### ISSUE TITLE
POC for moving git push to background

### ISSUE THREAD

**Issue by ginilpg** [appsmithorg/appsmith#25592]
As part of the POC, we're interested to know answers of these questions:
1. Is there any technical difficulty to move the git push to background?
2. What can go wrong if we do that?
3. What might be possible solutions to handle the situations described in questions 2

**Comment by nayan-rafiq** [comment]
Here are the answers to the questions: 
**Is there any technical difficulty to move the git push to background?**
No, technically it's possible to run the git push in background. I've tested it with current architecture, it's working.

**What can go wrong if we do that?**
The following things can happen if we move the git push to background:
1. The push failed due to a conflict in the server. Just before the push, someone pushed another commit to the same branch.
2. The push failed due to network failure or server restart.
3. While the push is in progress, the branch has been updated e.g. deleted, new commit added etc
