### ISSUE TITLE
[Feature]:  Allow CLI/API ingestion of json apps

### ISSUE THREAD

**Issue by ArtruneTranspara** [appsmithorg/appsmith#25957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have exported an APP in json format and wish to import it programmatically using either the CLI or API.

Also, when I import the app using JSON none of the queries work, it shows an error message as if they didn't have a URL, so I have to remove the URL press RUN query and then paste the URL again.

### Why should this be worked on?

Allows for automation and deployment of apps.

**Comment by lukasz-wasylyk** [comment]
I would love to have this feature implemented. We struggle with manual deployments currently and we could automate it using such CLI

**Comment by k0muc** [comment]
Required mechanism for CI/CD implementation

**Comment by Nikhil-Nandagopal** [comment]
@ArtruneTranspara @k0muc @lukasz-wasylyk we're working on #11522 to solve this problem so we believe that is a more elegant solution. You can follow that issue and we'd be interested in learning whether that solves your problem

**Comment by jwojnarowskiDTP** [comment]
And #11522 is dedicated for Business Edition

**Comment by Nikhil-Nandagopal** [comment]
Programmatically importing entire apps can become very difficult to maintain because app files become really large as you continue to build them and it isn't a very good long-term solution. You can still achieve this by looking at the API for the import file feature and hardcoding your access token in it but I believe the real power of this feature comes from the ability to automate deployments with your CI/CD and git is the right way to do that.
