### ISSUE TITLE
[Bug]: The 'Last edited' text under the app cards on the homepage is buggy

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith#26120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There is something wrong with the _who edited when_ text that shows under the app cards on the homepage. I've been seeing some weird stuff.

- Users who did not edit it last show up 
- Users who are not part of the workspace show up. But could have been a fork of the original app (in another workspace) to which the user had access. 

More context here - https://theappsmith.slack.com/archives/C02K2MZERSL/p1691477212763799

### Steps To Reproduce

Not sure

### Environment

Production

### Version

 v1.9.30

**Comment by GreenFlux** [comment]
@danciaclara thanks for flagging this. @hiteshjoshi @infinitetrooper , could we also stop updating the _Last edited_ timestamp just because the app is opened in the editor? I will often open an app just to view it in the editor, and that alone updates the timestamp without making any changes to the app.
