### ISSUE TITLE
export app as static .zip file

### ISSUE THREAD

**Issue by mikestaub** [appsmithorg/appsmith#2632]
## Summary

I would like to be able to export the app as a folder that can be hosted on s3 ( or any other provider ). Is this possible in the current architecture? I would be willing to add this feature and PR with guidance.

## Motivation

I would like to integrate the generated app into another application and prefer to not carry the backend dependency.

**Comment by mohanarpit** [comment]
Thanks for creating an issue for this. I'd love to understand the use-case in a little more detail. 

Since Appsmith is open source, you can host Appsmith on your own cloud server easily. If you don't want to bother with managing your server, you can use Appsmith Cloud (https://app.appsmith.com) to build & host your application. Any particular reason you want to host your app on S3?

If you would like to integrate an Appsmith application into your existing app, you can use our embed feature (early preview). In order to do this, append the query parameter `?embed=true` to the URL. For example, on an Appsmith Cloud hosted app, this would be: `https://app.appsmith.com/applications/abc/pages/xyz?embed=true`. This will ensure you can simply embed the app within an iFrame. Please note, that for this, the application needs to be made publicly available, else Appsmith will redirect to the login page.

**Comment by mikestaub** [comment]
The use case is shipping an application to an on-prem environment that does not have public internet access.

If we cannot decouple the java server component from the authored application, then we are forced to run it as a docker container in our kubernetes cluster, which we prefer to not do. We will have many authored applications running at the same time and they will have to all have their own backend container running to be usable.

Is there a reason the authored application needs the server as a runtime dependency? I understand why it is needed while authoring, but once the client is generated I would assume it could embed the appsmith engine in js, and export the whole thing as an html export we can host statically.

**Comment by Nikhil-Nandagopal** [comment]
@mikestaub the java server cannot be decoupled because appsmith does a lot of server-side logic such as RBAC, storing DB credentials, and safely executing the DB queries & APIs whose configurations are stored in the database so they cannot be tampered with by the client during execution.

**Comment by mikestaub** [comment]
@Nikhil-Nandagopal thanks for clarifying

**Comment by mikestaub** [comment]
If we assume all backend APIs are public and require no authentication, is this technically possible? 

Our use case is embedding the generated application inside another app, which handles all the authentication. We just want an easy way to create custom UIs that can be hosted anywhere.

How difficult would this decoupling be to do in your estimation? We may be willing to add this feature and then PR back into the repo for others to use.

**Comment by mohanarpit** [comment]
@mikestaub Unfortunately, Appsmith is built to talk to authenticated APIs and DB servers. Hence, the system is designed to store credentials securely. The fact that your backend API is public, is a special scenario and generally not the norm. 

To be honest, it's really hard to de-couple Appsmith's Java server from the client for a couple of reasons. 
1. We don't do client-side code generation today
2. All API calls are made by the Java server only. Moving this to the client will be a huge effort and expose security holes for everyone.

Like I mentioned earlier, currently, your options are slightly limited.
1. Self-host Appsmith & use the embedding feature by appending the query param `?embed=true` along with the page URLs.
2. If you need static code generation, might I suggest a different product like Webflow?
