### ISSUE TITLE
[Bug]: Unable to select dates from calender when default date field is configured in js

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#26600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When we configure anything on Default date property of JSONForm datepicker field type, the dates other than default are not getting selected from calender

### Steps To Reproduce

1. Drag & Drop a JSONForm
2. Configure setting for Datepicker field type
3. Enable js editor for `Default date` property
4. Bind the field. for eg: use `moment()'
5. Now click on datepicker field to select a date
6. Observe that other than default dates are not getting selected

### Environment

Production

### Issue video log

https://www.loom.com/share/df47bd1df14b457ba37dc827a8573ab8?sid=4f80bf46-fe8c-4abd-92bb-56a83d418219

### Version

Cloud/Production

**Comment by jacquesikot** [comment]
Hi @chandannkumar,

Thank you for raising this issue. The behavior you're observing—where the value of the DatePicker input resets when the default value changes—is expected. This happens because your default value is dynamic (moment()).

A more robust approach would be to define your dynamic value in a JS Object and then reference it in the defaultValue field of the DatePicker. For example:
JSObject1.currentTime

I've attached a link to a public [app](https://app.appsmith.com/app/dynamic-datepicker-default-value/page1-67585e3edc1c0509585cd82a) demonstrating this behaviour for your reference. Please feel free to check it out and let us know if you have further questions.

Thanks!
