### ISSUE TITLE
[Bug]: The setValue component is still buggy

### ISSUE THREAD

**Issue by 31604086** [appsmithorg/appsmith#26679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I expect that when a component sets a default value, it should not reset to the default value as other values change

### Steps To Reproduce

1. Create a new page
2. Create JS object2 as follows
export default {

myVar1: ['0','1'],

myVar2: {},

myFun1 () {

// write code here

myVar1 = [1,2,3]

this.myVar1[1] = '2'

},

async myFun2 () {

// use async-await or promises

// await storeValue('varName', 'hello world')

}

}

3. Drag and drop the two input components, setting the Default Value of the first component Input1 to {{JSObject1.myVar1[0]}},
The onFocus association for the second component, Input2, is JSObject1.myFun1
4. Deploy the new page, Input1 will be set to 0 by default, change the value to hello, then click Input2 and observe that the Input1 input box is reset to 0 and hello is lost.

### Environment

Production

### Version

Appsmith v1.9.34
```[tasklist]
### Tasks
```

**Comment by Druthi** [comment]
Had a discussion with @bharath31 and @Rishabh-Rathod on the behavior of this and we concluded that this is expected behavior. 

Reactivity works at the variable definition level and not at the level of the elements in a non-primitive variable like arrays and objects.

Therefore in the above scenario, "hello" will be lost as the values in the variable `myVar1` has changed thereby recomputed all the properties that are dependent on this variable.

**Comment by Druthi** [comment]
Closing this for now for reasons explained in the above comment.
