### ISSUE TITLE
[Bug]: (+) icon symbol is not displayed by default on selecting none for menu and input widget

### ISSUE THREAD

**Issue by kavitasmoolya** [appsmithorg/appsmith#26713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Icon property behavior is not consistent for icon widget and other widget  having icon as their property

Note : Issue exists for the widgets which has icon property 
ex :

- menu widget
- Input widget

Attached video : https://www.loom.com/share/60e053095e424356867e067cea5426da?sid=5bae4489-5f2f-4fa9-b6ca-0c161b33835c

### Steps To Reproduce

1. Drag and drop menu widget/input widget
2. Go to styling panel
3. Select any icon (lock icon) in icon property
4. now search for number in icon property such as 123, it will give `none` as search result
5. Select none and observe no icon displays 
6. Repeat same steps for icon widget and observe  (+) icon will be displayed by default on selecting none

### Environment

Production

### Version

Appsmith v1.9.35-SNAPSHOT

**Comment by dhruvikn** [comment]
@dilippitchika - I don't think showing (+) icon when we search for something and click on (none) is a good idea. (none) should ideally mean no icon is displayed - as we do in the input and the menu button widget. But since we have set the default icon for the icon button as "plus", it automatically picks up the plus icon. We can change this default to none, but that would result in a weird empty icon. Not sure what our next steps should be here.

![CleanShot 2023-09-07 at 16 22 18](https://github.com/appsmithorg/appsmith/assets/22471214/29d01d97-6bb9-4abe-ac11-de9e557b2913)

**Comment by dilippitchika** [comment]
The reason we added this was that we have a default icon in this icon button, can't we just hide the none option for icon button altogether?
