### ISSUE TITLE
[Feature]: Support Cosmos DB as an alternative to MongoDB

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith#26872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Appsmith requires MongoDB today, as it's the database to store all application data. 
Azure Cosmos DB is a globally distributed, multi-model database service offered by Microsoft Azure. Appsmith needs to be compatible with Cosmos DB as well so that it can be run with DocumentDB instead of MongoDB.

### Why should this be worked on?

Some self-hosted users are using Azure and it would enhance their experience it they can use Cosmos DB instead or MongoDB for storing Appsmith's application data.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2uwnrg)

**Comment by Nikhil-Nandagopal** [comment]
We're undertaking a migration to mongoDB so this should be solved

**Comment by IvanLC89** [comment]
I wanted to add that the issue occurs even when using the MongoDB model on CosmosDB.

![Image](https://github.com/user-attachments/assets/aa2cbb79-5984-4049-afa4-1eee5fbaf7b6)

The problem is that the entrypoint script checks whether the replica set is enabled by running the `rs` commands, which are not supported on CosmosDB. 

![Image](https://github.com/user-attachments/assets/8ecb4adf-f264-4f0b-8858-e62b80256acb)

This is because the replica set is managed directly by Azure

![Image](https://github.com/user-attachments/assets/8cfb1279-7e0c-4d0b-b63b-8f911c3e0341)

A possible suggestion is that the script doesn't validate the replica set, if the hostname matches specific domains:

1.  Azure `*.cosmos.azure.com`
2 . Aws    `*.docdb.amazonaws.com`

This is just an example. It'd be really handy to add this.
Thanks
