### ISSUE TITLE
[Feature]: The color of some elements does not change while hovering in the navbar.

### ISSUE THREAD

**Issue by nis06** [appsmithorg/appsmith#27370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we hover over the list items in the navbar, some elements change their color, but two of them do not. I recommend changing the color of each list item.
Like the color property in Enterprise changes on hover
<img width="957" alt="image" src="https://github.com/appsmithorg/appsmith/assets/112106948/5c3cb814-15dd-420b-9d9e-40f957db0775">

I recommend to do the same with Product and Resources.

<img width="960" alt="image" src="https://github.com/appsmithorg/appsmith/assets/112106948/63bade04-a7f4-426d-ac51-ab6666f403b4">

### Why should this be worked on?

Implementing this design change would ensure consistent alignment in the navbar when hovering. Currently, the hover effect appears inconsistent with the rest of the navbar.

**Comment by Arun9650** [comment]
hi, can i work on this issue

**Comment by tejasahluwalia** [comment]
Thanks for opening the issue. This was a conscious decision taken because the dropdown interaction of `Product` and `Resources` is different from the others that are plain links. So it didn't seem right to have the same hover interaction for both. 

The dropdown navbar elements also have the icon which is indicative its behaviour. Similar example: https://linear.app/ - the `Company` menu item vs the rest. 

We will consult with our designers on re-validating this choice if its confusing.

**Comment by Nikhil-Nandagopal** [comment]
Sorry we also do not accept contribution to the website. We only accept contribution to the product
