### ISSUE TITLE
[Bug]: Postgres plugin: fix idle connection issue with Supabase

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#27426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

ref: https://theappsmith.slack.com/archives/C03P17RSW6S/p1695106039593359?thread_ts=1694542897.484119&cid=C03P17RSW6S 

Also, tracking it on Supabase here: https://github.com/supabase/supabase/issues/17549 

### Steps To Reproduce

https://theappsmith.slack.com/archives/C03P17RSW6S/p1695106039593359?thread_ts=1694542897.484119&cid=C03P17RSW6S 

### Environment

Production

### Issue video log

https://theappsmith.slack.com/archives/C03P17RSW6S/p1695103878482639?thread_ts=1694542897.484119&cid=C03P17RSW6S

### Version

cloud, self hosted

**Comment by chasers** [comment]
Does your driver do pooling for you? 

If so you can set the max connection count, otherwise use the pooler provided by Supabase (pgbouncer or Supavisor) by using the provided connection string in the Supabase dashboard.

Maybe there are some things you could do to default users to using a Supabase connection pool.

**Comment by Nikhil-Nandagopal** [comment]
I believe this now works with the new supabase changes
