### ISSUE TITLE
[Task]: Do a quick poc on the approach to take with tag input 

### ISSUE THREAD

**Issue by tanvibhakta** [appsmithorg/appsmith#27436]
Current tag input: https://design-system.appsmith.com/old/?path=/story/design-system-tag-input--tag-ipt

We need to understand if we can use our existing tag component within our existing input component and make tag input a variation of input, or if we need to create a whole new component.

**Comment by albinAppsmith** [comment]
@tanvibhakta, can you do POC on can we do tag input using rc-select, because we need suggestions also part of tag input. This use case is there in EE. @ankitakinger  Can help here understand the use case.

If rc-select is not feasible then we can consider doing using input, popover and tag component.

cc: @rohitagarwal88

**Comment by tanvibhakta** [comment]
Can do, @albinAppsmith 

> we need suggestions also part of tag input. 

This is not currently a part of tag input's functionality, so it would help for me to see a sample or some designs to understand what is necessary.

**Comment by albinAppsmith** [comment]
Closing this task with following decisions made.
1. Will be using rc-select to implement tag component.
2. Suggestions will also be part of tag component.
