### ISSUE TITLE
[Bug]: [Sentry APPSMITH-SERVER-6] AppsmithPluginException in GSheets plugin

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#27444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://appsmith.sentry.io/issues/4303443810/?project=4505267188465664

### Steps To Reproduce

NA

### Environment

Production

### Version

Cloud

**Comment by NilanshBansal** [comment]
Added more logging info to sentry to know the exact root cause of this issue. 
Ref PR https://github.com/appsmithorg/appsmith/pull/28666 to issue  https://github.com/appsmithorg/appsmith/issues/28665

We will monitor this issue for a few weeks and then get back to this.

**Comment by NilanshBansal** [comment]
Error: `AppsmithPluginException: Appsmith server has received unsuccessful response from GoogleSheets`
`POST /api/v1/datasources/657ba36526b111462287b39a/trigger`

Ref: https://appsmith.sentry.io/issues/4303443810/events/?cursor=0%3A50%3A0&project=4505267188465664

**Comment by NilanshBansal** [comment]
This is an error from google due to the apostrophe (') present in the first row of the google sheet. 
https://github.com/appsmithorg/appsmith/assets/25542733/91b64a23-4fed-4403-b5b1-801d45761451
<img width="1417" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/4e3bb5d0-959f-4343-9609-f5b7467ef8e9">

**Comment by NilanshBansal** [comment]
Tried updating the google sheets query in the code from `SheetName!1:1` to `1:1` and `SheetName!A:ZZZ` to `A:ZZZ` as per [this](https://stackoverflow.com/a/37893568). This query always fetches the data from the first sheet in the worksheet.

For us, we need to select a particular sheet and fetch rows, hence this method doesn't work for us.

Since, this is an issue from google and we cannot fix this, I'm removing these logs from sentry and instead adding these to our mezmo logs.
@rohan-arthur
