### ISSUE TITLE
Test the property pane for WDS TextInput

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#27624]

**Comment by shadabbuchh** [comment]
Issue noticed in the WDS TextInput:

1. When we toggle the JS button for `Icon` prop, we see moustache binding braces by default. _This is a deviation from prod._
<img width="333" alt="Screenshot 2023-09-27 at 11 57 50 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/406b7c79-1080-41a1-a314-ab5f8c973baa">

2.  The `General` section comes before `Validation`. _Deviation from prod._
<img width="309" alt="Screenshot 2023-09-27 at 12 06 54 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/af940eaa-86bd-40b9-b785-a0840cc1300c">

3. `Height` property is present in the `Validation` section instead of the `General` section.
<img width="289" alt="Screenshot 2023-09-27 at 12 12 54 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/63cfe73c-eebc-4f44-8355-f5d239f77a1e">

4. Position of the `Spellcheck` property is not in congruence with prod.
<img width="273" alt="Screenshot 2023-09-27 at 12 14 57 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/7fc3f15b-a613-4eed-8176-2e41922c1d93">

5. Default text length & `Required` error message shown directly instead of a tooltip.
<img width="501" alt="Screenshot 2023-09-27 at 12 31 19 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/e2ee5444-ad1e-4829-8ed7-23a09049c3e2">
<img width="453" alt="Screenshot 2023-09-27 at 12 51 29 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/38b7fde1-7184-4d43-87e0-1332c755ffc8">

6. Multi-line text data type does not respect the Max characters validation.
https://www.loom.com/share/1f36d2c917a24b20ac805da422bdf03a

7. Tooltip appears directly on the screen. We do not see a icon for the same.
<img width="1401" alt="Screenshot 2023-09-27 at 12 40 09 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/5d8c2558-ce72-44ec-9355-32136771c27d">

8. When `Disabled` is turned on, user is still able to enter text inside TextInput.
9. When `Visible` is turned off and then we deploy the app, we get to see the widget for a fraction of a second and then it vanishes from the screen.
https://www.loom.com/share/f6e0429ad27141d29a690295d1d43b72

10. A long Label overlaps with the input field.
<img width="542" alt="Screenshot 2023-09-27 at 12 55 06 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/15bc171d-3abb-4ad4-93f4-7892c15a7b65">

11. The text inside the widget does not get reset when `Reset on Submit` is enabled.
12. Error is not thrown when an invalid input is entered.
- Enter any text.
- Now change the Data type to email
- `Invalid Input` error message will not appear on the screen automatically.

13. Changing the Data type to `Number` erases all the entered text.
- Enter any text.
- Now change the data type to number.
- Instead of throwing an error message, all the entered text is removed.

14. When we focus on the widget, the focus color is different from Prod.
<img width="480" alt="Screenshot 2023-09-27 at 3 45 12 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/aabce35c-097b-49b7-894f-f867a81f546b">

15. We get to see increment/decrement arrows when the data type is set to `Number`.
<img width="166" alt="Screenshot 2023-09-27 at 3 46 41 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/16774fcb-c433-49e2-a6da-461988cced1a">

16. Tooltip does not appear when `Label` is empty. In prod we get to see the tooltip even when there is no `Label`.
17.  Font size & family for the same themes are different when compared with prod.
18. Box shadow is not inherited from Theme.
19. As soon as we DnD the widget, the size handlers sort of overlap with the bottom edge of the widget. (makes it look untidy).
<img width="479" alt="Screenshot 2023-09-27 at 4 23 17 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/d299d4a1-95a6-49f7-8e75-075b38483ccc">

20. `Defalut value` does not reflect immediately in the input area.
https://www.loom.com/share/1461d6f79c63425faa454ee6b7a35f6c

21. The UI of the whole widget is not as it is in prod. The input area looks different. The white background is missing in the text area.

Moving this ticket to sprint backlog.
Cc: @KelvinOm

**Comment by KelvinOm** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Widget-Design-System-6434e3402be2c1002ea740be/issues/appsmithorg/appsmith/27624?planning-poker) with Zenhub @dhruvikn @ichik @jsartisan @KelvinOm

**Comment by ichik** [comment]
Number 5 is better UX.
Number 14 is expected change, number 17 possibly too.
