### ISSUE TITLE
Test WDS components in storybook

### ISSUE THREAD

**Issue by KelvinOm** [appsmithorg/appsmith#27629]
Lint tot storybook https://release--64c89da059b7d62ad3a60544.chromatic.com/

It is necessary to test how components behave:
1. when overflowing(a lot of content inside component);
2. on a small screen resolution.

**Comment by shadabbuchh** [comment]
This will be taken up for testing once #27631 is complete.
Cc: @KelvinOm

**Comment by shadabbuchh** [comment]
### Issues in this PR:

**Button:**

1. Having a lot of content inside, once the screen size is decreased the button is not completely visible. Should we show ellipsis instead?
<img width="808" alt="Screenshot 2023-09-28 at 11 10 57 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/6a664fc2-e8da-480c-a29d-f5c700249647">

2. On clicking the button we see a focus state. This is not good UI.
<img width="143" alt="Screenshot 2023-09-28 at 11 12 57 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/e3ebe5b0-0ac1-4447-81ff-5617b2cb03ad">

3. Can the negative variant be more red? Right now it gives a feel of pinkish-red.
4. When `isLoading` is set to true, we are able to click interact with the button. Instead shouldn't the button be uninteract-able? 
5. Focus state is visible when `isDisabled` is set to true. Can we instead make the button not interact-able at all? Same holds true when `aria-disabled` is set to true. (a proper cursor icon is needed for both Loading & Disabled state)
<img width="259" alt="Screenshot 2023-09-28 at 11 15 55 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/09733c36-719f-4a3d-9add-ba194301cdad">

6. When `isLoading` is set to true & we start entering some `className`, the text inside the button becomes visible & the Loading state looks weird. Also the focus state looks weird as well.
<img width="1920" alt="Screenshot 2023-09-28 at 11 25 44 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/906e0de0-22c3-4b1d-91ca-ad5590b2aaca">
<img width="340" alt="Screenshot 2023-09-28 at 11 27 13 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/fbb678c0-65b9-4167-9c7a-777078d24351">


7. When `draggable` is set to true we can drag the widget but it does not stay at the dragged position. Is this expected? Also shouldn't the control be called `isDraggable` just to maintain uniformity?
8. When both `isDiabled` & `draggable` are set to true, the button is draggable. Is this intentional?

-----------------------------------------------------------------------

**Checkbox:**

1. Upon decreasing the screen size, a long label disappears and the default label appear on the screen. 
https://www.loom.com/share/16e168fb06f1426ea6caa6471d5ec705

2. `className` does not render inside the console.
3. Proper cursor does not appear when the checkbox is disabled. The user might get confused about interacting in this case

--------------

**Checkbox group:**

1. The label seems to not be aligned with the checkboxes
<img width="29" alt="Screenshot 2023-09-28 at 3 56 39 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/735920c8-5e1f-40b3-b4bf-1ebd2f34e8a6">

2. A long label overlaps with the checkboxes
<img width="244" alt="Screenshot 2023-09-28 at 3 57 40 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/922b5714-9d9b-4b59-875b-256995955813">

3. Proper cursor should appear when the widget is disabled.
4. The label & the checkbox options look different from each other in the disabled state even though they have the same font color
<img width="168" alt="Screenshot 2023-09-28 at 4 05 56 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/c10b6d61-ac59-418f-bd09-90cc7bc30c5e">

5. When `isRequired` is set true and we do not select any option, no error is thrown.

---------

**Icon Button:**

1. Focus state appears on clicking on the Icon button.
2. Editing the `className` sends the icon button into loading state.

https://github.com/appsmithorg/appsmith/assets/39921438/3208ba0e-2580-4747-88dc-3902df4edbbd

3. When `draggable` is set to true we can drag the widget but it does not stay at the dragged position. Is this expected? 
4. When we lick the component in loading state, we get to see a focus state.
5. When both `draggable` & `visuallyDisabled` are set to true, we are able to drag the widget.

https://github.com/appsmithorg/appsmith/assets/39921438/71fb1e18-de40-4925-84b2-0e86b8d8a069

6. When `isLoading` & `visuallyDisabled` both are enabled together, the icon button does not look visually disabled. What is the expected behaviour here?
7. When `visuallyDisabled` is set to true, we are still able to drag the widget. Is this expected?
 
-------------

**Radio Group:**

1. A long label overlaps with the options.
<img width="737" alt="Screenshot 2023-09-29 at 8 41 18 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/9e773f42-781a-4f0f-9f88-6abea331c49c">

2. When disabled the Label & the options seem to be of different colors (in reality they are not).
3. When `isRequired` is set to true and we do not select any option, no error is thrown.
<img width="982" alt="Screenshot 2023-09-29 at 8 47 22 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/3626bf18-071b-467b-ba33-3723db03be7d">

-----------------

**Switch:**

1. As soon as we start entering `className` the switch disappears.

--------------

**Switch Group:**

1. On entering `className` the options & label squish together
<img width="972" alt="Screenshot 2023-09-29 at 9 12 15 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/0c37fbd0-a820-4767-a557-40c9c009bd77">

2. Long label name overlaps with the option.
3. No error thrown when `isRequired` is true & no option is selected.

---------------

**Text Area:**

1. Long label overlaps with the text area.
2. On setting `className` & `inputClassName` the label & text are squish together.
3. When `necessityIndicator` is set to `icon` no icon is displayed.
<img width="1162" alt="Screenshot 2023-09-29 at 9 32 22 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/c94278d7-b83c-4350-bf0f-94f16ec9e6db">

4. `isLoading` does not do anything.
5. While entering any text inside, we get to see the accent color on border. Is this intentional?
6. Upon entering a long error message/Label, the length of the input area also increases. Instead shouldn't the error message break according to the length of the input? 

https://github.com/appsmithorg/appsmith/assets/39921438/68fab24e-570c-42c9-a9e3-1a73fc438850

--------------

**TextInput:**

1. Long label name overlaps with the input area.
2. The input area is editable when `isLoading` is true. Is this expected?
3. On setting `className` & `inputClassName` the label & input are squish together.
4. If the text inside the input exceeds the length, can we show an ellipsis at the end?
5. For type = `password` when we click on the show password icon, we get a focus state.
<img width="131" alt="Screenshot 2023-09-29 at 10 50 57 AM" src="https://github.com/appsmithorg/appsmith/assets/39921438/3e3628a6-fcde-4d77-aacb-2665a8be48bb">

6. When `isRequired` is set to true, we do not get an error message if no text in entered.
7. When the screen size is reduced, the widget vanishes from the screen.

https://github.com/appsmithorg/appsmith/assets/39921438/751198b6-e1e3-4618-96dc-265d113e5a22

----------------

**Tooltip:**

1. `initialOpen` does not render appropriately.
2. `openDelay` & `closeDelay` do not work.
3. `shift` & `padding` do not render inside the canvas.

https://www.loom.com/share/f09a2ff6b2624d7dbfd7399f58814186

----------------

**Flex:**

1. `flexGrow`, `flexShrink` & `flexBasis` do not work together as expected.
2. While entering a value in `isHidden`, the component changes its alignment to vertical.
<img width="1920" alt="Screenshot 2023-10-02 at 5 11 26 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/33d71f88-f4e5-4dc0-a0d6-8f8eadd9b19f">

3. Even when `isHidden` is set to `false`, the component vanishes from the screen.
<img width="1920" alt="Screenshot 2023-10-02 at 5 12 37 PM" src="https://github.com/appsmithorg/appsmith/assets/39921438/2f62bd8c-76a0-4b6e-b810-285713d2b5f7">

4. `Margin` & `Padding` values do not render in the canvas.
5. `Width` & `Height` do not render in the canvas.
6. Most of the controls in the flex component do not render in the canvas.
