### ISSUE TITLE
[Bug]: when sso users tries to signup with form login after downgrade the users already exits issue is displayed

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#27914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

when sso users tries to signup with form login after downgrade the users already exits issue is displayed

### Steps To Reproduce

1. go to https://ee-2453.dp.appsmith.com
2. Email email verification from EE and downgrade the instance to CE
3. Now try to sign up with the SSO user email
4. the user is redirected with the error "email already exits please sign in"
5. if user tries to signin then its throws the error saying username or password is not correct

### Environment

Deploy Preview

### Version

v1.9.39

**Comment by abhvsn** [comment]
@Raksha Shetty I checked the following flows to gain the access for the account after the instance is downgraded:
Steps:
#### Simple sign up after downgrade via form login:

1. Admin adds the license key where OIDC is supported
2. Admin enables email by adding the SMTP configs 
3. Test user signs up with OIDC
4. Admin downgrades the instance  
5. Expected result:
6. test user should automatically gets logged out => Tested and working as expected
7. OIDC should no longer be available as a login method => Tested and working as expected
8. User signs up and gets the access of the apps created when logged in via OIDC

#### Forgot password flow:

- Same steps till 5
- Instead of directly signing up user chooses to opt for forgot password
- Email with reset password is received
- User resets the password and gains the access of the apps

#### Verify email flow:

- Same steps till 5
- User tries to sign up
- User is presented with a verification screen and mail is sent to the user
- User is able to login with the verification link

**Comment by pranayagarwal96** [comment]
Closing this issue as this is no longer a bug
