### ISSUE TITLE
[Bug]: Limit user sessions :: Two session are active when the option is enabled.

### ISSUE THREAD

**Issue by Harshask93** [appsmithorg/appsmith#27976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The observation is made when the two sessions are active and the "Limit user session" option is checked and saved on one of the sessions.

**Note:** Observation is also made on prod env.

### Steps To Reproduce

**Pre-req:** The "Limit user session" option should be unchecked.

1. Login as admin on two browsers (two active sessions)
2. On browser A - Check the "Limit user session" and click on "Save"
On browser B - Observe that the change is not reflected
3. Do a hard refresh on browser B and now the change is reflected.

**Actual behaviour:**
Even though the option is checked, both sessions remain active and work without facing any error.

### Environment

Deploy Preview

### Version

Appsmith Business v1.9.40

**Comment by abhvsn** [comment]
@Harshask93 This is happening because we don't run any migration on server when the admin enables limit session feature. But if you have 2 active sessions and try to sign in with additional one i.e. 3rd one previous 2 sessions should be invalidated.

Note: This is not related to 1-click though, it's the behaviour that is present on prod as well.

**Comment by deepikaappsmith** [comment]
I had a conversation with @infinitetrooper, and this is the expected behavior. 
"The idea was to log out of all existing sessions when logged into a new one, not to flush all sessions when the feature is checked."
