### ISSUE TITLE
[Feature]: Add support for isVisible property in the iframe widget

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith#27991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Iframe widget cannot be hidden or shown dynamically, making it a blocker for cases like auto-height in containers. This feels like an inconsistency.

### Why should this be worked on?

This will help developers create a better experience for their flows where they want to show iframe dynamically

**Comment by yasharma2301** [comment]
I can take this up

**Comment by Raylyyyy** [comment]
I can give a try on this

**Comment by danceAndJive** [comment]
Hi @dilippitchika, to start off the feature I have implemented a "visible" toggle for the iframe widget. Please see the screenshot below - 
![Screenshot 2023-10-17 at 10 45 10 am](https://github.com/appsmithorg/appsmith/assets/99446612/007a8684-69b0-4c31-97eb-c1aa7e373095)

Could you assign the issue to me please? Thank you.

**Comment by somangshu** [comment]
Greetings @danceAndJive, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Please tag your PR here for us to take it forward. 

Also, FYI, since this is the first time you are contributing, I am still assigning this to you, but in future please first get the issue assigned to yourself before you start work. This is for all of us to same time. 

@yasharma2301 @Raylyyyy did not see your comment in time, pleases find other GFIs and tag me directly on it if you are interested.

**Comment by Raylyyyy** [comment]
Sure, thanks

**Comment by hamzaadil56** [comment]
@somangshu @Nikhil-Nandagopal @dilippitchika can you guys tell me how to install git secrets in windows as I'm the newbie to contribute in this project for the community.

Thanks
