### ISSUE TITLE
[Bug]: Email verification screen - "not you" link issues

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#28613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On clicking of `not you` link in email confirmation page
1. It is taking user to sign in screen instead of sign up.
2. Link is opening in new tab which not required in this context.

### Steps To Reproduce

1. Goto sign up screen
2. Enter new email and password
4. Check the behaviour "not you" link in email verification screen

### Environment

Production

### Issue video log

https://github.com/appsmithorg/appsmith/assets/87797149/31a5775f-d62a-48ea-9a5e-f7bf7441f0bd

### Version

Cloud

**Comment by NilanshBansal** [comment]
@albinAppsmith why do you feel the user should be taken to signup screen in this case?
If you open https://app.appsmith.com in an incognito tab, by default it redirects to https://app.appsmith.com/user/login i.e. to login page and not signup. 

The same logic applies to when the user clicks on `not you` in the email verification modal, the user is taken to login page, because that is what is defaulted to. 

I believe this is the intended functionality. 
cc: @kocharrahul7 @rohan-arthur

**Comment by albinAppsmith** [comment]
@NilanshBansal I'm not able to recollect the reason for suggesting "navigate to sign up page". But still I fell we should not open it in a new tab because, user is confirming that this is not him by clicking on not you button, so there is no need to keep that window open.

**Comment by NilanshBansal** [comment]
@hetunandu do you know why we chose to open the `not you` redirect in a new window and not the same window?

**Comment by hetunandu** [comment]
@NilanshBansal @albinAppsmith 
No strong reason. This can open in the same window as well
