### ISSUE TITLE
[Bug]: Mongo movies sample DB  - Default new query generated errors out on running

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I try to create a new query of movies sample mongo db and execute it, it errors out with the message - Your query failed to execute:
JSON reader was expecting ':' but found ':'.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/dea4f15a-7215-4116-b6c6-46310b66ddcc

### Environment

Production

### Version

Cloud

**Comment by btsgh** [comment]
Some info on this - 
This is working fine in v1.9.46. It has broken in v1.9.47 onwards. 
The default query generated for movies sample db in v1.9.46, is this - **{ "homepage": "https://www.godzillavskong.net/"}**
From v1.9.47 onwards, it has changed to **{ "genres": "[{"name":"Comedy","id":35},{"name":"Crime","id":8fsdf0}]"}**

**Comment by sneha122** [comment]
Closing this issue, as the issue was a one time occurrence happened because someone modified and corrupted the mongoDB sample datasource. The issue got fixed automatically as sample Dbs are reset every 24 hours. The absolutely corrective fix would be to have sample DB instance separate for each user, so that any changes made by one user will not affect others.
