### ISSUE TITLE
[Bug]: There are more setters than getters for a widget.

### ISSUE THREAD

**Issue by zj131711** [appsmithorg/appsmith#29289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I want to know why the setter method of Text Widget is much more than the Reference properties. For example, I can use Text1.setTextColor() but cannot get Text1.textColor, it seems that other widgets are also in this situation. I personally think that the getter should have at least as many properties as the setter, so I'd like to know why it was designed this way.

### Steps To Reproduce

1. Add a Text Widget
2. Enter **Text1.** in the code editor and check the IntelliSense options
3. There are only 2 getter: text & isVisible but much more setter methods.

### Environment

Production

### Version

Cloud

**Comment by Nikhil-Nandagopal** [comment]
@zj131711 we didn't expect the need to have a user reference the color of a text widget since the developer is setting the color themselves. So they can always just define the color in a JSOjbect and reference that anywhere in the app.
The reference properties of a widget are only the internal values that a developer would not have access to.
