### ISSUE TITLE
[Bug] Creating a new datasource from an API with existing datasource copies values from the old one.

### ISSUE THREAD

**Issue by ofpiyush** [appsmithorg/appsmith#2929]
## Description

The new datasource ends up getting config from the older one.

### Steps to reproduce the behaviour:
Add steps to reproduce this behaviour, include console / network logs & screenshots
1. Create an API.
2. Attach a data source.
3. Add some headers to the data source and save.
4. Go back to the API and remove the datasource, change URL.
5. Create a new datasource from the API -> "store as datasource".
6. Headers from old datasource get copied to the new one.

### Important Details
 - Version: All
 - OS: All
 - Browser: All

**Comment by ApekshaBhosale** [comment]
One more case in this, new URL with no datasource takes datasource from previous API. 

Steps:
1. Create API
2. Attach a data source
3. Run API
4. Change URL

Response : "DEFAULT_REST_DATASOURCE is not correctly configured"
It's taking data source from previous API

@nidhi-nair Can you add your findings here please?

**Comment by nidhi-nair** [comment]
It seems that when an API with a datasource is replaced by one without a datasource, the embedded datasource is not getting updated within the action object. This is breaking for authenticated datasources since the embedded version of the datasource will never have encrypted information.

The API calls being made in both these cases will need to be checked, but seems like we're missing triggers to reset the action in the case @ApekshaBhosale has mentioned. Best guess is because pasting over an existing URL does not trigger onChange for a reset.

**Comment by nidhi-nair** [comment]
Increasing priority because this bug now breaks user experience negatively.

**Comment by nidhi-nair** [comment]
Close as it is not reproducible anymore
