### ISSUE TITLE
 [Bug]: S3 datasource screen in import modal has an additional End Point URL field 

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#29408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I import a json which contains S3 DS, an additional End point url field is added. 

### Steps To Reproduce

RELEASE:
<img width="1141" alt="release" src="https://github.com/appsmithorg/appsmith/assets/101863839/25dafd8b-f830-4e07-8f0f-a3950840cd1c">

PROD:
<img width="1124" alt="prod" src="https://github.com/appsmithorg/appsmith/assets/101863839/df71a1f3-690d-472c-8e8c-6242f4451149">

### Environment

Release

### Version

Cloud

**Comment by btsgh** [comment]
This is working fine in Production

**Comment by NilanshBansal** [comment]
@btsgh the enpoint URL field can also be seen in production.

https://github.com/appsmithorg/appsmith/assets/25542733/7b89ecef-2db1-45ce-a7ea-487e4288b5ef

**Comment by NilanshBansal** [comment]
It's due to the `datasourceConfiguration.endpoints` key present in export json for new applications created after merging of [this](https://github.com/appsmithorg/appsmith/pull/28146) PR. For older application export jsons, we were setting the complete datasourceConfiguration as null but post this change we only set sensitive fields as null.

Since, at the time of configuring S3, we don't accept the endpoint URL from the user, this field should **also not be set in the database** and hence should not be exported in the app json. 

<img width="867" alt="SCR-20231207-gtr" src="https://github.com/appsmithorg/appsmith/assets/25542733/5585d476-c76e-4a31-b4ed-d703a154ec46">

**Comment by btsgh** [comment]
Reducing the priority as per this [thread](https://theappsmith.slack.com/archives/CTHN8GX5Y/p1701946398160889?thread_ts=1701922055.561069&cid=CTHN8GX5Y)
