### ISSUE TITLE
[Bug]: Update the table version to v2 for generate CRUD functionality

### ISSUE THREAD

**Issue by AmanAgarwal041** [appsmithorg/appsmith#29567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Update the table widget version to v2 for generate crud functionality which is using v1 version right now

### Steps To Reproduce

1. Create a datasource preferably mysql, postgres, gsheet 
2. Click on generate page button to create the crud operation pages
3. Observe the table, its different what current table is present in the widgets panel.

### Environment

Production

### Version

Both

**Comment by AmanAgarwal041** [comment]
Earlier closed issue : https://github.com/appsmithorg/appsmith/issues/18250

**Comment by AmanAgarwal041** [comment]
Observations : 
https://github.com/appsmithorg/appsmith/pull/29457#issuecomment-1853529602

**Comment by sneha122** [comment]
Moving this to blocked state as I need confirmation from @sbalaji1192 for the order of columns, The tests failing in [PR](https://github.com/appsmithorg/appsmith/pull/29457) are failing due to legit reasons, in table v1, custom column for delete action would appear in the end but after replace v1 with v2, custom column for delete action is appearing in the beginning, this causes tests to fail
