### ISSUE TITLE
[Bug]: Themes are not retained when user does partial import and export

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#29916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Themes are not retained when user does partial import and export
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/8331eae2-d6a3-45e2-99a6-214b83e8d4b6">
<img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/b4db01bf-29f3-478a-8e54-ef0f47366bc4">

### Steps To Reproduce

1. Go to release.app.appsmith.com
2. Open the application which has the theme applied
3. Now go the page inside the app which has custom theme applied
4. Now click on that page and open the 3 dot meat ball icon and click on export now inside the modal select all datasource , widgets and queries
5. now once the page is exported
6. create a new workspace and a app now try to import that part in the new app
7. Now check the theme colour 
8. The applied theme colour will not be retained it just go back to default theme colour

### Environment

Release

### Version

v1.9.58

**Comment by rahulbarwal** [comment]
@RakshaKShetty this is expected behavior. 
Theme is an application level setting, so when you export a widget and import it in a new app it would indeed take the theme of the destination app. 

In the screenshot you updated theme to green color, 
1. but at the same time, before importing if you change the theme to red or pink on the destination app
2. and then import it again, it would take the new theme colors. 
3. Note: if you change the cell color(or any proerty of widget itself, it would be retained)


Let me know if you disagree or have any questions.

**Comment by RakshaKShetty** [comment]
@rahulbarwal Thanks a lot for the detailed descriptions. yes this looks correct i will go ahead and close this issue
