### ISSUE TITLE
[Bug]: Unable to migrate the business license to enterprise license on release license manager app

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#29998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to migrate the business license to enterprise license on release license manager app
 <img width="1440" alt="image" src="https://github.com/appsmithorg/appsmith/assets/45958978/d3f8924c-1df6-4c49-a12a-3357f46d5caa">

### Steps To Reproduce

1. Create a license from release customer portal make this license as a paid license 
2. now go to https://internal.appsmith.com/app/license-manager-app/view-licenses-649d3e531572505690b1ea7a?branch=release
3. check for same user and click on Action button
4. Now select the migration link and now select all the required detailes and click on confirm
5. The error message is displayed as in the attached screen shot

### Environment

Release

### Version

v1.9.58

**Comment by vivonk** [comment]
This issue is happening on backend when we are trying to attach a zero price plan for tracking usage but somehow price we are attaching belongs to an archived product because of which subscription update fails. We need to ensure that we are attaching only an active product's price for tracking usage.

**Comment by pranayagarwal96** [comment]
Closing the issue as this is no longer needed
