### ISSUE TITLE
[Feature] Not floating property panel

### ISSUE THREAD

**Issue by chrdoud** [appsmithorg/appsmith#3029]
## Summary

A fix property panel.

## Motivation

Hi, after few hours in appsmith i think that the floating property panel is not very productive. It's sometime hard to make prop panel visible. It can hide some element you want to view. It some time hard to see where it was.

**Comment by areyabhishek** [comment]
We built an early version of this. 
https://www.loom.com/share/a893da277e474f86876ded3df1b04a1d
If you want to try it out, please login here: https://deploy-preview-3242--appsmith-editor-ce.netlify.app/applications/60394bd4e05a915e92acb70d/pages/60394bd4e05a915e92acb70f/edit 
To login use: community@appsmith.com / community because the user database is different here.
