### ISSUE TITLE
[Bug]: onboarding flow is broken on release

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#30308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://theappsmith.slack.com/archives/C05P3ME9MBR/p1705313846909069

### Steps To Reproduce

in the slack thread

### Environment

Production

### Version

Cloud

**Comment by sneha122** [comment]
This was broken due to the changes made for consolidated APIs [PR](https://github.com/appsmithorg/appsmith/issues/29650) https://github.com/appsmithorg/appsmith/issues/29939. Since these PRs have been reverted for the time being, onboarding flow has started working again. @vsvamsi1 whenever you incorporate these changes back in, Please make sure to check the onboarding flow once.

CC: @rohan-arthur
