### ISSUE TITLE
[Enhancement]: Check for ca-certificates even if they are symlinks and not just files

### ISSUE THREAD

**Issue by pratapaprasanna** [appsmithorg/appsmith#30928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently our entrypoint script does check for ca-certificate files and ignores symlinks.

### Steps To Reproduce

Add a cert in ca-certs as symlinks and check if ca-certs are picked up in the logs

### Environment

Production

### Version

latest

**Comment by felixthekraut** [comment]
In Kubernetes when using a secret or configMap the files will always be mounted as symlinks instead of files (some context: https://stackoverflow.com/questions/50685385/kubernetes-config-map-symlinks-data-is-there-a-way-to-avoid-them). 

One workaround could be to add an additional init container that copies the files into /appsmith-stacks/ca-certs or adding a copy script to the appsmith container. Being that the init containers are managed by the helm chart I would prefer not to go that route.
