### ISSUE TITLE
[Bug]: no way of getting the updated sourceModuleId for existing modules after convert API from consumer side is called 

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#30976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When convert query to module is done, Under the hood , package is republished,
in that session, if we add another module instance from the same package(except from the newer module) , we have the older sourceModuleId that is being sent in the payload

Because of this , we are getting error from backend, dealing with stale data

### Steps To Reproduce

1. In an app, create a module from existing query (Make sure to add it in an existing package and not NEW package)
2. Now without page refresh, try to add another instance from the same previous package (Don't create instance from the newly created module in the previous step)
3. error will be thrown, dealing with older version/stale data

### Environment

Production

### Version

Self hosted

**Comment by kamakshibhat-appsmith** [comment]
Not fixed on release-ee @ashit-rath @ankitakinger

**Comment by ankitakinger** [comment]
This is happening because on conversion, a package is re-published, which was leading to user not being able to create a new module instance from the previously existing modules in that package (as it has stale `sourceModuleId` linked which needs an update).

To fix this, simply fetching modules wouldn't have helped as the `sourceModuleId` for the existing module instances on the page no more matches any of the module ids from the newly fetched `moduleMetadata`. Hence we need to also re-fetch all the module instances to fix stale module instances.

It doesn't make sense though to update everything modules and packages related all over the app just because a user converted 1 single query to module instance. I think we should look into package versioning and solve this in a better way since before re-publishing the package, the other modules were not touched. We do not change the ids of any entity at all just coz it got updated.

Moving this to needs info pipeline.

**Comment by subrata71** [comment]
### RCA
We need to fetch all module instances for the current page to avoid this while adding the newly created module to an existing package. This is because publish is done at the package-level and during publish we create a new version of everything thus it changes the sourceModuleId in the existing module instances as part of the auto-upgrade process.
