### ISSUE TITLE
[Bug]: Transition between edit and preview modes appear glitchy, more noticeable when modal is open

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Transition between edit and preview modes appear glitchy when a modal widget is open

### Steps To Reproduce

1. Toggle between view and preview mode

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://www.loom.com/share/060821de64434fb493f91927f281d2af

### Version

Cloud

**Comment by marks0351** [comment]
Bug in discussion: when any widget(yes not just modal widget) is selected, transition between edit/preview mode is glitchy

RCA: 
This happens because of the entire app rerendering twice when moving in between edit/preview mode.
two updates happen on the platform level when transitioning between edit/preview mode.
- url update (essential when moving in between js editor/query editor to preview mode)
- preview mode state update

potential solution: skip updating url for editor transitions.

@hetunandu can we pls fix this as part of IDE.
cc: @ramsaptami @somangshu
