### ISSUE TITLE
[Bug]: Deploy times out when trying to fetch status

### ISSUE THREAD

**Issue by ykag** [appsmithorg/appsmith#31791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I click Deploy, the git fetch status action times out after 30 seconds, this happens about 90% of the time, with the 10% being it working correctly and as expected.

This problem stops me from being able to commit and deploy changes to my application.

I would expect it to allow me to commit my changes and deploy a new version of my application.

"There was an unexpected error" alert shows up at the top.

![CleanShot 2024-03-14 at 10 17 29](https://github.com/appsmithorg/appsmith/assets/17621472/61521be2-88aa-4367-8598-f38bd714c995)

### Steps To Reproduce

Go to Deploy
Wait for Fetch Status to finish running
It does not finish
Unable to commit and deploy

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Self Hosted - v1.16

**Comment by brayn003** [comment]
Hi @ykag ,
Could you please share the specifications of the instance where you have deployed Appsmith?

**Comment by ykag** [comment]
@brayn003 we're running this on an m6a.xlarge instance, but it's done through ECS, so we have specified in the task definition a minimum of 4096mb memory to the task.

**Comment by riteshkew** [comment]
@ykag Thank you for getting back with the information. What you mentioned could be the case and since there are other possibilities of why this is failing, I would request you to please schedule a call with us, so that we can expedite the resolution from our end. You can use this [link](https://calendly.com/ritesh-catchup-15/30min) to schedule a call, please include support@appsmith.com as part of it.

**Comment by Nikhil-Nandagopal** [comment]
@ykag glad to hear it! We're now closing this issue. Let us know if this happens again
