### ISSUE TITLE
[Bug]: when mustache brackets are used outside, jsonpathkeys are not getting evaluated/refactored properly leaving client evaluations to send undefined as values in request

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#31807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

[Slack Thread](https://theappsmith.slack.com/archives/C04GRCN4CS3/p1710412801156269)

when mustache brackets are used outside, jsonpathkeys are not getting evaluated/refactored properly leaving client evaluations to send undefined as values in request

[Demo App.json](https://github.com/appsmithorg/appsmith/files/14603383/Demo.App.json)
[Demo Pkg.json](https://github.com/appsmithorg/appsmith/files/14603385/Demo.Pkg.json)

### Steps To Reproduce

.

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud/Release

**Comment by subrata71** [comment]
We have reduced the estimate to 1 SP as we decided to a proper RCA only. And based on the RCA we will decide whether we should prioritise solutioning this. 
cc: @ashit-rath

**Comment by subrata71** [comment]
### RCA (WIP)
Every input in `jsonPathKey` in the underlying entities of the module instance is getting refactored by pretending the name of the module instance name. If this refactoring is not done properly the client side will send undefined value for such jsonPathKeys during run time.

Package
{{
	{
		"k1": inputs.input1 + " ~ " + inputs.input2
	}
}}

"jsonPathKeys": [
    "\n\t{\n\t\t\"k1\": inputs.input1 + \" ~ \" + inputs.input2\n\t}\n"
]

Now, if this module is instantiated and let's say the name of the moduleinstance is `ModuleX1` then the jsonPathKeys for the underlying action is expected to be


"jsonPathKeys": [
    "\n\t{\n\t\t\"k1\": ModuleX1.inputs.input1 + \" ~ \" + ModuleX1.inputs.input2\n\t}\n"
]

But currently, due to this problem with AST it's not getting refactored in the expected way.
