### ISSUE TITLE
[Bug]: Input widget icon does not complete rendering when alignment is changed to left

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#31928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Input widget icon does not complete rendering when alignment is changed to left

### Steps To Reproduce

1. Drop an input widget on the Anvil DP (https://ce-28238.dp.appsmith.com/ currently)
2. add an icon to the widget
3. change it's alignment as seen in the video & observe the loading button appear with a perpetual loading icon
4. refresh the page and observe the loading icon is still present

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/d4c170bf025a4d0ca9890d6e884b6a91

### Version

cloud

**Comment by KelvinOm** [comment]
Fixed in current code base
<img width="1048" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkUvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf80034d2a6ae5367d08e0196cf22321e4775360/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202024-04-08%20%D0%B2%2012.35.25.png" alt="Снимок экрана 2024-04-08 в 12.35.25.png" />
