### ISSUE TITLE
[Bug]: Unnecessary vertical aligners show when a checkbox widget is empty

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unnecessary vertical aligners show when a checkbox widget is empty

### Steps To Reproduce

1.  drop a checkbox first and checkbox group widget next to each other
2. Clear options on the checkbox group widget
3. Try to move the checkbox widget and notice a verticle aligner show up but dropping the dragged widget to the line does not amount to anything

### Environment

Deploy Preview

### Severity

Low (Inconsistent UI/UX)

### Issue video log

https://www.loom.com/share/6acaf057fe404d489bbba4f60266dd22

### Version

cloud

**Comment by KelvinOm** [comment]
@marks0351 @ramsaptami Could you check this with recent changes?

**Comment by ramsaptami** [comment]
checking this on the latest builds and I can still see this issue @KelvinOm

**Comment by marks0351** [comment]
so the issue here is that even on drop nothing happens, its because the widget is being repositioned to its own original position. this happens if the options are present or not for checkbox group.

What baffles me is that there is an update happening assuming that its a new position, which happens only when the checkbox group is empty. That is an issue.
@ramsaptami can you confirm if this issue still needs a `high` priority.

**Comment by ramsaptami** [comment]
@marks0351 this doesn't need to be fixed asap but needs a fix before GA so I'm marking it `medium`
