### ISSUE TITLE
[Bug]: New API button doesn't work from REST API datasource review page

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#32064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

This is only on https://release-ee.appsmith.com/

The `+ New API` doesn't respond

https://github.com/appsmithorg/appsmith/assets/94514895/72275de9-0af2-4622-aab8-5860159e912f

### Steps To Reproduce

1. create a new REST API datasource - enter any URL and click save
2. Add config details for any one of the environments
3. Try switching to a different environment.
4. Go to the created datasource
5. click button `+ New API` and see that nothing happens

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

Release

**Comment by rohan-arthur** [comment]
[thread](https://theappsmith.slack.com/archives/C040LHZN03V/p1711443434764759)

**Comment by diegorolf** [comment]
Not sure if this works, but perhaps my issue has the same root cause. Just for one app I am unable to create new JS or queries. The action times out I think, and until it does it blocks me from editing existing queries.

[Discord ticket](https://discordapp.com/channels/725602949748752515/1221847432934064278)
