### ISSUE TITLE
[Feature]: Enable tooltips on table column header

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#32097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Sometimes table column headers require a longer explanation of a concise heading. Having a tooltip field for columns will enhance usability of the table widget

### Why should this be worked on?

Improve functionality and usability of the table widget

**Comment by BharathRavi27** [comment]
This can be really beneficial in a lot of cases. Table header could be a very short title but a tooltip can be used to explain any related information about column. 
<img width="386" alt="Screenshot 2024-04-22 at 9 41 08 AM" src="https://github.com/appsmithorg/appsmith/assets/22723153/ab077e9f-4016-4eeb-9edc-8551212ee824">

cc @blossom-babs

**Comment by hugorn** [comment]
It would be more complete if there was another way to do this, since not every field will come directly from the database, it could be a sum of fields, for example select sal, sal*1.5 as another from employees
The tooltip like this is better @blossom-babs 

<img width="413" height="113" alt="Image" src="https://github.com/user-attachments/assets/751d44f1-4c6c-4e93-b8b4-5554f9837178" />
