### ISSUE TITLE
Port in datasources form should be set by default

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#32136]
https://www.notion.so/Port-in-datasources-form-should-be-set-by-default-cf1c30e7fb0d4142b95eaa73206a4ff1

**Comment by AmanAgarwal041** [comment]
This issue was marked as `Ballpark: XXS`. We were unknown to the number of test failures due to this change, which led to this estimation. This issue is `S` estimation. The test failures were due to :
- Port values on creation of datasources, which were appending port values to default ports
- Updation in the datasource test connection error messages
- New test case to check the default port values.

**Comment by AmanAgarwal041** [comment]
Reopening this issue as the pr is reverted : https://github.com/appsmithorg/appsmith/pull/32726
