### ISSUE TITLE
[Bug]: SQL query created in JS Object is not working in runtime on temporal

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#32337]
1. I created the SQL query as a string as shown in below image
2. I'm binding the query string in the Postgres Query by using `{{this.params.query}}`
3. The query is failing and throwing an error.

<img width="1103" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be9026865809dbac0046b2a5ab86785f1185666d/image.png" alt="image.png" />

<img width="1848" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXNvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0aa3bdd9e8c46c6cda0c205b2cd4d661cf579e6/image.png" alt="image.png" />

**Comment by nsarupr** [comment]
So, this is happening because of the use of `Prepared Statement` toggle
When using the whole query with **Prepared Statement toggle ON**, we have a callout saying that `Dynamic bindings in prepared statements are only used to provide parameters inside SQL query. No SQL query found.`, but the same isn't present when using query from inside Workflows.

From our docs: https://docs.appsmith.com/connect-data/concepts/how-to-use-prepared-statements#dynamic-where-clauses

| Application |
| :---: |
| Query: Use prepared statement ON |
| ![Screenshot 2024-04-17 at 3 27 43 PM](https://github.com/appsmithorg/appsmith/assets/20905988/e2b509c4-f7cd-43d7-bc85-f6d1f0b2dee1) |
| Gives error when using the statement directly |
| ![Screenshot 2024-04-17 at 3 27 12 PM](https://github.com/appsmithorg/appsmith/assets/20905988/1e2183e0-5caa-428b-ad8c-fcec6eaa1507) |
| Query: Use prepared statement OFF |
| ![Screenshot 2024-04-17 at 3 38 26 PM](https://github.com/appsmithorg/appsmith/assets/20905988/4b696bd9-e2ed-4a7e-9ec0-bcfeb501dc6e) |
| Runs the statement properly |
| ![Screenshot 2024-04-17 at 3 38 11 PM](https://github.com/appsmithorg/appsmith/assets/20905988/3c1894ce-4944-48e7-851a-85a22ae12931) |


| Workflow |
| :---: |
| Query: Use prepared statement OFF |
| ![Screenshot 2024-04-17 at 3 34 02 PM](https://github.com/appsmithorg/appsmith/assets/20905988/1f28abd9-b955-4fae-969f-278d2ecc225a) |
| Runs the statement properly |
| ![Screenshot 2024-04-17 at 3 33 51 PM](https://github.com/appsmithorg/appsmith/assets/20905988/de13d68a-fc09-44ba-958a-5331fe6892bf) |
| Query: Use prepared statement ON |
| ![Screenshot 2024-04-17 at 3 40 01 PM](https://github.com/appsmithorg/appsmith/assets/20905988/b540804a-f006-4b37-b322-3cc9485adec0) |
| Gives error when using the statement directly |
![Screenshot 2024-04-17 at 3 40 33 PM](https://github.com/appsmithorg/appsmith/assets/20905988/21858e66-8e21-4e34-8f84-db3aa1ceddc7)

**Comment by nsarupr** [comment]
Closing this issue as created a another to fix the issue: https://github.com/appsmithorg/appsmith/issues/32737
