### ISSUE TITLE
[Bug]: In the split panes mode, in the ui section, as we hover over the widget, widget's border does not appear

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#32495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

 In the split panes mode, when I click the ui section, as I hover over the widget, widget's border does not appear

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/d2bf967d-a53d-4493-86e2-e6d47acf4782

### Environment

Production

### Severity

Low (Inconsistent UI/UX)

### Version

Cloud v1.19

**Comment by hetunandu** [comment]
This is an expected outcome for side by side

**Comment by rohan-arthur** [comment]
@btsgh the current behaviour is intentional - we want to signal to the user that there is a difference between selecting the widget (say, to make some edits to the properties), and interacting with the widget (say to change some selected option in a select widget). 

In order to achieve this, we have to discern the user's intention when they are clicking on some widget in the canvas. I explain in the attached video, please watch with sound

https://github.com/appsmithorg/appsmith/assets/94514895/0b358d87-9b91-481e-8781-ad55bf258f7a
