### ISSUE TITLE
[Bug]: Deleting jslib gives incorrect status in modal

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#32734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Deleting a jslib does not give a message to the effect that the jslib is deleted. It only says Application Settings modified.

### Steps To Reproduce

https://github.com/appsmithorg/appsmith/assets/101863839/a44c43af-73c3-4a1a-9732-40bb2abe0a7e

### Environment

Release

### Severity

High (Blocker to building or releasing)

### Version

Cloud

**Comment by brayn003** [comment]
Just tested this - Reproduction of this issue is not just related to deleting the jslib. Here are some additional scenarios -
1. Add a jslib and commit > remove jslib > status for jslib doesn't show up > add a jslib > now both jslib changes show
2. Add uzip-module jslib and commit > remove uzip-module > jslib status changes showup > add jsonwebtoken > no jslib status change show up
3. Add jsonwebtoken jslib and commit > remove jsonwebtoken > jslib status changes don't showup

The best way I can describe this -
Jslibs is acting funny with git

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by btsgh** [comment]
On an existing app, 
1. On master branch, installed a new library jsonwebtoken. The commit existed in the modal. Was able to successfully commit.
2. Removed library. Commit existed in the modal. Was able to commit successfully
3. Installed jsonwebtoken on newbranch and committed - was successful - details seen in modal. 
4. Merged the above to master. Merge successful
5. Deleted jsonwebtoken. Saw the commit in the modal. Discarded and pulled. This was successful and jsonwebtoken was seen back in the list of jslib
6. Deleted jsonwebtoken from branch. Committed. Merged to master. Checked if jsonwebtoken does not exist in master as well. Successful
7. Tried all the above in a new git connected app.
