### ISSUE TITLE
[Feature] Disabled widgets need to be styled in the same way.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3294]
## Summary
The way input widget looks when disabled looks very different from the way a dropdown looks when disabled. Need to have a consistent looks for the disabled widgets. 

## Additional Context
This issue was reported by a user on Discord.
Pasting the chat:
```
One more issue/feature request:
- Disabled widgets should be styled the same way; in the screenshot the input background is greyed and the dropdown is not

Also, I think it's enough to just change the background, and to keep the text color in black or very dark grey, to get a bit more contrast
```

**Comment by somangshu** [comment]
@momcilo-appsmith Note:
 - We need a design guideline change here to get this consistent everywhere (disabled style on any widget)
 - We need design for any exceptional case is required.

**Comment by somangshu** [comment]
@areyabhishek should this be focused on right now?

**Comment by areyabhishek** [comment]
It's not urgent, but we need to address this problem for consistency.

**Comment by somangshu** [comment]
@yatinappsmith can we have some QA efforts towards this. We need to identify any inconsistencies visible across widgets, We can fix everything at once then

**Comment by vivekverma2312** [comment]
@somangshu Currently the colours are inconsistent for different widgets on disabled state. Refer the screenshot for all the widgets. 
<img width="928" alt="Screenshot 2021-08-10 at 12 12 48 PM" src="https://user-images.githubusercontent.com/83569920/128820406-502facbf-25b5-4f13-8de3-a58da2240d09.png">

The cursor design is also different for some widgets. The widgets for which the cursor design are different with input widget are: (Assuming cursor design is correct for input widget)
1. Label widget
2. Radio widget
3. Rating widget
4. Rich Text Editor

**Comment by somangshu** [comment]
We need more information here @vivekverma2312, As discussed before kindly discuss with the design team to find the set of condition for a disable element given any widget. Once we have that we should formulate a comprehensive list consisting of all required change which will be worked on by the dev. I want to look as this holistically so that we can make better changes and have better consistency in the future

**Comment by momcilo-appsmith** [comment]
My suggestions:
For buttons:
* Use rgb (194,197, 199, 1) as background color
* No border
* Text in white

For Inputs:
* Leave it the same way it is

For checkboxes, radio buttons and toggles:
* Use the same settings as for the toggle button

**Comment by areyabhishek** [comment]
Thanks could you update the design system with this too?

**Comment by somangshu** [comment]
What about the RTE @momcilo-appsmith ? Is the current state alright?

**Comment by momcilo-appsmith** [comment]
@somangshu The current state is alright.

**Comment by RakshaKShetty** [comment]
the issue persists in 3 scenario
1. Select, Multi-select, and multi-select trees when these 3 widgets are disabled the style is not the same 
![image](https://user-images.githubusercontent.com/45958978/134005185-62d9581a-1926-47a3-8544-91319f9c27c6.png)
2. For the Rich editor widget when the user hovers on the options instead of hand icon the arrow icon is displayed this not same as in other widgets
3. When the text widget is disabled text color looks different from the input widget 
![image](https://user-images.githubusercontent.com/45958978/134005558-89dd0edc-00a5-44e2-8e1f-a9c6d883d5bc.png)

**Comment by eco-monk** [comment]
There seems to be a misunderstanding about the text widget
Text widget doesn't have a disabled mode, it has the option to disable processing text as links.
And it's used as illustrated below. 

![Screen Recording 2021-10-12 at 16 31 43](https://user-images.githubusercontent.com/66776129/136944132-22b0d832-64dc-41dd-91e1-ab3de40837b2.gif)

So, this cannot be treated as a disabled state.

@somangshu, please correct me If am wrong.
