### ISSUE TITLE
[Feature]: Support rsa-sha2-256 and rsa-sha2-512

### ISSUE THREAD

**Issue by hud-21326** [appsmithorg/appsmith#32970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add rsa-sha2-256 or rsa-sha2-512 as options when creating an SSH key in Appsmith for Git integration.

### Why should this be worked on?

Azure DevOps is [currently](https://devblogs.microsoft.com/devops/ssh-rsa-deprecation/) deprecating support for SSH-RSA keys. It also does not support ECDSA keys. Since those are the only two SSH key types that can be generated in Appsmith, this seems to break the integration between DevOps and Appsmith

**Comment by lbustelo** [comment]
+1 We just started experiencing this issue today.

**Comment by jhu8** [comment]
+1 We use Azure as our git provider and started experiencing issues with our git integration today as well.

**Comment by nidhi-nair** [comment]
Sorry that you have had to face such a disruption so abruptly folks! We're looking into this and will keep you updated on progress.

**Comment by amenasse** [comment]
Just wanted to get some clarification on the fix, #33052 seems to address a different problem - atomic commits not being supported by Azure Devops.

When generating keys and connecting does the appsmith git integration use one of the supported SSH signing algorithms mentioned in the initial ticket description ? We are seeing behaviour that could be related to the depreciation schedule mentioned in the article.

**Comment by nidhi-nair** [comment]
Hey @amenasse , thanks for raising your concern. While investigating this problem we discovered that since we introduced atomic pushes, all of Azure operations were affected. The earlier PR was to address that blocker and unblock folks that were only intermittently affected by the brownout phase that Azure's deprecation is in.

We hadn't been able to reproduce and hence successfully test our solution for moving on the SHA2 signing algorithms until very recently, but that's affected our test repositories as well now, so we're on our way to solving the issue. I'll re-open the issue so that the original intent is taken care of as well. Thanks for pitching in. 🙂
