### ISSUE TITLE
[Task]: Add mongoDB unique index for slug field in Tenant collection

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#33377]
### SubTasks

The `Tenant` domain `slug` field has an `@Unique` [annotation](https://github.com/appsmithorg/appsmith/blob/d1c9bde439138f0d6d4b414ff001f0fc07c93027/app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Tenant.java#L21) but there is no unique index for slug field in the mongo database. We should add an index in the database to maintain consistentency. 

<img width="1187" alt="image" src="https://github.com/appsmithorg/appsmith/assets/25542733/feef43e5-f472-40d2-91e7-72227bca4493">

**Comment by NilanshBansal** [comment]
@akshayvijayjain yes definitely.

**Comment by Naveen-Goud** [comment]
@NilanshBansal  can we use@Indexed annotation instead of @Unique, to gererate unique slug id in db?

![Screenshot from 2024-05-20 13-07-13](https://github.com/appsmithorg/appsmith/assets/72243823/bae76ec6-879b-4d5f-aecb-28ddc949d5bd)

**Comment by nidhi-nair** [comment]
@Naveen-Goud , agreed with your analysis. However, as a practice, we rely on migrations to create indices in the database and not annotations. The ask from this issue is that we create such a migration for this field as well. The reason we opt for migrations and not annotations is that the annotation is a part of compiled code. Spring auto-magically creates the index if it finds such a reference in code. However, if the annotation were to be slipped as part of any refactor, future "fresh DBs" would not have this index at all. This is much harder to do with migrations.

**Comment by Naveen-Goud** [comment]
hello @nidhi-nair , thanks for the response , I couldn't understand last statement regarding **"fresh db's"**.
but  I have worked on task , and replaced with @Indexed , and also made a migration file which generate a unigue index for the slug field.
![image](https://github.com/appsmithorg/appsmith/assets/72243823/b0bf65d1-40d6-4372-820b-a915e956d303)

this migration wil make the slug field unique id and will not  accept any  id which are similar , if the data s similar then it returns error 

![Screenshot from 2024-05-23 17-43-13](https://github.com/appsmithorg/appsmith/assets/72243823/bc8fb0a4-21bf-4e4f-93a0-5f4109b0e361)

and also because of the migration step , the slud id are arranged in ascending order.

**I also  have a question** , if we insert data with one field , the **slug** is considering **null** as id for first time and not allowing to create another object with inserting one field.

does the task also says that id's should be created in db when we try insert data without slug field?

**Comment by NilanshBansal** [comment]
This seems like a premature optimization as currently we have not moved to multi-tenancy. Right now, there is only 1 document in the Tenant collection always as there is only a single Tenant. 
Adding index to that does not make much sense right now. 
When we implement multi-tenancy we might figure out that ensuring uniqueness only on this field might not suffice. We might need to add other fields along with it to make a composite unique index.
