### ISSUE TITLE
[Bug]: Modal deletion behavior issue

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#33380]
https://www.loom.com/share/c447778f45814ce6a4a677d6f6c080a9

- modal reopens if modal deletion + undo delete was followed by another widget's deletion and undo delete action
- close icon is highlighted when modal deletion is undone

**Comment by marks0351** [comment]
there are two problems here
- undo/redo selection flow doesn't seem to be good enough to figure out the widget that is last changed coz it depends upon indexing the keys of the diff object [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/ReplaySaga.ts#L107) which is not accurate all the time. same issue happens in fixed layout as well.
- undo/redo selection also does not work if the widget is deleted as and when it is first added because all widgets see a diff since widgets shed some properties that are coming from fixed layout. we will need to clean up addition flow to make sure that does not happen.

I am moving this to product backlog and decreasing the priority to medium.
cc: @ramsaptami @somangshu
