### ISSUE TITLE
[Bug]: Widget's don't visually align with each other during certain conditions

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#33447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When a hug widget is placed with a fill widget, especially a widget with horizontal orientation, then the widgets do not align in a zone

### Steps To Reproduce

1. Drop a button widget on a zone
2. Drop a switch group widget on a different zone and change it's orientation to horizontal
3. Not place the switch widget next to the button and notice the alignment

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/8bb246103e114c2e861e6fa03a7ae667

### Version

cloud

**Comment by SaiCharanChetpelly31** [comment]
@ramsaptami  I set up Appsmith locally but can't find "zone" or "anvil" anywhere in the application. I can't able to reproduce the issue. Is this related to Anvil project?

**Comment by ramsaptami** [comment]
@SaiCharanChetpelly31 that's correct, it's part of the Anvil which is still a work in progress.
Please look at issues marked 'good first issue' if you're looking to contribute

**Comment by ichik** [comment]
We will create a comprehensive algorithm for this to guide the default widget placement. This is an exercise in combinatorics that would require significant time investment.
As far as priorities go this is rather low for now: we have more foundational needs to address.
First, we need to have a bigger widget set so that we don't have to immediately overhaul this algo and polish the base of the experience.
