### ISSUE TITLE
[Bug]: whitelisting IP addresses banner in datasources is not copy-able

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#33676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Say I want to connect to mongodb. When I am creating the new datasource, I see the banner to whitelist appsmith IP addresses. 
For ease of use, I would like to copy the IP addresses, but the text in that banner is not copy-able. 

### Steps To Reproduce

1. open any app
2. go to data section
3. click + to add a new datasource
4. select e.g., mongodb
5. see the blue banner on top for whitelisting IP addresses
6. try to copy it --> not copy-able

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud

**Comment by razelos** [comment]
Hi, I'm interested in picking up this issue. As far as I understand the code responsible for this text is located in the [https://github.com/appsmithorg/appsmith/blob/d71e050fa6ad1da1aed222d756fb2c523c75d322/app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx#L108](url). 
We should change some settings in the Typescript code, so that the text in the blue banner is copy-able.

**Comment by Nikhil-Nandagopal** [comment]
@razelos sure go for it!

**Comment by razelos** [comment]
Great will make a PR in the next few days!
