### ISSUE TITLE
[Feature] Provide a feature / utility to export / import a single app from mongo db.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3424]
## Summary
Some users want to export / import select apps only from their db.

Additional info:
A user has suggested something along these lines: https://stackoverflow.com/questions/53473151/mongodb-dump-filtering-documents-and-fields

**Comment by marcius** [comment]
The required steps could be:
- create a set of views that filter all the collections by a specific app ID
- run mongodump with the --viewsAsCollections option

The dump should be restorable only to a clean database, to prevent conflicts with IDs

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit what are your thoughts on this?

**Comment by mohanarpit** [comment]
In order to export specific apps, we also need to export the following datasets that are tied to the application:

- Actions, pages & layouts inside the application
- Any datasources being used by actions in the application
- All users who have access to this datasource/action with the correct permissions. Else what happens on import in another DB? 

Also, during import, we have to ensure that the ids for each of the entities that we export don't clash. Hence, the import functionality needs to be implemented. Else, it may work for some users and won't work for others.

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit Got it. Then I think it makes sense to do this as part of git sync itself. Since we need to have export / import there as well.

**Comment by Nikhil-Nandagopal** [comment]
We'll add the export option below the duplicate option in the app context menu
We'll add an import option in the org context menu

**Comment by pranavkanade** [comment]
@RakshaKShetty if you have tested this, can you please close this issue?
