### ISSUE TITLE
[Bug]: Back button doesn't work as expected, when copy pasting the Workspace Settings page URL

### ISSUE THREAD

**Issue by samhithav27** [appsmithorg/appsmith#34431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When I am on some other URL (eg: google.com), and I paste the Workspace Settings page URL onto the browser (eg: https://appsmith.z-apps.io/workspace/665da9a39f855f14f89855c7/settings/members) 
and then when I click on the Back button
I'm redirected to my previous URL (eg: google.com) 
It should redirect me to the Workspaces Page 

### Steps To Reproduce

1. Go to some random URL
2. Copy https://appsmith.z-apps.io/workspace/{workspace-id}/settings/members
3. Paste the above URL to a browser and click enter 
4. Click on back button
5. You will be redirected to the URL in point 1

### Environment

Release

### Severity

Medium (Frustrating UX)

### Version

v1.28

**Comment by Nikhil-Nandagopal** [comment]
Bumping this issue up to prod because it should have made it's way there by now if it was not fixed

**Comment by saicharan-zemoso** [comment]
Hello @Nikhil-Nandagopal , can I work on this issue ?
solution:
The back button which is used in multiple places is accepting a prop "goTo" and if noting is sent then it is going back in history.
back button used:
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/utils/helperComponents.tsx#L42-L51

so we can pass the path so that would append to the history and redirect to that previous page insted of going back in the history.

**Comment by saicharan-zemoso** [comment]
The same component was used in workspace setting, user profile page, members setting page for workspace,etc. so we can see the same behaviour in all this pages.
