### ISSUE TITLE
[Bug]: Git integration does not detect "App name"

### ISSUE THREAD

**Issue by rubenmoralesfever** [appsmithorg/appsmith#34677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I have a protected "master" branch where I found that I misspelt the "App name" in the "App Settings".
The workflow that I would expect to be able to follow is:
- Create bugfix branch
- Modify "App name" in the settings
- Commit
- Merge branch to master

But I can not do that because the git integration does not detect when I change the "App name" field modification as a change:

![image](https://github.com/appsmithorg/appsmith/assets/167100004/5ab99051-8d2a-4c8f-860a-5019af456992)
![image](https://github.com/appsmithorg/appsmith/assets/167100004/b25a94db-9fb5-4410-86eb-1e3c4cba9833)

As a workaround I unprotected the master branch, changed the title without any commit, and then protect the branch again.

### Steps To Reproduce

- Change the "App name" in "App Settings"
- Try to commit

**Expected behaviour**: detected changes can be committed
**Actual behaviour**: no changes are detected, and the title is changed automatically in the "Current deployed version" and in the "Preview section"

### Environment

Production

### Severity

Low (Cosmetic UI issues)

### Version

Cloud - 1.29

**Comment by nidhi-nair** [comment]
Hi @rubenmoralesfever ! We do not in fact persist the application name to the git repository. This is so that you are able to maintain different names for the same app across instances, or even in the same workspace. For example, if you are in a single instance set up, you may wish to demarcate the QA version of the app from the Production version explicitly by calling the names differently. Alternatively, there may be scenarios where you wish to have multiple versions of the same app in the same workspace, which could have led to namespace collision.

However, we do understand that the fact that you are unable to edit a property that is not controlled on git in the `protected` mode is sub-optimal UX. We'll try to think of a way to allow access to this and other non-git-controlled properties like making an application public, or allowing forking.

I am retaining the priority on this task as low since you already have a workaround, hope the explanation for why application names are not git-controlled makes sense to you?

**Comment by Nikhil-Nandagopal** [comment]
After some internal deliberation we've concluded that the app name is not meant to be tracked in the repository so that users can explicitly name the staging and production versions of their apps. Since that is a core use case, we won't be picking this issue up.
