### ISSUE TITLE
[Bug]: Owner is not getting updated on cypress dahborad

### ISSUE THREAD

**Issue by ApekshaBhosale** [appsmithorg/appsmith#34707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Owner is not getting updated. 

### Steps To Reproduce

1. go to cypress internal app, flaky list tab
2. take any row which has owner, change owner to any name
3. api will be successful and modal will close
4. refresh the app
5. see the stale owner 

### Public Sample App

https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master&environment=production

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Issue video log

https://www.loom.com/share/320649a57a2e4b278149ae5301ee74da

### Version

Cloud

**Comment by rahulbarwal** [comment]
There were 2 problems here: 
* The update query in the app was missing the `asignee` param update which led to it not updating the name.
         *  Fixed by updating the query


* Inline editing was enabled which was causing some problems while sending the params in update query(as it was dependant on the JSON form instead of the table)
         *  Fixed by disabling the inline editing.
