### ISSUE TITLE
[Bug]: Upgrading docker to newest version is not able to start

### ISSUE THREAD

**Issue by jancoow** [appsmithorg/appsmith#34784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I upgrade my docker image to the latest version, appsmith/appsmith-ee:latest . However, after update, the docker container was unable to start, with the following error:

```

/opt/appsmith/entrypoint.sh: line 5: tlog: command not found

```

Same problem with v1.29. v1.26 seems to work. 

### Steps To Reproduce

Pull latest docker image and try to run. 

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

self hosted, latest

**Comment by Nikhil-Nandagopal** [comment]
@jancoow which version were you upgrading from?

**Comment by pratapaprasanna** [comment]
Hey @jancoow  can you please let us know on what host eg:(ubuntu/fedora/RHEL) is appsmith deployed ?

This issue is fixed in v1.30 . can you please try v1.30 and let us know if the issue still persists ?

**Comment by kcalliauw** [comment]
Hello @pratapaprasanna and @Nikhil-Nandagopaal

Since the OP didn't respond to this, I'll post here and say that I'm having the same issue with any version I've tried above 1.27. I'm running on a **Ubuntu 22.04 (arm64) host**.

v1.27 works fine, as soon as I update the image to latest, or any version above 1.27 I tried (manually tried latest as well 1.28 through to 1.32)

For now, I've reverted back to v1.27

**Comment by pratapaprasanna** [comment]
Hey the issue looks interesting can you schedule a call [here](https://calendly.com/goutham-8) ?

**Comment by kcalliauw** [comment]
After our chat it was identified that the PATH environment variable was being overridden by Portainer (it seems it had copied that path from an earlier version). Since "tlog" was not in the original paths that were in my PATH variable, the script could not be found.

I had to edit my Portainer container and set PATH to the following value (which is the default now):

`/opt/bin:/opt/appsmith/utils/node_modules/.bin:/opt/java/bin:/opt/node/bin:/opt/temporal/cli/bin:/usr/lib/postgresql/14/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

Essentially, when the PATH is being overridden, make sure that `/opt/bin` is present.

Thanks very much to the Appsmith team for the assist!
