### ISSUE TITLE
[Bug]: The license seen on the License and Plans page in admin settings is incorrect for the release-ee instance

### ISSUE THREAD

**Issue by btsgh** [appsmithorg/appsmith#34851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

In the https://release-ee-https.appsmith.com/ instance, in the License and Plans page, the `Subscription end date` shows up as 7 May 2024, how ever, the enterprise features are still visible.
In the License manager app, for that particular user, the expiry shows up as 7 Feb 2025. There is a discrepancy in the dates shown in the UI and the actual Subscription end date

### Steps To Reproduce

Go to the License & Plans page on https://release-ee-https.appsmith.com/ by logging in as a demo user with instance admin rights.
Note that the Subscription end date` shows up as 7 May 2024, but the Enterprise features are still visible

### Environment

Production

### Severity

Medium (Frustrating UX)

### Issue video log

https://jam.dev/c/2b5ca318-3981-4c7d-b46f-6323715d0d35

### Version

Cloud

**Comment by abhvsn** [comment]
@btsgh this is because the subscription on the specific license is already expired on 7th May'24, but we have manually extended the license expiry to 7th Feb'25. If we want get this in sync we can just create the subscription and attach that with the license. I'm not changing this as someone may have done this to test if we can set the expiry explicitely even if the subscription is expired. Please use another key if we don't want to experience this deviation.  

<img width="1015" alt="Screenshot 2024-07-11 at 7 57 46 AM" src="https://github.com/appsmithorg/appsmith/assets/41686026/2c969b31-8781-4a9c-bf16-258d62f15d2e">

**Comment by btsgh** [comment]
Ok understood @abhvsn . It does not affect my testing in anyway.. I was wondering whether this was a bug that could impact the user.

**Comment by abhvsn** [comment]
@btsgh this was deliberately added just for the purpose where we wanted to keep the instance active for enterprise customers even if the subscription is expired. This is because by default we offer 3months of grace period after the subscription ends, but we have seen longer cycles hence license expiry and subscription cancellation are treated as 2 distinct event for enterprise customers now. Also one can extend the license from the LMA so that in case if the instance is down it can be brought up immediately.

**Comment by btsgh** [comment]
Okay. Will close this out then as it is intended that way.
