### ISSUE TITLE
[Bug]: Postgres migration unable to add the external postgres DB

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#35283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Postgres migration unable to add the external postgres DB

### Steps To Reproduce

1. Pull the image locally
2. go to docker. ENV 
3. Update the old postgres URI to New Postgres URI
4. the instance come up but throws error as in screenshot

### Environment

Deploy Preview

### Severity

High (Blocker to building or releasing)

### Version

deploypreview

**Comment by RakshaKShetty** [comment]
Screenshot shot DB url used ` postgresql://hasura_role_6feb1118-ef37-4c96-958d-efd979aec286:idQhJ9Hal1ob@autumn-term-13741886.us-west-2.aws.neon.tech/first-herring-74_db_291097`
![image](https://github.com/user-attachments/assets/d76d42aa-a0e0-40e1-bd51-51a64d0f1463)

**Comment by RakshaKShetty** [comment]
[backend-a6c9e394e42b.log](https://github.com/user-attachments/files/16530552/backend-a6c9e394e42b.log)

**Comment by abhvsn** [comment]
@RakshaKShetty is this related to license key not getting copied over from doscker.env when we update the DB URL?

**Comment by RakshaKShetty** [comment]
@abhvsn Sorry for the confusion here i am manually updating the old postgres uri with the new external uri as in the above comment in this scenario i see that instance will come up but it throws the license error.

**Comment by abhvsn** [comment]
@RakshaKShetty yeah that's where I'm coming to, it means the license key is not present in the DB at all. There are 2 possibilities:
1. If the license is not present in the env file we can say that this is working as expected, because we are starting with the fresh DB instance.
2. If the valid license key is present in the env file and still we are ending up in this state that means we are not following the same behaviour that we have on release.

Can we test with both the scenarios once.

**Comment by RakshaKShetty** [comment]
@abhvsn If i am correct here we dont show the license key in env file i just verified it with the nightly pull so in that case what should happen
point 2

**Comment by RakshaKShetty** [comment]
Issue is fixed
