### ISSUE TITLE
[Bug]: A HITL request is only being created if the user who're triggering the workflow has at least `EDIT` access to the workflow

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith#35301]
1. Create an approval workflow
2. Trigger the workflow from an app
3. Give view access to the app to a user
4. Get that user to trigger the workflow, creating an approval request
5. The workflow run shows a log saying the approval request is created but, when get requests is called, the request is not present.

More in the video below
[Fathom Recording](https://fathom.video/share/m3ysmzT3gUcbyVcxzN8Ep51zu2_AWoXA)

**Comment by nsarupr** [comment]
The creation of approval requests requires the execute_workflows permission. When a role has EDIT permission, it automatically includes the execute permission, enabling approval request creation. Since other actions are currently happening without permission checks, we need to ensure that approval requests can also be created without requiring explicit permissions.

**Comment by ayushpahwa** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workflows-Pod-652fff131a95920b9bf2bc7e/issues/appsmithorg/appsmith/35301?planning-poker) with Zenhub @nsarupr @srix
