### ISSUE TITLE
[Bug]: Discarding changes on the app side after JSModule's function name is updated and published results in error

### ISSUE THREAD

**Issue by kamakshibhat-appsmith** [appsmithorg/appsmith#35439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Discarding changes on the app side after JSModule's function name is updated and published results in error

related PR that fixes this for JSObject --> https://github.com/appsmithorg/appsmith-ee/pull/4817#issuecomment-2270585896

Related Conversation : https://theappsmith.slack.com/archives/C04HERDNZPA/p1722845492601399?thread_ts=1722591426.072349&cid=C04HERDNZPA

### Steps To Reproduce

1. have a git-connected app with one JS moduleInstance in master
2. branch out from master, say create b1
3. Goto JS module , update function name from myfun1 to myfunone
4. republish
5. You will see uncommitted changes on the app side
6. Discard and pull 
<img width="978" alt="Screenshot 2024-08-05 at 12 53 51 PM" src="https://github.com/user-attachments/assets/af94387a-8c92-4373-afaa-def01f260952">

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

Cloud/self-hosted

**Comment by yalhyane** [comment]
Hello, is this fixed please in newer versions? we're having this same issue and it's preventing us from pulling changes from git.

**Comment by subrata71** [comment]
Hi @yalhyane,

We’re sorry to hear you’re encountering this issue as well. We understand how disruptive this can be, and we want to assure you that we are actively working on a fix.

**Current Issue:** When a function name is modified in the latest published version and local changes are discarded, it can lead to unexpected behavior, preventing successful discarding and pulling from the remote repository. This is due to a bug we’re addressing.

We’re working on a fix that will enable you to successfully discard and pull changes from the remote repository in the scenario described. Once the fix is live, please keep the following in mind:

**Discard and Pull:** Discard all local changes to pull updates from the remote repository. After pulling, you will need to re-publish the package to fix any issues with broken module instances resulting from the discarded changes.

**Commit and Push:** After re-publishing, you might have some uncommitted changes. Please ensure to commit and push these changes to maintain a clean branch state.
