### ISSUE TITLE
[Feature] Don't eagerly load the data that is *only* required in inactive tabs

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#3544]
Currently, queries that provide data to widgets in inactive tabs are also loaded on page load. However, this data is not actually needed until that tab is selected. This can be a good area of optimizing the number of queries that run on page load.

More reasoning behind this (and an implementation using existing Appsmith features): https://gist.github.com/tazmaniax/584447ab527e1198d3fbc72ac70d5b7e (full credits to the amazing @tazmaniax 😄)

**Comment by tazmaniax** [comment]
In my case the tabs are not loaded on page load but when a customer is selected and it relies on local storage to capture what customer data is currently displayed in what tab. The issue is the local storage is retained across page loads and this means if the same user is loaded prior to the page load the tabs won't lazy load the tab data because it thinks that customer data is already loaded. Need a way to clear this specific local storage state on page load. Could this be an `onPageLoad` trigger handler to keep it super generic and applicable for other use cases?
![CleanShot 2021-03-14 at 12 42 17](https://user-images.githubusercontent.com/1079943/111069965-6e5ed880-84c7-11eb-8d42-173e91b6ad8a.png)

**Comment by tazmaniax** [comment]
@sharat87 in the end I fixed my issue with the local storage by clearing the tab customer state variables in question when a customer is selected as this is the natural point when everything needs to be reloaded anyway. So for this scenario no extra support for clearing local storage at page loaded is needed. I've updated the gist to include the additional logic again to help anyone in a similar position, https://gist.github.com/tazmaniax/584447ab527e1198d3fbc72ac70d5b7e. Thanks for all your help!

**Comment by Nikhil-Nandagopal** [comment]
@tazmaniax thank you for the detailed description! Queries in inactive tabs are loaded by default but this can be changed by simply marking the query onPageLoad as false in the settings section. We do run these queries because it is possible that another section of the app is expecting to use the data in an inactive tab since inactivity only represents a selection state. I think the correct solution for these is to not persist the storeValue and flip the onPageLoad for these Queries as false as you've mentioned in your gist. Adding a JS editor will also make writing this logic easier. I guess I want to close this issue because by default appsmith is designed to show as much data as quickly as possible but if developers don't want this, they are free to turn it off.
