### ISSUE TITLE
[Feature]: Remove Page ID From URL

### ISSUE THREAD

**Issue by adleviton** [appsmithorg/appsmith#35556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I'd like to have urls without the page ID at the end. 

For example:
`http://appsmith.test/app/my-first-application/page1-6698622b0f2e0909f9c99296`
becomes
`http://appsmith.test/app/my-first-application/page1`

Is it possible for to implement this for at least self-hosted instances? 

I've seen a couple discussions related to this:

- https://old-community.appsmith.com/t/how-to-make-really-custom-urls-in-appsmith/1768/5
- https://github.com/appsmithorg/appsmith/issues/33373
- https://github.com/appsmithorg/appsmith/issues/33683

### Why should this be worked on?

Besides being a cosmetic enhancement, I think it would help any issues caused by the page ID changing, which in turn caused the URL to change. With a changing URL, it can be problematic for deploying across different instances, embedding in iframes, or even simple situations like linking to an app in an email.

**Comment by Nikhil-Nandagopal** [comment]
@adleviton we have this feature already documented and being on self-hosted has no bearing on this.
1. You can simply have your apps connected to git and pull new changes which will ensure that the URL do not change. The URLs do not change on every deploy and only if you import an app to a new instance.
2. You should also be able to deploy on a new instance with the same URLs and ids by restoring a backup of the instance instead of importing the applications. https://docs.appsmith.com/getting-started/setup/instance-management/appsmithctl

I'm closing this feature request since it's already open in #33683 as you pointed out and cloud vs self-hosted has no bearing on this.

**Comment by Nikhil-Nandagopal** [comment]
@adleviton I believe that is what the issue #33683 talks about. It's not something we are able to pick up right now and we haven't seen a strong need for it because you can use git or the backup method mentioned.
