### ISSUE TITLE
[Bug]: `navigateTo` hidden pages is not working properly and breaking apps in deployed mode

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith#35557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

NavigateTo function to go to hidden page is breaking. Users see blank page, if they refresh they can see the actual page but, this results in loss of the query params, which is not ideal. This is breaking the deployed apps in user's prod.

### Steps To Reproduce

[NavigateTo (1).json](https://github.com/user-attachments/files/16551065/NavigateTo.1.json)

1. Create 2 pages
2. Hide one
3. Try to navigate to from page 1 to hidden page.

I've uploaded a sample app.

### Environment

Production

### Severity

Critical (Broken Production apps)

### Version

Latest

**Comment by jeet-playleap** [comment]
We are also experiencing a similar issue
 Expected Behavior: Navigation between custom tabs should work seamlessly in launch mode.
Actual Behavior: Navigation between custom tabs fails in launch mode but works correctly in edit mode.

Please let me know if you need any further information or if there are specific steps we should follow to address this issue.

**Comment by AmanAgarwal041** [comment]
@jeet-playleap Can you more details about this issue or loom recording maybe, if would be easier for us to triage this issue ? Thanks

**Comment by luigifan9** [comment]
Experiencing the same issue, temporarily unhid pages. Application was working fine for months, until two days ago it just stopped working due to this bug.

**Comment by Nikhil-Nandagopal** [comment]
@luigifan9 this should now be fixed

**Comment by luigifan9** [comment]
@Nikhil-Nandagopal Yes it is fixed now, thanks
