### ISSUE TITLE
[Feature]-[800]: Deprecate form button widget

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#3613]
## Description

Since we have resetWidget as a trigger function, we can deprecate the form button widget added with every form widget. This needs to be a backwards compatible change.

**Comment by riodeuno** [comment]
- Update Form widget configs to use normal button widget
- Migrate DSLs to convert all "FORM_BUTTON_WIDGET" to be "BUTTON_WIDGET"
- Migrate all "FORM_BUTTON_WIDGETS" which have the reset action to use the `resetWidget` action instead
- Jest test for migrations
- Documentation update if needed.

**Comment by dilippitchika** [comment]
https://www.notion.so/appsmith/Form-Btn-to-Btn-36f43ca84d8046e1b0b62de587f81cc7 @somangshu @riodeuno can you review the PRD once?

This is written with the assumption that we migrate all buttons to be form buttons by default, and only allow form control edits when the button is in a form. Will need design changes if we decide to proceed.

**Comment by riodeuno** [comment]
@dilippitchika I cannot access the notion doc. Also, here is an updated approach which I had commented in the PR by @techbhavin https://github.com/appsmithorg/appsmith/pull/5917#issuecomment-923753538

**Comment by momcilo-appsmith** [comment]
Hey @dilippitchika I don't think you guys need any design help here, I think this is pretty straightforward.

**Comment by dilippitchika** [comment]
Adding the PRD Here

<h2>Objective</h2>
<p>Instead of having 2 different buttons one traditional and one for form we only need one button throughout Appsmith. This helps manage the apps well both for users and us.</p>
<p>As part of this, we need to evaluate how to support the traditional button in forms as well and work in all current button cases. This will involve thorough migration check.</p>

<h2>Success Metrics *</h2>
Goal | Metric
-- | --
Use a single button component in forms and non-form use cases | No of bugs raised on form button inconsistency should decrease. No of buttons broken for people’s existing apps should be 0.


<ol>
<li>Disable on invalid form data</li>
<li>Reset form on Success | As a user, I want to use the button from the widget panel inside my form to perform exactly same actions as form buttons do so that I can add new actions in my forms. | This may need a separate form section in our buttons which can be dynamically disabled |
| Button when not a part of the form widget, should disable the form specific configuration. There should be a clear demarcation about the configs being form specific configs. | As a user, when I use the button in other places I don’t want to worry about form configuration |  |
| None of the existing functionality either in forms or in the regular buttons should not break |  |  |</li>
</ol>
<p>This may need design change, will need a review with Momcilo and Vasanth.</p>
<h2> Documentation </h2>
<ul>
<li>[ ]  Changes to the button widget documentation explaining the form configurations in buttons with cases on when it’s enabled and how to configure it</li>
</ul>

## Design change
![Screenshot 2022-01-27 at 11 16 34 PM](https://user-images.githubusercontent.com/19730984/151414683-540e5f6f-d763-455a-853d-ae14632949f3.png)

Introduce the reset form on success and disable on invalid forms option in the button widget for now. Update the tooltips to the following
Disable for Invalid Forms - Works only inside Form widget. Disables the button if any required widget in form is invalid.

Reset Form on Success - Works only inside Form widget. Resets the widgets in the form if the On Click event succeeds.

**Comment by dilippitchika** [comment]
@momcilo-appsmith please review the above info once, this will be an addition to the content pane for button.

**Comment by somangshu** [comment]
@dilippitchika added a dev small dev note from the last research, please see if it is not inline

**Comment by dilippitchika** [comment]
@somangshu it is inline, let's currently name it as "Form options" as you suggested.

**Comment by momcilo-appsmith** [comment]
Just added this to our design tasks, will be updated.

**Comment by dilippitchika** [comment]
@somangshu assigning to us to clear this up and proceed

**Comment by somangshu** [comment]
We have two ways to move forward

- [ ] Migrate all references, Create a checklist to test, Create all relevant tests, Use all the form references in internal apps to test all the use cases: Confidence 80%
- [ ]  Do not touch the older references, Do not add any migration, Create v2 to use button, show error on all old formButtons through validations or the above suggestion. Confidence 100%

**Comment by AS-Laguna** [comment]
A user would like to use a buttons `isDisabled` property, which doesn't currently exist in the Form Button Widget.

**Comment by somangshu** [comment]
@AS-Laguna Once we complete the above activity the form button will get replaced by a normal button and hence the isDisabled property will be available for the dev.

**Comment by somangshu** [comment]
@dilippitchika we now have #12291 merged and available soon, We can go ahead and pick this up with the second strategy we had discussed

> - [ ] Do not touch the older references, Do not add any migration, Create v2 to use button, show error on all old formButtons through validations or the above suggestion. Confidence 100%

**Comment by dilippitchika** [comment]
There's one issue which we may need to fix when we are taking this up. 

[Linked here in the video.](https://www.loom.com/share/56cc7ae651e34f8b88db0d730805e0b3)

Today our "reset form on success" field when switched on also resets if there's an error in the API which is incorrect, i believe this could be fixed here. @somangshu

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 1200 |
| Effort (months)  | 0.75 |

**Comment by dilippitchika** [comment]
@techbhavin assigning this to you, please discuss with somangshu and me once before picking this up

**Comment by somangshu** [comment]
### Summury of older discussion
- Two ways we could move ahead in > Check [this](https://github.com/appsmithorg/appsmith/issues/3613#issuecomment-1084333862) out
- Finally [POA](https://github.com/appsmithorg/appsmith/issues/3613#issuecomment-1138368757)

**Comment by somangshu** [comment]
## Actionable 
- [ ] Do we need a customised deprecation warning @dilippitchika
    - [ ] How do we achieve this @rahulramesha 
- [ ] We need to estimate the issue again @techbhavin 
- [ ] We need to identify how to deal with "reset form on success" [issue ](https://github.com/appsmithorg/appsmith/issues/3613#issuecomment-1138453150) @techbhavin

**Comment by dilippitchika** [comment]
@techbhavin we disable the fields when it's not in a form, please check the PRD above
