### ISSUE TITLE
[Task]: Resolve Blockhound Callouts for Gsheets plugin (Actions Execute API)

### ISSUE THREAD

**Issue by NilanshBansal** [appsmithorg/appsmith#36143]
### SubTasks

Resolve Blockhound Callouts for Gsheets plugin (Actions Execute API)

**Comment by sneha122** [comment]
Moving this back to sprint backlog as I have to look into two issues post merging the actions API improvements PR last week.
- https://theappsmith.slack.com/archives/C024GUDM0LT/p1725964415678489?thread_ts=1725960912.325389&cid=C024GUDM0LT
- https://theappsmith.slack.com/archives/C024GUDM0LT/p1725943060293719?thread_ts=1725864964.488269&cid=C024GUDM0LT

CC: @NilanshBansal @rohan-arthur

**Comment by sneha122** [comment]
Checked different operations in Google Sheets for blocking callouts and here are the observations:

Operation | Callout yes or no? | ThreadName
-- | -- | --
Fetch Details | No | NA
Fetch Many (Spreadsheets) | Yes | reactor-http-nio-4
Fetch Many (Sheet rows) | No | NA
Insert One (Spreadsheet) | No | NA
Insert One (Sheet rows) | No | NA
Insert Many (Sheet rows) | No | NA
Update One (Sheet rows) | No | NA
Update Many (Sheet rows) | No | NA
Delete One (Spreadsheet) | No | NA
Delete One (Sheet) | No | NA
Delete One (Sheet rows) | No | NA




These are the operations that were checked for google sheets, out of which we got a blocking callout for fetchSpreadSheets query which has fetch many operation and entity type selected as spreadsheet, which means this query fetches all the spreadsheets belonging to this specific datasource. We got a blocking callout when passing in GoogleSheetMethodsEnum to the getSpeadsheetData method of SheetUtils. This callout is coming from inside java.net and java.io package when loading the GoogleSheetMethodEnum file. Since this is not coming from our code directly and instead coming from external package, we can ignore this callout. 
<img width="1432" alt="Screenshot 2024-09-17 at 2 30 47 PM" src="https://github.com/user-attachments/assets/57d3cee5-a325-46cf-a6dd-455723ec14f3">


**Note that this blocking operation does not block main thread, so we are good to ignore it for now.**

Another thing I checked is replacing this enum with FeatureflagEnum which exists inside appsmith-interfaces package to see if it's an issue with GoogleSheetMethodEnum file specifically but even with FeatureFlagEnum, got the same callout
<img width="1427" alt="Screenshot 2024-09-19 at 11 44 23 AM" src="https://github.com/user-attachments/assets/47cca441-94b2-49d6-a5d1-6edd9966cd37">

Since this is not blocking main thread and callout is coming from an external package, we can close this issue safely.

CC: @NilanshBansal
