### ISSUE TITLE
[Bug]: Unable to login through SAML on nightly adaptive image

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#36659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unable to login through SAML on nightly adaptive image
![image](https://github.com/user-attachments/assets/f6c7f66c-0702-4cb1-9847-76472110ade2)

### Steps To Reproduce

1. pull nightly image locally
2. user postgres uri with RDS
3. now enable the saml auth
4. try to login with saml auth
5. we are seeing error as in attached screenshot

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

prod

**Comment by AnaghHegde** [comment]
@RakshaKShetty This is due to the localhost call being blocked by Appsmith. And this is not specific to postgres db, this is happening on mongo as well. This has nothing to do with the db infrastructure. I tried the same flow on `appsmith/appsmith-ee:latest` and the issue is reporducible here as well. 
The SAML auth flow is working fine in dp, you can check again on 4517 pg dp.
