### ISSUE TITLE
[Task] Understand and document the working of code for OnLoadExecutableUtils 

### ISSUE THREAD

**Issue by rishabhrathod01** [appsmithorg/appsmith#36719]
- findAllOnLoadExecutables
- findAndUpdateLayout

**Comment by NilanshBansal** [comment]
Noted all my findings in [this notion document](https://www.notion.so/appsmith/Working-of-api-v1-collections-id-PUT-API-11ffe271b0e280b7981bc2b477290820).
Also had initial understanding call with Nidhi and subsequent debugging sessions with Sneha and Rishabh. 
The following are the areas where we need to add more observability. 
https://www.notion.so/appsmith/Working-of-api-v1-collections-id-PUT-API-11ffe271b0e280b7981bc2b477290820?pvs=4#123fe271b0e280d29a78de3a9799e55d


### Instrumentation to be Added

(Try and add these to the actual functions instead of where these are getting executed as internally same functions are getting executed)

- `updateLayoutService.updatePageLayoutsByPageId()`  in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java#L456
- `unescapeMongoSpecialCharacters()` in https://github.com/appsmithorg/appsmith/blob/3032adc09cde653dd0c3d006dc9006759036654d/app/server/appsmith-server/src/main/java/com/appsmith/server/layouts/UpdateLayoutServiceCEImpl.java#L303
- `extractAllWidgetNamesAndDynamicBindingsFromDSL` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/layouts/UpdateLayoutServiceCEImpl.java#L131
- `getAllExecutablesByCreatorIdFlux` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L122
- `executableNameToExecutableMapMono` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L124
- `executablesInCreatorContextMono` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L134
- `addDirectlyReferencedExecutablesToGraph` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L141
- `getPossibleEntityReferences` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L598 (Add to the method as there are other functions invoking this)
- `updateExecutableSelfReferencingPaths` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L614
- `extractAndSetExecutableBindingsInGraphEdges` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L615(Add to method)
- `getPossibleEntityParentsMap` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L488. We can add observability to the method here - https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L555
- `addExplicitUserSetOnLoadExecutablesToGraph` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L159
- `getUnpublishedOnLoadExecutablesExplicitSetByUserInCreatorContextFlux` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L947 (Add in method)
- `fillSelfReferencingPaths` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L948
- `extractAndSetExecutableBindingsInGraphEdges` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L958 (Add to method)
- `recursivelyAddExecutablesAndTheirDependentsToGraphFromBindings` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L171 (Add to method)
- `addWidgetRelationshipToGraph` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L181
- `createGraphMono` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L185
- `computeOnPageLoadScheduleNamesMono` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L195
- `computeOnPageLoadExecutablesSchedulingOrder` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L816
- `filterAndTransformSchedulingOrderToDTO` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L420
- `flatPageLoadExecutablesMono` in https://github.com/appsmithorg/appsmith/blob/f547821362b20924971fa07476ffd12344a0fd61/app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java#L244
