### ISSUE TITLE
[Bug]: SMTP datasource should work without username and password

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith#37271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When configuring SMTP datasource without username and password, always throws error `Invalid authentication credentials. Please check datasource configuration.`

Ideally we should be able to configure SMTP datasource without username and password too.
More specifically we need to remove the manual validations added on SMTP code base as it is possible to configure smtp service without password as well
<img width="994" alt="Screenshot 2024-11-07 at 11 37 57 AM" src="https://github.com/user-attachments/assets/1f7924e3-dc46-4970-8bb6-b3a1349fc4c3">

### Steps To Reproduce

1. Use any email service for configuring SMTP datasource without setting up username and password
2. Create SMTP datasource with host port, keeping username and password blank
3. Test the configuration

### Environment

Production

### Severity

Medium (Frustrating UX)

### Version

v1.47

**Comment by shanid544** [comment]
@sneha122 Shall I pick this?

**Comment by sneha122** [comment]
@shanid544 Sure you can pick this up, could you please let me know what test case are you planning to add here?

**Comment by shanid544** [comment]
@sneha122 I used - docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog, able to reproduce the issue & fixed the issue, now we can configure SMTP with & without credentials. will test one more time & attach screenshots

**Comment by sneha122** [comment]
Thanks @shanid544 that's super helpful, can you please add relevant test cases along with the fix if possible?

**Comment by shanid544** [comment]
@sneha122 , Will update the existing test case

**Comment by shanid544** [comment]
@sneha122 
Scenario 1 : 
Suppose I am adding username alone/password alone as the part of conf, test should pass, what about save?

**Comment by sneha122** [comment]
@shanid544 Is it even possible to configure SMTP datasource with just the username or just the password? I don't think it is. But if it is then we need the test to pass in such cases

**Comment by sneha122** [comment]
Hi @shanid544 Were you able to figure out the test cases for this issue? If yes are you planning to raise a PR for this anytime soon?

**Comment by shanid544** [comment]
yes

**Comment by shanid544** [comment]
Could you please review this

### Solution Details
**To fix this, the following changes were implemented:**
**Updated Validation Method (validateDatasource)**
Before: Enforced mandatory username and password validation.
After: Removed the strict validation check for authentication fields, allowing for configurations without credentials.



```
if (authentication == null || !StringUtils.hasText(authentication.getUsername()) || !StringUtils.hasText(authentication.getPassword())) {
    invalids.add(new AppsmithPluginException(AppsmithPluginError.PLUGIN_AUTHENTICATION_ERROR).getMessage());
}
```

**Modified the SMTP Session Creation (datasourceCreate)**
Before: Always initialized the SMTP session with authentication, assuming credentials were required.
After: Updated the session creation to support both authenticated and unauthenticated configurations.


```

Properties prop = new Properties();
prop.put("mail.smtp.auth", "false"); // Default to no authentication

if (authentication != null && StringUtils.hasText(authentication.getUsername()) && StringUtils.hasText(authentication.getPassword())) {
    prop.put("mail.smtp.auth", "true");
    session = Session.getInstance(prop, new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(username, password);
        }
    });
} else {
    session = Session.getInstance(prop);
}
```

**Enhanced Testing for Authentication Scenarios (testDatasource)**
Before: Errors were logged if authentication failed, even for servers where authentication wasn’t required.
After: Introduced a flag to detect if authentication was required based on the session configuration, and adjusted error handling accordingly.



```
boolean isAuthRequired = "true".equals(connection.getProperty("mail.smtp.auth"));
if (isAuthRequired && transport != null) {
    try {
        transport.connect();
    } catch (AuthenticationFailedException e) {
        invalids.add(SMTPErrorMessages.DS_AUTHENTICATION_FAILED_ERROR_MSG);
    }
}
```

**Testing and Verification**
Unit Tests
Without Authentication:
Updated testNullAuthentication test case to ensure no errors are returned when authentication is absent.

```
@Test
public void testNullAuthentication() {
    DatasourceConfiguration invalidDatasourceConfiguration = createDatasourceConfiguration();
    invalidDatasourceConfiguration.setAuthentication(null);
    assertEquals(0, pluginExecutor.validateDatasource(invalidDatasourceConfiguration).size());
}
```
manual test:
_Manual Testing_

1. SMTP Server Testing with MailHog

Environment: Configured SMTP datasource using MailHog, set up via Docker.
Steps:
Configured the SMTP datasource in Appsmith without authentication (no username or password).
![Screenshot from 2024-11-11 14-44-11](https://github.com/user-attachments/assets/477c1fa2-83b1-4a7f-ac31-bb4e19145c82)
Created a query to send an email.
![Screenshot from 2024-11-11 14-44-56](https://github.com/user-attachments/assets/93e72fd2-045a-4ef0-aba8-b77e3c28fb6a)
Result: Email was successfully sent without requiring authentication credentials.
![Screenshot from 2024-11-11 14-45-32](https://github.com/user-attachments/assets/3fa2c02d-97f0-4a03-a559-6553c93d64ed)

2. Gmail SMTP Server Testing (Without Authentication)

Environment: Configured SMTP datasource using Gmail's SMTP server without providing authentication credentials.
Steps:
Set up the Gmail SMTP server in Appsmith without entering a username or password.
![Screenshot from 2024-11-11 14-46-49](https://github.com/user-attachments/assets/2d5bf4c9-c5e5-4848-a440-5073ffa093f6)
Created a query to send an email.
Result: Appsmith was able to connect to the Gmail SMTP server, and the email was successfully sent without authentication credentials.
![Screenshot from 2024-11-11 14-48-27](https://github.com/user-attachments/assets/dcc9f36f-58f1-4435-b095-1bef43c2ecb9)
Expected Result: Error should be thrown due to missing authentication credentials. Gmail requires authentication for sending emails, so the system should reject connections without credentials.
Go back and edit the datasource - add username and password, Will be able to send the mail.

3. Gmail SMTP Server Testing (With Authentication)

Environment: Configured SMTP datasource using Gmail's SMTP server with valid username and password.
Steps:
Entered Gmail SMTP server details along with valid authentication credentials in Appsmith.
Created a query to send an email.
Result: Email was successfully sent using the authenticated configuration.

**Comment by shanid544** [comment]
@sneha122 Could ypu please review this [PR](https://github.com/appsmithorg/appsmith/pull/37319)

**Comment by sneha122** [comment]
Thank you @shanid544 for the PR, I will review this
