### ISSUE TITLE
[Bug] Omnibar Issues

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#3742]
## Description

1. The documentation in the API / Query panes do not open the omnibar
2. Clicking the help icon in the property pane does not fire an omnibar open event
3. The omnibar recent items are not getting cleared on navigating to a new app
4. The omnibar could be enhanced a little with a hover interaction
5. The cheat sheet should be linked from the entity documentation

**Comment by Nikhil-Nandagopal** [comment]
- Reopening omnibar should be empty
- Recents is not working properly. If you navigate to an item and open it, it does not show the item in the recents
- Analytics is not firing for opening omnibar from API / Query / Widget
- The read more in the datasource page does not trigger the omnibar
- The documentation in the queries should open the corresponding documentation page not the main connect databases page
- Increase the height of omnibar by 30%

**Comment by rishabhsaxena** [comment]
@Nikhil-Nandagopal couple of notes related to this issue:
- Reopening omnibar should be empty: we're preserving the current state in the omnibar since the user might want to jump back to the documentation he was referring to
- Recents is not working properly. If you navigate to an item and open it, it does not show the item in the recents: we're keeping the latest n-1 entities in the recents, to make it easy to jump back to the prev one without pressing a down arrow

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena that's on case but the other case is that a user wants to switch to a new entity or new documentation. The recents should be used to do this instead of preserving the older search term which the user needs to clear every time.
I didn't understand your point about recents. If we only show n-1 then I can't see the most recent entity I jumped to right?

**Comment by rishabhsaxena** [comment]
The point about recents was that the user might want to jump back to the prev entity more instead of the current one, for example after switching from an action to the editor page, he wants to switch back to the action page

For the search query would it work if open the modal with the query text selected so that on typing/backspace the query is reset?

**Comment by Nikhil-Nandagopal** [comment]
@rishabhsaxena the previous entity will be just one more arrow down right? That should be better than not showing the current entity at all. I think you're thinking of users only using the omnibar but in reality, sometimes they switch  to an entity, scroll around the canvas and then want to jump back to that entity. Optimising between one keyboard press and 2 isn't very valuable. Similarly opening it in the searched state to optimise for the event of the user wanting to see the same entity isn't great when we can't predict what the user will do next. Let's make it easy for the user to move forward and make their next choice instead of guessing

**Comment by kaushik94** [comment]
@rishabhsaxena previously the omnibar recents is not working correctly. With this fix it is working correctly by showing the last "jumped to" entity. So it is ok to clear the query.

**Comment by rishabhsaxena** [comment]
> @rishabhsaxena previously the omnibar recents is not working correctly. With this fix it is working correctly by showing the last "jumped to" entity. So it is ok to clear the query.

@kaushik94 Have posted a comment on the PR, just for ref:
After removing `recentEntities = recentEntities.slice(1);` within `useRecentEntities` we should be able to see the current entity within recents

**Comment by kaushik94** [comment]
@rishabhsaxena this makes sense. I made the change to PR and it is working. Thanks.
