### ISSUE TITLE
[Bug] Placeholder text gets mangled on button click in the edit box.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#3778]
## Description
Placeholder text gets mangled on button click in the edit box.

Before:
![Screenshot 2021-03-30 at 7 10 24 PM](https://user-images.githubusercontent.com/1757421/112998796-03322900-918c-11eb-85b2-81096f21fe2e.png)

After:
![Screenshot 2021-03-30 at 7 11 06 PM](https://user-images.githubusercontent.com/1757421/112998837-0b8a6400-918c-11eb-996e-65baab8c63f7.png)

**Comment by arunvjn** [comment]
This issue has to do with the code editor's configuration. You can start debugging this issue by experimenting with the config [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/editorComponents/CodeEditor/index.tsx)

Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by mandvisingh** [comment]
Can i work on this issue?

**Comment by arunvjn** [comment]
@mandvisingh Go for it! 
Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). 

Please don't forget to register with [Appsmith's Hacktoberfest](https://hacktoberfest.appsmith.com/) Community in order to be eligible for Appsmith swag.

**Comment by Irongade** [comment]
Closing this issue since it's not reproducible.
