### ISSUE TITLE
Unexpected duplicated JSObject on update

### ISSUE THREAD

**Issue by carinanfonseca** [appsmithorg/appsmith#37848]
We had customers reporting that sometimes the JSObject got duplicated on update action. 
Since the team has been working on improving JSObjects stability and performance, we need to check if this issue is still happening. If not, we can close it. If yes, we need to understand the cause and the potential fix for it. 

[here](https://www.notion.so/appsmith/Unexpected-Duplicate-JSObject-creation-on-update-119fe271b0e280a49d43cd51e81ba03f?pvs=4) it is the page of the evidence, with the link for more context.

**Comment by sneha122** [comment]
Tried to reproduce this issue by following below steps:
**trying to save the JSObject in a complex application**
1. While it is saving, refresh the page
2. check if there is a duplicate JSObject created or not.
3. Do the same while trying to rename a function instead of updating the body of the function and verify the same.

Issue was not reproducible even for a large application and large JS object, hence closing it. 

CC: @rishabhrathod01 @carinanfonseca @nerbos
