### ISSUE TITLE
[Feature] Table URL columns pretty link

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith#4135]
## Summary
Allow users to configure a human readable text in the table widget's url type column configurations.

## Motivation
Today, the URL column works as is. Which means, that the url value is shown as is and is available as an anchor link.
Many common use-cases would require an alternative text to be shown which would still be an anchor link.

## Additional Context
It should have a new field which will be a computed text to be shown. If this is not configured, fallback to showing the url.

**Comment by somangshu** [comment]
Note: 

 - The property pane will consist of `Display text` field under the column type `URL` 
 - The `computed value` will have the href/url 
 - In the table column the `Display text` will be show unless empty, Otherwise show the `URL` directly
 - Is Both `display text` and `computed values` are null then the column should not redirect with the null value and clearly show that there is not link here

**Comment by somangshu** [comment]
Note:

 - [bug]: The URL column does not follow the alignment styling of the parent table.
