### ISSUE TITLE
[Bug] Name in the array of data does not change when the column name changes 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#4237]
Steps to reproduce:
1) Add a table
2) Add an array of data with multiple columns
3) Click on Property pane 
4) Scroll down to name of column
5) Change the name of the column 
and observe

Observation:
the name of the column changes in the table and in the column list but Array data does not change the column name 

Expectation:
Consistency of the data must be displayed to user  
![Screenshot 2021-04-30 at 1 51 42 PM](https://user-images.githubusercontent.com/71753653/116669096-cb511800-a9bb-11eb-955c-cfbd09bc935b.png)

**Comment by areyabhishek** [comment]
@prapullac The table generally accesses data from an API or DB query response. If the user changes the column name in a table, we cannot and shouldn't change the column name in the original database. 
The column name here is only for the end user readability. For example the original database column name might be: 'timeinmilliseconds' but the end user should see 'time' as the column name. It's not for the purpose of updating the original database.

Closing this issue because this works as expected.
