### ISSUE TITLE
[Bug] If user sign up from github which uses same email id as google account then new account got created

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#4369]
### Steps to reproduce the behaviour:

1. Sign up on appsmith using google account (vivek@appsmith.com)
2. Now create a github account with the same  google account ie. vivek@appsmith.com
3. Sign up with github on appsmith 
4. Observe that two different accounts are getting created.

Imp notes: When user login with google account on appsmith the user name is vivek@appsmith.com
if user login with github account on appsmith the username displayed as the user name of github ie. vivek2312

**Comment by prapullac** [comment]
Scenario :
Consider user has logged in with google account and then tried to log in using Google Id and Pass word it is observed that the two different accounts would be created and Shared application from other user would go only into Google account.

Video:
https://www.loom.com/share/be2570f0fae1484ab3b519a9eebfd515

**Comment by Nikhil-Nandagopal** [comment]
@mohanarpit do we have a solution for this? I think this was an exposed security issue as well so what action should we take here?

**Comment by mohanarpit** [comment]
There are 3 separate issues being discussed on this thread. I'll break them up so that we can address them individually. 

1. Google & Github OAuth2 logins with the same email ID create separate accounts. 
This is expected. This is because Github doesn't expose the email ID to us during signup/login. Hence, we don't really know the email ID being used behind the scenes and thereby end up creating a separate user account. This is NOT a bug. An inconvenience, sure. But not a bug. 

2. Google OAuth2 login & password login leading the user to separate accounts.
This is happening because of case sensitivity in our usernames. In the video you can see that the first letter is capitalized in one case, while it isn't in another case. Hence, this is causing a problem. This is a legitimate bug. 

3. Security issue that Nikhil is talking about. This is again a separate issue & we are resolving it separately. 

Overall, I'm closing this issue because the original description is not a bug. I'll open another one for the username case sensitivity.

**Comment by mohanarpit** [comment]
Opened another issue #5998 with the correct description.
