### ISSUE TITLE
[Feature] Allow users to customize the API confirmation pop-up

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#4415]
## Summary
The API confirmation popup shows a generic message today. Users would like to control it to show a custom message. We could consider turning this into an auto-generated small modal that is easy to customize.

## Motivation
According to a user on Discord, they want to customise the text, the button, and the popup title bar.

## Additional Context
<img width="531" alt="Screen Shot 2021-05-11 at 3 28 15 AM" src="https://user-images.githubusercontent.com/30255708/117729770-f2ec7f80-b208-11eb-81c3-e8f019e608d9.png">

**Comment by GreenFlux** [comment]
A user on Discord is asking about this feature. I suggested using a modal but it sounds like they have lots of different queries spread across different pages, so that creates a lot of extra work. It would be great if they could just type in a custom confirmation message right in the query/API settings. Do we have an idea of when this feature might be picked up?

**Comment by Nikhil-Nandagopal** [comment]
The right answer to this should be to launch our modules feature that will let users re-use a customisable confirmation modal

**Comment by riteshkew** [comment]
This request would be covered as part of Packages. Closing it for now
