### ISSUE TITLE
[Bug] Adding a new Google Sheets connection redirects to a page with 404 response

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#4460]
Reported by Zeger on Discord:

> Went to API's -> Add new Google Sheet -> configured a name and pressed "Continue". Ended up at this page (using backend docker tag v1.5).

![](https://cdn.discordapp.com/attachments/760761686549463060/842050131096240148/unknown.png)

**Marking as Critical since there's no workaround for using Google Sheets.**

**Comment by nidhi-nair** [comment]
Looks like the client side url for cloud services is not set, we will need to take a look at the nginx config for this user as well as whether the tokens were generated at all.

I'll be attempting to connect to the user on Discord.

**Comment by nidhi-nair** [comment]
The issue here was that the configuration for the user did not update to start using the cloud services url. As a result, while the server was retrieving the token, the client could not use it. Two changes required were to manually configure the url in the environment file and to use this variable in the nginx configuration.

We need to update this [file ]( https://github.com/appsmithorg/appsmith/blob/release/deploy/template/docker.env.sh) and include the changes in configuration in our release notes / documentation.

**Comment by sharat87** [comment]
Can we set the default value of cloud services URL inside the backend server? That way, it should work even without a change required in the docker.env file right?

**Comment by nidhi-nair** [comment]
Yes that's how we're handling it for the server, is there a way to do this on the client as well?

**Comment by YogeshJayaseelan** [comment]
unable to reproduce this now and hence closing this issue
