### ISSUE TITLE
[FEATURE] Duplicate or copy/paste widgets

### ISSUE THREAD

**Issue by bakerfugu** [appsmithorg/appsmith#454]
## Summary

Add the ability to duplicate or copy/paste widgets using keyboard shortcuts and UI buttons

## Motivation

This feature would help speed up the creation of apps, allowing for easy reuse of logic that has already been created.

## Additional Context

It would be annoying if the duplicated widget were always placed underneath the original one, because that could shift/bump other components. It would be nice if the component would be dropped underneath my cursor when I paste, or really any feature that lets me control where the duplicated widget is dropped.

**Comment by mohanarpit** [comment]
@bakerfugu We've released the feature to copy-paste widgets. This is available on [https://app.appsmith.com](https://app.appsmith.com) or in our latest release `v1.2.6`.

I'm closing this issue now. If you face any issues with this feature, please feel free to re-open this issue.

**Comment by Nikhil-Nandagopal** [comment]
Addressing the issue of where the widget is pasted, we decided that as a v1 we'll place the widget in the first free space of the container that is selected. So if no container is selected, it will place it below the existing widgets on the canvas (not moving anything). Do try out the interaction and let us know if you think it can be improved. (We didn't go with the approach of snapping the widget to the cursor because we wanted copy + paste to be fast and not need an additional cursor click)
