### ISSUE TITLE
[Enhancement] Avoid duplicating table column header

### ISSUE THREAD

**Issue by abhvsn** [appsmithorg/appsmith#4758]
## Summary

Currently user can have duplicated table column headers which can create confusion  

## Requirement
| Title | Desc | Comment | 
| ----- | ----- | ------- | 
| Highlight Duplicate | If a duplicate tile exist highlight the tile with a red(from theme) border | - |
| Show error | Show the error in the evaluated value popup and in the console too | - |

**Comment by somangshu** [comment]
@abhvsn When do we consider the object to be a duplicate? Do we compare the whole object?

**Comment by abhvsn** [comment]
@somangshu I don't think I get your question correctly. But when you asked about the duplicated object check we might go for shallow copy (soft equal). 
That said the intent of this issue is just to give some kind of error message when user tries to duplicate the header name in the table either by creating or updating the table column.
![Screenshot_20210809-182023_Chrome](https://user-images.githubusercontent.com/41686026/128709500-b04d1833-5868-4493-8e34-e16931c54325.jpg)

**Comment by somangshu** [comment]
Today the name of the column and the reference key are different, this was done so that the user can also show formatted table column name (with spaces etc). The selectedRow, tableData, currentRow all point the reference key. This seems like the correct decision.

However, From the UX POV we can show a validation error here. And highlight the tile in the error state

**Comment by vibhandikyash** [comment]
Currently showing highlighted input in case of duplicate column name.
Closing this issue for now.
cc: @dilippitchika
