### ISSUE TITLE
[Bug] Google OAuth redirect URI to internal service name with Helm Charts

### ISSUE THREAD

**Issue by amity0** [appsmithorg/appsmith#4785]
## Description
After adding google APPSMITH_OAUTH2_ALLOWED_DOMAINS, APPSMITH_OAUTH2_GOOGLE_CLIENT_ID & APPSMITH_OAUTH2_GOOGLE_CLIENT_SECRET envs I am getting this error:
 
![image](https://user-images.githubusercontent.com/43967600/120097199-e2f4fb00-c137-11eb-85b0-02b6e2ab8f40.png)

It looks like the redirect uri is the internal service name - appsmith-service and not the external name

Edit: relevant logs:

```
"30/May/2021:08:23:20 +0000" client=10.241.3.2 method=GET request="GET /oauth2/authorization/google HTTP/1.1" request_length=3335 status=302 bytes_sent=881 body_bytes_sent=0 referer=https://appsmith.my-real-domain.com/user/login http_x_forwarded_for=xxx.xxx.xxx user_agent="..." upstream_addr=xxx.xxx.xxx:80 upstream_status=302 request_time=0.012 upstream_response_time=0.012 upstream_connect_time=0.000 upstream_header_time=0.012
```
### Steps to reproduce the behaviour:

I installed appsmith using helm (This open pr: https://github.com/appsmithorg/appsmith/pull/2558) - I know that it's not officially supported but it worked for me

### Important Details

- Version: Self-Hosted latest images
- OS: GKE
- Browser chrome
- Environment production

**Comment by alonp99** [comment]
+1

**Comment by sharat87** [comment]
Hey @amity0, sorry you were facing trouble with this. Could you try our official Helm charts experience and let us know if that works for you? You can read more about it here: https://docs.appsmith.com/setup/kubernetes.

Since this issue is about an unofficial Helm chart, I'll be closing this. If you face any trouble on the official once, please feel free to open a new issue and we'll investigate there. Thanks!
