### ISSUE TITLE
[Bug]Navigate to signup when the user click on Reset password button

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#4841]
## Description

[What happened ] In Sign in Page->When the user enter the email in reset password window and click on reset button then the user should navigate to Signup page

Steps to reproduce the behaviour:

1.In Sign in Page 
2.Click on Forgot password link
3.Enetr the email
4.CLick on reset Button
5.Verify the display

expected result:
In Sign in Page->When the user enter the email in reset password window and click on reset button then the user should navigate to Signup page. also  add a alert message saying "Please check your email for reset password link"
Actual Result:
In Sign in Page->The user is allowed to  click on reset password button multiple times
![image](https://user-images.githubusercontent.com/45958978/120349076-6884d080-c31b-11eb-948f-45a11fe070e3.png)

### Important Details

-Important Details
Version: Cloud
OS: Windows
Browser Chrome
Environment Production

**Comment by maskmanlucifer** [comment]
@Pranay105  can i work on this issue ??

**Comment by Pranay105** [comment]
@maskmanlucifer here you go. Happy hacking :)

**Comment by maskmanlucifer** [comment]
> @maskmanlucifer here you go. Happy hacking :)

thank you :)

**Comment by alzaar** [comment]
Hey! Is this still available to work on ?

**Comment by tauantcamargo** [comment]
@Pranay105 could i get it?

**Comment by Hongkai-Zhai** [comment]
@Pranay105 Hey can I work on this issue?

**Comment by rajatagrawal** [comment]
Upon discussing with @riodeuno and @somangshu , it felt like the user experience doesn't get hampered with the current UX flow.

If we were to go about implementing the suggested changes to go back to the previous login screen, we will need to have additional UX considerations for,

1. Showing the UX for confirmation of reset password email sent on the login screen since the user would have navigated back to it.
2. If a user enters a wrong email address by mistake, then they will have to redo the whole flow again, which would be cumbersome.
3. The current flow doesn't hamper the user experience greatly in any way and lets the user achieve their desired goal, which is to reset the password.

Hence, we decided to close the issue. Please ackowledge @RakshaKShetty.
