### ISSUE TITLE
[Feature] Add support for WHERE conditions in Google Sheets

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4846]
## Summary

All CRUD operations in the plugin must support conditional row selection so that users can use this plugin as a structured data source. This format must be in line with the UQI.

## Motivation

Users have asked to be able to manipulate data not by row references but by column data, as below:

<img width="734" alt="Screenshot 2021-06-01 at 11 17 16 AM" src="https://user-images.githubusercontent.com/5298848/120420533-26db4080-c382-11eb-8368-99fb47c7a014.png">

**Comment by mohanarpit** [comment]
A potential solution to searching on Sheets via content: https://stackoverflow.com/a/49439220/716823

**Comment by zzgvh** [comment]
While CRUD operations with more "SQL-like" features would be nice I'm not sure they are actually needed. Since the data returned from a fetch is a list of objects where each object includes a rowIndex, as long as there is a way to uniquely identify rows or groups of rows, the rowIndex can be used to refer to the row(s) for manipulation.

However deleting multiple rows seems a little tricky since each row has to be deleted using a new call, leading to an interesting problem of how to chain delete events. So a bulk delete where you supply a list of row indices seems like a good idea.

**Comment by prapullac** [comment]
Issues on where clause are listed below:
[Bug] Deleting an extra row in the Where clause the entire rows added gets deleted #7630
