### ISSUE TITLE
[FEATURE] Data migration from self hosted instance

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#488]
## Summary

A user thought it might be a good idea to be able to migrate his data from one ec2 instance to another or from an ec2 instance to our cloud instance

## Motivation

Users are initially wary of giving the cloud version their db credentials but over time want to move to the cloud version because it's easier to manage or be able to restore their setup on another ec2 instance incase something un-foreseen happens to their instance

## Additional Context

Sentry does a great job with this feature!

**Comment by mohanarpit** [comment]
This is a great idea! Do you have any resources that link to how Sentry achieves this? Would love to learn from a good UX for this feature. 

Also, from my initial understanding, this feature requires that we do the following first:
1. Create a backup of all the data in the DB. 
2. Be able to restore the backup of the DB in another instance. The tricky part will be to preserve all the IDs.

**Comment by crooy** [comment]
Hi, so i think my question is related to this ticket. I am looking into running a system like appsmith to build various internal applications for my startup/scale-up.

Now we have a very experienced devops team but we dont want to spend time om worrying about databases if it can be prevented. Which is why I was wondering if you might know if i would run into any issues if I try to run appsmith against AWS DocumentDb instead of running a mongodb in a container?

What other backup/restore solutions would you recommend for me to look at for appsmith/mongodb?

**Comment by Nikhil-Nandagopal** [comment]
Hi @crooy 👋 
Your question is actually slightly different than this feature request.
Appsmith internally uses mongo to manage application data and performs all application logic on this db. So it is not a simple backup / restore option. All our application logic is written to interact with a mongo db so it wouldn't be possible to use a different DB. If you are worried about managing the application and database, we have a managed [Cloud Version](https://app.appsmith.com) which you can use 😄

**Comment by crooy** [comment]
Wow, quick response! 

Ok, first of all sorry for hijacking this ticket 😞. 

From your answer I cannot be certain you know what AWS Document DB is so to be certain: AWS DocumentDB is a mongodb compatible hosted database, there are some [differences](https://docs.aws.amazon.com/documentdb/latest/developerguide/functional-differences.html).

The thing I want to pay for hosted services so I can show an SLA to my product owners. Hypothetically, if I do a daily dump of the mongodb, could i restore the database if i want to go back a week for example?

**Comment by Nikhil-Nandagopal** [comment]
@crooy whoops my bad I might be wrong then. I definitely thought it was a new db. 😂 #TIL
 @mohanarpit can you help answer this better?

**Comment by mohanarpit** [comment]
@crooy I haven't tried Appsmith against DocumentDB. In theory, it could work but we can't guarantee longer term compatibility because DocumentDB is always a little behind on features supported by MongoDB itself. Hence, I wouldn't officially recommend it to you. But give it a shot and let us know your experience 😄 .

Having said that, incase you don't want to manage databases (who does?), you can either:
1. Use our cloud hosted version https://app.appsmith.com. In this case, you are transferring your problems of data management to us. 
2. Use MongoDB cloud. Here you get a hosted MongoDB instance with all the bells & whistles around backup, restore etc. You can host it in the same region as your AWS servers as well to minimize latency.

**Comment by crooy** [comment]
Thanks! I will let you know in case we try and experience Documentdb! Although you make a good point that mongodb-cloud might be smarter.

**Comment by Nikhil-Nandagopal** [comment]
This is not possible with import / export

**Comment by cep21** [comment]
@crooy did documentdb work?

**Comment by crash7** [comment]
> @crooy did documentdb work?

DocumentDB doesn't work for me (tried yesterday with the last version).

**Comment by crooy** [comment]
havent tried, sorry.
