### ISSUE TITLE
[Feature] Button Group Widget

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#4889]
## Summary

A widget to create a group of buttons and menus inside a single container.

Ex:
![Screenshot 2021-06-03 at 12 15 01 PM](https://user-images.githubusercontent.com/11089579/120599612-58790800-c465-11eb-8746-dec6be69c016.png)
 
## Requirements

Property | Values | Default | Definition
-- | -- | -- | --
orientation | 'horizontal'\|&nbsp;'vertical' | 'horizontal' | The group orientation (layout flow direction).
variant | 'contained'\|&nbsp;'outlined'\|&nbsp;'text' | 'outlined' | The variant to use.

## Design

https://www.figma.com/file/XT0We8ms6XC3iD73lTF2Zr/Button-Group-Widget?node-id=2%3A262

**Comment by somangshu** [comment]
@Nikhil-Nandagopal Each sub component will inherit styles from the parent widget. 
As discussed before, Button group is a combination of button and menu where the user can choose to create a nested list of options at any position/order. Leaving this choice to the user is of much more value

**Comment by areyabhishek** [comment]
I tested the button group widget and there are a few bugs and one enhancement that's necessary for the button to be more useful than just putting 3 individual buttons together.

Bugs:
1. The button variant option is placed incorrectly and should be in styles section(exactly like in other button widgets)
2. There's no way to change the color of a button
3. The list of button names has a visual bug. The top of the field is cut off. See screenshot below:
<img width="270" alt="Screen Shot 2021-11-13 at 2 18 29 AM" src="https://user-images.githubusercontent.com/30255708/141537099-388f099f-6c60-4c57-a350-ec4e8e2b180b.png">

Enhancement:
Allow users to use a JSON object to generate buttons on the fly. The button group and even the menu button should have a data property to achieve this. This enhancement will be incredibly useful because a user can generate a list of actions on the fly.

**Comment by somangshu** [comment]
@areyabhishek for point 2, The button color can change from the settings option given on each tile,

Closing the main issue again and raising this separately
