### ISSUE TITLE
[Bug] Incorrect "opens in new window" icon for chat option

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#4911]
<img width="241" alt="Screenshot 2021-06-03 at 6 45 44 PM" src="https://user-images.githubusercontent.com/5298848/120651069-fc7da600-c49b-11eb-9422-4475d673ac75.png">

**Comment by rafaeelaudibert** [comment]
Hey, I've just opened a PR for this @Pranay105 :)

**Comment by MitAbhay** [comment]
Can you assign this issue to me,

**Comment by MitAbhay** [comment]
@nidhi-nair

**Comment by Rishabh-Rathod** [comment]
> Can you assign this issue to me,

Hey👋🏼,  thanks for showing interest in this issue.

Unfortunately, this issue is already taken. Please do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+label%3Ahacktoberfest)

Looking forward to seeing your contributions :)

**Comment by kocharrahul7** [comment]
No longer visible
