### ISSUE TITLE
[Bug] Datepicker - Date does not get populated after an error in the default date and clearing the error

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#4947]
## Description
Release Frozen -It is observed that the date does not get populated on selecting appropriate date and even on converting to normal field the data does not get populated

**Expectation:**
Error must removed and data must get populated

**Steps to Reproduce:**
1.Launch Appsmith app in the Release frozen Environment
2.Add a date widget
3.Navigate to Property Pane --> Default Date
4.Convert to JS
5.Add inappropriate date an error is displayed
6.Leave the field empty
7.Now navigate to Date picker
8.Click on the date picker select the date
and observe

**VideoLink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/277c69c29bc944c5a434767f45fb2b5b-00001.gif)](https://www.loom.com/share/277c69c29bc944c5a434767f45fb2b5b)

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [Release Frozen]

**Comment by riodeuno** [comment]
We need to remove the flag in the defaultDate validations which makes this field `required`. Following this change, we need to verify if the widget functions correctly with `undefined` or empty values for this property.

**Comment by askalik** [comment]
could i work on this issue?

**Comment by somangshu** [comment]
Greetings @askalik, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

**Comment by dilippitchika** [comment]
@YogeshJayaseelan I wasn't able to reproduce this. Can you check once? If it's not happening please close it.

**Comment by YogeshJayaseelan** [comment]
@dilippitchika now this is working fine
