### ISSUE TITLE
Collaboration tour updates (frontend changes)

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#4957]

**Comment by RakshaKShetty** [comment]
Hi @rishabhsaxena  following the few issues still present in Onboarding tour
1.In "Tag a comment to the widget tour" instead of writing 'Why' it is written as 'y' Then the Text the is displayed twice
2.In the onboarding flow the Upload display picture should be display first then followed by "Tag a comment to the widget tour"
3.In the "Invite other people to your conversations" Th email text should be in same line instead of a line break

**Comment by RakshaKShetty** [comment]
@rishabhsaxena there is a missing tour "Tag a comment to the widget tour"  is missing

**Comment by rishabhsaxena** [comment]
@RakshaKShetty I think the changes are still not up on `app.appsmith.com`, they would be up on `release.app.appsmith.com`.

**Comment by RakshaKShetty** [comment]
> @RakshaKShetty I think the changes are still not up on `app.appsmith.com`, they would be up on `release.app.appsmith.com`.

@rishabhsaxena I tested it in release
