### ISSUE TITLE
[Feature] [Amazon S3] Add support to access buckets across different regions

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#5008]
## Summary
```
not related. I have used both us-east-1 and eu-west-1. minio error info as follows. API: SYSTEM()
Time: 12:13:51 CST 06/10/2021
DeploymentID: bfa6733f-084e-47e7-969e-0555be267365
Error: XML syntax error on line 1: invalid character entity &� (no semicolon) (*xml.SyntaxError)
       5: cmd/handler-utils.go:53:cmd.parseLocationConstraint()
       4: cmd/auth-handler.go:329:cmd.checkRequestAuthTypeToAccessKey()
       3: cmd/auth-handler.go:274:cmd.checkRequestAuthType()
       2: cmd/bucket-handlers.go:626:cmd.objectAPIHandlers.PutBucketHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

Looks like this issue: https://github.com/AlexAkulov/clickhouse-backup/issues/95

**Comment by trishaanand** [comment]
This issue is seen in the `Amazon S3 Plugin`. 

The code for the plugin can be found at :  server/appsmith-plugins/amazonS3Plugin. 

The solution for this would be to set path style to be true to allow accessing of buckets in different region. In the file `AmazonS3Plugin.java`, function `datasourceCreate()` creates the object `AmazonS3ClientBuilder s3ClientBuilder`. s3ClientBuilder should set the path style access to be true. This can be done by adding the following : 

```
s3ClientBuilder.setPathStyleAccessEnabled(Boolean.TRUE);
```

**Comment by trishaanand** [comment]
According to AWS, path style referencing is [deprecated](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/).

@mohanarpit : Should we support this at all? Or should we request developer users to create different S3 datasources for each region?

**Comment by trishaanand** [comment]
Removing Good First Issue tag till we resolve if we need to solve this.

**Comment by mohanarpit** [comment]
If AWS has deprecated path style referencing, then it doesn't make sense for Appsmith to support this use-case. Closing this issue.
