### ISSUE TITLE
[Bug] Scrolling doesn't work in the response for SQL queries

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith#5042]
When the result of an SQL Query has more rows that can be displayed at once, it should allow the user to scroll to see more rows. But scrolling is disabled/not-working.

https://user-images.githubusercontent.com/120119/121625554-4add0700-ca91-11eb-8ba4-00c5bfeec1b6.mov

### Important Details

- Version: Cloud
- OS: macOS
- Browser: Firefox
- Environment: Production, <https://app.appsmith.com>

**Comment by zdb999** [comment]
I've had this problem too. I've been able to scroll using a mouse scroll wheel or two fingers on a touch pad, but there's no visible scroll bar that you can drag or use to keep track of your vertical position. It took me a good ten minutes to figure out how to make it work on a laptop.

The same problem occurs in the SQL query box if the query is very long. I do wonder if this issue was introduced when the undesirable scroll bars on the table widget were eliminated. Not sure about this though.

**Comment by Nikhil-Nandagopal** [comment]
@arunvjn @kaushik94 can someone add a quick fix for this?
