### ISSUE TITLE
[Bug] Google API - Insert scenario overwrites an existing row data

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5076]
## Description
Release Frozen - Google API - It is observed that when a new spreadsheet is created with row data on index 1 and again inserting bulk rows to the same spreadsheet the existing row is updated with the new value

**Expected Result:**
Insert scenario should only insert record and should not update any existing row data

**Actual Result:**
Bulk insert updates an existing record

### Steps to reproduce the behaviour:

1.Launch Appmsith app in the Release frozen Environment 
2.Expand API
3.Click on Google API
4.Sync Datasource 
5.Click on create new API
6.Choose the type as 'Create new Spreadsheet' with the following row objects - [{ "rowIndex":1, "Name":"Value", "Mobile":"12345678"},
7.Click on run 
8.Go the newly created spreadsheet
9. Check if the row data are placed at row index 1
10. Now change the type to 'Bulk Insert'
11. Pass the spreadsheet url and sheet name
12. Pass the following row objects - [{ "Name":"App", "Mobile":"12345678"},
{ "Name":"Smith", "Mobile":"12345679"},
{ "Name":"Appsmith", "Mobile":"12345670"},
{ "Name":"Tool", "Mobile":"123456776"}]
13.Navigate to the spreadsheet and observe

**VideoLink:**
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/847bafc6ad294ca086df8ca7f3e11d59-00001.gif)](https://www.loom.com/share/847bafc6ad294ca086df8ca7f3e11d59)

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [Safari]
- Environment [Release Frozen]

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair this seems like a major issue

**Comment by leotom2000** [comment]
### Findings and Resolution

**Part A - Existing Behaviour**

- The Google Sheet(GS) System by default finds the nearest empty row from top and insets the new data (row) 
- - Not a issue when inserting single row of data as it fills the empty row and then it appends after the last row.
- For Bulk insert, the GS System finds the nearest empty row from top and takes it as the start index for appending data, and fills remaining rows from that row index, irrespective of weather the below rows are empty or not. so overwriting happens if the empty rows count is less than the number of rows inserted.
-  - This issue is  existing and can be simulated.

**Part B - Resolution**
As per docs : https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append#insertdataoption

- Data can be added to the Google sheet either by **appending** (overwriting rows below) or by **inserting** which can be controlled by the "insertdataoption" parameter having two values "OVERWRITE" and "INSERT_ROWS".
- Used this query parameter to resolve this issue.

**_Code Fix made :_**
- Have added "uriBuilder.queryParam("insertDataOption", "INSERT_ROWS");" to "com.external.config.BulkAppendMethod"
- This code change allowed data to be inserted wherever the first empty row is found in the google-sheet, retaining any rows below that.

**_Flip Side :_**
- A scenario that an empty row appearing, can be either by API or Manually
- While some structured RDBMS ignores or truncates empty row, google sheet retains it.
- New data(row) is inserted above the first empty row ie. empty row is not filled.
- - Henceforth every insert will happen above that first available empty row always and there can be old rows below that.

**Comment by Nikhil-Nandagopal** [comment]
@leotom2000 thank you for the detailed information on this issue! Could you also link the PR and close it once it's merged?
