### ISSUE TITLE
[Bug] Mongo_Plugin - Results are displayed when incorrect query is passed in 'Array of Pipeline' field in Aggregate scenario 

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5326]
## Description
Release - Mongo_Plugin - It is observed that on passing invalid query in the Array of Pipeline the result are still fetch-able 

**Expected Result:
Array of Pipeline should accept only valid query

Actual Result:**
Passing  { $match: { status: "A" } }fsgdgdfgh in the Array of pipeline still the result is fetch-able 
  
### Steps to reproduce the behaviour:

1. Launch appmsith app in the release environment 
2. Open existing mongo_Plugin Datasource 
3. Insert a Document with the following query - [{"_id":"1", "User":"Yogesh", "Status":"A", "Amount": "500"},
{"_id":"2", "User":"Anand", "Status":"A", "Amount": "500"},
{"_id":"3", "User":"Karthi", "Status":"B", "Amount": "500"},
{"_id":"4", "User":"Rajesh", "Status":"A", "Amount": "500"}]

4.Change the type to Aggregate and enter the collection name and passing the following query in the 'Array of Pipelines' - { $match: { Status: "B" } } and ensure results are valid 
5.Now pass the following invalid query in the array of pipelines and observe
{ $match: { status: "A" } }fsgdgdfgh

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [production, release
<img width="1280" alt="Screenshot 2021-06-30 at 5 36 25 PM" src="https://user-images.githubusercontent.com/35128442/123957805-da5b4300-d9c9-11eb-9ff2-893057697acb.png">
]

**Comment by mojtab23** [comment]
### Explanation
MongoDB aggregation pipeline consists of one or more [stages](https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline/#std-label-aggregation-pipeline-operator-reference) that process documents. Appsmith aggregation input also accepts a single JSON object and treats that as an aggregation pipeline with one stage, therefore we have two methods for validating user input in the aggregation pipeline, One validates an array of stages (JSON objects) and another one validates a single JSON object. 

This issue is related to the second method (single JSON) and because we use `org.bson.Document.parse()` and looks like it is not very strict in parsing JSON strings, it ignores invalid characters after the first JSON object in the string (after the first `{...}`).

### Possible solutions
Based on our UX and desired behavior we can do either:

- Just ignore it and close the issue, because if the first JSON object was a valid JSON and valid aggregation stage, it will work and update without problem.
- Add another and more strict JSON validation before the call to `org.bson.Document.parse()` so the cases like above will fail in the validation.
