### ISSUE TITLE
[Bug] Table search not working with onSearchTextChanged

### ISSUE THREAD

**Issue by WillemJann** [appsmithorg/appsmith#5444]
## Description

For the table widget, if the `onSearchTextChanged` action is defined the actual search functionality is not working anymore. The `onSearchTextChanged` action itself is executed, but the search (filter) on the table is not applied.

### Steps to reproduce the behaviour:

1. Create a table widget with some data.
2. Set `onSearchTextChanged` to some action (e.g. save the search value in the store or show a message)
3. Enter a search term. The search filter is not applied, but the action is executed.
4. Remove the `onSearchTextChanged` action.
5. Enter a search term. The search filter is now applied.

### Important Details

- Version: self-hosted, v1.5.5
- OS: Windows 10
- Browser: Chrome
- Environment: production

**Comment by Nikhil-Nandagopal** [comment]
@WillemJann can you tell us which datasource are you working with? Did you configure the datasource to filter data based on the {{ Table1.searchText }} field?

**Comment by WillemJann** [comment]
The datasource of the table is a MongoDB query. The datasource is not configured to filter on the {{ Table1.searchText }} field. That's on purpose, because the default search behavior is in all visible columns of the table, which is very useful.

**Comment by Nikhil-Nandagopal** [comment]
@WillemJann You can write the logic as {{ Table1.searchText === undefined ? {} : { name: Table1.searchText } }}
so that it defaults to all data when the searchText is empty

**Comment by somangshu** [comment]
Before a while we have actually made this change in #4039. When we set/bind `onSearchTextChanged` to an action we stop propagating the client side search.

**Comment by WillemJann** [comment]
Ah, I see that this behavior is introduced after #4039.

However, in previous versions of Appsmith we could benefit of the client-side search and additional actions. We use it to remember the search text, with an additional action it is saved in the store. The next time the default search text is read from the store, so that the same filtered table appears.

Client-side search is easier because we don't need to modify all queries to take the searchText into account. Is there no way to combine the client side search with additional actions via the `onSearchTextChanged` field? In other words, is there a way to continue the propagation when `onSearchTextChanged` is set.

I started this issue as a bug because it was working in a previous version of Appsmith 😉

**Comment by Nikhil-Nandagopal** [comment]
@WillemJann could you explain why are you triggering onSearchTextChanged if you don't need to perform server side search?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal I think what they need if to save the search text in the store and reference it the next time but let the client side handle the filtering process. @WillemJann Am I getting this right?

**Comment by WillemJann** [comment]
Yes, that's exactly right.

**Comment by somangshu** [comment]
@vicky-primathon do you think this is achievable?

**Comment by Nikhil-Nandagopal** [comment]
@WillemJann thank you for the details. @somangshu yeah we can have a separate property to disable client-side search.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal How do we handle disabled client-side search and no onSearchTextChanged action then. It would look like a bug to the end user. There could be other complexity as well here.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu sounds like a bug the developer introduced so maybe we shouldn't be the ones to handle that? We can also provide explicit options for client side search such as case sensitive, insensitive, prefix match, fuzzy match and disable.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal going by the first logic and ignoring that we allowed such a use case should work fine. Shall we implement this, It not a lot of effort and can be picked up soon

**Comment by WillemJann** [comment]
Any update on this? Client-side search is still not working if `onSearchTextChanged` is set.

**Comment by zegerhoogeboom** [comment]
I have the exact same use case and am running into the exact same issue after not having updated Appsmith for a while, suddenly the logic of remembering the table filter and doing client-side search is broken.

**Comment by Nikhil-Nandagopal** [comment]
@zegerhoogeboom can you explain the issue you're seeing with remembering the table filter? 
The client side search is applied on top of the server-side search so that needs an option to be disabled which we're working on. A way to get around this is to disable the search option in the table and use an input to perform the server side search. This will not perform any client side search on top of your results

**Comment by zegerhoogeboom** [comment]
Hi @Nikhil-Nandagopal sure, the issue is exactly like @WillemJann described earlier in this issue. In this image there is an action `onSearchTextChanged` specified and I'm searching for the text "Drop" which does *not* filter the results.

![image](https://user-images.githubusercontent.com/5371096/144027039-ed2ef3d4-27f8-46f6-9923-d39f13996af1.png)

When no `onSearchTextChanged` handler is specified the table *is* filtered

![image](https://user-images.githubusercontent.com/5371096/144027222-6b0b9da6-29fd-4b69-b637-45584d317da3.png)

What I want to happen, similar to @WillemJann is that client-side search is still done **and** the `onSearchTextChanged` handler can work, such that the search text can be remembered when the user e.g. reloads the page. I don't want to do any server-side search in this case.

**Comment by WillemJann** [comment]
@zegerhoogeboom this is indeed exactly the issue. When this is solved we can remember the search text of tables **and** make client-side search happen. Thanks for your explanation!
