### ISSUE TITLE
[Bug] Safari - Not able to view any existing app or view the newly app created

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#5480]
## Description
Safari - Release Environment - It is observed that user is not able to view any new or existing app in safari

**Expected Result:**
User should be able to view any existing apps or new apps

**Actual Result:**
User is not able to view any existing apps or new apps

### Steps to reproduce the behaviour:

1.Launch appsmith app in the Release Environment in Safari browser 
2.Open any existing apps and observe
3.Create new app and observe

**VideoLink:**
https://loom.com/share/37e610ccbb3f4789b09902910c3edf36

### Important Details

- Version: [14.1 (16611.1.21.161.3)]
- OS: [MacOS Big Sur Version 11.3]
- Browser [safari]
- Environment [release]

**Comment by somangshu** [comment]
This is because of a regex added at this line : https://github.com/appsmithorg/appsmith/blame/d56ebf83ad7234e03260c7aeaded804a4de797d1/app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx#L52

in this PR:
https://github.com/appsmithorg/appsmith/pull/4427

Here is the issue discussed on SO:
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group
