### ISSUE TITLE
[Bug] Width of drop-downs in property pane is shorter than the field width

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#5514]
The width of the dropdown should be the same as the width of the fields themselves.

<img width="257" alt="Screen Shot 2021-07-01 at 2 13 34 AM" src="https://user-images.githubusercontent.com/30255708/124028782-04d0ee80-da12-11eb-92f8-aed333d9f0e1.png">
<img width="263" alt="Screen Shot 2021-07-01 at 2 14 18 AM" src="https://user-images.githubusercontent.com/30255708/124028809-0bf7fc80-da12-11eb-9f6f-28698c6938cc.png">

**Comment by SandipPalit** [comment]
I would love to work on this Issue and I can solve it. Please assign it to me.

**Comment by riodeuno** [comment]
@SandipPalit Thanks for offering to help out with this issue. This is all yours. I'm assigning this to you!

**Comment by SandipPalit** [comment]
Thank You @riodeuno 
I am working on this issue and will submit the PR soon.

**Comment by ankurrsinghal** [comment]
This issue is arising because one of the property controls _DropdownControl_ which uses portals, is used by the _PropertyControl_. Now the _DropdownControlsProps_ has an optional prop _optionalWidth_ which defaults to **231px** and hence of lesser width than the trigger _PropertyControl_. Now during the control building, all the control props are of base type ControlProps which doesn't have _optionalWidth_. Even if we can typecast the props according to the control type how we should set the _optionalWidth_ according to the trigger PropertyControl. (Using a ref or bounds)

**Comment by Nikhil-Nandagopal** [comment]
@secure-crypto go for it!

**Comment by ankurrsinghal** [comment]
Hi @secure-crypto are you still working on this?

**Comment by Nikhil-Nandagopal** [comment]
@ankurrsinghal it doesn't seem like it. If you're keen please go for it!

**Comment by rohitagarwal88** [comment]
The issue is fixed on live. closing it
