### ISSUE TITLE
Load default filters from the `store`

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#5637]
# Objective
Add default filters to the table which applies on load, also expose the table widget filter API

# Requirement:
| Title | Desc | Comment |
| ---- | ----- | ----- |
| Default filter | This need the column where we need to apply the filter, the type of query (already available in the table filter) and load the value from either store or other objects; Once the control is set we will apply this filter by default | This will probably require a new control, Kindly discuss with design |
| filter: Internal prop | This will expose the selected/applied filters on the table as an array or objects `{key: string, value: string, query: string}` | - |

**Comment by nidhi-nair** [comment]
In order to make filtering in integrations easier, we need support for server side filtering which can be achieved by this feature. The idea is to refresh tableData on the basis of the filter.

Today for integrations that support filtering we have a particular format for the data to be entered in. But a more dynamic way of supporting this would be possible if the filters chosen by the end user can be applied to the integration instead.

**Comment by dilippitchika** [comment]
Picking this in #18098
