### ISSUE TITLE
[Enhancement] Show lint errors on imperative assignments without a setter method

### ISSUE THREAD

**Issue by hetunandu** [appsmithorg/appsmith#5822]
When a user writes an imperative statement without the use of setters, show a lint warning and prompt the user to use setters instead. 

eg: When a user writes `widget.isVisible = true`, show a lint error that says `isVisible is read-only. Use setVisiblity() instead`

**Comment by bharath31** [comment]
@Rishabh-Rathod @Druthi Could we add this to #3532?

**Comment by Rishabh-Rathod** [comment]
`Unfortunately, JSHint does not provide a direct configuration option to make a specific property of a global object read-only. The globals option in JSHint configuration is primarily used to define global variables and specify their values (true or false) to control whether assignments to those variables should be allowed or disallowed. However, enforcing read-only properties on a global object's specific property is beyond the scope of JSHint's capabilities.`

Due to above mentioned JSHint limitation, it won't be easy to implement the above functionality until we find a way to support it in our linting architecture. We could try exploring eslint. 

cc: @ohansFavour

**Comment by ohansFavour** [comment]
Hey @Rishabh-Rathod ,

Alongside JSHint's generation of lint errors, we also parse the user's code (using AST) and generate custom lint errors. We should be able to generate the "imperative assignments" errors while traversing the parsed tree.

**Comment by Rishabh-Rathod** [comment]
Thanks @ohansFavour. We will go ahead with the AST parsing for the above use case. Could you please help in the estimation of this task?

**Comment by Rishabh-Rathod** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/5822?planning-poker) with Zenhub @ohansFavour

**Comment by Rishabh-Rathod** [comment]
Adding 2 more story points according to the complexity of showing the error message with respect to widget property.
