### ISSUE TITLE
[Bug] Appsmith Deployment Fails on Redhat

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#5856]
## Description

A user reported an error while deploying appsmith on their redhat instance

```
Adding repo from: https://download.docker.com/linux/rhel/docker-ce.repo
Installing docker
Error: Failed to download metadata for repo 'docker-ce-stable': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Please share your email if you wish to receive support with the installation
```

**Comment by dulatello08** [comment]
I am that user and there is a way to install.
Comment install_docker* in install.sh and manually install it manually.

**Comment by sharat87** [comment]
Hey @dulatello08, thank you for chiming in. From the error message it looks like the installation for Docker failed to fetch metadata. Can you confirm if you have internet connectivity on this machine?

Also, did you already have Docker installed on your machine? Asking because if yes, then the script shouldn't have tried to install Docker again, that would be a bug.

**Comment by Nikhil-Nandagopal** [comment]
@sharat87 actually the docker download was also failing because the osname for redhat was Red Hat instead of rhel, after changing this, we got a new error
https://github.com/appsmithorg/appsmith/commit/b54869c03ebfb016042bfb4a718f1ce75bf6138d#diff-ed1191c237ea4ba8f2011568f4ed0208c8d0ca36cbde1285828a61b4ff2128b4
