### ISSUE TITLE
[Bug] When the same mock DB is added twice it shows an error.

### ISSUE THREAD

**Issue by Debsourabh** [appsmithorg/appsmith#5924]
## Description

[What happened]
 Currently trying to add the mock twice throws an error. 

Add steps to reproduce this behaviour, include console / network logs & screenshots

1. Go to datasource page
2. Try adding the same mock data twice

### Important Details

- Version: [Cloud 
- OS: [Windows]
- Browser [Chrome]
- Environment [production]
![image](https://user-images.githubusercontent.com/34486435/125974821-af264113-6563-42bb-8e4f-200d330e1e37.png)

**Comment by RakshaKShetty** [comment]
@AnaghHegde the user is able to create a duplicate mock database but when the user tries to run the query on the duplicate database the Auth error is displayed 
![image](https://user-images.githubusercontent.com/45958978/127602684-41c14f3c-9590-4ae3-91db-374a0d63df55.png)

**Comment by RakshaKShetty** [comment]
@AnaghHegde the issue is reproducible the user has a duplicate mock database that is already created (the older ones) when the user tries to run the query on the duplicate database the Auth error is displayed
![image](https://user-images.githubusercontent.com/45958978/129165206-6bbea934-ff4c-4130-83a5-2a2e37e1c361.png)
