### ISSUE TITLE
[Feature] Table Columns should Have Column properties and Cell properties

### ISSUE THREAD

**Issue by Tooluloope** [appsmithorg/appsmith#5943]
## Summary

Properties like Visible and Disabled are applied to the column and not individual cells in the column while Text align and and other stylings are applied to cells, this should be properly separated

![Screenshot 2021-07-16 at 10 38 53](https://user-images.githubusercontent.com/31691737/126111479-a1bd7405-0e9d-464d-b5e8-12c652b53181.png)

## Motivation
Would cause confusion for Users

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope can you explain this better? It seems both are applied on the cells of the column and can be conditionally controlled using currentRow

**Comment by Tooluloope** [comment]
@nikhil, So using `currentRow` in evaluating true or false for the `Visible` would always return a boolean array which would eventually evaluate to true for the property.

That's the difference between The column and Cell properties, The Cell should have an array of values, while the column should evaluate to a boolean

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope So why can't this also be a cell property? We don't need visible as a column property here. In fact inside a column, they should all be cell properties, isn't that right?

**Comment by Tooluloope** [comment]
@nikhil From the original issue, it applies to just the column https://github.com/appsmithorg/appsmith/issues/3250

**Comment by Nikhil-Nandagopal** [comment]
@Tooluloope sorry to be clear even in the original it applied to the cell itself. As hetu mentioned, we must be able to control it via JS so that some buttons are visible/disabled conditionally. There is no case to disable/hide the entire column because that can be achieved by simply hiding the column from the table setting.

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal I think is how I think this feature should work.
- `isDisabled` will utilise `currentRow` to enable cell level enabling or disabling of a `button` type column
- `isVisible` will be a column level property which will _*not*_ utilise `currentRow` and will be applied to the whole column _*dynamically*_  as opposed to the current UI based column visibility setting.

I believe this is in line with some of the requests we have received from our users.

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno we already have isVisible at the column level to show / hide. Why can't this property also work the same as isDisabled? I don't think there is a strong case for showing / hiding the entire column dynamically as much as there is for the values in the column.

**Comment by riodeuno** [comment]
@Nikhil-Nandagopal Just to clarify, what you're suggesting is the following:
- Allow users to "disable", "hide/show" a cell using `currentRow` as a new feature. This is only used for button type columns.
- General column visibility is a feature we already have, although not dynamic, and since there is no strong case for this, we can defer implementing any updates to this, to a later date.

**Comment by Tooluloope** [comment]
Should we bring this discussion to https://github.com/appsmithorg/appsmith/issues/3250, and probably closed this issue?

**Comment by Nikhil-Nandagopal** [comment]
@riodeuno yeah I am ok with not introducing it till later. But hide / show is not only for button types, it can be for any cell. I am only against bringing in a column-level visibility inside the column because it already exists at the table property level. If we introduce it as dynamic, we can do that for the cell level and add logic like if all cells are hidden, hide the column.

**Comment by Tooluloope** [comment]
@Nikhil-Nandagopal, The `isDisabled` property is for the button type column, and it's on the cell level. I believed this is cleared out already.

The contention now is on the Cell visibility or Column visibility within the Column property pane.

It could be possible to add both i.e. (Cell visibility and Column visibility) but make them under different Headers.
Cos as @riodeuno stated, there are requests received for making the columns visible dynamically.

**Comment by somangshu** [comment]
@Nikhil-Nandagopal @areyabhishek @riodeuno 

We see that the isVisible property is a column level function. This is appropriate but should be extended to the individual button as well as shown below. It makes sense to show/hide, enable/disable a button in every cell.
<img width="1415" alt="Screenshot 2021-07-20 at 1 31 44 PM" src="https://user-images.githubusercontent.com/11089579/126309617-3c4db8b6-f41b-4a97-a03b-14540415430c.png">

For the rest of the column types the isVisible function should apply on the whole column rather that on cell. The manipulation we need on an individual cell with all other column types can be handled through the computedValue (data manipulation). The dev can choose to hide the whole column based on a condition (ex hide one column for a user)
<img width="1425" alt="Screenshot 2021-07-20 at 1 32 10 PM" src="https://user-images.githubusercontent.com/11089579/126309693-154f1611-8043-4648-9dc7-783907b6a8ed.png">

Conclusion: We think the `isVisible` property should be per column for controlling visibility for a column based on a binding/expression for all column types apart for button. The Button column should have `isVisible` & `isDisabled` for every cell as its not dependent on the current row.

**Comment by Nikhil-Nandagopal** [comment]
@somangshu unfortunately users rarely think in those terms i.e hide the cell with the computed value and this becomes inconsistent because
1. All other properties inside the column property can control the cell
2. It won't work for buttons / checkboxes / dropdowns that we add in the future for each cell
Why can't the rule be that it controls the cell but if all cells are hidden, we hide the column? I think dynamically hiding columns is also generally not a great UX practice because it suddenly shifts data.

**Comment by somangshu** [comment]
We will try to resolve this from the UX standpoint. 

- The column setting view should have a column level `visible` property which applies to the cell. The property should behave consistently for all types.


Problems: 
- Currently showing is `visible` in the both button properties and column settings can be confusing
- Showing a cell level activity (`visible`) in the column settings can be confusing
- For type button, the isVisible property right now applies on cell level. 

[Deploy preview](https://deploy-preview-4819--appsmith-editor-ce.netlify.app/)

@momcilo-appsmith need your help here. 

cc @areyabhishek

**Comment by somangshu** [comment]
@Tooluloope The proposed solution here is:
- The visible property remains in the column settings and applies on a cell level
-  Another property introduced here which will let the user choose to hide the column in case all cells are empty, This property is not going to be JS convertible. 

CC: @areyabhishek @Nikhil-Nandagopal @riodeuno

**Comment by Tooluloope** [comment]
@somangshu, For the first point, the control for this visible Property would then have to be a JSControl since switch cannot be used for cell Level control

For the second point, Once the switch is `true`, the column is meant to be hidden solely if all cells are empty? or if they are hidden?
