### ISSUE TITLE
[Enhancement][JS Snippets] Research/POC on the best storage options for snippets (Fast search/filter)

### ISSUE THREAD

**Issue by arunvjn** [appsmithorg/appsmith#5986]
Need to find the best storage option for Snippets. The storage should provide fast search and retrieval based on various parameters like entity, field, data type and text. It should be convenient to update the collection in case any modification is required in the future.

**Comment by sumitsum** [comment]
I have been looking into the options to store JS snippets so that we can do the following operations efficiently:
* run complex search queries that must do fuzzy text match
* update snippets data

I considered the following three options:
(1) Mongodb Atlas text search
(2) store snippets in file + serach via Algolia
(3) store snippets in Mongodb cloud + search via Algolia

Regarding option (1) - On paper it seemed to be the best option - since no extra operational complexities would be required if the data is both stored in Mongo Atlast and queried over there as well. However, when trying out few AND / OR type of search queries on a small dataset I realized that it is tremendously painful to write any meaningful search query in BSON. Plus the kind of operators that Mongo Atlas provides for fuzzy text search, it looks like it may not be possible to construct many AND / OR mixed type of search queries that may be required. Documentation is also not very helpful.
Note: Regular mongodb does not allow fuzzy text search. This feature is offered exclusively by Mongo Atlas.

Regarding option (2) - It didn't seem to be very useful because keeping the snippets on a file makes it very difficult to update them. e.g. if we want to update the number of times each snippet gets selected, we can't do it if the data resides in a file. This option came into consideration because keeping the snippets on file would allow us to host it on Github, and take contribution from users via regular pull requests to update the file.

Regarding option (3) - this seems to be the best option as of now. It allows us to keep the snippets in Mongo db, hence making it possible to update the data in future - e.g. to increment the usage count for each snippet and it allows us to use use Algolia's search API, which is much more convenient and faster as compared to Mongo Atlas. Also, since we already use Algolia to search documentation text from Omnibar, basic infra to query from Algolia is already available which can be leveraged. The only downside is that it would add to operational complexity - we would need to set up a job that runs periodically or on trigger to sync up data from Mongo cloud to Algolia. Such a job already exists on AWS lambda for documentation data, hence we can set up a job for snippets along similar lines.

Adding another data point: current documentation queries on Algolia seem to return within 50 -150 ms, whereas API calls to our API server to fetch data seems to return in 300- 600 ms range, sometimes even longer.

Based on the actions pod meeting on `30-07-2021`, we have concluded that option (3) seems to be the most promising, hence I will be moving forward with it.
