### ISSUE TITLE
[Bug] False positive and false negative messages displayed while system handles incorrect variable naming for a GSheets datasource

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#5988]
## Description
False success and failure messages displayed when user follows incorrect variable naming convention for datasource on Google Sheets.

### Steps to reproduce the behaviour:
1. Go to add datasources, add and authorize Google Sheets
2. Go to 'create new query' and type in a query name that begins with a number
3. Run the query
4. App displays an **error** for naming convention _(expected behaviour)_
5. Edit query name to add alphabets at the start to follow naming convention and click 'Run' - still displays an **error** _(false negative)_
6. Click on 'Run' again - displays response and **success** message _(expected behaviour)_
7. Edit name again to remove the added alphabets and hit 'Run' - displays **success** message and 'Logs' republishes the same json response from step 6 _(false positive)_

## Important Note
Method 'List Sheets' in query does check for naming convention - unsure if this is a requirement hence no errors are displayed and this scenario is void for the method.

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Chrome
- Environment: production
https://www.loom.com/share/aed0b0acf8bc436785b4ede03e607ca9

**Comment by Nikhil-Nandagopal** [comment]
@nidhi-nair could you have a look at this?

**Comment by nidhi-nair** [comment]
Multiple issues here, which is applicable for all query editors:
1. The refactor call is made after the execute call on button click `Run`. So the false positive happens because the execution happens with the old valid name, and then the refactor happens.
2. The refactor itself should fail at UI level with the same rules as the backend is failing this execution for
3. The backend should have also returned with an error for the refactor call.

@ajinkyakulkarni I'll pick up # 3 from the above, but the others look like client side changes. Could you please help?

**Comment by nidhi-nair** [comment]
Unassigning myself from this issue since the backend fix for this has been merged. Please feel free to bring me back in if anything more is required.

**Comment by Nikhil-Nandagopal** [comment]
Let's close this. I just checked and all rename calls are only checked from the backend there's no frontend validation
