### ISSUE TITLE
[Bug] Unable to download PNG and JPEG option 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#5999]
Steps to reproduce:
1) Add an Image widget
2) Bind image for download 'on click'
3) click on the image 
and observe

Observation:
It is observed that the image does not get downloaded and displays an error "file is empty"

Expectation:
An appropriate  image is added into the image field the file must be downloaded

![Screenshot 2021-07-20 at 2 20 51 PM](https://user-images.githubusercontent.com/71753653/126291838-740e931a-f0be-42a2-abda-5928fa42b00f.png)

**Comment by ajinkyakulkarni** [comment]
This is the issue 
![image](https://user-images.githubusercontent.com/800578/126297643-eba946b0-de13-4b9a-937b-71aa934c1ae2.png)

**Comment by ajinkyakulkarni** [comment]
This issue is solved if the MIME-type is changed to "application/x-binary".  This is probably not ideal. We should be able to use "image/png" But if that is not possible then we map binary files automatically to "application/x-binary" internally?

<img width="550" alt="2021-07-20_14-59-20" src="https://user-images.githubusercontent.com/800578/126298181-651515cc-b132-48f8-9e36-4423058bb2db.png">

**Comment by ajinkyakulkarni** [comment]
TODO: We also need to update the documentation for this change.

**Comment by hetunandu** [comment]
Fixed with #6179
