### ISSUE TITLE
[Bug] Property pane code editor have limit on copy text

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6043]
## Description

Weird bug in the Property pane code editor where the user cannot select the whole text (ctrl + a). The cursor does not move right or down after a point in time. The code editor example below has about 48 lines

### Steps to reproduce the behaviour:

![unknown](https://user-images.githubusercontent.com/11089579/126466946-5dbecf04-dfe9-4883-9926-38cbd5d6270e.png)
![unknown (1)](https://user-images.githubusercontent.com/11089579/126466987-9f88ea62-e022-4002-ad6f-2280bbd1d37b.png)
![unknown (2)](https://user-images.githubusercontent.com/11089579/126466990-3135520a-2d82-4765-bf9a-f32ce3bfb0bd.png)

### Important Details

- Version: [Cloud]
- OS: [e.g.MacOSX]
- Browser [chrome, safari]
- Environment [production]

**Comment by somangshu** [comment]
When the user copy and pastes they get the whole content.

**Comment by zzgvh** [comment]
Some additional info.

I'm seeing this in the Select widget Options field, but also in the Submit button, both the onClick and Reset form on success fields.
If I click at the end of a field with this bug, I don't get the cursor placed at the end but at the place where the select all selection would end as shown in the screenshots. At this point I can use the arrow keys to navigate two chars back (left arrow) and then the cursor jumps to between char 2 and three from the actual end. By doing that the bug disappears and selection works normally.

**Comment by ramsaptami** [comment]
Seems to be a specific edge case that we're not able to replicate on our end. Would need more information to investigate this.

**Comment by zzgvh** [comment]
[Johannas Plants.txt](https://github.com/appsmithorg/appsmith/files/6866808/Johannas.Plants.txt)

 Here is an export of one of my apps experiencing this issue. It's renamed to get past GH's limit on file formats!

The bug appears in many places, an example is the submit button in the Plantera view; both the `Reset form on success` and the `onClick` fields have largish IIFEs. When I click in the field and do ctrl-a to select all it looks like not all text is selected. But if I copy and paste it everything is there. Also if I scroll down to the end of the field I cannot set the cursor at the end of the JS, it ends up in the exact spot where the selection from ctrl-a ends! When the cursor is in this spot, if I go left three steps, using the left arrow key, the cursor ends up three chars from the actual end of the script and the bug is "gone", a ctrl-a now grabs the full selection.

I'm running this on Linux mint, FireFox version 89.0.2.

Holler if you need the spec of my Google sheets to be able to run the app!

**Comment by somangshu** [comment]
:wave @zzgvh, Thanks a lot for the additional information to support us here. 

@ramsaptami can we check to see if the above information helps. Lets import the app attached to test this out.

**Comment by ramsaptami** [comment]
@somangshu When there's a space between code lines then Ctrl+A _highlight_ only reads characters until it sees any two consecutive brackets  "}}" or "}]" as EOF up to the point where it can omit the last 5 characters including actual EOF (refer to video for further understanding). On the functionality front everything seems to be working as expected, Ctrl+A is selecting all text and Ctrl+C copies all available text. 

If user removes these spaces then text highlight is working as expected, i.e. all text is selected. 

This 'bug' seems to happen with code that's longer than ~15 lines.
https://www.loom.com/share/7a714bf18e1142cf88a8d38b0f3892c5

**Comment by somangshu** [comment]
@SatishGandham can you tell us if this is a problem with the code editor?

**Comment by ramsaptami** [comment]
UPDATE: Dropping a new table widget on the current release and trying to select all or go to the end of the default code is not possible (was possible before to the best of my knowledge). The last line is being cropped off - but I'm able to copy, paste and delete the entire code.
![image](https://user-images.githubusercontent.com/79509062/132203533-d98f5e0b-a538-4936-8cc1-e1920666541c.png)
