### ISSUE TITLE
Configure proxy server with static IP in the cloud 

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#6045]
When we move to a clustered environment, the API & DB queries initiated by the server will originate from different IPs. But we ask our users to whitelist specific IPs in their database & API servers to ensure security. This means that all action executions originating from any of the JVMs in Appsmith's cloud should be routed through a forward proxy server (Nginx). The Nginx server will be tied to a static IP that our users can whitelist.

### Additional Context
Refer: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
Alternate Solution: https://docs.aws.amazon.com/vpc/latest/userguide/egress-only-internet-gateway.html

We should configure the http/https proxy & the SOCKS proxy (for JDBC protocol)
pertain to the feature.

**Comment by dncpax** [comment]
hi there. also interested in this. But isn't it the same as #3311?

**Comment by sharat87** [comment]
Hey @dncpax, that's actually a different issue. That issue is about supporting a way to configure HTTP Proxy, to be used when making API request calls.

This one's actually not about a _proxy_ exactly, but about having a static IP for egress from Appsmith's cloud offering, [app.appsmith.com](https://app.appsmith.com). This was actually completed last week and can be closed now. Thanks 😄
