### ISSUE TITLE
[Bug] Containers always has a scroll even after you remove a widget

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6146]
Containers continue to keep a scroll even when there are no widgets in them.

**Comment by somangshu** [comment]
@areyabhishek the container property `Scroll Content` adds the scroll to the widget component. When a widget underneath is deleted in the scroll enabled mode the the container component resets to the initial position. 

Uploading Screen Recording 2021-07-27 at 10.24.29 AM.mov…


Can you detail the issue here a bit.

**Comment by areyabhishek** [comment]
I was shown this on a video call by a user. See this [video.](https://drive.google.com/file/d/1jnUuFKsMytCRPIKmYw_pOzofVSeQiswN/view?usp=sharing) See this video from 13:30 to see the scrollbar issue in list containers after copy paste and delete.

**Comment by somangshu** [comment]
Got it, Thanks for the info, This should be looked at with the list widget bugs we are fixing right now. @jsartisan can you prioritise this accordingly.

**Comment by jsartisan** [comment]
@somangshu Sure. Will be fixing this one too with other fixes.

**Comment by Tooluloope** [comment]
@somangshu This is fixed as well
