### ISSUE TITLE
[BUG] Delete column shifts right and left when clicked

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#620]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Login
2. Go to Share --> Manage Users 
3. Click on Delete column

Expected Result: It shifts right and left when user clicks on it
Actual Result: It should stay firm

Attachment: https://drive.google.com/drive/folders/19dPNui95icdE1VxL-Tygtl_LwEc1-IBH?usp=sharing

**Comment by satbir121** [comment]
We are using `react-table` library. The column width gets re-calculated when the sort icon is added. One solution can be to add `minWidth` to the columns as mentioned in [this doc](https://react-table.tanstack.com/docs/api/useTable#column-options).

The `minWidth` has to be added for the Delete column inside `columns` variable in[ this file](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/organization/Members.tsx#L68)

**Comment by pushkar1393** [comment]
Is anyone working on this? If not can someone please assign me to it? Thank you.

**Comment by Nikhil-Nandagopal** [comment]
@pushkar1393 go for it!

**Comment by pushkar1393** [comment]
Awesome, thanks! For testing purposes do you have an auto-reload setup that I am missing or  do I need to yarn build and start ?

**Comment by pushkar1393** [comment]
> We are using `react-table` library. The column width gets re-calculated when the sort icon is added. One solution can be to add `minWidth` to the columns as mentioned in [this doc](https://react-table.tanstack.com/docs/api/useTable#column-options).
> 
> The `minWidth` has to be added for the Delete column inside `columns` variable in[ this file](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/organization/Members.tsx#L68)

This approach won't work, because `minWidth` or other similar properties don't affect the `headerProps` even though they are successfully passed on to the Table component unless `useBlockLayout` or `useAbsoluteLayout` hook is passed as an option to `useTable` hook. In that case, each cell gets treated as an `inline-block` and css props are applied but that doesn't seem like a feasible solution. Table component currently uses  `useFlexLayout` internally. 

So I think one way around it would be to pass an optional StyledComponent prop to Table component which can be used to wrap around cells if present. Another way would be to pass on a `headerClassName` inside the `columns` array but not sure how I would create a CSS class in the current structure, of `Members.tsx`
Please let me know what you think of it? Any other suggestions are welcome.Thank you.

**Comment by satbir121** [comment]
Hey @pushkar1393 There doesn't seem to be a good quick solution for this. I was thinking that fixing width might not be the right solution for column shifting due to sort.

Proposing another solution here:
Just create a HiddenArrow like this:
```
const HiddenArrow = styled(DownArrow)`
  visibility: hidden;
`
```
And use it like this:

```
    {
      column.isSorted ? (
        column.isSortedDesc ? (
          <UpperArrow />
        ) : (
            <DownArrow />
          )
      ) : (
          <HiddenArrow />
        )
    }
```

**Comment by pushkar1393** [comment]
Sounds good to me. Will update it soon. Thank you.
