### ISSUE TITLE
[Feature]Send a hint to turn off Prepared Statement if the error says syntax error at or near $x

### ISSUE THREAD

**Issue by trishaanand** [appsmithorg/appsmith#6235]
## Summary

More often than not, users are not used to Prepared Statements semantics and don't understand why their queries are failing. Hint messages would be a solution in the short term to get them unblocked by turning off prepared statement

**Comment by Nikhil-Nandagopal** [comment]
Instead of this, I suggest we do this as part of UQI where if a user is using the form, prepared statements are on and if a user is selecting the raw method, prepared statements are off

**Comment by areyabhishek** [comment]
@Nikhil-Nandagopal Do we need to wait for UQI to go live for this? Why not turn this off right now? It's a small change and will help users immediately. UQI can solve it well, but I don't see the point of waiting. 

Also what is the difference between raw method and form? Why not keep them turned off for both methods for consistency?

**Comment by Nikhil-Nandagopal** [comment]
@areyabhishek prepared statements are very useful to users for a couple of reasons
1. It automatically adds quotes for users who used to face a lot of issues while binding values
2. It automatically escapes special characters for users so their queries don't suddenly break when their users input special chars like ' and " or newlines in widgets.
3. It adds an important layer of security for users
So turning it off will only shift the problem than solve the problem. The real problem is that prepared statements have a few edge cases that need to be handled better so we should fix that. 

I'm not against prompting people to turn it off, the reason we didn't go with this solution is that we realized that we could not confidently say that it is a prepared statement problem. This would have been hit or miss solution so we decided that instead of introducing more complexity, we'd fix it once and for all with UQI.

Why we proposed prepared statements to be on for form and off for raw is because
- The form method of entry is restrictive and we are in control of what fields you are entering in the SQL, thus we can guarantee prepared statements work in all cases and is a convenience feature for users.
- With UQI, the form will become powerful enough to cover most CRUD use cases and you will only need to go to raw mode when you need to do query generation which is the case where prepared statements fails. So this mode will have prepared statements off.

**Comment by ajinkyakulkarni** [comment]
Internal thread about a short term solution to this problem https://theappsmith.slack.com/archives/C01HXJPFWBC/p1631289225107600 (we will basically show a static message/hint to users)
