### ISSUE TITLE
[Bug] Error message and null data message on generate app when table has no data/only numericals

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6239]
## Description
- [ ] When table has no records, user can generate a page but the error message displayed does not convey this message appropriately (screenshot attached).
- [x] Include a message when table has no data with an appropriate text since the dropdown would not have any column. Currently, a tiny portion of the dropdown appears which feels incomplete
- [x] When table contains only non-string entities, columns are not displayed under **select column** dropdown (only displays a portion of the dropdown similar to above scenario) so include an appropriate text to inform user of this.
- [x] Include the text 'optional' next to **select column** dropdown as it's not apparent feature to the user

### Steps to reproduce the behaviour:
1. Go to datasource and click on generate app
2. Select table that contains no data (present under mock data - table userDiscounts) and click on 'Generate App'
3. Observe the error message displayed

### Important Details
- Version: CLoud
- OS: Win10
- Browser: Chrome
- Environment: deploy preview

![Untitled](https://user-images.githubusercontent.com/79509062/127469167-ea0c73c4-b3a8-478c-a90f-277b09f420ea.png)

![image](https://user-images.githubusercontent.com/79509062/127471052-3b57d3f5-8f21-417f-b114-d839b6d18946.png)

**Comment by Rishabh-Rathod** [comment]
@abhvsn 
> When a table has no records, the user can generate a page but the error message displayed does not convey this message appropriately (screenshot attached).

Any idea how can we improve this?

**Comment by abhvsn** [comment]
So there are 2 issues that we are discussing here :
1. Postgres default nomenclature is case-insensitive so in above screenshot it failed because the tableName should have been public."userDiscounts" instead of "public.userdiscounts". Fix for this is already in release
2. When the table doesn't have string type columns we can display clear message that "Only text columns are supported for generate page feature", any thoughts?

**Comment by abhvsn** [comment]
Closing this as the dependency of the searchable column has been removed and also the table name reference has been taken from the _datasourceStructure.tables.templates_

**Comment by ramsaptami** [comment]
@abhvsn are we still looking into the error message when table data is null? Think that can be a bit more clearer for the user

**Comment by abhvsn** [comment]
@ramsaptami the issue was SelectQuery failing, we have taken care of edge case related to case-sensitivity of table name in postgres as discussed above. Also AFAIK for tables without text columns we are showing users specific error message that only string datatype is supported for generate page task for search column dropdown, @Rishabh-Rathod please add if I missed out on anything or correct me if I'm wrong

**Comment by Rishabh-Rathod** [comment]
@ramsaptami Are you asking about the case when there are no columns at all in the table? 

In that case, Shall we disable the "Generate Page" button with msg that "Please select a non-empty table"?

**Comment by ramsaptami** [comment]
We could still provide an option to generate an empty table right? What if the user has an empty table they want to update from inside their application? @Nikhil-Nandagopal any thoughts on this?

**Comment by Nikhil-Nandagopal** [comment]
@ramsaptami if the rows are empty that makes sense but if the columns are empty then it won't be possible since appsmith doesn't support column modification yet
