### ISSUE TITLE
[BUG] No server side validation for email and password length + wrong email regex for email notifications

### ISSUE THREAD

**Issue by akbansa** [appsmithorg/appsmith#627]
I can do whatever I want with email, no need for any EMAIL format to be sent for a user to be created.

1. **Check this function responsible for sign up:**
https://github.com/appsmithorg/appsmith/blob/04368d675e891700998ed3d6d4f1b9f69f1819f0/app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java#L483

Also, while sending emails from the server your EMAIL REGEX is not valid for many domains like `.website`, `.analytics`, `.education`

2. **Check the variable defined in the notification service:**
https://github.com/appsmithorg/appsmith/blob/04368d675e891700998ed3d6d4f1b9f69f1819f0/app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java#L38

Here are the options for (2):
[Option 1](https://regex101.com/r/BCZIA4/2)
[Option 2](https://www.regular-expressions.info/email.html)

Once you decide on the regex, you can create a helper function to use for an invite, signup, login, etc.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand can you verify this

**Comment by trishaanand** [comment]
1. Since we allow for GitHub signup, we allow the username (which is currently linked to email) to not be mandated to be of email type. The format for the email is checked only by the frontend when the user is trying to sign up using email and password.
2. We could improve upon our email regex to disallow sending of emails in case of bad email.

**Comment by Nikhil-Nandagopal** [comment]
@trishaanand I think it comes down to the contract. For Github signup, the access token will give us the username so we're confident of that data whereas here the frontend is explicitly sending us data so this should be validated

**Comment by pc9795** [comment]
IMO for the starters, we can use `@Email` annotation form validation API on the `User `object's email field. It can protect us in the resource layer. Usually, validations are handled there only. 
For the rest of the cases instead of using a regex, we should use library functions which are tested and used by many others. One of which is https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/EmailValidator.html in the Apache commons validator library.

**Comment by Nikhil-Nandagopal** [comment]
@pc9795 would you like to take this up?

**Comment by pc9795** [comment]
Sure 👍

**Comment by prapullac** [comment]
Verified the issue as it is working as expected
