### ISSUE TITLE
[Feature] Restrict app viewers from creating organizations and apps

### ISSUE THREAD

**Issue by areyabhishek** [appsmithorg/appsmith#6298]
## Summary
Today app viewers for a particular organization can create their own personal organizations and apps inside them. This could be a bad user experience for the viewers because they are expecting to use an app, but not create apps.

Some ideas for solutions:
1. If a user has been invited to an org as a viewer, hide buttons to create an org. They can enable this button if they'd like by going to their personal settings
2. Have a dev mode and a viewer mode for the homepage. By default a viewer lands in the viewer mode, which as the org creation+app creation turned off. The user would need to toggle a setting somewhere to become a developer and create orgs+apps

This is important for viewer UX and will matter for large teams a lot

[Comment from Discord:
](https://discord.com/channels/725602949748752515/760761686549463060/870753889463435344)<img width="793" alt="Screen Shot 2021-07-31 at 1 24 10 AM" src="https://user-images.githubusercontent.com/30255708/127705182-3bf4f46c-0a51-42ae-8625-539fca7285da.png">

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_5laoc)

**Comment by PatrickHuetter** [comment]
+1 This feature would be very helpful. I think it should be configurable for every role or user wether it's possible to invite new users and also wether it's possible to create apps. And it should be just the hiding in the frontend. Instead the API calls should also check wether user has granted access to the features. Otherwise it would be security issue/risk.

**Comment by Nikhil-Nandagopal** [comment]
Hi @PatrickHuetter 👋 
We're working on enabling granular access control for different user groups in this issue #3317

**Comment by madsween** [comment]
I think this would be a great thing. I am doing a trial of various low code tools to use in my small business and am concerned that my non technical employees will waste time messing around create junk in their own org rather focusing on the job and just using apps provided. If I add a user as "app viewer" for my domain.com I would expect them to literally be viewers and not creators.

**Comment by renekahremann** [comment]
+1 I have the same problem like madsween. I don't see any reason why "Viewers" should be able to create their own organization. This is very important for us.

**Comment by vuiets** [comment]
@madsween and @renekahremann sorry about the delay in getting back to you. Thanks for voting this up and sharing your use case with us. 

We are actively working on granular access control in [#3317](https://github.com/appsmithorg/appsmith/issues/3317) and since this is related, I'd love to hear more about this over a call. Sharing my calendly here so you may pick a time that works best for you :)
📆 Calendly: https://calendly.com/appsmith-vishak/conversations
