### ISSUE TITLE
[Feature] s3 plugin: auto fill the region field in datsource page

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6313]
## Summary
From slack:

> QQ, when an S3 datasource is configured with the wrong region, and we execute a query with that datasource, we get the error saying “this is not the right region, this other one is the right region”, so it looks like we have information on what the right region is. Can we simplify this for the user by not asking for the region at all, and just infer it instead?

**Comment by sharat87** [comment]
Currently, we have a region selector in S3 datasources and the bucket is selected in S3 queries. This is very confusing since if I selected region-A in the datasource and turns out my bucket is in region-B, and my query fails. The mental model breaks here, because S3 buckets can ever belong to one and only one region. So, should we have both region and bucket configurations in the same place? Either both in the datasource, or both in the query configuration.

Extending that thought, can we completely do away with the region selector? If we can infer that from the bucket name, the user won't have to deal with entering a region at all, right? That would make the experience much smoother when dealing with S3 integration.

cc @ajinkyakulkarni @mohanarpit @Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
+1 @sumitsum @ajinkyakulkarni can we just let users enter / select a bucket in the datasource and infer everything else from here?

**Comment by ajinkyakulkarni** [comment]
@trishaanand Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/6313?planning-poker)

**Comment by ajinkyakulkarni** [comment]
@trishaanand @ohansFavour Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Appsmith-Actions-Pod-603dd87bd4dff90011242dc9/issues/appsmithorg/appsmith/6313?planning-poker)

**Comment by trishaanand** [comment]
Adding higher estimate point to ensure that we have tested with all the service providers and are not breaking anything for any of them.
