### ISSUE TITLE
[Bug] select widget: default value is not set if the value is non text type

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6348]
## Description
Consider the following example:
```
[
  {
    "label": "Blue",
    "value": 1
  },
  {
    "label": "Green",
    "value": 2
  },
  {
    "label": "Red",
    "value": 3
  }
]
```
Ideally setting the default option field to `1` should set the default label to `Blue` but this does not take effect in practice. It works as expected if the numbers are converted to string though like `"value": "1"`.

**Comment by somangshu** [comment]
@Tooluloope @vivekverma2312 please confirm if this is fixed with the new change

**Comment by Tooluloope** [comment]
@somangshu @sumitsum 
The issue here is that you'll have to use the binding to indicate it's a number type.

The jsControl sees any raw input as text
<img width="824" alt="Screenshot 2021-08-04 at 21 24 58" src="https://user-images.githubusercontent.com/31691737/128249917-8b1f78a4-7db0-4419-b06a-eb8bb97b3ab6.png">
