### ISSUE TITLE
[Bug]The Binding fails for the text widget when the response is an array or an object for the generate Crud page

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#6357]
## Description

[What happened]The Binding fails for the text widget when the response is an array or an object for the generate Crud page

### Steps to reproduce the behaviour:

![image](https://user-images.githubusercontent.com/45958978/128013355-0d69fc5e-50a3-4743-842c-51f218c237f2.png)

### Important Details

- Version: [Cloud]
- OS: [e.gMacOSX]
- Browser [ Firefox]
- Environment [release]

**Comment by Rishabh-Rathod** [comment]
As the mock (sample) movies database has `genres` data as an `array of objects` instead of a `string`, that is the reason we see this error.

This will not happen when a user tries to generate a page using normal DB. 

If then also we want to resolve the debugger error then we might need to modify the mock DB.
