### ISSUE TITLE
[Bug] Cyclic Dependency error occurs and the app crashes when the user generate table and chart from mongo query

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#6375]
## Description
Release frozen - It is observed that when the user generates table and then chart from an mongo query - cyclic dependency error occurs 

Expected Result:
Cyclic dependency error should not occurs when generating widgets from datasource

### Steps to reproduce the behaviour:

1.Launch appmsith app in the release frozen environment 
2.Click on Datasource 
3.Choose Mongo Plugin 
4.Choose option with uri 
5.Pass the following uri
6. Choose type as 'Insert Document' and give an name for document 
7. Pass the following input - 
[{“_id”:1, “Från” :”Yogesh” , “Frõ” :”Active”},
{“_id”:2, “Från” :”Vivek” , “Frõ” :”Active”},
{“_id”:3, “Från” :”Prapulla” , “Frõ” :”Active”},
{“_id”:4, “Från” :”Raksha” , “Frõ” :”Active”}]
8.Click on run
9.Choose the type as find document , Pass the document name entered as step 6 , enter the query as {}
10.click on run 
11. Generate Table widget from the result 
12. Navigate back to Mongo query 
13. Again generate chart widget form the result and observe

VideoUrl:
https://loom.com/share/85a6e0655763493e9c74d4889f8aedb9

### Important Details

- Version: [11.3]
- OS: [MacOS]
- Browser [chrome, safari]
- Environment [release frozen]

**Comment by rahulramesha** [comment]
@somangshu This issue is due to the special characters in `propertyPath`, As mentioned by @hetunandu  Special Characters are not Supported in names i.e. `propertyPath`s, but since `primaryColumns` are user Defined names from input control,It gets added to the `propertyPath`. Originally all special characters were replaced by `_`, this was changed in https://github.com/appsmithorg/appsmith/pull/6041.
