### ISSUE TITLE
[Perf] Further Optimisations of PropertyPane Connections

### ISSUE THREAD

**Issue by rahulramesha** [appsmithorg/appsmith#6417]
PropertyPane Connections were optimised to an extent as part of the editing optimisations. But this can be further optimised with optimising other selectors and moving code to fetch link on click instead of updating every time.

**Comment by btsgh** [comment]
Since this is a performance improvement, no visual changes are seen on the UI. As per discussion with @aswathkk  - Tested the Property Pane of a few widgets (input / text / checkbox group), specifically looked at the property pane connections area and the other property options and no issues seen. Hence closing the issue.
