### ISSUE TITLE
[Feature] Table widget: select all rows across table pages.

### ISSUE THREAD

**Issue by sumitsum** [appsmithorg/appsmith#6430]
## Summary
Need a way to select all rows across table pages. 

```
In a table with multirow selection and multiple pages, if I press the checkbox in the table header, I would expect it to select all the rows in the table instead it selects only the rows in current page. :tired_face:

It is also not possible to select the various pages with the "select all" checkbox because each selection cancels the previous one.
```

**Comment by DevSnap** [comment]
https://github.com/DevSnap/appsmith/commit/529332b4182d613ff409c6705e0c3bc24708cad3

It works and seems trivial..

Anyway this is my first attempt to contribute to an open source project (but I don't develop in react :laughing:), so there's probably something missing.

I need this to release an appsmith app into production. :heart_eyes:

**Comment by somangshu** [comment]
Hey @DevSnap 👋 , Thanks for taking the time to contribute to Appsmith. 😄  Can you please create a pull request in the Appsmith  repo against the Release branch and request for a review from me or anybody in the team. We will then be able to take this forward quickly. Let me know if you have any challenges

**Comment by DevSnap** [comment]
I'll add some details about the use case. @somangshu 

I have a table with a large amount of rows and external filters.
After applying a filter I would like to perform an action on all rows.
With the current behavior this is inconvenient because:
a)
> It is also not possible to select the various pages with the "select all" checkbox because each selection cancels the previous one.

b)
I can't trigger the select action in all rows from an external button.


For point "a".
In ant design instead is possible. (https://ant.design/components/table/#components-table-demo-row-selection-and-operation) 

Personally as a user I would expect to select ALL rows across table pages.
e.g. 
https://material-ui.com/components/tables/#sorting-amp-selecting
https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/styling/awesome-bootstrap-checkbox/

**Comment by somangshu** [comment]
@DevSnap Thanks for the detailed explanation, While we are reviewing your PR, We also have another active issue #5634 where we want to solve multiple problems related to the mass selection from the design point of view. 

In my understanding something like this would be apt 👇 
![Screenshot 2021-08-09 at 3 07 15 PM](https://user-images.githubusercontent.com/11089579/128686925-d0658c60-5496-45e6-b04a-bea40241a9e9.png)

**Comment by somangshu** [comment]
We should verify this throughly, Regressions around table widget need to be avoided.

@mohanarpit @yatinappsmith this PR is contributed by an external dev, This PR CI workflow skipped the UI test and the server build, How can this be rectified?
