### ISSUE TITLE
[BUG] Corrupt token is allowing activation of the membership.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#650]
## Description
Created a new account (A1) and invited an another new user to the team. 
Copied the invitation link, corrupted the attached token with random values and opened it in the browser.
Entered password for SignUp.
Automatically adds me to the A1 account team.

### Steps to reproduce the behaviour:
1. Login Using Email and Password.
2. Invite new User 
3. Open the invitation email and copy the link
4. Corrupt the token by replacing any character with a random character.
5. Open link, enter password.
6. Automatically adds to the invitee organization.

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by mohanarpit** [comment]
We no longer use invitation tokens. The new user is added to the organization when the invitation is sent out to them. The signup link is only for their account accessibility. 

In order to fix this, we need to remove the unused query parameter token from the URL being sent in the email. This can be done by removing the token parameter in variable `INVITE_USER_CLIENT_URL_FORMAT` in `UserServiceImpl`. 

The function `createNewUserAndSendInviteEmail` in the same class also needs to remove the token replacement when it constructs the email parameters.

**Comment by prapullac** [comment]
Verified the issue and works as expected
