### ISSUE TITLE
Multi-select widget dropdown: animation and position

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#6502]
@Tooluloope Some comments about the multi-select widget animation: https://www.loom.com/share/fd7cb9d07db841cf938d49c75ba85d97

_Originally posted by @areyabhishek in https://github.com/appsmithorg/appsmith/issues/5069#issuecomment-895313653_

**Comment by somangshu** [comment]
Agreed, Note @Tooluloope 
We should have consistency between the select and multi-select widget
- The dropdown position need a solution, How can we always open it at bottom
- The animation applied to the widget should be fade in/out just like the select widget.

**Comment by areyabhishek** [comment]
@somangshu the dropdown will need to open from the top too for long lists.

**Comment by Tooluloope** [comment]
@areyabhishek @somangshu From the video, The reason why it opens from the top is because of the limited space from the widget to the end of the page.

The Multiselect on the Left is closer to the bottom and the one of the right is a bit higher. That's why there's a repositioning.

Select WIdget also does the same, due to availability of space.
<img width="910" alt="Screenshot 2021-08-11 at 07 26 45" src="https://user-images.githubusercontent.com/31691737/128980052-da452e07-fcc1-47b4-a38f-7eabeaad25f5.png">

**Comment by somangshu** [comment]
@Tooluloope i feel that this behaviour is alright given that we have consistency between the select and multi-select widgets. Let change the animation to what we see with the select widget
