### ISSUE TITLE
[Enhancement] Toggle buttons on property pane should change on press of space bar

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6684]
## Summary
Keyboard shortcut for space bar to change value of toggle properties on property pane on press of space bar

![image](https://user-images.githubusercontent.com/79509062/129869437-01c1165a-e6f1-45c4-929f-516fea818817.png)

**Comment by aswathkk** [comment]
I found that the switch is getting toggled if we press the Space button.
1. Click on "Visible" ![Screenshot 2021-11-17 at 12 04 35 AM](https://user-images.githubusercontent.com/10436935/142045206-6c13a03d-8cc7-4a8f-82f3-5b25daf8d89b.png)
2. Press `Tab` key.
3. Press `Space` key to see the switch toggles.

These interactions are not visible properly since we aren't highlighting the selection by pressing the tab key.

**Comment by somangshu** [comment]
@ramsaptami We are right now working on #8845 that will address all issues with the keyboard navigation inside property pane, It totally skipped my mind, but your inputs will be really valuable here. Please let us know anything you might thing is not included in the [scope](https://app.zenhub.com/workspaces/ui-builders-pod-603e3779daa13d000e3b42be/board?labels=keyboard%20shortcut&epics=275993885_8845&repos=275993885)

**Comment by ramsaptami** [comment]
@somangshu I've added a few existing issues to the epic that's related to keyboard shortcuts. I'll tag more if I come across any

**Comment by aswathkk** [comment]
Closing this since the actual issue is fixed and focus styling will be added on #6000
