### ISSUE TITLE
[BUG] Submit button going into an infinite loading state when clicked without specifying 'File name' for download action

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#673]
Attachment : https://drive.google.com/drive/folders/1BcGLwjinCW0uitCQBmEr-bIcKg9holPB?usp=sharing

Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1.Hit https://app.appsmith.com/
2. Under an organization, click on 'Create New' in order to create a new application
3. Edit Application
4. From the Form Widgets, pick button
5. In the button, Set onClick to download and do not provide any details i.e. Data to download and file name with extension
6. click on submit button

Issue : Submit button fails as seen in the video.
Note: There is a relevant warning message that defining file name is a must. (We're good with this)

**Comment by hetunandu** [comment]
Hey I am Hetu, one of the maintainers at Appsmith. This is a great issue for anyone with basic JS skills looking to start contributing to the repo.

Bug happens because `download` action did not invoke the event callback on an error. Adding another line [here](https://github.com/appsmithorg/appsmith/blob/master/app/client/src/sagas/ActionExecutionSagas.ts#L152) before the return calling the even callback with `event.callback({ success: false });` should solve this issue.

> Need more guidance while working on this? Feel free to mention me in a comment on this issue and I'll be happy to help you out 😄

**Comment by MartinTuroci** [comment]
Would like to work on the issue.

**Comment by hetunandu** [comment]
Sorry @MartinTuroci but someone had already raised the PR by the time I could assign this to anyone. I request you to please check our other issues, I am sure there would be some that would interest you. 🙂
