### ISSUE TITLE
[Enhancement] Date picker must exit on pressing esc key when 'close on selecting' is turned off

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#6798]
## Summary
When **date picker widget** has 'close on selection' turned off, then user has to click away from the date picker pop-up in order to close the calendar. Pressing on **Esc key** must also close the calendar - which is not supported currently. Only the property pane exits on pressing the **Esc key**.

**Comment by nishihere19** [comment]
Can I work on this issue?

**Comment by ramsaptami** [comment]
It's your @nishihere19 

Don't forget to read the [contributor guidelines](https://github.com/appsmithorg/appsmith/blob/769ee31f87cfe7866e5cd87a2c2df9da48f778cc/CONTRIBUTING.md) before working on this issue. Good luck!

**Comment by nishihere19** [comment]
Thanks.

**Comment by ramsaptami** [comment]
I'll assign this issue to you @onifs10 since no PR has been raised so far

**Comment by somangshu** [comment]
@keyurparalkar need you to take a look here, This issue was resolved by an external contributor, We need to either rectify the conflicts there or create our own branch based on the changes in linked PR. Once done get an approval from reviewer and QA and merge the PR to release. If you have any questions related to this please get in touch with the tema

**Comment by onifs10** [comment]
@somangshu  i could go ahead and resolve the conflict on my own branch

**Comment by somangshu** [comment]
Yes please @onifs10, That will be great, @SatishGandham can re-review and if everything looks good we will go ahead and merge this

**Comment by onifs10** [comment]
@somangshu done
