### ISSUE TITLE
[Feature] Local deployment: Super user creation form

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith#6934]
## Summary

Introduce a form, only for a virgin instance, to create a super user - https://www.figma.com/file/lqtUfzJO50RpEhxKttYeOg/Local-Dev-Main?node-id=1609%3A22142

**Comment by RakshaKShetty** [comment]
@sbalaji1192 Following are the issues found in the Welcome Page setup for local development
1. The error message is not displayed when the "Full Name" Input box is kept empty
2. The Full name input box is not considered as a mandatory filed
3. The verify Password field is not considered as a mandatory field and there should be an error when the user has not entered the Password
4. The "Appsmith_" and the header text displayed below should not have the same Font and Font weight
5. The cursor highlight is very din when the user clicks on any input box for entering data
6. The last step name is displayed 1/3 instead of 3/3
7. The small text should not be displayed next to the "Make my first app button". when the user click on Make your first app button
8. The thin vertical line should not be displayed below org on the application page in light mode
9. The error message should be displayed when user enters the different password in "Create password" and "Verify password" input boxes
10. The hyperlink in the Pages should be displayed in blue color
11. The Roles are displayed in Role dropdown but we don't have any doc to cross verify the Correct roles
12. There is a lot of empty white spaces across the pages
