### ISSUE TITLE
[Feature] Access request data of an API query

### ISSUE THREAD

**Issue by vnodecg** [appsmithorg/appsmith#7041]
## Summary

need ability to access the request info of an API query using javascript

## Motivation

Users might want to use the request information to modify response. For example we can get the user name from the request and append it to response body

User request:
https://discord.com/channels/725602949748752515/760761686549463060/882786117219409970

**Comment by mohanarpit** [comment]
The reason we don't expose the request body for APIs or queries is because this can become a security loophole for applications. If you bind a UI widget to the request body, you are potentially exposing all your business users/viewers to be able to see that data in view mode. This could lead to security problems especially for DB queries & in some cases API request bodies. 

At Appsmith, since we follow the security-by-default model, we don't expose this datapoint to users in the application.
