### ISSUE TITLE
[BUG] Misleading "Connecting to APIs" screenshot

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#711]
## Description

Screenshot on the "Connecting to APIs" (https://docs.appsmith.com/core-concepts/apis) needs to be updated to the new UI (something like the one below)

![image](https://user-images.githubusercontent.com/4999463/94124812-1da0e800-fe73-11ea-934c-4c1b39bdb9b7.png)

### Why is this needed?

- There is only one field now and an editable API name field as opposed to the 3 fields as shown
- There are only "Delete" and "Run" as opposed to "Delete", "Run" and "Save"
- A new Settings tab has been added which is not shown in the current screenshot

**Comment by SamriddhiMishra** [comment]
@Nikhil-Nandagopal Can I use the same image(above) to replace?

**Comment by Hard-Coder05** [comment]
@Nikhil-Nandagopal I would like to work on this issue!

**Comment by mohanarpit** [comment]
Hey @Hard-Coder05 , since @SamriddhiMishra has claimed this earlier, let's give him 2 days to raise a PR before we re-assign the issue.

@SamriddhiMishra You can use the screenshot in the issue or even create your own screenshot by signing up on [https://app.appsmith.com](https://app.appsmith.com)

Also, I would encourage you to participate in [Appsmith's Challenge](https://github.com/appsmithorg/appsmith/discussions/863) by inviting your friends by tagging on the [Github Discussion](https://github.com/appsmithorg/appsmith/discussions/863)

**Comment by SamriddhiMishra** [comment]
@mohanarpit @Nikhil-Nandagopal 
I have raised PR https://github.com/appsmithorg/appsmith-docs/pull/28
Please review this.
