### ISSUE TITLE
[BUG] Developer has an access to invite users but doesn't have access to 'Invite users' under manage users

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#715]
Browser Details: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on Cloud.

Issue: If a Developer has access to 'Invite Users' from homepage then developer should be able to access manage users workflow.
Note: On the **manage users** workflow, there can be a restriction where Developer can't change role of the user. But not being able to access this workflow at all is contradictory.

<img width="1777" alt="Screen Shot 2020-09-24 at 6 37 44 PM" src="https://user-images.githubusercontent.com/49346036/94149070-0ecb2d00-fe95-11ea-81b0-2be57e57384a.png">

**Comment by trishaanand** [comment]
@Nikhil-Nandagopal : By design, managing user access to the organization is limited to Administrators. Developers have been given permission to invite other developers and viewers to the organization but managing ( updating a role, deleting a user from the organization ) are still limited by design to the Administrators only.
