### ISSUE TITLE
[BUG] Default value isn't set for dropdown multi-select.

### ISSUE THREAD

**Issue by visibleajay** [appsmithorg/appsmith#718]
## Description
Default value isn't selected for dropdown mult-select.

### Steps to reproduce the behaviour:
1. Add a dropdown with multi-select `Selection Type`.
2. Provide default value.
3. Deploy the app.
4. The default value aren't set for multi-select dropdown.

[Video In Action](https://drive.google.com/file/d/14eOBCvk9jkTvyq2dt4JSWu31lU6YhAlY/view?usp=sharing)

### Important Details
 - Version: Cloud
 - OS: MacOs 10.14.6
 - Browser: Firefox 80.0.1 (64-bit).

**Comment by jyash97** [comment]
Can I take a look at these issue?

**Comment by Nikhil-Nandagopal** [comment]
@jyash97 go for it!

**Comment by jyash97** [comment]
Hey @Nikhil-Nandagopal  👋 

I looked into this issue and found that this was happening because `selectedOptionValueArr`  was empty. Sharing context below for a better understanding: 

We use same component for MultiSelect and Single Select, so to distinguish the values we were tracking 2 variables - `selectedOptionValue` for single select & `selectedOptionValueArr` for multi-select. The issue is in the case of both types the `defaultValue` is added in `selectedOptionValue` and there is no key in the redux store for `selectedOptionValueArr` in the first mount because we don't save the key in the backend. 

**Solution:** 

1. To add that key conditionally on the first mount and pass the default value in the case of MutliSelect. [ This will be tricky and a type of hack so I have skipped this ]
2. To keep the same variable to track the value i.e using only `selectedOptionValue` for both the dropdowns. [ Created PR ]

**Issue**

I created a PR for the `2` solution mentioned and have tested the functionally it works well in both the cases. But I am seeing a TS issue - 

Have a prop called `selectedOptionValue` which can be a string and an array of string. Type: `string | string[]`. But when I use any array method on the prop it throws a TS error which is expected as the methods are not present for `string` type. 

Is there a way to fix this issue? Would really appreciate any help or pointers :)

**Comment by hetunandu** [comment]
Hey @jyash97. Thanks for such a detailed context to help us understand what your thoughts are around this solution. I checked this further and seems like this is failing since the `selectedOption` binding is multi select. You should see this error printed in the console when running in dev
<img width="1050" alt="Screenshot 2020-10-19 at 2 07 09 PM" src="https://user-images.githubusercontent.com/12022471/96421486-76666500-1214-11eb-8c27-1f6d9c38f6da.png">

I suspect that solving this logic should bring everything else in line. 

Regarding your proposed solutions, they both assume that the binding value wont be available on mount, while it should. We don't render with the props stored with the server, but go through an evaluation cycle to make sure the bindings `{{ }}` are evaluated, validated and parsed. But since there was an error this particular binding, the correct values are not getting set.

Let me know if this logic is not very clear and you want more information about it.
