### ISSUE TITLE
[Bug] Input Widget does not show default value if it is 0 for number type

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith#7246]
Input Widget does not show default value if it is 0 for number type

### Steps to reproduce the behavior:

1. Drop an input widget on the canvas
2. Set the input type to number and set the default value to 0
3. Notice the input widget does not show 0 even on refresh.

**Comment by zzgvh** [comment]
A workaround for forms posting is to set an undefined form value to 0:
```javascript
{{
 {numberFieldName: Form.data.Input || 0}
}}
```

**Comment by zzgvh** [comment]
I'm also seeing a problem that may be associated with this bug, or it may be separate, I cannot tell. But it started appearing at the same time as this bug.

The problem I'm seeing is that fast entry of numbers in the field get "dropped". This is probably because of interaction with the `appsmith.store`. A small vid to demonstrate:


https://user-images.githubusercontent.com/142613/132507091-1ecb46f3-4fb8-42f8-bb13-cc252283abdf.mp4


As you can see in the vid, the `Seed_count_1` field is updated when the __Frö 1__ Select is changed. This is done by setting `appsmith.store.plantera.seed_count_1`. When I manually set the value to 0, it is removed which is the bug in this issue.

Last in the video I enter the value 75, first slowly and that works as expected, but when the entry is done quickly, the second number is dropped. You can see it flicker in the field and disappear.

The following code is in the Seed_count_1 input field. 

In the onTextChanged field:

```javascript
{{
storeValue("plantera", {
  ...appsmith.store.plantera,
  seed_count_1: parseInt(Seed_count_1.text),
});
}}
```

In the Default Text:
```javascript
{{appsmith.store?.plantera?.seed_count_1 || 0}}
```

**Comment by zzgvh** [comment]
I'm also seeing the problem with "missing updates" when you increase or decrease the value of a Number select quickly using the up and down arrows, similar to when entering numbers fast.

**Comment by jsartisan** [comment]
@somangshu The code looks ok but we will need to check if this change won't break any existing application similar to the table widget change that went last week.
