### ISSUE TITLE
[Feature]-[344]:Custom chart config, Increase ease of use

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#7263]
## Summary

While using the chart widget custom config, It a difficult UX to create the final required object. To make this easy we will:
- Chart Type: Separate the  chart widget types and use all value which will accept a string and use the validation array to check the sanity of the given value
- Chart config: The config from the datasource object will be a separate field to all used to copy some configuration directly from the fusion chart examples

**Comment by riodeuno** [comment]
@somangshu I believe this feature should be implemented in a new version of the chart widget.
This DX deviates a lot from the existing property configuration of the custom chart configuration. In an attempt to maintain DX for existing chart widget users, we will increase code complexity and include APIs which is otherwise not necessary.

**Comment by somangshu** [comment]
I agree, We should consider the extensibility to use other chart SDKs in the future then, We have an ongoing discussion around this

**Comment by somangshu** [comment]
@dilippitchika this issue has gone through a round of development and we have faced roadblocks we did not want to ahead with. We should be doing a v2 hear, and on that note I need your inputs on how to make the usage of custom charts convenient for the user.

**Comment by dilippitchika** [comment]
Reach: 258 in last 6 months
Impact: High

**Comment by dilippitchika** [comment]
## Stats
| Stat | Values |
| ------------- | ------------- |
| Reach     | 258 |
| Effort (months)  | 1.5 |
