### ISSUE TITLE
[BUG] Can't use app name after deleting first one

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#727]
## Description

Created an app and deleted it to try and create it again. But the tool threw an error that I the app exists already while I deleted the app already. 

### Steps to reproduce the behaviour:

1. Create New
2. Create an app and delete it
3. Create New and use the same name as before

Screencast: https://recordit.co/GxqoLDqAjv

### Important Details
 - Version: [Cloud]
 - OS: [Windows 10]
 - Browser [Google Chrome 85.0.4183.102 (Official Build) (64-bit)]

**Comment by malathit** [comment]
@Nikhil-Nandagopal I would like to work on this issue. I have fair experience of spring boot. I just figured out the reason for this issue is the soft delete done in DB. There are 2 ways to solve this issue. 
- Renaming the application name to add a string such as **[DELETED] - <random string>**
- Not considering the deleted applications on creation of new application

**Comment by Nikhil-Nandagopal** [comment]
@malathit I don't believe that is the issue. This looks like a frontend problem because after refreshing the page, you can create an app with the same name.

**Comment by prapullac** [comment]
verified the issue as it is working as expeceted
