### ISSUE TITLE
(JS-0417) Avoid `.bind()` or Arrow Functions in JSX properties

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#7440]
## Description
A bind call or arrow function in a JSX property will create a brand new function on every single render. This is bad for performance.

## Occurrences
There are 660 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0417/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0417/occurrences/)

**Comment by Nightowl-8** [comment]
can you assign me this issue?

**Comment by Rishabh-Rathod** [comment]
Hey @Nightowl-8, thanks for showing interest 🎉 , This is all yours. Assigning this to you now. 

As this issue has 699 occurrences, I would suggest resolving it for not more than 10 files in a single PR. Would be easier for you to contribute that way and for us to merge your changes in small chunks. 😁

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate it if you can open a PR within the next 4 days.

**Comment by J-Ankit2020** [comment]
Can i work on this issue

**Comment by Rishabh-Rathod** [comment]
> Can i work on this issue

Hey👋🏼 @J-Ankit2020,  thanks for showing interest in this issue.

Unfortunately, this issue is already taken. Please do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+label%3Ahacktoberfest)

Looking forward to seeing your contributions :)

**Comment by jdkramhoft** [comment]
I can work on this issue, since they removed their assignment

**Comment by samyakjain10** [comment]
Hey this issue has many occurences. Can I also work on this issue??

**Comment by samyakjain10** [comment]
@Rishabh-Rathod Please assign me this issue so that I can start working on it.

**Comment by Rishabhkaul** [comment]
@Rishabh-Rathod maybe time to remove assignee on this :)

**Comment by priyanka-mahour** [comment]
can I work on this issue?

**Comment by nikhil-babar** [comment]
@Rishabh-Rathod plz can you assign me this issue

**Comment by Ayan726** [comment]
@Rishabh-Rathod hello!! can i work on this issue?

**Comment by Rishabh-Rathod** [comment]
Hey👋🏼  @Ayan726, thanks for showing interest in this issue.

Unfortunately, this issue is not open for external contribution. Please do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22)

Looking forward to seeing your contributions :)

**Comment by Ayan726** [comment]
Thank you for letting me know :) I will check out other issues.
