### ISSUE TITLE
(JS-0050) Avoid use of `==` and `!=`

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#7445]
## Description
It is considered good practice to use the type-safe equality operators `===` and `!==` instead of their regular counterparts `==` and `!=`. If one of those occurs in an innocent-looking statement such as `a == b` the actual problem is very difficult to spot.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/appsmithorg/appsmith/issue/JS-0050/occurrences/](https://deepsource.io/gh/appsmithorg/appsmith/issue/JS-0050/occurrences/)

**Comment by bharat-patodi** [comment]
If it is alright, I'd like to take this up.

**Comment by yashraut362** [comment]
can I pick this issue?

**Comment by Rishabh-Rathod** [comment]
Hey👋🏼 @yashraut362 ,  thanks for showing interest in this issue.

Unfortunately, this issue is already taken. Please do check our other [Good First issues](https://github.com/appsmithorg/appsmith/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+label%3Ahacktoberfest)

Looking forward to seeing your contributions :)

**Comment by kalashjain23** [comment]
Umm, I see no actions on this issue from about a month, so if possible can I be assigned too for issue? @Rishabh-Rathod

**Comment by yatinappsmith** [comment]
Verified as part fo regression testing
