### ISSUE TITLE
[BUG] When JS in Disabled is set for a button, it doesn't work for users

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#748]
## Description

I've set a button to be disabled if another field (date in this example) is not picked/is empty. It works perfectly in the builder but when deployed, it doesn't. 

In the builder
![image](https://user-images.githubusercontent.com/4999463/94280521-2248c780-ff6b-11ea-9ff9-ef7eb5e126c4.png)

For the users
![image](https://user-images.githubusercontent.com/4999463/94280589-355b9780-ff6b-11ea-8187-42ca6a221103.png)

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Google Chrome (v. 85.0.4183.102)

**Comment by Nikhil-Nandagopal** [comment]
@harishkotra thanks for catching this. I'm updating the bug after triaging it

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu when a date picker default value is cleared, the date should be set to undefined instead of "". That is leading to it to seem as though the disabled value is not working when in fact it has to do with the value of the date picker

**Comment by mohanarpit** [comment]
@all-contributors Please add @harishkotra for their invaluable contribution towards bug reporting.

**Comment by somangshu** [comment]
This issue is now fixed

Button when datepicker is empty
![Screenshot 2021-05-05 at 3.44.56 PM.png](https://images.zenhubusercontent.com/60583007e1e4e5398dc9ec58/94979747-25b2-40cb-8363-ccb6cb897c23)

Button when date picker has a value
![Screenshot 2021-05-05 at 3.45.05 PM.png](https://images.zenhubusercontent.com/60583007e1e4e5398dc9ec58/60393acc-1459-4a3a-ab3b-1de38d8256f9)
