### ISSUE TITLE
[BUG] Widget breaks when input value contains too many characters

### ISSUE THREAD

**Issue by Saket2** [appsmithorg/appsmith#755]
Attachment: https://drive.google.com/drive/folders/1QjXyW6_K8G33DDxL_VJrh3ulcEzNzM4_?usp=sharing

Browser Details: Chrome
Device Details: macOS 10.15.6 (MacBook Pro)
Note: Tried on cloud.

Steps to replicate:
1. Go to the editor and pick any widget (e.g. Dropdown, Radio Button, checkbox)
2. Provide an input value which has too many characters

Actual Result: Dropdown isn't in usable state. Radio button and Checkbox get distorted.

**Comment by Nikhil-Nandagopal** [comment]
@Saket2 2 options here were to either truncate the text or let it overflow. We chose to let it overflow so that developer can resize the widget to fit the text. Truncation doesn't work because the data is dynamic and in some cases data from backend might be larger than what developer originally thought. So we took a call to let it break the UI so the developer knows how much space he has to give to it which you can't gauge if it's truncated. Closing this but I hope this made sense
