### ISSUE TITLE
[Bug] Cursor not auto turning into hand pointer when onClick is true for Images

### ISSUE THREAD

**Issue by RoopKrrish9696** [appsmithorg/appsmith#7571]
## Description

When I set the configuration of onClick to true for an Image, the cursor still remains the same, it is not turning into a hand pointer by default. 

### Steps to reproduce the behaviour:

1. Go to 'Entity page' and Click on '+' icon beside the widgets label
2. Click on 'Image' and Drag the widget into UI Building space
3. Click on 'Settings' and set an action for 'onClick' 
4. Now deploy and try hovering/clicking on the image, it still stays as a cursor

### Important Details

- Version: Cloud
- OS: Windows
- Browser: Chrome
- Environment: Production

**Comment by nishihere19** [comment]
Can I work on this?

**Comment by SandipPalit** [comment]
@RoopKrrish9696 @somangshu I would like to work on this issue, since I have experience in this field.

**Comment by rafaeelaudibert** [comment]
@RoopKrrish9696 The hover state is only shown when the render mode is `PAGE` as per line 183 on https://github.com/appsmithorg/appsmith/blob/87b13eca2d52544df4f8e7508d964d43649bd878/app/client/src/widgets/ImageWidget/widget/index.tsx.

@somangshu Do we want to change this to only show it? If so, I've opened a PR (#8082) with this change.

**Comment by somangshu** [comment]
@rafaeelaudibert in order to contribute to an open source issue, you always need to first claim it, Since @nishihere19 claimed the issue first, I will not be able to assign this issue to you. Please look at other hacktoberfest labeled issue, claim one and then work it further, Its in the best interest of us to save everyones time, Hope you understand. Happy hacking 😄

**Comment by somangshu** [comment]
Greetings @nishihere19, thanks for showing interest 🎉 , This is all your. Assigning this to you now. 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com/) in order to be eligible for Appsmith swag.

**Comment by nishihere19** [comment]
Thank you!

**Comment by nishihere19** [comment]
Hi, can you please reopen my PR for this issue? I was not able to apply the suggestions on time due to some emergency but I would still like to fix this issue.

**Comment by somangshu** [comment]
@nishihere19 I have done that, Kindly push the update in the next 2 days as mentioned on the PR as well
