### ISSUE TITLE
[Bug] Icon dropdown of Button widget is overlapped by button radius on the property pane

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#7575]
## Description
Border radius property of the Button widget overlaps Icon dropdown 

### Steps to reproduce the behaviour:
1. Drag and drop a button widget on the canvas and go to the property pane.
2. Click on the icon dropdown and observe the overlap

### Important Details
- Version: Cloud
- OS: Win10
- Browser: Chrome
- Environment: Release

![image](https://user-images.githubusercontent.com/79509062/133768356-585403de-9e2f-406e-83c6-092c12864d52.png)

**Comment by nishihere19** [comment]
Can I work on this issue if no one is doing it currently?

**Comment by ramsaptami** [comment]
It's all your's @nishihere19 :)

**Comment by nishihere19** [comment]
Before proceeding, I want to confirm that, in this we are trying to open the dropdown below the input instead of the upper side which overlaps other properties. If this is fine, I will fix and give PR soon. Also, I am new here so if you know which files I shud look into, link them. Thank you!

**Comment by jsartisan** [comment]
@nishihere19 The text of this is a little misleading. Let me explain the exact issue.

in the icon selector control we have, there is a search field. that search field is no space above the search field.
<img width="779" alt="Screenshot 2021-10-01 at 7 37 49 PM" src="https://user-images.githubusercontent.com/6636360/135633918-22bb648a-d032-477d-8d7d-f3f6d3564ecb.png">

This is happening due to the wrong CSS. 

### Solution:
1. There is some margin on `bp3-input-group` of the icon dropdown. You will need to remove it and add some margin bottom ( 5px is good ).
<img width="817" alt="Screenshot 2021-10-01 at 7 40 10 PM" src="https://user-images.githubusercontent.com/6636360/135634404-da8c43e2-de66-4b41-9859-d91669eb2d5d.png">

2. Also, you will need some padding on `.bp3-popover-content` ( again 5px is good ) and box-shadow to it ( 0px 0px 0px 1px #e1e1e1 )

The final result will look like this:
<img width="710" alt="Screenshot 2021-10-01 at 7 35 05 PM" src="https://user-images.githubusercontent.com/6636360/135634961-4d9f38db-7abe-44ce-9196-c348a3a9c47c.png">

The file you will need to work is `src/components/propertyControls/IconSelectControl.tsx`. Let us know if you have doubt/suggestion or a better approach to this issue :) Happy Coding.

**Comment by jsartisan** [comment]
@nishihere19 The text of this is a little misleading. Let me explain the exact issue.

in the icon selector control we have, there is a search field. that search field is no space above the search field.
<img width="779" alt="Screenshot 2021-10-01 at 7 37 49 PM" src="https://user-images.githubusercontent.com/6636360/135633918-22bb648a-d032-477d-8d7d-f3f6d3564ecb.png">

This is happening due to the wrong CSS. 

### Solution:
1. There is some margin on `bp3-input-group` of the icon dropdown. You will need to remove it and add some margin bottom ( 5px is good ).
<img width="817" alt="Screenshot 2021-10-01 at 7 40 10 PM" src="https://user-images.githubusercontent.com/6636360/135634404-da8c43e2-de66-4b41-9859-d91669eb2d5d.png">

2. Also, you will need some padding on `.bp3-popover-content` ( again 5px is good ) and box-shadow to it ( 0px 0px 0px 1px #e1e1e1 )

The final result will look like this:
<img width="710" alt="Screenshot 2021-10-01 at 7 35 05 PM" src="https://user-images.githubusercontent.com/6636360/135634961-4d9f38db-7abe-44ce-9196-c348a3a9c47c.png">

The file you will need to work is `src/components/propertyControls/IconSelectControl.tsx`. Let us know if you have doubt/suggestion or a better approach to this issue :) Happy Coding.

**Comment by ipankajchaudhary** [comment]
Can i work on this?

**Comment by nishihere19** [comment]
Thanks for clarifying @jsartisan !

**Comment by jsartisan** [comment]
Closing as will be fixing this in #9714
