### ISSUE TITLE
[Bug] Input validation doesn't work for default values

### ISSUE THREAD

**Issue by zzgvh** [appsmithorg/appsmith#7675]
## Description

I have a bunch of Input fields that have the Number data type. For many of these there are allowed ranges of numbers. These ranges can be dynamic depending on other data in the form but even one of my simple regexes, `^[0-9]*$`, that allows only positive numbers, suffers from the bug. The issue is that the Submit button remains enabled for invalid values of the Input.

### Steps to reproduce the behaviour:

* Create a Form.
* Add an Input, set its Data Type to Number.
* Set the Regex to `^[0-9]*$`.
* Set Default Text to `{{appsmith.store?.test?.count_1 || 0}}`. 
* Set onTextChanged to:

`{{
    storeValue("test", {
        ...appsmith.store.test,
        count_1: parseInt(Input1.text),
    });
}}`

Click the up-down arrows on the input. When the number changes from 0 to -1 and subsquent changes to negative numbers the Submit button flickers to disabled but then reverts to being enabled. The number widget also flickers the invalid input red box for a very short while, I don't see it every time.

Demo app: [Regex bug.txt](https://github.com/appsmithorg/appsmith/files/7202136/Regex.bug.txt) (Rename to Regex bug.json!)

### Important Details

- Version: Cloud 
- OS: Linux Mint 19
- Browser: Firefox
- Environment production

**Comment by Nikhil-Nandagopal** [comment]
@zzgvh thanks for the bug report. Simple steps to reproduce this are
- Drag an input
- Add validation for positive numbers  ^\d*[1-9]\d*$
- Add an error message error
- Enter -5 in the input and the error is seen
- add {{-5}} as a default text and no error message is seen

**Comment by sbalaji1192** [comment]
Will be take care in https://github.com/appsmithorg/appsmith/issues/9119

**Comment by btsgh** [comment]
Tested the issue on Release. Issue Resolved. Observations below -
1. With Nikhil's steps, the issue was resolved. 
2. I was finding however that the issue existed with the app shared by the user.
Had a discussion with @aswathkk  .. he clarified that old input widget was deprecated. The App the user shared is still using the old version of input widget. As per his suggestion, in the application shared by the user, I inserted a new input widget and deleted the old one, then found that the issue was resolved.
