### ISSUE TITLE
[Bug] Pressing cmd+enter within 1-2 sec of typing executes an old query

### ISSUE THREAD

**Issue by ajinkyakulkarni** [appsmithorg/appsmith#7754]
## Description

On the query pane, if you press cmd+enter within 1-2 sec of typing a query, it executes an old/previous query

### Steps to reproduce the behavior:

1. Go to query pane
2. Write a select SQL query `select * from users where id = 1`
3. Change the value of id and quickly press cmd+run
4. Notice that the results from the previous value of id are being returned

### Important Details
- Environment: production

**Comment by hetunandu** [comment]
@ajinkyakulkarni 
Issue is that the running event of the action is processed faster than the edit event. We do a check if an action is getting saved to avoid this issue but the action is not started saving yet as well. I think we should add some artificial delay because executing via shortcuts are really fast.

**Comment by mohanarpit** [comment]
@hetunandu Instead of introducing an artificial delay, what if we made "Save+Run" the default for all actions? This way, the client sends a single request to the server & expects the server to save the latest configuration and then execute. It'll slow down the execute marginally, but will increase the reliability of the execution.

**Comment by hetunandu** [comment]
@mohanarpit this sounds similar to the dry run/draft functionality we had earlier.

**Comment by ajinkyakulkarni** [comment]
Is there any relation of this issue to #7507?
