### ISSUE TITLE
[Bug]In the table widget the first row data is deleted by default if the user performs delete action without selecting the row 

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#7838]
## Description In the table widget the first row data is deleted by default if the user performs delete action without selecting the row 

[What happened]In the crud page the user should select the row before performing the delete functionality else the first row is deleted by default

### Steps to reproduce the behavior:

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/319156d2968b49d097286f431f91cc74-00001.gif)](https://www.loom.com/share/319156d2968b49d097286f431f91cc74)

### Important Details

- Version: [Cloud ]
- OS: macOS
- Browser chrome
- Environment release

**Comment by somangshu** [comment]
With the latest change #3407, the click on action is not going to select row, Instead will set an internal property called as `triggeredRow`, And references to `{{table.selectedRow}}` will need to change to the new property in the template applications.

**Comment by somangshu** [comment]
Because this feature has broken apps, we have decided that the following changes will be made in order to rectify that
Note:
- On button click the selectedRow will be set and the onRowSelected will be triggered
- On button click the triggeredRow will continue to get set
- The row must not de-select on click of the selected row action button again
- No migrations or reverse migrations are required
