### ISSUE TITLE
[Bug] when the header is not added to cURL command default must be empty 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7900]
Steps to reproduce:
1) Add a cURL by removing a header 
2) Click on the import 
and observe

Observation:
It is observed that when the cURL is converted to API by default the header is considered as  "Form URL" even when the data sent is Json and retrieving of data is also not displayed properly. Even on changing the body selection, the data retrieving is. not appropriate 

Expectation:
When the header is not specified by the user we have to allow the user to specify and move the data body to align appropriately.
Possibly we can read the data imported to API and specify appropriate data section 

Video:
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/534c91a990024889ae0b283975f7dc14-00001.gif)](https://www.loom.com/share/534c91a990024889ae0b283975f7dc14)

**Comment by AmanAgarwal041** [comment]
After doing RCA, I have found that this bug is a backend issue. 
The issue is with the parsing of the curl input : 
file : `app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java` can be looked for `parse` function at line number 279 for changes to fix the bug.
