### ISSUE TITLE
[Bug] appsmith/appsmith-server container exits all of a sudden

### ISSUE THREAD

**Issue by suv95** [appsmithorg/appsmith#7929]
## Description
I noticed that `appsmith/appsmith-server` container exits once in a while. I have attached relevant screenshots, including the logs from the exited container. What could be the possible reason for such a failure? How can I help to fix it?

<img width="1680" alt="Screenshot 2021-09-29 at 2 31 50 PM" src="https://user-images.githubusercontent.com/68137932/135239960-c8c93100-3d1a-4af7-a4c1-ebe4d1c09b19.png">
<img width="1680" alt="Screenshot 2021-09-29 at 2 34 19 PM" src="https://user-images.githubusercontent.com/68137932/135239991-ae8204ee-ee83-4ab5-8a2b-ad398b855065.png">

### Important Details

- Version: Appsmith Self Hosted v1.5.24
- OS: Ubuntu
- Browser: Not relevant
- Environment: Not relevant

**Comment by sharat87** [comment]
Hey @suv95, from your screenshot, it looks like it's `appsmith-editor` that's down, and `appsmith-server` is actually up.

That said, this happens when the `appsmith-editor` and `appsmith-server` container and updated and are restarted at the same time. The nginx container (`appsmith-editor`) will fail to contact the upstream server container, because nginx starts much faster than Java, and then it promptly quits.

A solution to this is to have `restart: "unless-stopped"` added to the `nginx` service. In your `docker-compose.yml` file, add the highlighted line from below screenshot:

![Screenshot 2021-09-29 at 17 07 17](https://user-images.githubusercontent.com/120119/135261049-dc180e3e-00c3-43de-98c8-f8a6b9a3c6b2.png)

**Comment by suv95** [comment]
Thanks for the detailed explanation, @sharat87. I'll give it a try.

**Comment by sharat87** [comment]
Fixed by introducing a delay in updated images being pushed to DockerHub. This shouldn't be happening in the future, even if `restart: "unless-stopped"` is not present (although I'd recommend having it anyway).
