### ISSUE TITLE
[Bug] The evaluated value field moves into response pane which looks inappropriate 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#7934]
Steps to reproduce:
1) Create a GSheet datasource
2) Navigate to create New API
3) Navigate to lower fields that are closer to the response field 
4) Click on Row offset  and scroll
and observe that the evaluated value field 

Observation:
It is observed that on scrolling the evaluated value field moves into the response field which does not look appropriate as it does not belong to the place 

Expectation:
the evaluated value field must go along the respective field and not overlap on the response field
![Screenshot 2021-09-29 at 4 34 55 PM](https://user-images.githubusercontent.com/71753653/135259062-849d682d-7947-4406-83cb-25d7ecdf4cea.png)

**Comment by NoxiousPenguin** [comment]
Hey, could I be assigned this issue

**Comment by felixsuarez0727** [comment]
In regards to this issue:
Old React is mixed with the new one (hooks), so it's a little tricky, and may cause future bugs.
The issue descriptions states that the expected solution is to have the Evaluated Value outside the response container. So if, for example, this situation happens:

![image.png](https://images.zenhubusercontent.com/61ea7dcf08f2d17203f6f2fc/37f6af73-ff92-4c3e-9b57-e2ae813bbfb5)

If the expected solution is implemented, this won't look right, as well, because EvaluatedValue container won't be visible.

One of the solutions is to have a window listener, that listen to a scroll event and then hides the EvaluatedValue. Hence, everytime the final user scrolls, this component will hide and the problem will be solved.

**Comment by sumitsum** [comment]
@prapullac can you please check if this issue is still valid ?
