### ISSUE TITLE
[Bug] The Icon size of the Rate widget is smaller compared to all other widget in the entity explorer

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#7945]
## Description
Release - It is observed that the icon size of the rate widget is smaller compared to the all other widgets in the entity explorer

Expected Result:
Icon size of widget in the entity explorer should be same for all widget

### Steps to reproduce the behaviour:

1. Launch appsmith app in the release environment
2. Open any of the app and observe the icon size of rate widget 

### Important Details

- Version: [11.3]
- OS: [e.g.MacOS Big Sur]
- Environment [production, release]

<img width="1680" alt="Screenshot 2021-09-29 at 6 35 04 PM" src="https://user-images.githubusercontent.com/35128442/135274047-cf445e82-85f7-4b28-80c4-0ba1d29ce2c8.png">

**Comment by adarshlilha** [comment]
@somangshu @YogeshJayaseelan Can I take this up?

**Comment by somangshu** [comment]
👋  @adarshlilha, Thanks a lot for showing intrest in contributing to Appsmith 🚀 . Unfortunately this issue is invalid and i'll have to close it. Please checkout other good first issues which have better description. Mostly you will also be able to find the required solution on the thread of the issue. Please let me know if you need any help finding them. Happy Hacking 😄  

@YogeshJayaseelan all icons in the widget pane have the same height and width, This is basically because of how much space the icon cover in the container you feel the sizes are different, Since we are already working on the design system and widget discoverability this will be covered in a more generic sense. Closing this for now.
