### ISSUE TITLE
[Feature] Button tooltip enhancements

### ISSUE THREAD

**Issue by rishabhsaxena** [appsmithorg/appsmith#7948]
## Summary
Button tooltip enhancements.

- Line breaks within the content aren't supported currently. 
Quoting based on feedback:
```
input 
'df
df
df'
 inside a tooltop it shows 'df df df'
 ```

**Comment by Schnurres** [comment]
Better tooltips in general would help. My company uses a competing low code tool a lot and that tool offers more flexible tooltips. We implement the entire 'help' section of our application within tooltips. We got text-labels on every page or near important widges that say 'help' and when you hover over them a giant tooltip with helpful advice on how to use the page/widget is shown.

**Comment by Bhavin789** [comment]
Hi @somangshu @Schnurres , was just going through this discussion and have a thought that people generally use `Popover` instead of a tooltip in such cases when they have very large content to display and are user dismissive. 

Tooltips are generally for lesser content.

I referred [this](https://ux.stackexchange.com/questions/88844/when-should-i-use-a-popover-vs-a-tooltip). 

Maybe we can support a new `Popover` component?

[Reference](https://ant.design/components/popover/) in Antd.
