### ISSUE TITLE
[Bug] By Default input widgets valid field evaluated value is 'undefined'

### ISSUE THREAD

**Issue by YogeshJayaseelan** [appsmithorg/appsmith#8014]
## Description
Release/Production - It is observed that by default the input widget's valid field evaluated value is undefined 

Expected Result:
Evaluated value should not be undefined

### Steps to reproduce the behaviour:

1. Launch Appmsith app in the release environment 
2. Drag and drop input widget 
3. Click on the valid field and observe the evaluated value 

### Important Details

- Version: [11.3]
- OS: [MacOS Big Sur]
- Browser [chrome, safari]
- Environment [production, release]

<img width="1680" alt="Screenshot 2021-09-30 at 6 19 47 PM" src="https://user-images.githubusercontent.com/35128442/135458579-0e3622c4-92ee-4757-9792-8c2d837849a3.png">

**Comment by sbalaji1192** [comment]
@somangshu @YogeshJayaseelan Is this creating any issue.
Valid field is a boolean value, so I guess having a default value as undefined makes sense. we cannot have true or false as default value. as they have contextual meaning here. 
Same goes for maxChar, its default value is undefined, since it's a number and we can't have 0 as default value.
