### ISSUE TITLE
[Bug] Data on standup app "Today's update"page is not coming on release but showing on prod

### ISSUE THREAD

**Issue by vivekverma2312** [appsmithorg/appsmith#8062]
## Description: After export/import of app from prod to release, when I filled the standup app the data is reflected on prod but not showing on release.

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2de1f5cce4244c4dad5c86078edd7933-00001.gif)](https://www.loom.com/share/2de1f5cce4244c4dad5c86078edd7933)

### Important Details

- Version: [Cloud / Self-Hosted vx.x]
- OS: [e.g.MacOSX]
- Environment [production, release, deploy preview]

**Comment by hiteshjoshi** [comment]
The issue is export/import doesn't take JS objects into consideration atm. Because it's not live for users. And standup app is using JsObjects to modify data formats etc. 

App exported on prod : 
![Screenshot 2021-10-01 at 4 44 42 PM](https://user-images.githubusercontent.com/217911/135611260-80725d90-3bf6-42b7-9902-05dc15a86163.png)

App imported on prod : 
![Screenshot 2021-10-01 at 4 44 31 PM](https://user-images.githubusercontent.com/217911/135611306-aff4278e-757a-426c-b421-cd2a44ed099e.png)

**Comment by hiteshjoshi** [comment]
This is fixed is release. We shall open again if @yatinappsmith feels the need.
