### ISSUE TITLE
[Bug] - Property pane UI issues

### ISSUE THREAD

**Issue by albinAppsmith** [appsmithorg/appsmith#8235]
## Description

- [x] Switch to JS button hover not showing pointer
- [x] Date picker property pane, format dropdown is overflowing
- [x] Action dropdown in property pane is overflowing if long text is added

**Comment by GreenFlux** [comment]
Here's another issue in the properties pane.

![Screen Shot 2021-10-08 at 8 57 03 AM](https://user-images.githubusercontent.com/24459976/136561422-f0c2a674-5ee3-4cb5-ac84-a409cf587d3c.png)

The syntax highlighting is formatting the first two closing brackets instead of the last two. It seems to be confused when the only value in the `{{ }}` is an empty object `{}` .
