### ISSUE TITLE
[Bug] Pull request template is not working

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#826]

**Comment by OmkarPh** [comment]
Hi @prapullac,
Can i work on this?

**Comment by Nikhil-Nandagopal** [comment]
Hi @OmkarPh this might be a difficult issue because we ourselves aren't sure what's wrong. I suggest you start with our good first issues

**Comment by OmkarPh** [comment]
Hello, @Nikhil-Nandagopal 
I have use Pull_request_template.md file for adding Pull request template, cannot be this a simple solution?

Sorry if i misunderstood the issue ;)

**Comment by Nikhil-Nandagopal** [comment]
@hetunandu can you help with the issue here

**Comment by OmkarPh** [comment]
Can you check out this [PR](https://github.com/treeverse/lakeFS/pull/695)
I did this same thing, but it was not required there, but it worked !

**Comment by OmkarPh** [comment]
If this serves purpose, please give me an opportunity to do the same here too :)

**Comment by hetunandu** [comment]
Hey @OmkarPh, thanks for you interest in Appsmith! The problem is we already have a template in our .github folder [here](https://github.com/appsmithorg/appsmith/blob/release/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md) Can you see why does that not work? We have followed the guide mentioned [here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) 
Keep in mind, we want to be able to create multiple templates for features, fix etc.

**Comment by OmkarPh** [comment]
Well, thanks @hetunandu for this opportunity,
Please give me some time, I'll try my best to search for the cause and work out something, It's good to work with you guys 😄

**Comment by OmkarPh** [comment]
Hi @hetunandu,
I tried ways of adding a PR template.md file:
- Repository/pull_request_template.md   <- This works
- Repository/.github/pull_request_template.md   <- This works
- Repository/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md   <- This doesn't work , **But**

### I researched a bit and found out that, if I trigger a PR to appsmith repo by appending this query at end of PR URL:
## **`?template=pull_request_template.md`**

i.e. final URL of PR:

### https://github.com/appsmithorg/appsmith/compare/release...OmkarPh:patch-1?template=pull_request_template.md

as you can see in this Screenshot:

![image](https://user-images.githubusercontent.com/48476025/94990931-30b36680-059d-11eb-993e-c6d695d2142a.png)


## Summarising, the cause is probably a bug in Github workflow or it's their mistake in documentation

I suggest using the following option coz it works flawlessly without any extra effort
- ### Repository/.github/pull_request_template.md   



On the other hand, if we use:
- ### Repository/.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
User would have to add the query, **`?template=pull_request_template.md`**



Finally, I'm asking you guys, should I go ahead with this conveinient method : 

### Repository/.github/pull_request_template.md

**Comment by hetunandu** [comment]
Hey @OmkarPh thanks for the detailed response. I get the issue now, will raise this up with GitHub support. Meanwhile I think we can go ahead with moving the template under `.github` directory. Please raise a PR and assign me for review.

**Comment by OmkarPh** [comment]
Yep I'll do it

**Comment by OmkarPh** [comment]
It's a good feeling to be helpful 😄

**Comment by OmkarPh** [comment]
Hi @hetunandu 
I made a PR, can you checkout that.

**Comment by abramjkline** [comment]
Having PR Templates nested in the .github/PULL_REQUEST_TEMPLATE/  dir still does not work with slash commands. However, it does work with GH CLI.

**Comment by umairqaisar000** [comment]
You must create templates on the repository's default branch. 
Add .github/PULL_REQUEST_TEMPLATE.md file inside your default branch. And Github will automatically pick the PR message when creating the Pull Request. But Make sure it is added inside your default branch.

**Comment by nwoodr94** [comment]
> You must create a template on the repository's _**default branch**_. Add .github/PULL_REQUEST_TEMPLATE.md file inside your default branch. And Github will automatically pick the PR template description when creating the pull request. But make sure it is added inside your default branch.

My default branch is `master` and I have a template at `.github/pull_request_template.md`, but I still get no template when opening pull requests. Any ideas?

Default Branch:
![Image](https://github.com/user-attachments/assets/66b99bdf-cca2-4543-a4f6-a0ec4be4f50b)

Template:
![Image](https://github.com/user-attachments/assets/4b98e431-f9ec-415e-a959-a67431f6b933)

Pull Request:
