### ISSUE TITLE
[Feature] Add option to navigate (scroll) to specific widget in the "Navigate To" action

### ISSUE THREAD

**Issue by oskarannas** [appsmithorg/appsmith#8314]
## Summary

(I've search the docs and GH issues but could not find any mention of this function so adding it here.)

It would be nice to have the option in the "Navigate To" action to set a widget name to navigate/scroll to.

## Motivation

If you have a page with many widgets you would be able to add a button that could make the page scroll to another widget.

This should also work between pages.

### Example flow
- I have two pages, "Admin" and "Logs"
- On the "Admin" page i update a post in a table
  - This change generates a row in the "reports" table, which exists on the "Logs" page
- Next to the table on the "Admin" page i have a button that says "Go to the reports table"
- I click the button and appsmith navigates to the "Logs" page and scrolls down to the "reports"

A bonus would be i after scrolling the active widget would temporarily have a "glowing" border, or similar, to show that it's where we should focus.

## Additional Context

This might be solved in different ways.

The easiest (front end wise) would be to allow a page name and widget name to be set in the "Page Name or URL" field.

**Page Name or URL**
Mypage#myWidget

Another way would be to add a separate field for "Widget" so that you enter the page and widget in separate fields.

The "Query Params" and "Target" could keep their current behavior.

**Comment by tiger360** [comment]
is there still no way  to allow users to call a function that scrolls to any widget on a page ?

**Comment by Nikhil-Nandagopal** [comment]
@tiger360 unfortunately this has not yet been planned

**Comment by makulais** [comment]
See issues #4874, #7757 that request focus on specific widgets as either a JS function or action. This should provide the same functionality.

**Comment by GreenFlux** [comment]
I just realized this is already possible by appending the page url with `#WIDGET_ID`. You can see the ID of the widget in the url while in edit mode, and then add a `navigateTo()` action that adds the ID to `appsmith.url.fullpath`.

Since this already works by widget ID, could we update the UI for the navigateTo() action's Type-property `['Page Name', 'url']` to provide a third `'Widget'` option, for selecting the widget's ID by name? And if it could also set the cursor focus for input widgets, this could be used to create a tab-order with `onSubmit: navigateTo(widget)`. 
cc @dilippitchika

**Comment by Nikhil-Nandagopal** [comment]
@bharath31 @satbir121 this seems like a small change to our action selector. Can we do this?

**Comment by bharath31** [comment]
closing this in favour of #4874
