### ISSUE TITLE
[Bug] 500 Internal Server Error

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#836]
## Description

I'm testing out the endpoints to see if they are vulnerable and if they respond directly to GET requests in the browser and found https://app.appsmith.com/api/v1/pages to respond with a HTTP Error 500. 

![image](https://user-images.githubusercontent.com/4999463/94706158-78e54580-035f-11eb-953e-aa7dede291a3.png)

### Important Details
- Version: Cloud
- OS: Windows 10
- Browser: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by Jain-Sanchit** [comment]
@Nikhil-Nandagopal  Can you please elaborate the issue , I would like to work on this.

**Comment by trishaanand** [comment]
@Jain-Sanchit : Actually, this endpoint should not be open. The solution should be to disable/throw an error when this endpoint is hit. When I attempted this on my local, I didn't hit this issue. The response was big but it didn't throw a 500. I would surmise that on production, the size of the response may be too big leading to possibly out of memory error, etc. possibly.
Since this API should not be accessible, lets not fix the 500, but instead throw an error when this API is hit.

**Comment by prapullac** [comment]
Verified the issue as it is working as expected
