### ISSUE TITLE
[Bug] Platform allows insecure passwords for user accounts

### ISSUE THREAD

**Issue by harishkotra** [appsmithorg/appsmith#837]
## Description

User signup accepts insecure passwords like '12345678' which is a major security issue. Across the platform a strong password policy is required.

**Comment by priyanshu-shubham** [comment]
I would like to work on this issue.

**Comment by mohanarpit** [comment]
In order to solve for this, we need to add a custom password validator in the Java spring code base. Refer: [https://stackabuse.com/spring-custom-password-validation/](https://stackabuse.com/spring-custom-password-validation/). The example uses the `passay` maven library.

We should add the custom validator class in the package `com.appsmith.server.helpers` in the `appsmith-server` maven module. The validator function `isValid` should then be called in the function `UserServiceImpl#userCreate()` before the password encryption takes place.

**Comment by mohanarpit** [comment]
@priyanshu-shubham Welcome to Appsmith! 🎉 

I'm assigning the issue to you. Please go through our [Contribution Guide](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md) before you start. 

Also, would appreciate if you can raise a PR in the next 2 days.

**Comment by priyanshu-shubham** [comment]
Thanks @mohanarpit

**Comment by priyanshu-shubham** [comment]
@mohanarpit I am getting this error while building the final jar. 
 com.external.plugins.PostgresPluginTest: Container startup failed

**Comment by mohanarpit** [comment]
@priyanshu-shubham Do you have Docker installed on your system? Please re-check if you followed all the steps in the [Contribution Guide](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). 

If you still see this error and would like help in debugging it, please join our [Discord Channel]() and ping this on the #support channel there. It'll be much easier to debug there.

**Comment by Nikhil-Nandagopal** [comment]
@priyanshu-shubham I'm unassigning you since I don't see a PR raised for this

**Comment by harishkotra** [comment]
@Nikhil-Nandagopal no above-them for this one? I'm surprised this is labeled as a low priority one and an enhancement while this to me is a serious security concern.

**Comment by shinnlok** [comment]
@Nikhil-Nandagopal Can I work on this?

**Comment by mohanarpit** [comment]
Closing this issue as "Wont-fix" because we don't want to implement this in the product at this juncture since it makes user signups harder. Will come back to this issue incase the product direction changes in the future.
