### ISSUE TITLE
[Bug]:  Tab widget does not read the Default Tab defined 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is observed that even after adding Tab 5 the error message is not displayed to the user.

### Steps To Reproduce

```markdown
1) Add a Tab widget
2) Click on the Property pane
3) Navigate to the default tab
4) Add the tab value as TAB 5, ensure it is not added
and observe it displays an error 
5) Now add/ rename the Tab name as TAB 5
and observe
```

### Environment

Release

### Version

Cloud

**Comment by SatishGandham** [comment]
Instead of text field for default tab, if we provide a dropdown the problem will be solved.
When the tab name is changed after it is set as default tab, ensure that the change is reflected in the default tab as well.

**Comment by somangshu** [comment]
@SatishGandham what if someone wants to use a ternary operator to have different default tabs based on a condition. This use case can scale. We should not make it a drop-down.

**Comment by vicky-primathon** [comment]
Here, the defaultTab needs to be validated when tabs/tabsObj property of Tabs widget changes. Right now we don't any way to validate a widget property whenever any property changes. Similar problem exists in Button Group Widget, Checkbox Widget etc.

To do this we need to make use of **dependencies** property of Widget Property Configurations and make use of this so that whenever any dependency changes that property can be re-validated.

There is a **dependencies** property in property pane configurations which is not being used as of now but defined for lot of different properties in different widget.

**Comment by somangshu** [comment]
@riodeuno need your help in understanding if this should be a platform level change, and who should be handling it?

**Comment by riodeuno** [comment]
@somangshu 
@vicky-primathon 's approach is correct here. We need to validate the `defaultTab` using `ValidationTypes.FUNCTION` type of validation, which will use the `tabsObj` as a dependency.
Let's update the validation function and write unit tests for the same.

**Comment by vicky-primathon** [comment]
@riodeuno i made those changes earlier but could not fix the issue since the dependency does not work at platform level. Should i made the changes suggested by you irrespective of the dependency not working problem ?

**Comment by somangshu** [comment]
@Tooluloope do you have clarity on what needs to be done, Please drop your solution here in that case

**Comment by yaldram** [comment]
Not able to re-produce this anymore, seems to be fixed.
