### ISSUE TITLE
[Bug]: Checkbox group widget appears blank when more than 4 Options are added

### ISSUE THREAD

**Issue by shwetha-ramesh** [appsmithorg/appsmith#8503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/eff3a122318d481ea2ddb61c3df3a64c-00001.gif)](https://www.loom.com/share/eff3a122318d481ea2ddb61c3df3a64c)

### Steps To Reproduce

```markdown
1. Drag and drop a checkbox group widget
2. Open property pane
3. Click on '+ Options' 
4. Observe when more than 4 Options are added the widget appears blank
```

### Environment

Release

### Version

Cloud

**Comment by dilippitchika** [comment]
@somangshu the problem is more serious. Looks like we can't add any label/value which is empty. But by default we add empty which breaks the widget. I guess we need to show error in the data rather than widget. Needs some design help.

https://www.loom.com/share/ee74a20feb594af887e01f27ef81172e

**Comment by somangshu** [comment]
@dilippitchika What do you mean by show the error on data and not the widget?

Also, I think a better way to solve this would be to add a pre-filled name and value in the control, this will be worked by the Ui Builders POD. What do you think?

**Comment by dilippitchika** [comment]
My initial thought was the same, that you add pre-filled name and value. The problem was if I click add option again, it will add the same name/value and this error will re-occur. We have to check that as well and add prefix or suffix, maybe this is straightforward.

By error on data, i mean this area where user is adding the options
![Screenshot 2022-01-12 at 4 07 26 PM](https://user-images.githubusercontent.com/19730984/149124625-e00017df-3d02-4c3f-9549-38b63a9ad0ea.png)

**Comment by somangshu** [comment]
@dilippitchika We can auto increment a prefix on the pre-filled label to solve that
