### ISSUE TITLE
[Epic]: Input widget issues

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith#8506]
### Objective

All issue reported, related to input widget validation and evaluated value

### Success Metrics

| Goal          | Metric         |
| ------------- | -------------- |
| consistent behaviour  | All cases must be handled well with validation |

**Comment by sbalaji1192** [comment]
As per the Initial technical decision on 16/11/2021:

- We are going with a new version of the Input widget
- TEXT, PASSWORD, EMAIL, and PHONE NO. input types will be considered as string type, while NUMBER, CURRENCY will be considered as a number type.
- Maintaining PHONE NO. and CURRENCY input types along with other input types in a single widget is a hassle, since said input types have special cases when it comes to formatting and validations. So, We might need to segregate PHONE NO. and CURRENCY into their own widgets. (needs product team's opinion).
- We need to do more research on and implement PHONE NO. and CURRENCY formatting and validations.
- We need to standardize the form widget property pane categories and order.

Next actions:

- Discussion with product team about segregating input widget types. -  @sbalaji1192 @somangshu 
- Research about the PHONE NO. and CURRENCY validations and formatting. - @sbalaji1192 
- Documentation of new improved widget validations. @sbalaji1192

**Comment by somangshu** [comment]
@sbalaji1192 does this require a documentation change, In that case we have to inform @dilippitchika & @Pranay105 about the release so that they can plan this properly.

**Comment by sbalaji1192** [comment]
@somangshu Have spoken to @Pranay105 & @dilippitchika  already. I will write some draft documentation sometime this week or early next week.

**Comment by somangshu** [comment]
@sbalaji1192 @YogeshJayaseelan @vivekverma2312 we have closed the main PR which was resolving the issues here, There are still some pending issues which were not closed, Please verify and close this soon such that we can take a call on the rest of the open issues. 

@dilippitchika @Pranay105 this is getting release, We might need to check for the documentation changes.
