### ISSUE TITLE
[Feature]: Consistent Widget Defaults

### ISSUE THREAD

**Issue by cokoghenun** [appsmithorg/appsmith#8516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Throughout Appsmith, widgets have default data that is inspired by various ideologies and this is starting to tell on the maturity level of our product. Let me outline a few of these here:

* List widget has a default data that is inspired by Pokemon
* The audio widget plays a podcast that features Retool
* Iframe widget has Wikipedia embedded
* The video widget point to a really old video about Appsmith
* ...and many more

These inconsistencies may seem to be of little consequence, but they quickly begin to add up and cast a dark shadow on our product. As a result this needs to be fixed and resolved immediately!

### Why should this be worked on?

All widgets defaults need to be worked on so they have consistency across the board. This includes all widgets mentioned in the last section and many others.

**Comment by mohanarpit** [comment]
@cokoghenun It's all yours! 🎉 

Please don't forget to read the [Contribution Guidelines](https://github.com/appsmithorg/appsmith/blob/master/CONTRIBUTING.md). Would appreciate if you can open a PR within the next 2 days.

Also, please don't forget to register with [Appsmith's Hacktoberfest Community](https://hacktoberfest.appsmith.com) in order to be eligible for Appsmith swag. 😄
