### ISSUE TITLE
[Bug]: Data not being parsed into Float

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#8878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the user navigates into Google API and sets the Query row into 1-100 which has the combination of both empty decimal and integers. The API displays an error
![Screenshot 2021-10-28 at 12 22 06 PM](https://user-images.githubusercontent.com/71753653/139206522-07d5fbd3-18d7-4ff7-8661-ae5ced44cb76.png)

### Steps To Reproduce

1) Navigate to Google sheet
2) Authorise the sheets 
3) Click on the new API 
4) Select fetch as the method
5) Add the where clause 
6) Click on Run 
and observe

Ensure the user data has a combination of integer and decimal in the google sheet 

### Environment

Release

### Version

Cloud

**Comment by leotom2000** [comment]
PR #9923 created related to this fix was cancelled since PR #9711 handled the same main issue and merged the changes.

**Comment by leotom2000** [comment]
Found another related issue on testing as follows.
(1) To have a Google sheet with column of integers/decimals, 
     (1.1 ) try to fetch eg. 3456.77 - works fine
(2) Goto google Sheet, select the column to be fetched
   (2.1) Select from menu "Format"=>"Number"=>"Number"
        (The column get formatted with comma delimited numbers)
(3) Now when tried to fetch 3456.77, will thow error as mentioned in the defect.

**Comment by leotom2000** [comment]
### Findings and Resolution

**Existing Behaviour and Failure reason**
- The system is unable to handle comma delimited numbers
- so it fails


**Resolution**
- Filtered the commas from the String Input 
- Used Decimal Formatter to handle Float and Double 


**Files Modified**
appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java



**_Issues Fixed_**
#9667 
#7794
#8878 - This issue

Generating a Single PR addressing the above 3 issues since they are related
