### ISSUE TITLE
[Bug]: input default text does not update

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#9011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The input default text does not update when the store is updated with the same value again

### Steps To Reproduce

1. Drag an input and bind it to {{ appsmith.store.text }}
2. Drag a button and bind the onClick to {{ storeValue('text', 15) }}
3. Click on the button and see the input value update
4. end the input to a new value and click the button again
5. The input does not get updated

### Environment

Production

### Version

Cloud

**Comment by ajinkyakulkarni** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/FE-Coders-Pod-6167d1b64ee5f20014242ab7/issues/appsmithorg/appsmith/9011?planning-poker) with ZenHub @hetunandu @ApekshaBhosale @ohansFavour @Rishabh-Rathod

**Comment by eco-monk** [comment]
@Nikhil-Nandagopal, as far as `appsmith.store.text`, `defaultText` field is concerned. Nothing has changed, right?
Since we're setting the same value again.
When the user makes a change to the input field, they're changing `Input.text`.

Perhaps we should create a new binding field `Input.text`?
That should serve the use-case that we're after. (resetting field value on a button click)

Or perhaps we could use the form reset function?

---

Otherwise when `appsmith.store.text` actually changes, the input field would get updated.

**Comment by eco-monk** [comment]
Otherwise when `appsmith.store.text` actually changes, the input field would get updated.

On second thought, this is questionable behaviour too. 
`defaultText` is supposed to fill in only when the input field is empty. (`OnInit` kind of event)

Perhaps we're blending two different functionalities (`text` and `defaultText`) into one property.

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk yes that is right, text and defaultText are meant to overwrite each other depending on which was updated last. @hetunandu should have some context on how the evaluation works here

**Comment by eco-monk** [comment]
@Nikhil-Nandagopal. 
I had a discussion with @hetunandu.

We'll be working on a feature that allows users to set meta properties of a widget.
https://github.com/appsmithorg/appsmith/issues/3532

We should be able to use this to reset `text` on buttonClick, instead of using `defaultText` and `appsmith.store`.
(Using form reset is also another option)

---

About using `appsmith.store`.
When `storeValue('text', 15)` is called consecutively. It's not considered a change.
Because the store would remain the same `{ text: 15 }` -> `{ text: 15 }`.

Hence evaluation will not be triggered. 
We have this check to prevent unnecessary evaluation on events where there's no change to the data tree.

**Comment by Nikhil-Nandagopal** [comment]
@eco-monk you are right, the default text has not changed in this case so this is not valid
