### ISSUE TITLE
[Epic]: Appsmith IDE

### ISSUE THREAD

**Issue by Nikhil-Nandagopal** [appsmithorg/appsmith#9060]
### Objective

Our objective is to improve the Appsmith IDE for developers building complex applications

### Success Metrics

- Fewer misclicks during navigation
- Lower time to switch between different entities

### Requirements

- Create a long term layout for the IDE that will enable us to easily add features in different sections
- Optimise for Navigation between Queries and Pages
- Have a clear hierarchy and mental model for information
- Take both global and page-level queries into account

### Developer Handoff Document in Figma

https://www.figma.com/file/aeCo7j5ecU83euTPDpQCH4/Appsmith-IDE-Explorations?node-id=37%3A6182

### RACI matrix

| ------------- | ------------- |
| Responsible   | @arunvjn @albinAppsmith |
| Accountable   | @aakashDesign |
| Consulted     | @Nikhil-Nandagopal, @mohanarpit, @hiteshjoshi  |
| Informed      | @areyabhishek |

**Comment by Nikhil-Nandagopal** [comment]
Update:
Today we all agree that Pages, Queries, JS & Datasources should all be treated as files inside the IDE. Each file on opening has a different UI and interaction but all files are managed the same way i.e they are renamed, copied, deleted, organized, and discovered through a consistent set of file management operations.
Our next explorations are to figure out the best way to organize these files. 
Some opinions we've discussed are around
- Separating UI Files in a section
- Removing sections and allowing users to group/organize files however they like
- Having separate sections for different file types

Questions To Be answered
- Where should DB schemas be discovered?
- Where should the state of the local storage and temporary storage be discovered?
- How will global/local files organization work?
- What are the main sections in the editor and what type of information do they contain?

Next Action Items:
- @aakashDesign to come back with more iterations around tabs / recent section in the editor / different file organization strategies and answers to the above questions

**Comment by aakashDesign** [comment]
Update: 
Sharing new designs for Entity Explorer with modules for Widgets, Files, & Datasources - nested inside pages.

Prototype - https://www.figma.com/proto/aeCo7j5ecU83euTPDpQCH4/Appsmith-IDE-Explorations?page-id=300%3A13689&node-id=314%3A26406&viewport=284%2C48%2C0.72&scaling=min-zoom&starting-point-node-id=300%3A13690 

Figma- https://www.figma.com/file/aeCo7j5ecU83euTPDpQCH4/Appsmith-IDE-Explorations?node-id=300%3A13689

Today's discussion centered around -
- Files & Folders on explorer - Sorting options & types, nameSpace for api/query when nested inside folders.
- Widget List - the explorer keeps moving when selecting widgets on a large canvas, at it get annoying. How might we solve that.
- Datasources - which datasources show up on the explorer - app lever/page level. Also, which datasources show up on the new file screen.

Next action items on design front -
- More iterations on Sort by Type, & Sort by Datasources.
- Update the 'New File' screen for page, app, and org level datasources. Users should be able to understand that they are creating a query, and not just selecting a datasource.
- Show visual differentiation between Dependencies & rest of the items on explorer, as dependencies are at an App level.
- Use a better icon for pages.
- Reset new datasources page with tabs for Active & Create new.
- What if instead of Files & Folders, we only designed Files & Groups. Groups don't need to follow namespaces.

Questions to be answered from the engineering front -
- Can we execute folders right now, or they will be tackled as a V2.

**Comment by arunvjn** [comment]
**Update:**

**Next action items - DEV**
- Widgets section should be collapsed by default
- CMD OPTION N for new file pop up
- Remove sort option with groups as the default
- On new page, queries and datasources section should be expanded
- Edit name text to Rename text
- Anchor on data sources when + data sources is clocked and when selected from omnibar
- Parallax effect for widgets/JS Object/ queries headers
- White line at bottom of omnibar modal.

**Next action items - Design**
- New icons for API, Queries, JS Objects and Datasources
- Move bindings to a modal
- Solve the collapse explorer interaction

_Decisions on UX to be closed by Monday._

**Comment by arunvjn** [comment]
**Update - 24 Dec**

**Next action items - Dev**

- Different Hover states for Sections in explorer (Widgets, Queries/JS Objects).
- Align all explorer icons.
- Keep DB schema collapsed by default.
- Chevron icons for entity explorer pin/unpin.

**Next action items - UI/UX** 

- Callout to introduce the new explorer.
- “Add new” buttons to the sections in the entity explorer.
- Empty state for the sections in the explorer.

**Comment by arunvjn** [comment]
Closing this EPIC since the entity explorer redesign is complete. 
Will be taking up additional enhancements/Improvements as adhoc requests.
