### ISSUE TITLE
[Bug]: cyclic dependency error is displayed in one of the old application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

One of the old app is facing a cyclic dependency error in both release and Production
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/4b38cd96fc8746dda988995e8a68deca-00001.gif)](https://www.loom.com/share/4b38cd96fc8746dda988995e8a68deca)
Link for the app : (https://release.app.appsmith.com/applications/616d26cd8cc2642df8e19f51/pages/616d26cd8cc2642df8e19f57/edit/queries/616d26cd8cc2642df8e19f5f

### Steps To Reproduce

1. Opened one of the old app
2. The cyclic dependency error is displayed

### Environment

Production

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
This issue wasn't reproducible in any other application and even in the same application, hence deprioritizing this issue.

**Comment by Nikhil-Nandagopal** [comment]
@Rishabh-Rathod lets close if we can't reproduce

**Comment by Rishabh-Rathod** [comment]
@Nikhil-Nandagopal just to clarify, this issue was there in the application at a certain page where we could see now also but there is no way we can re-create that again. Also, I wasn't able to find out it in past it went into that bad state.

Also, it happened only for the release app which also opens up the possibility that there was a bug in the release which never went to prod which might have caused this issue.
