### ISSUE TITLE
[Bug]: Indent line of code is not aligned properly on JS editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Manually indenting on a copy paste code that's being indented causes the lines to get misaligned.

![image](https://user-images.githubusercontent.com/79509062/142731986-787181be-6cca-480a-b750-c16e078a0467.png)

### Steps To Reproduce

1. Copy paste a long code to JS editor and try to format code by indenting and observe the indents misalinged like above

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
design https://www.figma.com/file/X03G0OsEtvH9JHDhU8XREy/JS-Editor-Improvements?node-id=1082%3A61878

**Comment by rohan-arthur** [comment]
requirements derived from old conversation in https://github.com/appsmithorg/appsmith/issues/9269#issuecomment-1003015660

### Updated Requirements
_Note_: there are competing schools of thought whether to use spaces or tabs for indentation, and again about how many spaces/tabs for each level of indentation. Since the JSEditor already has the indentation facility partially working, we will stay with: 2 tabs per level of indentation

The following rules should apply for auto indentation in the JS Editor (with inputs from here https://google.github.io/styleguide/jsguide.html#formatting-block-indentation):

### Auto Indent

- [x] 1. Each time a new block or block-like construct is opened, the indent should increase by two tabs. A block is defined by either '{', '[', or '(' followed by a new line
- [x] 2. This indent should continue until the block is closed. When the block is closed by the corresponding '}', ']', or ')', the next line should start with (- two tabs)
- [x] 3. at all times, the user should be able to over-ride the auto-indentation to allow for users with peculiar tastes :-D

### Manual trigger

- [ ] 1. At any time, I should be able to trigger prettify of my code, and on doing so the indentations should be reset according to the scheme described above.
- [ ] 2. The formatting should work on the entire code in the editor
- [ ] 3. The "Prettify" button should be offered as both a button and a keyboard shortcut
- [ ] 4. Button/CTA placement - [design](https://www.figma.com/file/X03G0OsEtvH9JHDhU8XREy/JS-Editor-Improvements?node-id=1207%3A62790)
- [ ] 5. Keyboard shortcuts are as follows (same as vscode, considering its popularity, open to other options):
            On Windows Shift + Alt + F
            On Mac Shift + Option + F
            On Linux Ctrl + Shift + I
- [ ] 6. The keyboard shortcut should be shown in as per the [design](https://www.figma.com/file/X03G0OsEtvH9JHDhU8XREy/JS-Editor-Improvements?node-id=1207%3A62790)



### For later
- [ ] 3. When I go "home"(home key on windows or cmd+left arrow on mac) on my keyboard, the cursor should move to the first column after current indentation level - this should also apply to selection. E.g, at the end of the line, if I do cmd+shift+left arrow, the line should be selected only until the current first indented column. //this works for the "home" button, but not for "cmd+left", which works in vscode.
- [ ] 4. If I go "home" when I am already on the current first indented column, the cursor should take me to column 0
- [ ]  (can do selection-based prettify in a later release)

**Comment by rohan-arthur** [comment]
need to discuss this further

**Comment by Rishabh-Rathod** [comment]
After discussion with @parth-appsmith, regarding auto indent on save vs shortcut or manual triggers.

We realized that on save formatting might not be the best experience for users in scenarios like
1. When users add multiple tabs or spaces inline intentionally. 

Hence, we could move forward with the manual triggers for now.

**Comment by rimildeyjsr** [comment]
The edge case bug has been solved, updating the cypress tests. Pushing to QA to get the manual testing started, so the process can be parallelised a bit!
