### ISSUE TITLE
[Enhancement]: Auto indent code on JS editor

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- [ ] When copy pasting large code into JS Editor, there are times when the code is not readable because of incorrect indentation. To indent it properly, user would either have to use another tool or manually indent each line. Instead, we could provide an option to indent code via a button _and_ keyboard shortcut.
- [ ] Pressing enter at the end of a long line, adds a new line and cursor right below the current line instead of formatting below the closing braces

A nice tool that I refer to: https://zebzhao.github.io/indent.js/

### Why should this be worked on?

Improves usability on the JS editor and any other suitable spaces inside the application and enhances the "developer-first" experience.

**Comment by rohan-arthur** [comment]
_Note_: there are competing schools of thought whether to use spaces or tabs for indentation, and again about how many spaces/tabs for each indentation. Since the JSEditor already has the indentation facility partially working, we will stay with: 
1. 2 tabs per level of indentation

The following rules should apply for auto indentation in the JS Editor (with inputs from here https://google.github.io/styleguide/jsguide.html#formatting-block-indentation):
### Auto Indent
- [ ] Each time a new block or block-like construct is opened, the indent should increase by two tabs. A block is defined by either '{', '[', or '(' followed by a new line
- [ ] This indent should continue until the block is closed. When the block is closed by the corresponding '}', ']', or ')', the next line should start with (- two tabs)
- [ ] When I go "home"(home key on windows or cmd+left arrow on mac) on my keyboard, the cursor should move to the first column after current indentation level - this should also apply to selection. E.g, at the end of the line, if I do cmd+shift+left arrow, the line should be selected only until the current first indented column.
- [ ] If I go "home" when I am already on the current first indented column, the cursor should take me to column 0

### Manual trigger
- [ ] At any time, I should be able to trigger pretty print of my code, and on doing so the indentations should be reset according to the scheme described above. 
- [ ] If I have made a selection in the editor, the prettify should be applied to the selection only
- [ ] If I have not made a selection in the editor, the prettify should be applied on the entire code
- [ ] The "Prettify" (confirm name from design-copy team) should be offered as both a button and a keyboard shortcut
- [ ] Button placement - design
- [ ] Keyboard shortcuts are as follows (same as vscode, considering its popularity): 
On Windows Shift + Alt + F
On Mac Shift + Option + F
On Ubuntu Ctrl + Shift + I

**Comment by rohan-arthur** [comment]
_Note_: there are competing schools of thought whether to use spaces or tabs for indentation, and again about how many spaces/tabs for each level of indentation. Since the JSEditor already has the indentation facility partially working, we will stay with: 2 tabs per level of indentation

The following rules should apply for auto indentation in the JS Editor (with inputs from here https://google.github.io/styleguide/jsguide.html#formatting-block-indentation):

### Auto Indent

- [ ] 1. Each time a new block or block-like construct is opened, the indent should increase by two tabs. A block is defined by either '{', '[', or '(' followed by a new line
- [ ] 2. This indent should continue until the block is closed. When the block is closed by the corresponding '}', ']', or ')', the next line should start with (- two tabs)
- [ ] 3. When I go "home"(home key on windows or cmd+left arrow on mac) on my keyboard, the cursor should move to the first column after current indentation level - this should also apply to selection. E.g, at the end of the line, if I do cmd+shift+left arrow, the line should be selected only until the current first indented column.
- [ ] 4. If I go "home" when I am already on the current first indented column, the cursor should take me to column 0
- [ ] 5. at all times, the user should be able to over-ride the auto-indentation to allow for users with peculiar tastes :-D

### Manual trigger

- [ ] 1. At any time, I should be able to trigger format of my code, and on doing so the indentations should be reset according to the scheme described above.
- [ ] 2. The formatting should work on the entire code in the editor (can do selection-based formatting in a later release)
- [ ] 4. The "Format" should be offered as both a button and a keyboard shortcut
- [ ] 5. Button/CTA placement - need design input
- [ ] 6. Keyboard shortcuts are as follows (same as vscode, considering its popularity, open to other options):
            On Windows Shift + Alt + F
            On Mac Shift + Option + F
            On Ubuntu Ctrl + Shift + I
- [ ] 7. The keyboard shortcut should be shown in _______ (will update after design input)

### Design requirements
- [ ] 1. Button and title ("Format" or something else)
- [ ] 2. How to show the shortcut? CMD+? works only on canvas

**Comment by ApekshaBhosale** [comment]
pending on designs. functionality is on branch name - 'auto-indent-js-editor'

**Comment by rohan-arthur** [comment]
updated requirements in #9628

**Comment by rohan-arthur** [comment]
will be fixed with #9268
