### ISSUE TITLE
[Bug]:  S3 : First filter must be not be allowed to delete 

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#9302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the S3 fetch method is added it is observed that the first where clause can be deleted and the condition remains on undeleted. Making this UI difficult 

### Steps To Reproduce

1) Add Query S3 fetch method 
2) Add a Group filter 
3) Delete 1st where clause 
4) and observe 
![Screenshot 2021-11-23 at 3 54 09 PM](https://user-images.githubusercontent.com/71753653/143015593-6366994c-b1f7-4f41-8167-a219ad4ed180.png)

### Environment

Release

### Version

Cloud

**Comment by rohan-arthur** [comment]
- Tab does not work with UQI components
- Aakash had talked about getting rid of the green CTAs on where clause in favour of the CTAs like in the sort component. Have we worked on this yet?
- The where component does not seem to be following the filter design on Figma, do we have a task for this?
- Do we have support for the help text, and other meta props on the components as provided on the Figma file?
from [here](https://theappsmith.slack.com/archives/C02KTH6EHUG/p1646115609033869)

**Comment by parth-appsmith** [comment]
@rashmi-rai you can check the designs and the solution in this [Notion doc](https://www.notion.so/appsmith/Redesign-of-filter-where-components-for-UQI-30d2f4eb20d946d8a2b5a466f50feab1)

Design File: https://www.figma.com/file/Qs7p5frNx7uEfVYpADGk0d/?node-id=54%3A4654

**Comment by rashmi-rai** [comment]
@parth-appsmith you can find deploy preview of S3 where clause here. https://appsmith-f9rkshwlp-get-appsmith.vercel.app/user/login

**Comment by parth-appsmith** [comment]
@rashmi-rai I found some inconsistencies on the UI can you please correct them.
1. Misalignment of Where group conditions, the box is not in line with the end of the upper component.
![UQI Files Misalignment 1](https://user-images.githubusercontent.com/92779003/157603708-6162d750-4098-4bbd-a34d-2679e41073d9.png)
![UQI Files Misalignment 2](https://user-images.githubusercontent.com/92779003/157603713-02f58777-ee72-4d9c-bbec-16271575fbe5.png)

2. In case where we reach the limit of 4 group conditions, instead of making the options of "Add Where Group Condition" disappear lets show it in a disables state. On hover the disabled option will show a tool tip informing why is the option disabled. 
Have added the designs for this in the same file, you can view it from [here].(https://www.figma.com/file/Qs7p5frNx7uEfVYpADGk0d/Query-Pane-Improvements?node-id=230%3A13263)

3. Do we not allow "Switch to JSON editor" for S3 data source? 

@nidhi-nair also wanted to understand these changes to the where clause will be made for all data sources right not just S3.

**Comment by nidhi-nair** [comment]
It will be applied to all plugins that have switched to UQI. The other plugins that use support `WHERE` are using a different component, we should invest in making them comply with UQI instead of redoing the older component.

**Comment by rashmi-rai** [comment]
1. Misalignment of Where group conditions -> Done.
2. Disable state for level for and tooltip on hover -> Done
3. Do we not allow "Switch to JSON editor" for S3 data source? This will show up only after Switch to Json view PR is merged. 
4. Label text change.  Won’t be reflected in the deploy preview. But here is the screenshot ![Screenshot 2022-03-16 at 6.39.04 PM.png](https://images.zenhubusercontent.com/61287a32887234048832d53a/f8f9dd81-d1cc-4d33-b1d5-9cbc473f8f84)

@parth-appsmith Shall we go ahead with these changes or wait for the Switch to Json PR to get merged?

**Comment by btsgh** [comment]
Tested the issue and now found the following behaviour - https://www.loom.com/share/7d422c4f219d40d9981f7cc4e6930c43

**Comment by btsgh** [comment]
Tested the issue and now found the following behaviour - https://www.loom.com/share/7d422c4f219d40d9981f7cc4e6930c43

When I delete the first where clause after adding a group filter, the first where clause gets deleted, which is fine, and the group filter condition moves up, so far so good.
However, when I run the query, I get an error. This is because of two AND conditions present from the first where clause as well as the group filter. This behaviour seems incorrect.
