### ISSUE TITLE
[Bug]: Firestore where clause doesn't seem to work

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith#9414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When querying Firestore, if I add a where clause, it doesn't seem to work. I get an empty dataset back even though I know that the record exists. This seems to happen for integer values.

### Steps To Reproduce

1. Create an app with Firestore query
2. List the documents in the collection
3. Add a where clause filter to search for a specific document
4. See that the response is an empty array when you know that the relevant document exists.

Screenshots below:
<img width="1153" alt="Screenshot 2021-11-27 at 9 59 10 AM" src="https://user-images.githubusercontent.com/458946/143668029-441c8224-f2a4-4275-b012-f960e8458b4d.png">
<img width="1169" alt="Screenshot 2021-11-27 at 9 58 54 AM" src="https://user-images.githubusercontent.com/458946/143668032-96ebf247-4f5c-4bc7-8daa-cbc988b84cc4.png">

### Environment

Production

### Version

Cloud

**Comment by leotom2000** [comment]
### Findings and Resolution

In where condition when the value is a String, it is processed successfully
When the comparing  value is a number, it does not fetch - so the Issue exists
When tested the issue exists for Boolean, Date and Timestamp.

The reason is when the request is sent as a String, firestore searches for Sting Only,
so depending upon the datatype it needs to be sent as object
Made code changes to sent object as a part of query.

That way now Number, Boolean, Date and Timestamps issues are fixed.
Also in the where condition when the Key or Value contains space in front or back those caused issue.
trimmed the empty spaces and additional issues were resolved.

File modified :  app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/utils/WhereConditionUtils.java
