### ISSUE TITLE
[Bug]: The same page name is created When 2 different users are working on same application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The same page name can be created When 2 different users are working on same application
![image](https://user-images.githubusercontent.com/45958978/144049329-b5743d81-a829-4a11-ba8b-ebcbf71ecedc.png)

### Steps To Reproduce

1. log in to appsmith with 2 different users 
2. Use the same application 1 for editing
3. Now as a user 1 create a new page 1
4. Now as a user 2 create a new page 
5. The page name will be page 1
6. This should be happening there should be only one page with the page name 1

### Environment

Production

### Version

Cloud

**Comment by pranavkanade** [comment]
@nayan-rafiq can you please look into this? Don't think this can be resolved from FE alone.
@RakshaKShetty this issue was always there on our platform. It falls under the scope of Collab V2. This shouldn't be marked high.

**Comment by nayan-rafiq** [comment]
One way of fixing this is - generate the page name in BE. If create page API is called, BE will generate a page name. But this can have another impact. For example, suppose an user has Page 1 and Page 2. If another user already created Page 3, then create page for current user will create a page with name "Page 4" which might seem confusing to the user because that user doesn't know "Page 3" is already created. 
@pranavkanade do you have any thoughts on that?

**Comment by pranavkanade** [comment]
@nayan-rafiq This is definitely not a `high` priority issue. My guess is we've been carrying this issue since early days so it's not a pressing issue. I think we should take this up with Collab V2. The other problem with moving name generation part in the BE is, we'll also have to move it for `query`, `api` and `widget`.
