### ISSUE TITLE
[Bug] . and ) don't work in page name

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#955]
When creating / renaming a page inside an Appsmith application, the characters `.` and `)` are not allowed. Ideally, we should allow all characters to be typed inside the page name without restriction.

**Comment by Jain-Sanchit** [comment]
I would like to worn on this if i may get the proper path to the code file of this section .

**Comment by mohanarpit** [comment]
@riodeuno Can you help @Jain-Sanchit with the relevant files that he can use to fix this issue?

**Comment by riodeuno** [comment]
@Jain-Sanchit The page entity names are resolved using the function `resolveAsSpaceChar` in `app/client/src/utils/helpers.tsx`. This function takes the user entered string and returns a new value to allow only spaces (currently), by replacing all consecutive non-alphanumeric characters (regex `\W`) with one space character. 
Hope this helps.

**Comment by Jain-Sanchit** [comment]
@riodeuno Thanks for the info . I will get onto this and try solving the issue.

**Comment by Jain-Sanchit** [comment]
@satbir121  @riodeuno Can you please let me know where is being this function actually used , in which component , as there may be scenarios that I update the function but function was needed somewhere else . So is there any way to know where is this function is being used in the code ? So that before raising a pull request I will be sure about its correctness .
Thanks

**Comment by mohanarpit** [comment]
@Jain-Sanchit If you're using an IDE like VSCode, you can right click on the function name and choose "Find all references". A quick google search for your IDE will tell you the flow (if you aren't using VSCode).
