### ISSUE TITLE
[Bug]: cannot reach widgets inside a list if the list has a "OnListItemClick" property specified.

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#9568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the list has some widgets inside, and something specified in the "OnListItemClick" property. Now you cannot select the widgets inside the list. When you attempt to, the OnListItemClick gets called instead. :(

Uploading Screen Recording 2021-12-04 at 9.27.37 PM.mov…

### Steps To Reproduce

1. I have created an app to reproduce this: https://app.appsmith.com/applications/61ab8e37d3e4214454c23c86/pages/61ab8e37d3e4214454c23c88/edit
2. see there are 2 lists: List1 and List2
3. List1 has OnListItemClick property to open some modal. List2 has no OnListItemClick event specified. 
4. When you try to access some widget inside List1, the modal opens and the property pane also shows the properties of the modal. You cannot anymore access the properties of the widgets inside the list unless you remove the OnListItemClick property and reset it to "no action"
5. You can do all this with List2, I'm guessing because it has no OnListItemClick specified. 

### Environment

Production

### Version

Cloud

**Comment by dilippitchika** [comment]
This is exactly the same issue, I faced when I was developing my first app. I had added the binding for page change onListItemSelected, had to reset that to no action as long as I was working on the list.
This issue applies to all widgets but will cause the most pain to users of List (onlistitemselect) and Table (onRowSelect) widgets.

There are 2 ways to show property panes, 
1. On clicking any widget it should show the property pane. This is the easiest to learn as when a user starts out, it's most intuitive. 
2. On clicking the settings property of any widget on hover shows the property pane. This is visible on the screen but because we are habituated to clicking the widget directly no one clicks on the setting and for this we have to move our cursor. 
![Screenshot 2021-12-24 at 11 47 09 AM](https://user-images.githubusercontent.com/19730984/147323942-c686beff-6719-43bc-85df-c9847190b813.png)

My current thoughts around the solution are:
1. Stop certain actions from executing selectively in the edit mode. Certain actions in edit mode which change the view can only be triggered using a special way in the view mode.
2. Remove the click to open a widget option all together and change the user's mental model itself. Very painful for current users. Will also need some design improvements.

I will research more on this and get back if there's any better UX possible. Any evidence of others facing this issue will help us prioritise this better @Nikhil-Nandagopal. 

CC - @somangshu @riodeuno @momcilo-appsmith

**Comment by Nikhil-Nandagopal** [comment]
@dilippitchika as discussed, I believe the real problem here is a child widget's click should not trigger the parent widget in the list.

**Comment by unknown1337** [comment]
Exactly same issue here. Clicking on a child item (e.g. icon button) inside a list item will cause both the action of the icon button onclick and the list item onclick to be fired which is NOK. Especially as a list item click will do a redirect to a new page showing details for that item and a icon click showmodel will be supressed .

**Comment by somangshu** [comment]
@unknown1337 we are aware of the situation and are working on our solution for the list widget

@Tooluloope @ashit-rath is there a way to make this work on the V1 version?

**Comment by Tooluloope** [comment]
Let me look into this, I believe it should be solvable in v1

**Comment by kamal0808** [comment]
Whoa, this stopped triggering onListItemClick event while clicking anywhere on the list. Is there an alternative to keep that alive? @Nikhil-Nandagopal

**Comment by dilippitchika** [comment]
@kamal0808 your current list widget should not have any impact. Only if you drag a new widget you should see this behavior change. Are you seeing it break in your current list widget?
