### ISSUE TITLE
[Bug] The fields in the API pane don't revert to their original size when they lose focus

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#958]
## Steps to reproduce

1. Go to the API pane in the Appsmith editor
2. Type a very long URL in the URL field. Optionally, type a long text in the input fields for query params or header params.

## Observation
The fields expand vertically to show the complete text when it's in focus. When the input field loses focus, it doesn't go back to it's original size.

## Expected behaviour
When an input field loses focus, it should go back to it's original size.

**Comment by Jain-Sanchit** [comment]
@Nikhil-Nandagopal  Why we can not see the issue , this link requires a login and over login it says you don't have access? A lot of issues are having no description but this link only .
Please help me understand this.

**Comment by mohanarpit** [comment]
@Jain-Sanchit Sorry that you faced this issue. We migrated a lot of issues from our internal tracker on Notion to Github which caused these Notion links to appear instead of complete description. For now, please tag @prapullac , @Nikhil-Nandagopal or me incase you'd like more details for any issue. We'll furnish more details as possible. 

Apologies for this less-than-ideal experience till we figure out a more holistic fix.

**Comment by Nikhil-Nandagopal** [comment]
@Jain-Sanchit i've updated this so you can pick it up if you like

**Comment by ThakurKarthik** [comment]
Hey @hetunandu @Nikhil-Nandagopal is this already claimed by someone? If not I can give it a try.
Thanks

**Comment by Nikhil-Nandagopal** [comment]
@ThakurKarthik  go for it!

**Comment by mohanarpit** [comment]
@hetunandu I'm unable to reproduce this issue. Can you please confirm if this issue is still valid?

**Comment by prapullac** [comment]
Verified the issue
