### ISSUE TITLE
[Feature]: Possibility to deploy Appsmith on Docker with another port than 443

### ISSUE THREAD

**Issue by fungiboletus** [appsmithorg/appsmith#9591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It seems that the Docker image of Appsmith is hardcoded with the 443 SSL port, which is not very convenient when you already have something using the port 443. It could be nice to be able to run Appsmith on other ports too.

### Why should this be worked on?

-

**Comment by mohanarpit** [comment]
You can always modify the ports in the `docker-compose.yml` file to use other host machine ports that map to 443 within the container. In the below example, on the host machine Appsmith will occupy ports 8080 (HTTP), 8443 (HTTPS) & 9801 for supervisor & control. 

```
    ports:
      - "8080:80"
      - "8443:443"
      - "9801:9001"
```

Does this configuration help? Are you running into any issues with custom ports being configured in this manner?

**Comment by Nikhil-Nandagopal** [comment]
Closing this issue as this should be possible

**Comment by sharat87** [comment]
Small note on suggested change in `docker-compose.yml` file, if you intend to use HTTPS, please keep the 80's port mapping intact. That is, please leave the `80:80` line as is. The reason is because `certbot` and Let's Encrypt rely on this port mapping to provision the SSL certificate for your domain. If this port was changed, the SSL certificate provisioning would fail.

However, if you don't intend to use HTTPS, you may freely change `80:80` to any other port mapping like `8080:80` to use port 8080 for example.

**Comment by fungiboletus** [comment]
Could it be possible to disable HTTPS ? I don't really need a let's encrypt certificate, the host is not public, and the tunnels towards my host are already encrypted.

**Comment by sharat87** [comment]
That is currently not possible, but we just merged a PR where if the certificate provisioning fails, for whatever reason, the server would proceed to start without HTTPS, with just HTTP. The PR is at https://github.com/appsmithorg/appsmith/pull/9546. It should be released soon within this week.
