### ISSUE TITLE
[Feature]: Split the Appsmith docker container

### ISSUE THREAD

**Issue by fungiboletus** [appsmithorg/appsmith#9592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The AppSmith Docker container is a big container containing many services, such as :

 - backend
 - cron
 - editor
 - mongodb !
 - redis 
 - rts
 - stdout

Everything is managed through supervisor and the documentation invites us to check it. I'm just wondering why not doing like one container per service. It's more standard and easier to work with for people used with Docker. The deployment already uses Docker Compose.

### Why should this be worked on?

The current setup is not broken, but is a bit uncommon.

**Comment by mohanarpit** [comment]
Earlier, Appsmith did ship with multiple containers in a `docker-compose.yml` file, one for each of the services listed above. Lots of users would face issues in configuring & getting all the containers to run properly on various environments. In an attempt to simplify the deployment for users, we ended up bundling everything into a single container & bringing service orchestration to `supervisord`. This model ensures that running & deploying Appsmith becomes a much simpler affair rather than having to configure & run multiple services. 

In addition to this, when Appsmith introduces new features/services (real-time commenting, multi-player editing etc), it becomes much easier for you as a user to take advantage of these services. As a user, you don't have to update your `docker-compose.yml` file. You simply upgrade the container & take advantage of the new features. In our heads, this was a win-win situation. 

I understand that this may seem uncommon, but other large open-source companies like Gitlab also ship a single container that has all the services running inside it. 😄

**Comment by fungiboletus** [comment]
Thanks for your answer. I understand that it is designed towards simplicity for beginners. Maybe I can use the same images than the ones for the Kubernetes deployment. And I didn't know Gitlab was doing that too :D
