### ISSUE TITLE
[Bug]: this.params is undefined in API request body field

### ISSUE THREAD

**Issue by chrispytoes** [appsmithorg/appsmith#9609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an API PUT request, where I am trying to use `{{ this.params.value }}` inside the request body, and I get this error:

`TypeError: Cannot read properties of undefined (reading 'params')`

This is the body I am attempting to use, set to JSON:

```
{
	"value": "{{ this.params.value }}"
}
```

### Steps To Reproduce

Self-explanatory

### Environment

Production

### Version

Self-Hosted

**Comment by mohanarpit** [comment]
In order to use params that are passed to an API, you will need to trigger it via a button or some other trigger. Then you can invoke the API via: 
```
Api1.run(
  () => { showAlert("API success"); },
  () => { showAlert("API error"); },
  {"value": "Your value", "anotherKey": "Another value" }
);
```

You can then access the params via `{{ this.params.value }}` or `{{ this.params.anotherKey }}`. 

Check out more details about the API signature at: https://docs.appsmith.com/framework-reference/run#signature

**Comment by chrispytoes** [comment]
> In order to use params that are passed to an API, you will need to trigger it via a button or some other trigger. Then you can invoke the API via:
> 
> ```
> Api1.run(
>   () => { showAlert("API success"); },
>   () => { showAlert("API error"); },
>   {"value": "Your value", "anotherKey": "Another value" }
> );
> ```
> 
> You can then access the params via `{{ this.params.value }}` or `{{ this.params.anotherKey }}`.
> 
> Check out more details about the API signature at: https://docs.appsmith.com/framework-reference/run#signature

I am aware of how params are supposed to work. I can use `this.params.myParam` inside query parameters and the URL, but not in the request body. Doing this in the request body gives me the error inside the editor field itself. Perhaps it's just that the code inspector for the request body field does not recognize `this.params`?

**Comment by chrispytoes** [comment]
@Nikhil-Nandagopal Can I get a clearer answer on this? It doesn't look like my question was fully understood and I do believe it is a bug. If it's not a bug then it should at least be documented that you can't use params within a request body.

**Comment by mohanarpit** [comment]
Hey @chrispytoes 

Here's an [example video](https://www.loom.com/share/e68f9ca0682f47e9843fbeab9104ff3e) showing how the params work even in the body for an API request.

I'm sorry I should have been clearer earlier. In your case, you are seeing the `undefined` value in the evaluated value pane because when your cursor is focusing on that field, Appsmith doesn't know what the value will be. The idea of passing params in this way to an API is to re-use the API for different inputs (exactly like functions in JS). Hence, if you peer only inside the function, there's no way for the function to tell you what the value of a variable is until you actually invoke the function. 

Does this help answer your question? 

I agree that we should improve our documentation in order to explain this concept more clearly.

**Comment by chrispytoes** [comment]
@mohanarpit No, you're still not understanding me. The error, `TypeError: Cannot read properties of undefined (reading 'params')` means the variable `this.params` is undefined, not `this.params.myValue`. As in, `this.params = undefined`, not `this.params.myValue = undefined`.

**Comment by chrispytoes** [comment]
I've done some more testing and it seems like executing the request despite the error does actually work. However Appsmith still recognizes it as a runtime error in the log, and assumes the request has failed, which is what confused me.

**Comment by Nikhil-Nandagopal** [comment]
Hi @chrispytoes 👋  you're right, this is an issue with our linting that we're working on. It will execute but it shows a lint error. This issue is already tracked here #6732
