### ISSUE TITLE
[Bug] Additional Notifications when an app is deleted

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#961]
## Expected

When an application is deleted from the homepage, there should be only 1 notification which informs the user that the application has been successfully deleted. 

## Observation
Instead we see 2 additional notifications which do not make sense.

## Screenshot
![image](https://user-images.githubusercontent.com/458946/95244093-27d9c380-082f-11eb-9e82-8a2775813e02.png)

**Comment by jyash97** [comment]
Hey @prapullac 

Can I take a look at this ? This is when we see error notifications after deleting an application. Right ?

**Comment by mohanarpit** [comment]
@jyash97 Yes you are right. I've added more details to the issue description. Have assigned you the issue as well.

**Comment by jyash97** [comment]
@mohanarpit  

I have found the root cause for the issue and have 2 approaches that may require inputs from the team. I am adding all the details below: 

### Current Issue

The above issue happens because we send an update API request just after deleting; Triggered due to the `onBlur` event of `EditableText` present [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Applications/ApplicationCard.tsx#L328).

Update API is also called every time we close the context menu. ( Even if we don't change the app name ). Check the below video for more details:

https://www.loom.com/share/a225b18ba0984563bf575de5c6f6416c

### Solution

We need to prevent update API on blur event which is called after a successful deletion of the application.

1. Trigger update API in `onTextChanged` which will be on `enter` press. The current behavior is as we type on the input and close the context menu the application name gets updated. **[ This changes current behavior ]**

___

###  Issue in EditableText onTextChanged prop

`onTextChanged` prop in `EditableText` is not called as we type the input. It is triggered only when we press `enter` as the callback is linked in `onConfirm` method [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/ads/EditableText.tsx#L179).

### Solution

Call `onTextChanged` as the input changes. We can add debouncing so that if an API is linked with `onTextChanged` we don't end up in calling the API as user types. **[This doesn't change the current behavior ]**

___

According to me the latter option is a good approach, as it makes the component ( EditableText ) more flexible. 

Let me know what you guys think on this.

**Comment by mohanarpit** [comment]
@jyash97 Thanks a lot for the detailed analysis and suggestions on the code change. 

@satbir121 Can you please comment on the above suggestions?

**Comment by mohanarpit** [comment]
@satbir121 Bumping this up for you. Can you please check if the above implementation is valid?

**Comment by jyash97** [comment]
Hey @mohanarpit 👋   was this already fixed in the PR linked?

**Comment by prapullac** [comment]
Verified the issue
