### ISSUE TITLE
[Bug]: The Update query fails to update for all matching Document in mongo

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user try to update all the matching document at once the update happens only for 1 data in the mongo database
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/ad32bd8ae7484ac3aeeed9ca7f052eef-00001.gif)](https://www.loom.com/share/ad32bd8ae7484ac3aeeed9ca7f052eef)

### Steps To Reproduce

1. go to the database
2. add the mongo database
3.  Select the update query 
4. add the query in such a way that the user is trying to update 2 records with the same name
5. Now select the All matching documents in the limit dropdown 
6. Run the query 
7. The update happens for only 1 data

### Environment

Production

### Version

Cloud

**Comment by leotom2000** [comment]
Able to simulate the issue

**Comment by leotom2000** [comment]
**Issue Resolution Summary :**
There were two findings causing this issue.
(1) UPDATE_LIMIT should be updateMany.Limit instead of update.Limit , only then it may parse and set the multi attribute as true, earlier it was always false. Made that code change.
(2)  "$set" is an attribute required in the later Mongo 4 version and above, since the development started in the earlier version it was not handled. Handled that to resolve the issue.

The above changes affected the existing Unit Test which already handled the $set' attribute. The code implementation added one more $set attribute to the output query, so changes were done in the UnitTest file.

**Comment by RakshaKShetty** [comment]
@leotom2000 i could repro the issue so reopening the issue https://www.loom.com/share/af5b3c3ee9d749f790b85cf1145563ee

**Comment by leotom2000** [comment]
Described below the findings about updating a document in Mongo.
As per docs : https://docs.mongodb.com/manual/reference/operator/update/
-- To update a document, MongoDB provides update operators, such as $set, to modify field values.
-- Some update operators, such as $set, will create the field if the field does not exist.

so the syntax like "  $set: { "size.uom": "in", status: "P" }," needs to be followed while doing the update.
A guideline of the syntax is there in the field placeholder.

The below syntax will work instead of {"name" : "cycle"}
working syntax : {$set : {"name" : "cycle"} }

We need to follow the above working syntax because, the user need to be given options to all update operators like "$currentDate, $inc, $min, $max, $mul, $rename, $set,$ setOnInsert, $unset,"   as per https://docs.mongodb.com/manual/reference/operator/update/.

The above syntax would not have worked earlier since there was an issue and was then fixed.
So no code change is required at this time, please test it with the above guideline and let us know the update.

**Comment by RakshaKShetty** [comment]
@leotom2000 I tried the scenario which you explained and it is working

**Comment by prapullac** [comment]
Based on the above comment by @RakshaKShetty we can close the issue
