### ISSUE TITLE
[Bug]: The S3 CRUD list file query fails when the user navigates to the list file query and deploy the application

### ISSUE THREAD

**Issue by RakshaKShetty** [appsmithorg/appsmith#9649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The S3 CRUD list file query fails when the user navigates to the list file and deploy the application
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/41dff33ee0324eaa936a5f146fd7300a-00001.gif)](https://www.loom.com/share/41dff33ee0324eaa936a5f146fd7300a)

### Steps To Reproduce

1. Generate the S# CRUD page
2. Now click on List File Query
3. Don't edit any data in the list file Query
4. Now click on Deploy mode
5. The List file query Fails

### Environment

Production

### Version

Cloud

**Comment by sumitsum** [comment]
The issue seems to be from the FE side. The CRUD page that gets generated is not assigning the correct values for the `ListFiles` action config's `where` clause. When a new list action is created manually then the `where` clause looks like 
```
{
  "condition": "AND",
  "children": [...]
}
```
However,  when the generate page flow is used, then the auto generated `ListFiles`  `where` clause looks like this
```
{
  "children": []
}
```
On manually selecting the top level condition to AND the query starts working again.
