### ISSUE TITLE
[Bug]: WHERE clause for GSheets errors out with datatype conflict

### ISSUE THREAD

**Issue by rohan-arthur** [appsmithorg/appsmith#9667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used the "Generate from data table" method to create an app on top of my google sheet.
link: https://docs.google.com/spreadsheets/d/1sMXmKBm__L2tAEf7XJ6Y4NFJwzuu1u9nj_jTd0KGg1M/edit?usp=sharing
sheet name: "Customers"

on the select query, when I add a WHERE clause on column ID, I get the error: 
The value at placeholderText is invalid
TypeError: Cannot read properties of undefined (reading 'Email')
{
"placeholderText":""
}

<img width="1152" alt="Screenshot 2021-12-09 at 10 14 21 AM" src="https://user-images.githubusercontent.com/94514895/145337155-d003dd89-69f3-4745-b6c5-f7db458907fd.png">
![Uploading Screenshot 2021-12-09 at 10.14.21 AM.png…]()

### Steps To Reproduce

1. create a CRUD application with the above sheet
2. go to query "SelectQuery"
3. add WHERE clause: "ID == C100"
4. RUN

Expected result:
I should get one row in response because there is a row with ID "C100"

Actual result: 
error as stated above.

### Environment

Production

### Version

Cloud

**Comment by rohan-arthur** [comment]
there are several errors in the console, here's one that seems to be particularly interesting:
`The value at tableData is invalid
This value does not evaluate to type Array<Object>
{
"tableData":"Error while interacting with value 2345678901 : For input string: "2345678901". The data type value was being parsed to was : INTEGER"
}`

The data in my sheet is as follows:
--------------------------------------------------------------------
ID | Name | Email | Phone Number
-- | -- | -- | --
C100 | First Customer | firstcustomer@appsmith.com | 1234567890
C101 | Second Customer | secondcustomer@appsmith.com | 2345678901
C102 | Third Customer | thirdcustomer@appsmith.com | 3456789012
--------------------------------------------------------------------

1. notice that in my WHERE clause, I specify ID==C100, that's the first row
2. notice from the error above that the complaint is for the "Phone number" column on the second row

**Comment by rohan-arthur** [comment]
comment from @nidhi-nair : "That number on the second row is outside of integer range so it failed"

**Comment by nidhi-nair** [comment]
Will need to be fixed along with a related issue #7794

**Comment by leotom2000** [comment]
### Findings and Resolution

**Existing Behaviour and Failure reason**
- The system takes the datatype of each column from the first row.
- if there is a 4 digit Number it considers all data in the columns and set it as an INTEGER
- In case another row contains a 15 digit Number, it still generates the insert query as preparedStatement.setInteger(15DigitNumber)
- so it fails


**Resolution**
- Understanding the handling and behaviour of datatype in googleSheet, the following is done
- (1) When we identify the datatype as INTEGER,  we set the column dataType as LONG
- (2) When we identify the datatype as FLOAT,       we set the column dataType as DOUBLE.
- Now with this fix, we can handle data with bigger datatype which are introduced later in lower rows of the grid.


**Files Modified**
appsmith-interfaces/src/main/java/com/appsmith/external/constants/FieldName.java
appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/IFilterDataServiceCE.java
appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java



**_Issues Fixed_**
#9667 - This issue
#7794
#8878

Generating a Single PR addressing the above 3 issues since they are related
