### ISSUE TITLE
[Bug]: Redirection after login does not work for Google and Github

### ISSUE THREAD

**Issue by nidhi-nair** [appsmithorg/appsmith#9819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/5298848/146347391-dfd00370-1e97-43b9-b25e-5816f82ad52b.mov

### Steps To Reproduce

1. Use direct link to an app in incognito mode.
2. After being redirected to login, use Google authentication to login

### Environment

Production

### Version

Cloud

**Comment by anvaravind** [comment]
@nidhi-nair  @Nikhil-Nandagopal  I found the issue is because of appending additional "= " in  String prefix = Security.STATE_PARAMETER_ORIGIN + "=";"   and Security.STATE_PARAMETER_ORIGIN translated to "origin="  and in the auth success endpoint we get 
![image](https://user-images.githubusercontent.com/12210689/171820942-284bc952-69e7-4f2e-a57a-2a80fb269cbf.png)


I have tested the changes and raised a PR #14268 Kindly have a look

**Comment by vuiets** [comment]
Thanks for taking the time out to look into this and raising a fix @anvaravind 🔥 

Give us a little while to review this and take it forward.

**Comment by nidhi-nair** [comment]
Hey @anvaravind! Thanks for contributing to the Appsmith repository! We've merged in your PR, it should show up as part of our next release. 😄 

Please do let us know if you have any feedback around your experience with contributing to Appsmith. If you'd like to contribute to Appsmith some more, please have a look at our issues marked as `Good First Issues`.
