### ISSUE TITLE
[Feature]: Need a way to assign country code dynamically to Input widget

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith#9822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Phone number type Input widget's country code could be dynamically assignable by the Appsmith developer.

### Why should this be worked on?

[Here](https://discord.com/channels/725602949748752515/760761686549463060/921005827354153021)'s a user's use case: 

> When using the input widget and selecting the type "phone", the default country can't be inferred from the default value.. which means if I use the input for existing data... to update my database... and I click update without doing anything... it will overwrite the value with whatever default country you have... and it gets worse.. because it adds it over the existing sufix .. so +3400000 becomes say +1340000 then +11340000 and so on....

**Comment by paulochang** [comment]
Ideally, the "default country" shouldn't even be configurable but inferred from the default value, because that is how it ends up being saved in the database when submitting the form. 

i.e if my "default value" is "+3412345323", it should be understood that the default country code is "+34" and the actual "default value" is "12345323".
This helps when creating "Edit" input fields from existing data. 

There is still the case where someone wants to set up *just* the default country, I can see two ways of handling this:

Either allow setitng up ONLY the default value as .. say "+34" ... or allow the user to set up the default country separately but disable it as soon as the user enters a default value as to infer it from it instead.

**Comment by somangshu** [comment]
Hey @paulochang, Thanks for adding the additional context here. The problem with you approach is that its difficult to identify the country code give that the length of country code and actual phone number ranges from x to y (1 to 4 in case of country code). We however have thought ok making the country code field JS convertible with the right set of validation to solve this problem. You can then dynamically provide the code.

**Comment by somangshu** [comment]
@sbalaji1192 please drop any additional info which could be helpful for the next dev (if required)!

**Comment by dilippitchika** [comment]
@sbalaji1192 can you link this to the input widget fixes you are doing. Also, we should add js snippet in our docs which can split a phone number into country code and number.

**Comment by somangshu** [comment]
@sbalaji1192 can you tell us if this covered already, In that case we need to link it to the relevant PR so that it gets closed accordingly, we should ideally also move it the relevant EPIC

**Comment by sbalaji1192** [comment]
@somangshu Yes. we are providing a Js convertible option for country code dropdown.  I have already added this issue ID to the input widget v2 issue.
