### ISSUE TITLE
[Bug]: User location continues to be tracked by watchPosition() even after restricting access

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith#9849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`watchPosition()` continues to track users after disabling location access from browser

[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/b281179a5c464dcdb91f28c0a9233217-00001.gif)](https://www.loom.com/share/b281179a5c464dcdb91f28c0a9233217)

### Steps To Reproduce

1. Allow location access on browser and use `watchPosition()` to get user location as seen in the video
2. Restrict location access and change user location and observe map pin change position 

### Environment

Release

### Version

Cloud

**Comment by Rishabh-Rathod** [comment]
As per the discussion, this issue is related to browser API tracking user location even after permission has been restricted by the user ( until there is no tab switch or refresh ) and sending to callback attached by us.
cc: @hetunandu 

Currently noticed only in chrome, we need to check in other browsers for the same.
@yatinappsmith @ramsaptami 
Can we please re-analyze this issue and confirm if this still needs to be a release-blocker?

**Comment by rohan-arthur** [comment]
removing the "release blocker" tag after discussion with @prapullac - this is browser behaviour, will continue to look for behaviour in other services.

**Comment by bharath31** [comment]
@ravikp7 would your geolocation changes fix this issue as well?

**Comment by ravikp7** [comment]
@bharath31 As rightly pointed out by Rishabh above, until we refresh the page or switch tabs, the location access change (allow/prevent) won't get into effect. It's not an issue with our code.

**Comment by bharath31** [comment]
@ramsaptami can we close this out since it is a browser API limitation?

**Comment by satbir121** [comment]
Its a browser limitation.
