### ISSUE TITLE
[Bug]:  Unable to access Admin settings page

### ISSUE THREAD

**Issue by yatinappsmith** [appsmithorg/appsmith#9851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to access Admin settings page in locally built .

### Steps To Reproduce

1. Click your account in top right corner
2. Click Admin settings page
3.
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/2e6fbd5f0d8f45d4b4660e89654ff943-00001.gif)](https://www.loom.com/share/2e6fbd5f0d8f45d4b4660e89654ff943)

### Environment

Release

### Version

Self-Hosted

**Comment by nayan-rafiq** [comment]
@yatinappsmith Is there any error in browser log?

**Comment by yatinappsmith** [comment]
Based on discussion with Trisha 
It is looking for environment file at a very particular location. This should actually work with the fat container.
Because the file location is as per the fat container.

**Comment by yatinappsmith** [comment]
[log9851.log](https://github.com/appsmithorg/appsmith/files/7734873/log9851.log)
adding logs

**Comment by sharat87** [comment]
@nayan-rafiq, the problem is in the slim-container setup. The backend server, even if it has access to an environment file to load and save changes to, cannot restart the server today. Because there is no supervisor in a slim container setup. The fix is here to show some form of an error message instead of the blank page, saying something like "Admin settings is not available on this instance.", instead of a blank page. This might need some changes in the client as well though.

**Comment by yatinappsmith** [comment]
Feature is not supported in slim container

**Comment by rohan-arthur** [comment]
re-opening this, and removed the `critical` tag.
On a slim container, the user should still see some information when they try to access the admin settings.

**Comment by hiteshjoshi** [comment]
@sharat87 this requires frontend to know if its a slim container or not.

**Comment by hiteshjoshi** [comment]
We need a proper error code and error message from the backend. @kocharrahul7 and @akash-codemonk to pick

**Comment by sharat87** [comment]
We now do get a proper error message. Fixed as part of https://github.com/appsmithorg/appsmith/pull/13373.

**Comment by sharat87** [comment]
Reopening to show a graceful error message on the client too.
