### ISSUE TITLE
[Bug]: Change of error message when Organization name is blank

### ISSUE THREAD

**Issue by chandannkumar** [appsmithorg/appsmith#9912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Organization settings>general setting> edit organization name should throw a proper error message when blank.
current message: "Please select a name". Since this not a dropdown please change the text

### Steps To Reproduce

1. Go to Organization settings>general setting
2. Edit Organization name and set it as Blank
3. Observe the message you see

### Environment

Production

### Version

Cloud

**Comment by deepika-appsmith** [comment]
In General settings, we now have an instance name; when saved blank, it defaults to Appsmith. This issue is no longer relevant, hence
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmZlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3eca58da629e237fb7ce65b602fa8392e948252/Screen%20Recording%202024-03-14%20at%205.07.45%E2%80%AFPM.mov)

 closing the issue.
