### ISSUE TITLE
[Bug] Checkbox widget: Toggle issue while unchecking the checkbox

### ISSUE THREAD

**Issue by prapullac** [appsmithorg/appsmith#994]
https://www.notion.so/Checkbox-widget-Toggle-issue-while-unchecking-the-checkbox-9067004e6a044b91942d2897f69b2df4

**Comment by jyash97** [comment]
Hey @prapullac 

Can you confirm if the issue you mentioned above is related to this: https://www.loom.com/share/d008f346db6547da8e1b7e078d0c9fa5

<details>
  <summary>If <b>yes</b> expand for more details else I will create a separate issue</summary>
<p>

  The above issue is happening due to the styles applied on `active` pseudo-class which removes the background. I tried removing the active classes and it seems to work. [Working video](https://www.loom.com/share/653fe6a9735e438a883bb97b19003904) (Recorded from development mode).

Let me know if this looks good I will open a PR :)
</p>
</details>

**Comment by prapullac** [comment]
Hi @jyash97 
This is the same issue that your talking about.

**Comment by jyash97** [comment]
Thanks @prapullac I will create a PR  :)
